package com.bornfire.xbrl.entities.BRSS;

import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

@Repository
public interface ReportValidationsRepo extends JpaRepository<ReportValidations, String> {

	Optional<ReportValidations> findById(String directorId);

	@Query(value = "select * from BRBS_REPORT_VALIDATION_TABLE ORDER BY srl_no", nativeQuery = true)
	List<ReportValidations> getValidationList();
	
	@Query(value = "update BRBS_REPORT_VALIDATION_TABLE set cur_status=?2 where srl_no=?1", nativeQuery = true)
	void updateValidateChkFlg(String srl_no, String cur_status);
	
	@Query(value = "select * from BAML_RPT_MAST ORDER  BY SRL_NO", nativeQuery = true)
	List<RBSReport> getReport_details();

	@Query(value = "select DISTINCT to_char(CUR_QTR_END_DATE,'dd/MM/yyyy')as CUR_QTR_END_DATE from BRBS_RPT_MAST where ROWNUM = 1 order by CUR_QTR_END_DATE desc", nativeQuery = true)
	String getCurrentQtr(SimpleDateFormat simpleDateFormat);

	@Query(value = "Select (SELECT (NVL(INTERNAL_RATING_FACE_TO_FACE_1B,0)+NVL(INTERNAL_RATING_FACE_TO_FACE_2B,0)+NVL(INTERNAL_RATING_FACE_TO_FACE_3B,0)) FROM  T2_CFT_CUSTOMER_RATING_RPT_TB WHERE REPORT_DATE=?1)as TotalT2,(SELECT (TOT_BY_PRODUCT2_LOW_CUST_COUNT+TOT_BY_PRODUCT7_MEDIUM_CUST_COUNT+TOT_BY_PRODUCT12_HIGH_CUST_COUNT) FROM T5A_PROFILE_FACE_TO_FACE WHERE REPORT_DATE=?1)TotalT5A from dual", nativeQuery = true)
	List<Object[]> getCheckSrlNo1(String date);

	////Srl_no2
	@Query(value = "Select (NVL(a.TOT_BY_PRODUCT2_LOW_CUST_COUNT,0)+NVL(a.TOT_BY_PRODUCT7_MEDIUM_CUST_COUNT,0)+NVL(a.TOT_BY_PRODUCT12_HIGH_CUST_COUNT,0))as TotalT5A,NVL(b.T9_10C_TOTAL_CUR_FACETOFACE,0) as TotalT9 from T5A_PROFILE_FACE_TO_FACE a ,T9_RISK_RATING_MIG_SUMARY_TABLE b where a.report_date=b.report_date and a.report_date=?1", nativeQuery = true)
	List<Object[]> getCheckSrlNo2(String date);
	
	 ////Srl_no3
	@Query(value = "SELECT (NVL(a.TOT_BY_PRODUCT2_LOW_CUST_COUNT,0)+NVL(a.TOT_BY_PRODUCT7_MEDIUM_CUST_COUNT,0)+NVL(a.TOT_BY_PRODUCT12_HIGH_CUST_COUNT,0))as COUNT ,b.T9_10D_TOTAL_CUR_NON_FACETOFACE FROM T5B_PROFILE_NON_FACE_TO_FACE a,T9_RISK_RATING_MIG_SUMARY_TABLE b WHERE a.REPORT_DATE=b.REPORT_DATE and a.REPORT_DATE=?1", nativeQuery = true)
	List<Object[]> getCheckSrlNo3(String date);
	
    ////Srl_no4
	@Query(value = "SELECT (NVL(a.TOT_BY_PRODUCT3_LOW_DEBIT_TRAN_COUNT,0)+NVL(a.TOT_BY_PRODUCT5_LOW_CREDIT_TRAN_COUNT,0)+NVL(c.TOT_BY_PRODUCT3_LOW_DEBIT_TRAN_COUNT,0)+NVL(c.TOT_BY_PRODUCT5_LOW_CREDIT_TRAN_COUNT,0))as LOW_COUNT,"
			+ "(NVL(a.TOT_BY_PRODUCT8_MEDIUM_DEBIT_TRAN_COUNT,0)+NVL(a.TOT_BY_PRODUCT10_MEDIUM_CREDIT_TRAN_COUNT,0)+NVL(c.TOT_BY_PRODUCT8_MEDIUM_DEBIT_TRAN_COUNT,0)+NVL(c.TOT_BY_PRODUCT10_MEDIUM_CREDIT_TRAN_COUNT,0))as MEDIUM_COUNT	,"
			+ "(NVL(a.TOT_BY_PRODUCT13_HIGH_DEBIT_TRAN_COUNT,0)+NVL(a.TOT_BY_PRODUCT15_HIGH_CREDIT_TRAN_COUNT,0)+NVL(c.TOT_BY_PRODUCT13_HIGH_DEBIT_TRAN_COUNT,0)+NVL(c.TOT_BY_PRODUCT15_HIGH_CREDIT_TRAN_COUNT,0))as HIGH_COUNT,"
			+ "NVL(b.TOTAL_SUM_LOW_TRAN_COUNT,0),NVL(b.TOTAL_SUMMED_TRAN_COUNT,0),NVL(b.TOTAL_SUMHIGH_TRAN_COUNT,0) "
			+ "FROM T5A_PROFILE_FACE_TO_FACE a,T5B_PROFILE_NON_FACE_TO_FACE c ,T12A_TRAN_CUST_TYPE_TABLE b WHERE a.report_date=b.report_date and b.report_date=c.report_date and a.REPORT_DATE=?1", nativeQuery = true)
	List<Object[]> getCheckSrlNo4(String date);
	
	////Srl_no5
	@Query(value = "SELECT (NVL(a.TOT_BY_PRODUCT4_LOW_DEBIT_TRAN_AMOUNT,0)+NVL(a.TOT_BY_PRODUCT6_LOW_CREDIT_TRAN_AMOUNT,0)+NVL(b.TOT_BY_PRODUCT4_LOW_DEBIT_TRAN_AMOUNT,0)+NVL(b.TOT_BY_PRODUCT6_LOW_CREDIT_TRAN_AMOUNT,0))as LOW_COUNT,"
			+ "(NVL(a.TOT_BY_PRODUCT9_MEDIUM_DEBIT_TRAN_AMOUNT,0)+NVL(a.TOT_BY_PRODUCT11_MEDIUM_CREDIT_TRAN_COUNT,0)+NVL(b.TOT_BY_PRODUCT9_MEDIUM_DEBIT_TRAN_AMOUNT,0)+NVL(b.TOT_BY_PRODUCT11_MEDIUM_CREDIT_TRAN_COUNT,0))as MEDIUM_COUNT,"
			+ "(NVL(a.TOT_BY_PRODUCT14_HIGH_DEBIT_TRAN_AMOUNT,0)+NVL(a.TOT_BY_PRODUCT16_HIGH_CREDIT_TRAN_AMOUNT,0)+NVL(b.TOT_BY_PRODUCT14_HIGH_DEBIT_TRAN_AMOUNT,0)+NVL(b.TOT_BY_PRODUCT16_HIGH_CREDIT_TRAN_AMOUNT,0))as HIGH_COUNT,"
			+ "c.TOTAL_SUM_LOW_TRAN_AMT,c.TOTAL_SUMMED_TRAN_AMT,c.TOTAL_SUMHIGH_TRAN_AMT FROM T5A_PROFILE_FACE_TO_FACE a,T5B_PROFILE_NON_FACE_TO_FACE b,T12A_TRAN_CUST_TYPE_TABLE c WHERE a.REPORT_DATE=b.REPORT_DATE and b.REPORT_DATE=c.REPORT_DATE and a.REPORT_DATE=?1", nativeQuery = true)
	List<Object[]> getCheckSrlNo5(String date);
	
	////Srl_no6
	@Query(value = "SELECT NVL(a.CASH_DEP_LOW_TRAN_COUNT,0),NVL(a.CASH_DEP_LOW_TRAN_AMT,0),NVL(a.CASH_DEPMED_TRAN_COUNT,0),NVL(a.CASH_DEPMED_TRAN_AMT,0),NVL(a.CASH_DEPHIGH_TRAN_COUNT,0),NVL(a.CASH_DEPHIGH_TRAN_AMT,0),"
			+ "NVL(b.c8f_cur_total_nof_dep_tran_low,0),NVL(b.c8g_cur_total_to_val_tran_low,0),NVL(b.c8d_cur_total_nof_dep_tran_med,0),NVL(b.c8e_cur_total_to_val_tran_med,0),NVL(b.c8b_cur_total_nof_dep_tran_hig,0),"
			+ "NVL(b.c8c_cur_total_to_val_tran_hig,0) FROM T12A_TRAN_CUST_TYPE_TABLE a,T16A_IND_CASH_DEP_TABLE b WHERE a.report_date=b.report_date and a.REPORT_DATE=?1", nativeQuery = true)
	List<Object[]> getCheckSrlNo6(String date);
	
    ////Srl_no7
	@Query(value = "SELECT NVL(a.CASH_WITHD_LOW_TRAN_COUNT,0),NVL(a.CASH_WITHD_LOW_TRAN_AMT,0),NVL(a.CASH_WITHDMED_TRAN_COUNT,0),NVL(a.CASH_WITHDMED_TRAN_AMT,0),NVL(a.CASH_WITHDHIGH_TRAN_COUNT,0),"
			+ "NVL(a.CASH_WITHDHIGH_TRAN_AMT,0),NVL(b.c8f_cur_total_nof_dep_tran_low,0),NVL(b.c8g_cur_total_to_val_tran_low,0),NVL(b.c8d_cur_total_nof_dep_tran_med,0),NVL(b.c8e_cur_total_to_val_tran_med,0),"
			+ "NVL(b.c8b_cur_total_nof_dep_tran_hig,0),NVL(b.c8c_cur_total_to_val_tran_hig,0) FROM T12A_TRAN_CUST_TYPE_TABLE a,T16B_IND_CASH_WITHDRAW_TABLE b WHERE a.report_date=b.report_date and a.REPORT_DATE=?1", nativeQuery = true)
	List<Object[]> getCheckSrlNo7(String date);
	
    ////Srl_no8
	@Query(value = "SELECT NVL(a.DOM_INW_LOW_TRAN_COUNT,0),NVL(a.DOM_INW_LOW_TRAN_AMT,0),NVL(a.DOM_INWMED_TRAN_COUNT,0),NVL(a.DOM_INWMED_TRAN_AMT,0),NVL(a.DOM_INWHIGH_TRAN_COUNT,0),NVL(a.DOM_INWHIGH_TRAN_AMT,0),"
			+ "NVL(b.C10_TOTAL_LOW_TRAN_COUNT,0),NVL(b.C10_TOTAL_LOW_TRAN_AMT,0),NVL(b.C10_TOTAL_MEDIUM_TRAN_COUNT,0),NVL(b.C10_TOTAL_MEDUM_TRAN_AMT,0),NVL(b.C10_TOTAL_HIGH_TRAN_COUNT,0),NVL(b.C10_TOTAL_HIGH_TRAN_AMT,0) "
			+ "FROM T12A_TRAN_CUST_TYPE_TABLE a ,T12G_DOMESTIC_INWARD_REMITTANCE b WHERE a.report_date=b.report_date and a.REPORT_DATE=?1", nativeQuery = true)
	List<Object[]> getCheckSrlNo8(String date);
	
	 ////Srl_no9
	@Query(value = "SELECT a.DOM_OUT_LOW_TRAN_COUNT,a.DOM_OUT_LOW_TRAN_AMT,a.DOM_OUTMED_TRAN_COUNT,a.DOM_OUTMED_TRAN_AMT,a.DOM_OUTHIGH_TRAN_COUNT,a.DOM_OUTHIGH_TRAN_AMT,b.C10_TOTAL_LOW_TRAN_COUNT,"
			+ "b.C10_TOTAL_LOW_TRAN_AMT,b.C10_TOTAL_MEDIUM_TRAN_COUNT,b.C10_TOTAL_MEDUM_TRAN_AMT,b.C10_TOTAL_HIGH_TRAN_COUNT,b.C10_TOTAL_HIGH_TRAN_AMT FROM T12A_TRAN_CUST_TYPE_TABLE a,"
			+ "T12F_DOMESTIC_OUTWARD_REMITTANCE b WHERE a.report_date=b.report_date and  a.REPORT_DATE=?1", nativeQuery = true)
	List<Object[]> getCheckSrlNo9(String date);
	
	 ////Srl_no10
	@Query(value = "SELECT a.INT_TRADE_INW_LOW_TRAN_COUNT,a.INT_TRADE_INW_LOW_TRAN_AMT,a.INT_TRADE_INWMED_TRAN_COUNT,a.INT_TRADE_INWMED_TRAN_AMT,a.INT_TRADE_INWHIGH_TRAN_COUNT,a.INT_TRADE_INWHIGH_TRAN_AMT,"
			+ "(NVL(b.C10_TOTAL_LOW_CN_LOW_TRAN_COUNT,0)+NVL(b.C10_TOTAL_MEDIUM_CN_LOW_TRAN_COUNT,0)+NVL(b.C10_TOTAL_HIGH_CN_LOW_TRAN_COUNT,0))as LOW_COUNT,(NVL(b.C10_TOTAL_LOW_CN_LOW_TRAN_AMT,0)+NVL(b.C10_TOTAL_MEDIUM_CN_LOW_TRAN_AMT,0)+NVL(b.C10_TOTAL_HIGH_CN_LOW_TRAN_AMT,0))as LOW_AMT,"
			+ "(NVL(b.C10_TOTAL_LOW_CN_MEDIUM_TRAN_COUNT,0)+NVL(b.C10_TOTAL_MEDIUM_CN_MEDIUM_TRAN_COUNT,0)+NVL(b.C10_TOTAL_HIGH_CN_MEDIUM_TRAN_COUNT,0))as MED_COUNT,(NVL(b.C10_TOTAL_LOW_CN_MEDUM_TRAN_AMT,0)+NVL(b.C10_TOTAL_MEDIUM_CN_MEDUM_TRAN_AMT,0)+NVL(b.C10_TOTAL_HIGH_CN_MEDUM_TRAN_AMT,0))as MED_AMT,"
			+ "(NVL(b.C10_TOTAL_LOW_CN_HIGH_TRAN_COUNT,0)+NVL(b.C10_TOTAL_MEDIUM_CN_HIGH_TRAN_COUNT,0)+NVL(b.C10_TOTAL_HIGH_CN_HIGH_TRAN_COUNT,0))as HIGH_COUNT,(NVL(b.C10_TOTAL_LOW_CN_HIGH_TRAN_AMT,0)+NVL(b.C10_TOTAL_MEDIUM_CN_HIGH_TRAN_AMT,0)+NVL(b.C10_TOTAL_HIGH_CN_HIGH_TRAN_AMT,0))as HIGH_AMT FROM T12A_TRAN_CUST_TYPE_TABLE a,T12B_INTERNATIONAL_TRADE_RELATED_INWARD_REMITTANCE b WHERE a.report_date=b.report_date and a.REPORT_DATE=?1", nativeQuery = true)
	List<Object[]> getCheckSrlNo10(String date);
	
    ////Srl_no11
	@Query(value = "SELECT a.INT_TRADE_OUT_LOW_TRAN_COUNT,a.INT_TRADE_OUT_LOW_TRAN_AMT,a.INT_TRADE_OUTMED_TRAN_COUNT,a.INT_TRADE_OUTMED_TRAN_AMT,a.INT_TRADE_OUTHIGH_TRAN_COUNT,a.INT_TRADE_OUTHIGH_TRAN_AMT,"
			+ "(NVL(b.C10_TOTAL_LOW_CN_LOW_TRAN_COUNT,0)+NVL(b.C10_TOTAL_MEDIUM_CN_LOW_TRAN_COUNT,0)+NVL(b.C10_TOTAL_HIGH_CN_LOW_TRAN_COUNT,0))as LOW_COUNT,(NVL(b.C10_TOTAL_LOW_CN_LOW_TRAN_AMT,0)+NVL(b.C10_TOTAL_MEDIUM_CN_LOW_TRAN_AMT,0)+NVL(b.C10_TOTAL_HIGH_CN_LOW_TRAN_AMT,0))as LOW_AMT,"
			+ "(NVL(b.C10_TOTAL_LOW_CN_MEDIUM_TRAN_COUNT,0)+NVL(b.C10_TOTAL_MEDIUM_CN_MEDIUM_TRAN_COUNT,0)+NVL(b.C10_TOTAL_HIGH_CN_MEDIUM_TRAN_COUNT,0))as MED_COUNT,(NVL(b.C10_TOTAL_LOW_CN_MEDUM_TRAN_AMT,0)+NVL(b.C10_TOTAL_MEDIUM_CN_MEDUM_TRAN_AMT,0)+NVL(b.C10_TOTAL_HIGH_CN_MEDUM_TRAN_AMT,0))as MED_AMT,"
			+ "(NVL(b.C10_TOTAL_LOW_CN_HIGH_TRAN_COUNT,0)+NVL(b.C10_TOTAL_MEDIUM_CN_HIGH_TRAN_COUNT,0)+NVL(b.C10_TOTAL_HIGH_CN_HIGH_TRAN_COUNT,0))as HIGH_COUNT,(NVL(b.C10_TOTAL_LOW_CN_HIGH_TRAN_AMT,0)+NVL(b.C10_TOTAL_MEDIUM_CN_HIGH_TRAN_AMT,0)+NVL(b.C10_TOTAL_HIGH_CN_HIGH_TRAN_AMT,0))as HIGH_AMT FROM T12A_TRAN_CUST_TYPE_TABLE a,"
			+ "T12C_INTERNATIONAL_TRADE_RELATED_OUTWARD_REMITTANCE b WHERE a.report_date=b.report_date and a.REPORT_DATE=?1", nativeQuery = true)
	List<Object[]> getCheckSrlNo11(String date);
	
    ////Srl_no12
	@Query(value = "SELECT a.INT_NON_TRADE_INW_LOW_TRAN_COUNT,a.INT_NON_TRADE_INW_LOW_TRAN_AMT,a.INT_NON_TRADE_INWMED_TRAN_COUNT,a.INT_NON_TRADE_INWMED_TRAN_AMT,"
			+ "a.INT_NON_TRADE_INWHIGH_TRAN_COUNT,a.INT_NON_TRADE_INWHIGH_TRAN_AMT,(NVL(b.C10_TOTAL_LOW_CN_LOW_TRAN_COUNT,0)+NVL(b.C10_TOTAL_MEDIUM_CN_LOW_TRAN_COUNT,0)+NVL(b.C10_TOTAL_HIGH_CN_LOW_TRAN_COUNT,0))as LOW_COUNT,(NVL(b.C10_TOTAL_LOW_CN_LOW_TRAN_AMT,0)+NVL(b.C10_TOTAL_MEDIUM_CN_LOW_TRAN_AMT,0)+NVL(b.C10_TOTAL_HIGH_CN_LOW_TRAN_AMT,0))as LOW_AMT,"
			+ "(NVL(b.C10_TOTAL_LOW_CN_MEDIUM_TRAN_COUNT,0)+NVL(b.C10_TOTAL_MEDIUM_CN_MEDIUM_TRAN_COUNT,0)+NVL(b.C10_TOTAL_HIGH_CN_MEDIUM_TRAN_COUNT,0))as MED_COUNT,(NVL(b.C10_TOTAL_LOW_CN_MEDUM_TRAN_AMT,0)+NVL(b.C10_TOTAL_MEDIUM_CN_MEDUM_TRAN_AMT,0)+NVL(b.C10_TOTAL_HIGH_CN_MEDUM_TRAN_AMT,0))as MED_AMT,"
			+ "(NVL(b.C10_TOTAL_LOW_CN_HIGH_TRAN_COUNT,0)+NVL(b.C10_TOTAL_MEDIUM_CN_HIGH_TRAN_COUNT,0)+NVL(b.C10_TOTAL_HIGH_CN_HIGH_TRAN_COUNT,0))as HIGH_COUNT,(NVL(b.C10_TOTAL_LOW_CN_HIGH_TRAN_AMT,0)+NVL(b.C10_TOTAL_MEDIUM_CN_HIGH_TRAN_AMT,0)+NVL(b.C10_TOTAL_HIGH_CN_HIGH_TRAN_AMT,0))as HIGH_AMT FROM T12A_TRAN_CUST_TYPE_TABLE a,T12E_INTERNATIONAL_NON_TRADE_RELATED_OUTWARD_REMITTANCE b WHERE a.report_date=b.report_date and a.REPORT_DATE=?1", nativeQuery = true)
	List<Object[]> getCheckSrlNo12(String date);
	
    ////Srl_no13
	@Query(value = "SELECT a.INT_NON_TRADE_OUT_LOW_TRAN_COUNT,a.INT_NON_TRADE_OUT_LOW_TRAN_AMT,a.INT_NON_TRADE_OUTMED_TRAN_COUNT,a.INT_NON_TRADE_OUTMED_TRAN_AMT,"
			+ "a.INT_NON_TRADE_OUTHIGH_TRAN_COUNT,a.INT_NON_TRADE_OUTHIGH_TRAN_AMT,(NVL(b.C10_TOTAL_LOW_CN_LOW_TRAN_COUNT,0)+NVL(b.C10_TOTAL_MEDIUM_CN_LOW_TRAN_COUNT,0)+NVL(b.C10_TOTAL_HIGH_CN_LOW_TRAN_COUNT,0))as LOW_COUNT,"
			+ "(NVL(b.C10_TOTAL_LOW_CN_LOW_TRAN_AMT,0)+NVL(b.C10_TOTAL_MEDIUM_CN_LOW_TRAN_AMT,0)+NVL(b.C10_TOTAL_HIGH_CN_LOW_TRAN_AMT,0))as LOW_AMT,(NVL(b.C10_TOTAL_LOW_CN_MEDIUM_TRAN_COUNT,0)+NVL(b.C10_TOTAL_MEDIUM_CN_MEDIUM_TRAN_COUNT,0)+NVL(b.C10_TOTAL_HIGH_CN_MEDIUM_TRAN_COUNT,0))as MED_COUNT,"
			+ "(NVL(b.C10_TOTAL_LOW_CN_MEDUM_TRAN_AMT,0)+NVL(b.C10_TOTAL_MEDIUM_CN_MEDUM_TRAN_AMT,0)+NVL(b.C10_TOTAL_HIGH_CN_MEDUM_TRAN_AMT,0))as MED_AMT,(NVL(b.C10_TOTAL_LOW_CN_HIGH_TRAN_COUNT,0)+NVL(b.C10_TOTAL_MEDIUM_CN_HIGH_TRAN_COUNT,0)+NVL(b.C10_TOTAL_HIGH_CN_HIGH_TRAN_COUNT,0))as HIGH_COUNT,(NVL(b.C10_TOTAL_LOW_CN_HIGH_TRAN_AMT,0)+NVL(b.C10_TOTAL_MEDIUM_CN_HIGH_TRAN_AMT,0)+NVL(b.C10_TOTAL_HIGH_CN_HIGH_TRAN_AMT,0))as HIGH_AMT FROM T12A_TRAN_CUST_TYPE_TABLE a,T12D_INTERNATIONAL_NON_TRADE_RELATED_INWARD_REMITTANCE b WHERE a.report_date=b.report_date and a.REPORT_DATE=?1", nativeQuery = true)
	List<Object[]> getCheckSrlNo13(String date);
	
    ////Srl_no14
	@Query(value = "SELECT (NVL(a.TOTAL_SUM_LOW_TRAN_COUNT,0)+NVL(a.TOTAL_SUMMED_TRAN_COUNT,0)+NVL(a.TOTAL_SUMHIGH_TRAN_COUNT,0))as COUNT,(NVL(a.TOTAL_SUM_LOW_TRAN_AMT,0)+NVL(a.TOTAL_SUMMED_TRAN_AMT,0)+NVL(a.TOTAL_SUMHIGH_TRAN_AMT,0))as AMT,"
			+ "b.C12_TRAN_COUNT,b.D12_TRAN_AMOUNT FROM T12A_TRAN_CUST_TYPE_TABLE a,T23_DISTRIBUTION_CHANNEL_TABLE b WHERE a.REPORT_DATE=b.REPORT_DATE and a.REPORT_DATE=?1", nativeQuery = true)
	List<Object[]> getCheckSrlNo14(String date);

	
	
	//@Query(value = "select (select count(*) from T2_CFT_CUSTOMER_RATING_RPT_TB)as T2_COUNT ,(select count(*) from T5A_PROFILE_FACE_TO_FACE)as T5A_COUNT from dual", nativeQuery = true)
	//List<Object[]> getCheckSrlNo2();


	
}
