package com.bornfire.xbrl.entities.BRSS;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

@Entity
@Table(name ="T10_KYC_CDD_REVIEW_FREQ_TABLE")
public class T10Report {

	
	private String	D1_CURRENT_INDIVIDUALS_LOW;
	private String	E1_CURRENT_INDIVIDUALS_MEDIUM;
	private String	F1_CURRENT_INDIVIDUALS_HIGH;
	private String	D2_CURRENT_CORPORATES_LOW;
	private String	E2_CURRENT_CORPORATES_MEDIUM;
	private String	F2_CURRENT_CORPORATES_HIGH;
	private String	F2_CURRENT_RESPONDENT_LOW;
	private String	F2_CURRENT_RESPONDENT_MEDIUM;
	private String	F2_CURRENT_RESPONDENT_HIGH;
	private String	F2_CURRENT_CORRESPONDENT_LOW;
	private String	F2_CURRENT_CORRESPONDENT_MEDIUM;
	private String	F2_CURRENT_CORRESPONDENT_HIGH;
	private String	D3_CURRENT_NON_PROFIT_ORGANIZATIONS_LOW;
	private String	E3_CURRENT_NON_PROFIT_ORGANIZATIONS_MEDIUM;
	private String	F3_CURRENT_NON_PROFIT_ORGANIZATIONS_HIGH;
	private String	D4_CURRENT_TRUSTS_OTHER_THAN_NPOS_AND_TCSPS_LOW;
	private String	E4_CURRENT_TRUSTS_OTHER_THAN_NPOS_AND_TCSPS_MEDIUM;
	private String	F4_CURRENT_TRUSTS_OTHER_THAN_NPOS_AND_TCSPS_HIGH;
	private String	D5_CURRENT_ALL_OTHERS_LOW;
	private String	E5_CURRENT_ALL_OTHERS_MEDIUM;
	private String	F5_CURRENT_ALL_OTHERS_HIGH;
	private String	D6_CURRENT_GBC_1_LOW;
	private String	E6_CURRENT_GBC_1_MEDIUM;
	private String	F6_CURRENT_GBC_1_HIGH;
	private String	D6_CURRENT_GBC_2_LOW;
	private String	E6_CURRENT_GBC_2_MEDIUM;
	private String	F6_CURRENT_GBC_2_HIGH;
	private String	D6_CURRENT_PEPS_DOMESTIC_LOW;
	private String	E6_CURRENT_PEPS_DOMESTIC_MEDIUM;
	private String	F6_CURRENT_PEPS_DOMESTIC_HIGH;
	private String	D7_CURRENT_PEPS_FOREIGN_LOW;
	private String	E7_CURRENT_PEPS_FOREIGN_MEDIUM;
	private String	F7_CURRENT_PEPS_FOREIGN_HIGH;
	private String	D7_CURRENT_PBC_LOW;
	private String	E7_CURRENT_PBC_MEDIUM;
	private String	F7_CURRENT_PBC_HIGH;
	private String	D7_CURRENT_RELATED_PARTY_LOW;
	private String	E7_CURRENT_RELATED_PARTY_MEDIUM;
	private String	F7_CURRENT_RELATED_PARTY_HIGH;
	private String	D8_CURRENT_TRUST_AND_COMPANY_SERVICE_PROVIDERS_TCPS_LOW;
	private String	E8_CURRENT_TRUST_AND_COMPANY_SERVICE_PROVIDERS_TCPS_MEDIUM;
	private String	F8_CURRENT_TRUST_AND_COMPANY_SERVICE_PROVIDERS_TCPS_HIGH;
	private String D7_CURRENT_EXEMPT_LOW;
	private String E7_CURRENT_EXEMPT_MEDIUM;
	private String F7_CURRENT_EXEMPT_HIGH;
	private String	VERIFY_FLG;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern ="dd/MM/yyyy")
	private Date	ENTRY_DATE;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern ="dd/MM/yyyy")
	private Date	MODIFY_DATE;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern ="dd/MM/yyyy")
	private Date	VERIFY_DATE;
	private String	ENTRY_USER;
	private String	MODIFY_USER;
	private String	VERIFY_USER;

	
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern ="dd/MM/yyyy")
	@Id
	private Date	REPORT_DATE;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern ="dd/MM/yyyy")
	private Date	REPORT_DUE_DATE;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern ="dd/MM/yyyy")
	private Date	REP_SUBMIT_DATE;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern ="dd/MM/yyyy")
	private Date	REP_PERIOD_FROM;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern ="dd/MM/yyyy")
	private Date	REP_PERIOD_TO;
	private String	REP_FREQ;
	private String	NIL_REPORT_FLG;
	private String	SRL_NO;
	private String	ENTITY_FLG;
	private String	MODIFY_FLG;
	private String	A1_PRODUCT;
	private String	A2_PRODUCT;
	private String	A3_PRODUCT;
	private String	A4_PRODUCT;
	private String	A5_PRODUCT;
	private String	A6_PRODUCT;
	private String	A7_PRODUCT;
	private String	A8_PRODUCT;
	private String	A9_PRODUCT;
	private String	A10_PRODUCT;
	private String	A11_PRODUCT;
	private String	A12_PRODUCT;
	private String	A13_PRODUCT;
	private String	A14_PRODUCT;
	private String	A15_PRODUCT;

	public String getD1_CURRENT_INDIVIDUALS_LOW() {
		return D1_CURRENT_INDIVIDUALS_LOW;
	}
	public void setD1_CURRENT_INDIVIDUALS_LOW(String d1_CURRENT_INDIVIDUALS_LOW) {
		D1_CURRENT_INDIVIDUALS_LOW = d1_CURRENT_INDIVIDUALS_LOW;
	}
	public String getE1_CURRENT_INDIVIDUALS_MEDIUM() {
		return E1_CURRENT_INDIVIDUALS_MEDIUM;
	}
	public void setE1_CURRENT_INDIVIDUALS_MEDIUM(String e1_CURRENT_INDIVIDUALS_MEDIUM) {
		E1_CURRENT_INDIVIDUALS_MEDIUM = e1_CURRENT_INDIVIDUALS_MEDIUM;
	}
	public String getF1_CURRENT_INDIVIDUALS_HIGH() {
		return F1_CURRENT_INDIVIDUALS_HIGH;
	}
	public void setF1_CURRENT_INDIVIDUALS_HIGH(String f1_CURRENT_INDIVIDUALS_HIGH) {
		F1_CURRENT_INDIVIDUALS_HIGH = f1_CURRENT_INDIVIDUALS_HIGH;
	}
	public String getD2_CURRENT_CORPORATES_LOW() {
		return D2_CURRENT_CORPORATES_LOW;
	}
	public void setD2_CURRENT_CORPORATES_LOW(String d2_CURRENT_CORPORATES_LOW) {
		D2_CURRENT_CORPORATES_LOW = d2_CURRENT_CORPORATES_LOW;
	}
	public String getE2_CURRENT_CORPORATES_MEDIUM() {
		return E2_CURRENT_CORPORATES_MEDIUM;
	}
	public void setE2_CURRENT_CORPORATES_MEDIUM(String e2_CURRENT_CORPORATES_MEDIUM) {
		E2_CURRENT_CORPORATES_MEDIUM = e2_CURRENT_CORPORATES_MEDIUM;
	}
	public String getF2_CURRENT_CORPORATES_HIGH() {
		return F2_CURRENT_CORPORATES_HIGH;
	}
	public void setF2_CURRENT_CORPORATES_HIGH(String f2_CURRENT_CORPORATES_HIGH) {
		F2_CURRENT_CORPORATES_HIGH = f2_CURRENT_CORPORATES_HIGH;
	}
	public String getF2_CURRENT_RESPONDENT_LOW() {
		return F2_CURRENT_RESPONDENT_LOW;
	}
	public void setF2_CURRENT_RESPONDENT_LOW(String f2_CURRENT_RESPONDENT_LOW) {
		F2_CURRENT_RESPONDENT_LOW = f2_CURRENT_RESPONDENT_LOW;
	}
	public String getF2_CURRENT_RESPONDENT_MEDIUM() {
		return F2_CURRENT_RESPONDENT_MEDIUM;
	}
	public void setF2_CURRENT_RESPONDENT_MEDIUM(String f2_CURRENT_RESPONDENT_MEDIUM) {
		F2_CURRENT_RESPONDENT_MEDIUM = f2_CURRENT_RESPONDENT_MEDIUM;
	}
	public String getF2_CURRENT_RESPONDENT_HIGH() {
		return F2_CURRENT_RESPONDENT_HIGH;
	}
	public void setF2_CURRENT_RESPONDENT_HIGH(String f2_CURRENT_RESPONDENT_HIGH) {
		F2_CURRENT_RESPONDENT_HIGH = f2_CURRENT_RESPONDENT_HIGH;
	}
	public String getF2_CURRENT_CORRESPONDENT_LOW() {
		return F2_CURRENT_CORRESPONDENT_LOW;
	}
	public void setF2_CURRENT_CORRESPONDENT_LOW(String f2_CURRENT_CORRESPONDENT_LOW) {
		F2_CURRENT_CORRESPONDENT_LOW = f2_CURRENT_CORRESPONDENT_LOW;
	}
	public String getF2_CURRENT_CORRESPONDENT_MEDIUM() {
		return F2_CURRENT_CORRESPONDENT_MEDIUM;
	}
	public void setF2_CURRENT_CORRESPONDENT_MEDIUM(String f2_CURRENT_CORRESPONDENT_MEDIUM) {
		F2_CURRENT_CORRESPONDENT_MEDIUM = f2_CURRENT_CORRESPONDENT_MEDIUM;
	}
	public String getF2_CURRENT_CORRESPONDENT_HIGH() {
		return F2_CURRENT_CORRESPONDENT_HIGH;
	}
	public void setF2_CURRENT_CORRESPONDENT_HIGH(String f2_CURRENT_CORRESPONDENT_HIGH) {
		F2_CURRENT_CORRESPONDENT_HIGH = f2_CURRENT_CORRESPONDENT_HIGH;
	}
	public String getD3_CURRENT_NON_PROFIT_ORGANIZATIONS_LOW() {
		return D3_CURRENT_NON_PROFIT_ORGANIZATIONS_LOW;
	}
	public void setD3_CURRENT_NON_PROFIT_ORGANIZATIONS_LOW(String d3_CURRENT_NON_PROFIT_ORGANIZATIONS_LOW) {
		D3_CURRENT_NON_PROFIT_ORGANIZATIONS_LOW = d3_CURRENT_NON_PROFIT_ORGANIZATIONS_LOW;
	}
	public String getE3_CURRENT_NON_PROFIT_ORGANIZATIONS_MEDIUM() {
		return E3_CURRENT_NON_PROFIT_ORGANIZATIONS_MEDIUM;
	}
	public void setE3_CURRENT_NON_PROFIT_ORGANIZATIONS_MEDIUM(String e3_CURRENT_NON_PROFIT_ORGANIZATIONS_MEDIUM) {
		E3_CURRENT_NON_PROFIT_ORGANIZATIONS_MEDIUM = e3_CURRENT_NON_PROFIT_ORGANIZATIONS_MEDIUM;
	}
	public String getF3_CURRENT_NON_PROFIT_ORGANIZATIONS_HIGH() {
		return F3_CURRENT_NON_PROFIT_ORGANIZATIONS_HIGH;
	}
	public void setF3_CURRENT_NON_PROFIT_ORGANIZATIONS_HIGH(String f3_CURRENT_NON_PROFIT_ORGANIZATIONS_HIGH) {
		F3_CURRENT_NON_PROFIT_ORGANIZATIONS_HIGH = f3_CURRENT_NON_PROFIT_ORGANIZATIONS_HIGH;
	}
	public String getD4_CURRENT_TRUSTS_OTHER_THAN_NPOS_AND_TCSPS_LOW() {
		return D4_CURRENT_TRUSTS_OTHER_THAN_NPOS_AND_TCSPS_LOW;
	}
	public void setD4_CURRENT_TRUSTS_OTHER_THAN_NPOS_AND_TCSPS_LOW(String d4_CURRENT_TRUSTS_OTHER_THAN_NPOS_AND_TCSPS_LOW) {
		D4_CURRENT_TRUSTS_OTHER_THAN_NPOS_AND_TCSPS_LOW = d4_CURRENT_TRUSTS_OTHER_THAN_NPOS_AND_TCSPS_LOW;
	}
	public String getE4_CURRENT_TRUSTS_OTHER_THAN_NPOS_AND_TCSPS_MEDIUM() {
		return E4_CURRENT_TRUSTS_OTHER_THAN_NPOS_AND_TCSPS_MEDIUM;
	}
	public void setE4_CURRENT_TRUSTS_OTHER_THAN_NPOS_AND_TCSPS_MEDIUM(
			String e4_CURRENT_TRUSTS_OTHER_THAN_NPOS_AND_TCSPS_MEDIUM) {
		E4_CURRENT_TRUSTS_OTHER_THAN_NPOS_AND_TCSPS_MEDIUM = e4_CURRENT_TRUSTS_OTHER_THAN_NPOS_AND_TCSPS_MEDIUM;
	}
	public String getF4_CURRENT_TRUSTS_OTHER_THAN_NPOS_AND_TCSPS_HIGH() {
		return F4_CURRENT_TRUSTS_OTHER_THAN_NPOS_AND_TCSPS_HIGH;
	}
	public void setF4_CURRENT_TRUSTS_OTHER_THAN_NPOS_AND_TCSPS_HIGH(
			String f4_CURRENT_TRUSTS_OTHER_THAN_NPOS_AND_TCSPS_HIGH) {
		F4_CURRENT_TRUSTS_OTHER_THAN_NPOS_AND_TCSPS_HIGH = f4_CURRENT_TRUSTS_OTHER_THAN_NPOS_AND_TCSPS_HIGH;
	}
	public String getD5_CURRENT_ALL_OTHERS_LOW() {
		return D5_CURRENT_ALL_OTHERS_LOW;
	}
	public void setD5_CURRENT_ALL_OTHERS_LOW(String d5_CURRENT_ALL_OTHERS_LOW) {
		D5_CURRENT_ALL_OTHERS_LOW = d5_CURRENT_ALL_OTHERS_LOW;
	}
	public String getE5_CURRENT_ALL_OTHERS_MEDIUM() {
		return E5_CURRENT_ALL_OTHERS_MEDIUM;
	}
	public void setE5_CURRENT_ALL_OTHERS_MEDIUM(String e5_CURRENT_ALL_OTHERS_MEDIUM) {
		E5_CURRENT_ALL_OTHERS_MEDIUM = e5_CURRENT_ALL_OTHERS_MEDIUM;
	}
	public String getF5_CURRENT_ALL_OTHERS_HIGH() {
		return F5_CURRENT_ALL_OTHERS_HIGH;
	}
	public void setF5_CURRENT_ALL_OTHERS_HIGH(String f5_CURRENT_ALL_OTHERS_HIGH) {
		F5_CURRENT_ALL_OTHERS_HIGH = f5_CURRENT_ALL_OTHERS_HIGH;
	}
	public String getD6_CURRENT_GBC_1_LOW() {
		return D6_CURRENT_GBC_1_LOW;
	}
	public void setD6_CURRENT_GBC_1_LOW(String d6_CURRENT_GBC_1_LOW) {
		D6_CURRENT_GBC_1_LOW = d6_CURRENT_GBC_1_LOW;
	}
	public String getE6_CURRENT_GBC_1_MEDIUM() {
		return E6_CURRENT_GBC_1_MEDIUM;
	}
	public void setE6_CURRENT_GBC_1_MEDIUM(String e6_CURRENT_GBC_1_MEDIUM) {
		E6_CURRENT_GBC_1_MEDIUM = e6_CURRENT_GBC_1_MEDIUM;
	}
	public String getF6_CURRENT_GBC_1_HIGH() {
		return F6_CURRENT_GBC_1_HIGH;
	}
	public void setF6_CURRENT_GBC_1_HIGH(String f6_CURRENT_GBC_1_HIGH) {
		F6_CURRENT_GBC_1_HIGH = f6_CURRENT_GBC_1_HIGH;
	}
	public String getD6_CURRENT_GBC_2_LOW() {
		return D6_CURRENT_GBC_2_LOW;
	}
	public void setD6_CURRENT_GBC_2_LOW(String d6_CURRENT_GBC_2_LOW) {
		D6_CURRENT_GBC_2_LOW = d6_CURRENT_GBC_2_LOW;
	}
	public String getE6_CURRENT_GBC_2_MEDIUM() {
		return E6_CURRENT_GBC_2_MEDIUM;
	}
	public void setE6_CURRENT_GBC_2_MEDIUM(String e6_CURRENT_GBC_2_MEDIUM) {
		E6_CURRENT_GBC_2_MEDIUM = e6_CURRENT_GBC_2_MEDIUM;
	}
	public String getF6_CURRENT_GBC_2_HIGH() {
		return F6_CURRENT_GBC_2_HIGH;
	}
	public void setF6_CURRENT_GBC_2_HIGH(String f6_CURRENT_GBC_2_HIGH) {
		F6_CURRENT_GBC_2_HIGH = f6_CURRENT_GBC_2_HIGH;
	}
	public String getD6_CURRENT_PEPS_DOMESTIC_LOW() {
		return D6_CURRENT_PEPS_DOMESTIC_LOW;
	}
	public void setD6_CURRENT_PEPS_DOMESTIC_LOW(String d6_CURRENT_PEPS_DOMESTIC_LOW) {
		D6_CURRENT_PEPS_DOMESTIC_LOW = d6_CURRENT_PEPS_DOMESTIC_LOW;
	}
	public String getE6_CURRENT_PEPS_DOMESTIC_MEDIUM() {
		return E6_CURRENT_PEPS_DOMESTIC_MEDIUM;
	}
	public void setE6_CURRENT_PEPS_DOMESTIC_MEDIUM(String e6_CURRENT_PEPS_DOMESTIC_MEDIUM) {
		E6_CURRENT_PEPS_DOMESTIC_MEDIUM = e6_CURRENT_PEPS_DOMESTIC_MEDIUM;
	}
	public String getF6_CURRENT_PEPS_DOMESTIC_HIGH() {
		return F6_CURRENT_PEPS_DOMESTIC_HIGH;
	}
	public void setF6_CURRENT_PEPS_DOMESTIC_HIGH(String f6_CURRENT_PEPS_DOMESTIC_HIGH) {
		F6_CURRENT_PEPS_DOMESTIC_HIGH = f6_CURRENT_PEPS_DOMESTIC_HIGH;
	}
	public String getD7_CURRENT_PEPS_FOREIGN_LOW() {
		return D7_CURRENT_PEPS_FOREIGN_LOW;
	}
	public void setD7_CURRENT_PEPS_FOREIGN_LOW(String d7_CURRENT_PEPS_FOREIGN_LOW) {
		D7_CURRENT_PEPS_FOREIGN_LOW = d7_CURRENT_PEPS_FOREIGN_LOW;
	}
	public String getE7_CURRENT_PEPS_FOREIGN_MEDIUM() {
		return E7_CURRENT_PEPS_FOREIGN_MEDIUM;
	}
	public void setE7_CURRENT_PEPS_FOREIGN_MEDIUM(String e7_CURRENT_PEPS_FOREIGN_MEDIUM) {
		E7_CURRENT_PEPS_FOREIGN_MEDIUM = e7_CURRENT_PEPS_FOREIGN_MEDIUM;
	}
	public String getF7_CURRENT_PEPS_FOREIGN_HIGH() {
		return F7_CURRENT_PEPS_FOREIGN_HIGH;
	}
	public void setF7_CURRENT_PEPS_FOREIGN_HIGH(String f7_CURRENT_PEPS_FOREIGN_HIGH) {
		F7_CURRENT_PEPS_FOREIGN_HIGH = f7_CURRENT_PEPS_FOREIGN_HIGH;
	}
	public String getD7_CURRENT_PBC_LOW() {
		return D7_CURRENT_PBC_LOW;
	}
	public void setD7_CURRENT_PBC_LOW(String d7_CURRENT_PBC_LOW) {
		D7_CURRENT_PBC_LOW = d7_CURRENT_PBC_LOW;
	}
	public String getE7_CURRENT_PBC_MEDIUM() {
		return E7_CURRENT_PBC_MEDIUM;
	}
	public void setE7_CURRENT_PBC_MEDIUM(String e7_CURRENT_PBC_MEDIUM) {
		E7_CURRENT_PBC_MEDIUM = e7_CURRENT_PBC_MEDIUM;
	}
	public String getF7_CURRENT_PBC_HIGH() {
		return F7_CURRENT_PBC_HIGH;
	}
	public void setF7_CURRENT_PBC_HIGH(String f7_CURRENT_PBC_HIGH) {
		F7_CURRENT_PBC_HIGH = f7_CURRENT_PBC_HIGH;
	}
	public String getD7_CURRENT_RELATED_PARTY_LOW() {
		return D7_CURRENT_RELATED_PARTY_LOW;
	}
	public void setD7_CURRENT_RELATED_PARTY_LOW(String d7_CURRENT_RELATED_PARTY_LOW) {
		D7_CURRENT_RELATED_PARTY_LOW = d7_CURRENT_RELATED_PARTY_LOW;
	}
	public String getE7_CURRENT_RELATED_PARTY_MEDIUM() {
		return E7_CURRENT_RELATED_PARTY_MEDIUM;
	}
	public void setE7_CURRENT_RELATED_PARTY_MEDIUM(String e7_CURRENT_RELATED_PARTY_MEDIUM) {
		E7_CURRENT_RELATED_PARTY_MEDIUM = e7_CURRENT_RELATED_PARTY_MEDIUM;
	}
	public String getF7_CURRENT_RELATED_PARTY_HIGH() {
		return F7_CURRENT_RELATED_PARTY_HIGH;
	}
	public void setF7_CURRENT_RELATED_PARTY_HIGH(String f7_CURRENT_RELATED_PARTY_HIGH) {
		F7_CURRENT_RELATED_PARTY_HIGH = f7_CURRENT_RELATED_PARTY_HIGH;
	}
	public String getD8_CURRENT_TRUST_AND_COMPANY_SERVICE_PROVIDERS_TCPS_LOW() {
		return D8_CURRENT_TRUST_AND_COMPANY_SERVICE_PROVIDERS_TCPS_LOW;
	}
	public void setD8_CURRENT_TRUST_AND_COMPANY_SERVICE_PROVIDERS_TCPS_LOW(
			String d8_CURRENT_TRUST_AND_COMPANY_SERVICE_PROVIDERS_TCPS_LOW) {
		D8_CURRENT_TRUST_AND_COMPANY_SERVICE_PROVIDERS_TCPS_LOW = d8_CURRENT_TRUST_AND_COMPANY_SERVICE_PROVIDERS_TCPS_LOW;
	}
	public String getE8_CURRENT_TRUST_AND_COMPANY_SERVICE_PROVIDERS_TCPS_MEDIUM() {
		return E8_CURRENT_TRUST_AND_COMPANY_SERVICE_PROVIDERS_TCPS_MEDIUM;
	}
	public void setE8_CURRENT_TRUST_AND_COMPANY_SERVICE_PROVIDERS_TCPS_MEDIUM(
			String e8_CURRENT_TRUST_AND_COMPANY_SERVICE_PROVIDERS_TCPS_MEDIUM) {
		E8_CURRENT_TRUST_AND_COMPANY_SERVICE_PROVIDERS_TCPS_MEDIUM = e8_CURRENT_TRUST_AND_COMPANY_SERVICE_PROVIDERS_TCPS_MEDIUM;
	}
	public String getF8_CURRENT_TRUST_AND_COMPANY_SERVICE_PROVIDERS_TCPS_HIGH() {
		return F8_CURRENT_TRUST_AND_COMPANY_SERVICE_PROVIDERS_TCPS_HIGH;
	}
	public void setF8_CURRENT_TRUST_AND_COMPANY_SERVICE_PROVIDERS_TCPS_HIGH(
			String f8_CURRENT_TRUST_AND_COMPANY_SERVICE_PROVIDERS_TCPS_HIGH) {
		F8_CURRENT_TRUST_AND_COMPANY_SERVICE_PROVIDERS_TCPS_HIGH = f8_CURRENT_TRUST_AND_COMPANY_SERVICE_PROVIDERS_TCPS_HIGH;
	}
	public Date getREPORT_DATE() {
		return REPORT_DATE;
	}
	public void setREPORT_DATE(Date rEPORT_DATE) {
		REPORT_DATE = rEPORT_DATE;
	}
	public Date getREPORT_DUE_DATE() {
		return REPORT_DUE_DATE;
	}
	public void setREPORT_DUE_DATE(Date rEPORT_DUE_DATE) {
		REPORT_DUE_DATE = rEPORT_DUE_DATE;
	}
	public Date getREP_SUBMIT_DATE() {
		return REP_SUBMIT_DATE;
	}
	public void setREP_SUBMIT_DATE(Date rEP_SUBMIT_DATE) {
		REP_SUBMIT_DATE = rEP_SUBMIT_DATE;
	}
	public Date getREP_PERIOD_FROM() {
		return REP_PERIOD_FROM;
	}
	public void setREP_PERIOD_FROM(Date rEP_PERIOD_FROM) {
		REP_PERIOD_FROM = rEP_PERIOD_FROM;
	}
	public Date getREP_PERIOD_TO() {
		return REP_PERIOD_TO;
	}
	public void setREP_PERIOD_TO(Date rEP_PERIOD_TO) {
		REP_PERIOD_TO = rEP_PERIOD_TO;
	}
	public String getREP_FREQ() {
		return REP_FREQ;
	}
	public void setREP_FREQ(String rEP_FREQ) {
		REP_FREQ = rEP_FREQ;
	}
	public String getNIL_REPORT_FLG() {
		return NIL_REPORT_FLG;
	}
	public void setNIL_REPORT_FLG(String nIL_REPORT_FLG) {
		NIL_REPORT_FLG = nIL_REPORT_FLG;
	}
	public String getSRL_NO() {
		return SRL_NO;
	}
	public void setSRL_NO(String sRL_NO) {
		SRL_NO = sRL_NO;
	}
	public String getENTITY_FLG() {
		return ENTITY_FLG;
	}
	public void setENTITY_FLG(String eNTITY_FLG) {
		ENTITY_FLG = eNTITY_FLG;
	}
	public String getMODIFY_FLG() {
		return MODIFY_FLG;
	}
	public void setMODIFY_FLG(String mODIFY_FLG) {
		MODIFY_FLG = mODIFY_FLG;
	}
	public T10Report() {
		super();
		// TODO Auto-generated constructor stub
	}
	public String getA1_PRODUCT() {
		return A1_PRODUCT;
	}
	public void setA1_PRODUCT(String a1_PRODUCT) {
		A1_PRODUCT = a1_PRODUCT;
	}
	public String getA2_PRODUCT() {
		return A2_PRODUCT;
	}
	public void setA2_PRODUCT(String a2_PRODUCT) {
		A2_PRODUCT = a2_PRODUCT;
	}
	public String getA3_PRODUCT() {
		return A3_PRODUCT;
	}
	public void setA3_PRODUCT(String a3_PRODUCT) {
		A3_PRODUCT = a3_PRODUCT;
	}
	public String getA4_PRODUCT() {
		return A4_PRODUCT;
	}
	public void setA4_PRODUCT(String a4_PRODUCT) {
		A4_PRODUCT = a4_PRODUCT;
	}
	public String getA5_PRODUCT() {
		return A5_PRODUCT;
	}
	public void setA5_PRODUCT(String a5_PRODUCT) {
		A5_PRODUCT = a5_PRODUCT;
	}
	public String getA6_PRODUCT() {
		return A6_PRODUCT;
	}
	public void setA6_PRODUCT(String a6_PRODUCT) {
		A6_PRODUCT = a6_PRODUCT;
	}
	public String getA7_PRODUCT() {
		return A7_PRODUCT;
	}
	public void setA7_PRODUCT(String a7_PRODUCT) {
		A7_PRODUCT = a7_PRODUCT;
	}
	public String getA8_PRODUCT() {
		return A8_PRODUCT;
	}
	public void setA8_PRODUCT(String a8_PRODUCT) {
		A8_PRODUCT = a8_PRODUCT;
	}
	public String getA9_PRODUCT() {
		return A9_PRODUCT;
	}
	public void setA9_PRODUCT(String a9_PRODUCT) {
		A9_PRODUCT = a9_PRODUCT;
	}
	public String getA10_PRODUCT() {
		return A10_PRODUCT;
	}
	public void setA10_PRODUCT(String a10_PRODUCT) {
		A10_PRODUCT = a10_PRODUCT;
	}
	public String getA11_PRODUCT() {
		return A11_PRODUCT;
	}
	public void setA11_PRODUCT(String a11_PRODUCT) {
		A11_PRODUCT = a11_PRODUCT;
	}
	public String getA12_PRODUCT() {
		return A12_PRODUCT;
	}
	public void setA12_PRODUCT(String a12_PRODUCT) {
		A12_PRODUCT = a12_PRODUCT;
	}
	public String getA13_PRODUCT() {
		return A13_PRODUCT;
	}
	public void setA13_PRODUCT(String a13_PRODUCT) {
		A13_PRODUCT = a13_PRODUCT;
	}
	public String getA14_PRODUCT() {
		return A14_PRODUCT;
	}
	public void setA14_PRODUCT(String a14_PRODUCT) {
		A14_PRODUCT = a14_PRODUCT;
	}
	public String getA15_PRODUCT() {
		return A15_PRODUCT;
	}
	public void setA15_PRODUCT(String a15_PRODUCT) {
		A15_PRODUCT = a15_PRODUCT;
	}
	public String getD7_CURRENT_EXEMPT_LOW() {
		return D7_CURRENT_EXEMPT_LOW;
	}
	public void setD7_CURRENT_EXEMPT_LOW(String d7_CURRENT_EXEMPT_LOW) {
		D7_CURRENT_EXEMPT_LOW = d7_CURRENT_EXEMPT_LOW;
	}
	public String getE7_CURRENT_EXEMPT_MEDIUM() {
		return E7_CURRENT_EXEMPT_MEDIUM;
	}
	public void setE7_CURRENT_EXEMPT_MEDIUM(String e7_CURRENT_EXEMPT_MEDIUM) {
		E7_CURRENT_EXEMPT_MEDIUM = e7_CURRENT_EXEMPT_MEDIUM;
	}
	public String getF7_CURRENT_EXEMPT_HIGH() {
		return F7_CURRENT_EXEMPT_HIGH;
	}
	public void setF7_CURRENT_EXEMPT_HIGH(String f7_CURRENT_EXEMPT_HIGH) {
		F7_CURRENT_EXEMPT_HIGH = f7_CURRENT_EXEMPT_HIGH;
	}
	public String getVERIFY_FLG() {
		return VERIFY_FLG;
	}
	public void setVERIFY_FLG(String vERIFY_FLG) {
		VERIFY_FLG = vERIFY_FLG;
	}
	public Date getENTRY_DATE() {
		return ENTRY_DATE;
	}
	public void setENTRY_DATE(Date eNTRY_DATE) {
		ENTRY_DATE = eNTRY_DATE;
	}
	public Date getMODIFY_DATE() {
		return MODIFY_DATE;
	}
	public void setMODIFY_DATE(Date mODIFY_DATE) {
		MODIFY_DATE = mODIFY_DATE;
	}
	public Date getVERIFY_DATE() {
		return VERIFY_DATE;
	}
	public void setVERIFY_DATE(Date vERIFY_DATE) {
		VERIFY_DATE = vERIFY_DATE;
	}
	public String getENTRY_USER() {
		return ENTRY_USER;
	}
	public void setENTRY_USER(String eNTRY_USER) {
		ENTRY_USER = eNTRY_USER;
	}
	public String getMODIFY_USER() {
		return MODIFY_USER;
	}
	public void setMODIFY_USER(String mODIFY_USER) {
		MODIFY_USER = mODIFY_USER;
	}
	public String getVERIFY_USER() {
		return VERIFY_USER;
	}
	public void setVERIFY_USER(String vERIFY_USER) {
		VERIFY_USER = vERIFY_USER;
	}
	public T10Report(String d1_CURRENT_INDIVIDUALS_LOW, String e1_CURRENT_INDIVIDUALS_MEDIUM,
			String f1_CURRENT_INDIVIDUALS_HIGH, String d2_CURRENT_CORPORATES_LOW, String e2_CURRENT_CORPORATES_MEDIUM,
			String f2_CURRENT_CORPORATES_HIGH, String f2_CURRENT_RESPONDENT_LOW, String f2_CURRENT_RESPONDENT_MEDIUM,
			String f2_CURRENT_RESPONDENT_HIGH, String f2_CURRENT_CORRESPONDENT_LOW,
			String f2_CURRENT_CORRESPONDENT_MEDIUM, String f2_CURRENT_CORRESPONDENT_HIGH,
			String d3_CURRENT_NON_PROFIT_ORGANIZATIONS_LOW, String e3_CURRENT_NON_PROFIT_ORGANIZATIONS_MEDIUM,
			String f3_CURRENT_NON_PROFIT_ORGANIZATIONS_HIGH, String d4_CURRENT_TRUSTS_OTHER_THAN_NPOS_AND_TCSPS_LOW,
			String e4_CURRENT_TRUSTS_OTHER_THAN_NPOS_AND_TCSPS_MEDIUM,
			String f4_CURRENT_TRUSTS_OTHER_THAN_NPOS_AND_TCSPS_HIGH, String d5_CURRENT_ALL_OTHERS_LOW,
			String e5_CURRENT_ALL_OTHERS_MEDIUM, String f5_CURRENT_ALL_OTHERS_HIGH, String d6_CURRENT_GBC_1_LOW,
			String e6_CURRENT_GBC_1_MEDIUM, String f6_CURRENT_GBC_1_HIGH, String d6_CURRENT_GBC_2_LOW,
			String e6_CURRENT_GBC_2_MEDIUM, String f6_CURRENT_GBC_2_HIGH, String d6_CURRENT_PEPS_DOMESTIC_LOW,
			String e6_CURRENT_PEPS_DOMESTIC_MEDIUM, String f6_CURRENT_PEPS_DOMESTIC_HIGH,
			String d7_CURRENT_PEPS_FOREIGN_LOW, String e7_CURRENT_PEPS_FOREIGN_MEDIUM,
			String f7_CURRENT_PEPS_FOREIGN_HIGH, String d7_CURRENT_PBC_LOW, String e7_CURRENT_PBC_MEDIUM,
			String f7_CURRENT_PBC_HIGH, String d7_CURRENT_RELATED_PARTY_LOW, String e7_CURRENT_RELATED_PARTY_MEDIUM,
			String f7_CURRENT_RELATED_PARTY_HIGH, String d8_CURRENT_TRUST_AND_COMPANY_SERVICE_PROVIDERS_TCPS_LOW,
			String e8_CURRENT_TRUST_AND_COMPANY_SERVICE_PROVIDERS_TCPS_MEDIUM,
			String f8_CURRENT_TRUST_AND_COMPANY_SERVICE_PROVIDERS_TCPS_HIGH, String d7_CURRENT_EXEMPT_LOW,
			String e7_CURRENT_EXEMPT_MEDIUM, String f7_CURRENT_EXEMPT_HIGH, String vERIFY_FLG, Date eNTRY_DATE,
			Date mODIFY_DATE, Date vERIFY_DATE, String eNTRY_USER, String mODIFY_USER, String vERIFY_USER,
			Date rEPORT_DATE, Date rEPORT_DUE_DATE, Date rEP_SUBMIT_DATE, Date rEP_PERIOD_FROM, Date rEP_PERIOD_TO,
			String rEP_FREQ, String nIL_REPORT_FLG, String sRL_NO, String eNTITY_FLG, String mODIFY_FLG,
			String a1_PRODUCT, String a2_PRODUCT, String a3_PRODUCT, String a4_PRODUCT, String a5_PRODUCT,
			String a6_PRODUCT, String a7_PRODUCT, String a8_PRODUCT, String a9_PRODUCT, String a10_PRODUCT,
			String a11_PRODUCT, String a12_PRODUCT, String a13_PRODUCT, String a14_PRODUCT, String a15_PRODUCT) {
		super();
		D1_CURRENT_INDIVIDUALS_LOW = d1_CURRENT_INDIVIDUALS_LOW;
		E1_CURRENT_INDIVIDUALS_MEDIUM = e1_CURRENT_INDIVIDUALS_MEDIUM;
		F1_CURRENT_INDIVIDUALS_HIGH = f1_CURRENT_INDIVIDUALS_HIGH;
		D2_CURRENT_CORPORATES_LOW = d2_CURRENT_CORPORATES_LOW;
		E2_CURRENT_CORPORATES_MEDIUM = e2_CURRENT_CORPORATES_MEDIUM;
		F2_CURRENT_CORPORATES_HIGH = f2_CURRENT_CORPORATES_HIGH;
		F2_CURRENT_RESPONDENT_LOW = f2_CURRENT_RESPONDENT_LOW;
		F2_CURRENT_RESPONDENT_MEDIUM = f2_CURRENT_RESPONDENT_MEDIUM;
		F2_CURRENT_RESPONDENT_HIGH = f2_CURRENT_RESPONDENT_HIGH;
		F2_CURRENT_CORRESPONDENT_LOW = f2_CURRENT_CORRESPONDENT_LOW;
		F2_CURRENT_CORRESPONDENT_MEDIUM = f2_CURRENT_CORRESPONDENT_MEDIUM;
		F2_CURRENT_CORRESPONDENT_HIGH = f2_CURRENT_CORRESPONDENT_HIGH;
		D3_CURRENT_NON_PROFIT_ORGANIZATIONS_LOW = d3_CURRENT_NON_PROFIT_ORGANIZATIONS_LOW;
		E3_CURRENT_NON_PROFIT_ORGANIZATIONS_MEDIUM = e3_CURRENT_NON_PROFIT_ORGANIZATIONS_MEDIUM;
		F3_CURRENT_NON_PROFIT_ORGANIZATIONS_HIGH = f3_CURRENT_NON_PROFIT_ORGANIZATIONS_HIGH;
		D4_CURRENT_TRUSTS_OTHER_THAN_NPOS_AND_TCSPS_LOW = d4_CURRENT_TRUSTS_OTHER_THAN_NPOS_AND_TCSPS_LOW;
		E4_CURRENT_TRUSTS_OTHER_THAN_NPOS_AND_TCSPS_MEDIUM = e4_CURRENT_TRUSTS_OTHER_THAN_NPOS_AND_TCSPS_MEDIUM;
		F4_CURRENT_TRUSTS_OTHER_THAN_NPOS_AND_TCSPS_HIGH = f4_CURRENT_TRUSTS_OTHER_THAN_NPOS_AND_TCSPS_HIGH;
		D5_CURRENT_ALL_OTHERS_LOW = d5_CURRENT_ALL_OTHERS_LOW;
		E5_CURRENT_ALL_OTHERS_MEDIUM = e5_CURRENT_ALL_OTHERS_MEDIUM;
		F5_CURRENT_ALL_OTHERS_HIGH = f5_CURRENT_ALL_OTHERS_HIGH;
		D6_CURRENT_GBC_1_LOW = d6_CURRENT_GBC_1_LOW;
		E6_CURRENT_GBC_1_MEDIUM = e6_CURRENT_GBC_1_MEDIUM;
		F6_CURRENT_GBC_1_HIGH = f6_CURRENT_GBC_1_HIGH;
		D6_CURRENT_GBC_2_LOW = d6_CURRENT_GBC_2_LOW;
		E6_CURRENT_GBC_2_MEDIUM = e6_CURRENT_GBC_2_MEDIUM;
		F6_CURRENT_GBC_2_HIGH = f6_CURRENT_GBC_2_HIGH;
		D6_CURRENT_PEPS_DOMESTIC_LOW = d6_CURRENT_PEPS_DOMESTIC_LOW;
		E6_CURRENT_PEPS_DOMESTIC_MEDIUM = e6_CURRENT_PEPS_DOMESTIC_MEDIUM;
		F6_CURRENT_PEPS_DOMESTIC_HIGH = f6_CURRENT_PEPS_DOMESTIC_HIGH;
		D7_CURRENT_PEPS_FOREIGN_LOW = d7_CURRENT_PEPS_FOREIGN_LOW;
		E7_CURRENT_PEPS_FOREIGN_MEDIUM = e7_CURRENT_PEPS_FOREIGN_MEDIUM;
		F7_CURRENT_PEPS_FOREIGN_HIGH = f7_CURRENT_PEPS_FOREIGN_HIGH;
		D7_CURRENT_PBC_LOW = d7_CURRENT_PBC_LOW;
		E7_CURRENT_PBC_MEDIUM = e7_CURRENT_PBC_MEDIUM;
		F7_CURRENT_PBC_HIGH = f7_CURRENT_PBC_HIGH;
		D7_CURRENT_RELATED_PARTY_LOW = d7_CURRENT_RELATED_PARTY_LOW;
		E7_CURRENT_RELATED_PARTY_MEDIUM = e7_CURRENT_RELATED_PARTY_MEDIUM;
		F7_CURRENT_RELATED_PARTY_HIGH = f7_CURRENT_RELATED_PARTY_HIGH;
		D8_CURRENT_TRUST_AND_COMPANY_SERVICE_PROVIDERS_TCPS_LOW = d8_CURRENT_TRUST_AND_COMPANY_SERVICE_PROVIDERS_TCPS_LOW;
		E8_CURRENT_TRUST_AND_COMPANY_SERVICE_PROVIDERS_TCPS_MEDIUM = e8_CURRENT_TRUST_AND_COMPANY_SERVICE_PROVIDERS_TCPS_MEDIUM;
		F8_CURRENT_TRUST_AND_COMPANY_SERVICE_PROVIDERS_TCPS_HIGH = f8_CURRENT_TRUST_AND_COMPANY_SERVICE_PROVIDERS_TCPS_HIGH;
		D7_CURRENT_EXEMPT_LOW = d7_CURRENT_EXEMPT_LOW;
		E7_CURRENT_EXEMPT_MEDIUM = e7_CURRENT_EXEMPT_MEDIUM;
		F7_CURRENT_EXEMPT_HIGH = f7_CURRENT_EXEMPT_HIGH;
		VERIFY_FLG = vERIFY_FLG;
		ENTRY_DATE = eNTRY_DATE;
		MODIFY_DATE = mODIFY_DATE;
		VERIFY_DATE = vERIFY_DATE;
		ENTRY_USER = eNTRY_USER;
		MODIFY_USER = mODIFY_USER;
		VERIFY_USER = vERIFY_USER;
		REPORT_DATE = rEPORT_DATE;
		REPORT_DUE_DATE = rEPORT_DUE_DATE;
		REP_SUBMIT_DATE = rEP_SUBMIT_DATE;
		REP_PERIOD_FROM = rEP_PERIOD_FROM;
		REP_PERIOD_TO = rEP_PERIOD_TO;
		REP_FREQ = rEP_FREQ;
		NIL_REPORT_FLG = nIL_REPORT_FLG;
		SRL_NO = sRL_NO;
		ENTITY_FLG = eNTITY_FLG;
		MODIFY_FLG = mODIFY_FLG;
		A1_PRODUCT = a1_PRODUCT;
		A2_PRODUCT = a2_PRODUCT;
		A3_PRODUCT = a3_PRODUCT;
		A4_PRODUCT = a4_PRODUCT;
		A5_PRODUCT = a5_PRODUCT;
		A6_PRODUCT = a6_PRODUCT;
		A7_PRODUCT = a7_PRODUCT;
		A8_PRODUCT = a8_PRODUCT;
		A9_PRODUCT = a9_PRODUCT;
		A10_PRODUCT = a10_PRODUCT;
		A11_PRODUCT = a11_PRODUCT;
		A12_PRODUCT = a12_PRODUCT;
		A13_PRODUCT = a13_PRODUCT;
		A14_PRODUCT = a14_PRODUCT;
		A15_PRODUCT = a15_PRODUCT;
	}
	

	
	
}
