package com.bornfire.xbrl.entities.BRSS;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;
@Entity
@Table(name = "T12A_TRAN_CUST_TYPE_TABLE")
public class T12AReport {

	
	private String	CASH_DEP_PRODUCT;
	private BigDecimal	CASH_DEP_LOW_TRAN_COUNT;
	private BigDecimal	CASH_DEP_LOW_TRAN_AMT;
	private BigDecimal	CASH_DEPMED_TRAN_COUNT;
	private BigDecimal	CASH_DEPMED_TRAN_AMT;
	private BigDecimal	CASH_DEPHIGH_TRAN_COUNT;
	private BigDecimal	CASH_DEPHIGH_TRAN_AMT;
	private String	CASH_WITHD_PRODUCT;
	private BigDecimal	CASH_WITHD_LOW_TRAN_COUNT;
	private BigDecimal	CASH_WITHD_LOW_TRAN_AMT;
	private BigDecimal	CASH_WITHDMED_TRAN_COUNT;
	private BigDecimal	CASH_WITHDMED_TRAN_AMT;
	private BigDecimal	CASH_WITHDHIGH_TRAN_COUNT;
	private BigDecimal	CASH_WITHDHIGH_TRAN_AMT;
	private String	FX_SALE_EQL_PRODUCT;
	private BigDecimal	FX_SALE_EQL_LOW_TRAN_COUNT;
	private BigDecimal	FX_SALE_EQL_LOW_TRAN_AMT;
	private BigDecimal	FX_SALE_EQLMED_TRAN_COUNT;
	private BigDecimal	FX_SALE_EQLMED_TRAN_AMT;
	private BigDecimal	FX_SALE_EQLHIGH_TRAN_COUNT;
	private BigDecimal	FX_SALE_EQLHIGH_TRAN_AMT;
	private String	FX_SALE_MORE_PRODUCT;
	private BigDecimal	FX_SALE_MORE_LOW_TRAN_COUNT;
	private BigDecimal	FX_SALE_MORE_LOW_TRAN_AMT;
	private BigDecimal	FX_SALE_MOREMED_TRAN_COUNT;
	private BigDecimal	FX_SALE_MOREMED_TRAN_AMT;
	private BigDecimal	FX_SALE_MOREHIGH_TRAN_COUNT;
	private BigDecimal	FX_SALE_MOREHIGH_TRAN_AMT;
	private String	FX_PUR_EQL_PRODUCT;
	private BigDecimal	FX_PUR_EQL_LOW_TRAN_COUNT;
	private BigDecimal	FX_PUR_EQL_LOW_TRAN_AMT;
	private BigDecimal	FX_PUR_EQLMED_TRAN_COUNT;
	private BigDecimal	FX_PUR_EQLMED_TRAN_AMT;
	private BigDecimal	FX_PUR_EQLHIGH_TRAN_COUNT;
	private BigDecimal	FX_PUR_EQLHIGH_TRAN_AMT;
	private String	FX_PUR_MORE_PRODUCT;
	private BigDecimal	FX_PUR_MORE_LOW_TRAN_COUNT;
	private BigDecimal	FX_PUR_MORE_LOW_TRAN_AMT;
	private BigDecimal	FX_PUR_MOREMED_TRAN_COUNT;
	private BigDecimal	FX_PUR_MOREMED_TRAN_AMT;
	private BigDecimal	FX_PUR_MOREHIGH_TRAN_COUNT;
	private BigDecimal	FX_PUR_MOREHIGH_TRAN_AMT;
	private String	DOM_INW_PRODUCT;
	private BigDecimal	DOM_INW_LOW_TRAN_COUNT;
	private BigDecimal	DOM_INW_LOW_TRAN_AMT;
	private BigDecimal	DOM_INWMED_TRAN_COUNT;
	private BigDecimal	DOM_INWMED_TRAN_AMT;
	private BigDecimal	DOM_INWHIGH_TRAN_COUNT;
	private BigDecimal	DOM_INWHIGH_TRAN_AMT;
	private String	DOM_OUT_PRODUCT;
	private BigDecimal	DOM_OUT_LOW_TRAN_COUNT;
	private BigDecimal	DOM_OUT_LOW_TRAN_AMT;
	private BigDecimal	DOM_OUTMED_TRAN_COUNT;
	private BigDecimal	DOM_OUTMED_TRAN_AMT;
	private BigDecimal	DOM_OUTHIGH_TRAN_COUNT;
	private BigDecimal	DOM_OUTHIGH_TRAN_AMT;
	private String	INT_TRADE_INW_PRODUCT;
	private BigDecimal	INT_TRADE_INW_LOW_TRAN_COUNT;
	private BigDecimal	INT_TRADE_INW_LOW_TRAN_AMT;
	private BigDecimal	INT_TRADE_INWMED_TRAN_COUNT;
	private BigDecimal	INT_TRADE_INWMED_TRAN_AMT;
	private BigDecimal	INT_TRADE_INWHIGH_TRAN_COUNT;
	private BigDecimal	INT_TRADE_INWHIGH_TRAN_AMT;
	private String	INT_TRADE_OUT_PRODUCT;
	private BigDecimal	INT_TRADE_OUT_LOW_TRAN_COUNT;
	private BigDecimal	INT_TRADE_OUT_LOW_TRAN_AMT;
	private BigDecimal	INT_TRADE_OUTMED_TRAN_COUNT;
	private BigDecimal	INT_TRADE_OUTMED_TRAN_AMT;
	private BigDecimal	INT_TRADE_OUTHIGH_TRAN_COUNT;
	private BigDecimal	INT_TRADE_OUTHIGH_TRAN_AMT;
	private String	INT_NON_TRADE_INW_PRODUCT;
	private BigDecimal	INT_NON_TRADE_INW_LOW_TRAN_COUNT;
	private BigDecimal	INT_NON_TRADE_INW_LOW_TRAN_AMT;
	private BigDecimal	INT_NON_TRADE_INWMED_TRAN_COUNT;
	private BigDecimal	INT_NON_TRADE_INWMED_TRAN_AMT;
	private BigDecimal	INT_NON_TRADE_INWHIGH_TRAN_COUNT;
	private BigDecimal	INT_NON_TRADE_INWHIGH_TRAN_AMT;
	private String	INT_NON_TRADE_OUT_PRODUCT;
	private BigDecimal	INT_NON_TRADE_OUT_LOW_TRAN_COUNT;
	private BigDecimal	INT_NON_TRADE_OUT_LOW_TRAN_AMT;
	private BigDecimal	INT_NON_TRADE_OUTMED_TRAN_COUNT;
	private BigDecimal	INT_NON_TRADE_OUTMED_TRAN_AMT;
	private BigDecimal	INT_NON_TRADE_OUTHIGH_TRAN_COUNT;
	private BigDecimal	INT_NON_TRADE_OUTHIGH_TRAN_AMT;
	private String	ALL_OTH_TRANSFER_DEB_PRODUCT;
	private BigDecimal	ALL_OTH_TRANSFER_DEB_LOW_TRAN_COUNT;
	private BigDecimal	ALL_OTH_TRANSFER_DEB_LOW_TRAN_AMT;
	private BigDecimal	ALL_OTH_TRANSFER_DEBMED_TRAN_COUNT;
	private BigDecimal	ALL_OTH_TRANSFER_DEBMED_TRAN_AMT;
	private BigDecimal	ALL_OTH_TRANSFER_DEBHIGH_TRAN_COUNT;
	private BigDecimal	ALL_OTH_TRANSFER_DEBHIGH_TRAN_AMT;
	private String	ALL_OTH_TRANSFER_CRED_PRODUCT;
	private BigDecimal	ALL_OTH_TRANSFER_CRED_LOW_TRAN_COUNT;
	private BigDecimal	ALL_OTH_TRANSFER_CRED_LOW_TRAN_AMT;
	private BigDecimal	ALL_OTH_TRANSFER_CREDMED_TRAN_COUNT;
	private BigDecimal	ALL_OTH_TRANSFER_CREDMED_TRAN_AMT;
	private BigDecimal	ALL_OTH_TRANSFER_CREDHIGH_TRAN_COUNT;
	private BigDecimal	ALL_OTH_TRANSFER_CREDHIGH_TRAN_AMT;
	private String	ALL_OTH_INW_PRODUCT;
	private BigDecimal	ALL_OTH_INW_LOW_TRAN_COUNT;
	private BigDecimal	ALL_OTH_INW_LOW_TRAN_AMT;
	private BigDecimal	ALL_OTH_INWMED_TRAN_COUNT;
	private BigDecimal	ALL_OTH_INWMED_TRAN_AMT;
	private BigDecimal	ALL_OTH_INWHIGH_TRAN_COUNT;
	private BigDecimal	ALL_OTH_INWHIGH_TRAN_AMT;
	private String	ALL_OTH_OUT_PRODUCT;
	private BigDecimal	ALL_OTH_OUT_LOW_TRAN_COUNT;
	private BigDecimal	ALL_OTH_OUT_LOW_TRAN_AMT;
	private BigDecimal	ALL_OTH_OUTMED_TRAN_COUNT;
	private BigDecimal	ALL_OTH_OUTMED_TRAN_AMT;
	private BigDecimal	ALL_OTH_OUTHIGH_TRAN_COUNT;
	private BigDecimal	ALL_OTH_OUTHIGH_TRAN_AMT;
	private String	OTHER_FEES_PRODUCT;
	private BigDecimal	OTHER_FEES_LOW_TRAN_COUNT;
	private BigDecimal	OTHER_FEES_LOW_TRAN_AMT;
	private BigDecimal	OTHER_FEESMED_TRAN_COUNT;
	private BigDecimal	OTHER_FEESMED_TRAN_AMT;
	private BigDecimal	OTHER_FEESHIGH_TRAN_COUNT;
	private BigDecimal	OTHER_FEESHIGH_TRAN_AMT;
	private String	TOTAL_SUM_PRODUCT;
	private BigDecimal	TOTAL_SUM_LOW_TRAN_COUNT;
	private BigDecimal	TOTAL_SUM_LOW_TRAN_AMT;
	private BigDecimal	TOTAL_SUMMED_TRAN_COUNT;
	private BigDecimal	TOTAL_SUMMED_TRAN_AMT;
	private BigDecimal	TOTAL_SUMHIGH_TRAN_COUNT;
	private BigDecimal	TOTAL_SUMHIGH_TRAN_AMT;
	private String	THIRD_TRAN_500K_INW_PRODUCT;
	private BigDecimal	THIRD_TRAN_500K_INW_LOW_TRAN_COUNT;
	private BigDecimal	THIRD_TRAN_500K_INW_LOW_TRAN_AMT;
	private BigDecimal	THIRD_TRAN_500K_INWMED_TRAN_COUNT;
	private BigDecimal	THIRD_TRAN_500K_INWMED_TRAN_AMT;
	private BigDecimal	THIRD_TRAN_500K_INWHIGH_TRAN_COUNT;
	private BigDecimal	THIRD_TRAN_500K_INWHIGH_TRAN_AMT;
	private String	THIRD_TRAN_500K_OUT_PRODUCT;
	private BigDecimal	THIRD_TRAN_500K_OUT_LOW_TRAN_COUNT;
	private BigDecimal	THIRD_TRAN_500K_OUT_LOW_TRAN_AMT;
	private BigDecimal	THIRD_TRAN_500K_OUTMED_TRAN_COUNT;
	private BigDecimal	THIRD_TRAN_500K_OUTMED_TRAN_AMT;
	private BigDecimal	THIRD_TRAN_500K_OUTHIGH_TRAN_COUNT;
	private BigDecimal	THIRD_TRAN_500K_OUTHIGH_TRAN_AMT;
	private String	THIRD_TRAN_1000K_INW_PRODUCT;
	private BigDecimal	THIRD_TRAN_1000K_INW_LOW_TRAN_COUNT;
	private BigDecimal	THIRD_TRAN_1000K_INW_LOW_TRAN_AMT;
	private BigDecimal	THIRD_TRAN_1000K_INWMED_TRAN_COUNT;
	private BigDecimal	THIRD_TRAN_1000K_INWMED_TRAN_AMT;
	private BigDecimal	THIRD_TRAN_1000K_INWHIGH_TRAN_COUNT;
	private BigDecimal	THIRD_TRAN_1000K_INWHIGH_TRAN_AMT;
	private String	THIRD_TRAN_1000K_OUT_PRODUCT;
	private BigDecimal	THIRD_TRAN_1000K_OUT_LOW_TRAN_COUNT;
	private BigDecimal	THIRD_TRAN_1000K_OUT_LOW_TRAN_AMT;
	private BigDecimal	THIRD_TRAN_1000K_OUTMED_TRAN_COUNT;
	private BigDecimal	THIRD_TRAN_1000K_OUTMED_TRAN_AMT;
	private BigDecimal	THIRD_TRAN_1000K_OUTHIGH_TRAN_COUNT;
	private BigDecimal	THIRD_TRAN_1000K_OUTHIGH_TRAN_AMT;
	private String	THIRD_TRAN_MORE_1000K_INW_PRODUCT;
	private BigDecimal	THIRD_TRAN_MORE_1000K_INW_LOW_TRAN_COUNT;
	private BigDecimal	THIRD_TRAN_MORE_1000K_INW_LOW_TRAN_AMT;
	private BigDecimal	THIRD_TRAN_MORE_1000K_INWMED_TRAN_COUNT;
	private BigDecimal	THIRD_TRAN_MORE_1000K_INWMED_TRAN_AMT;
	private BigDecimal	THIRD_TRAN_MORE_1000K_INWHIGH_TRAN_COUNT;
	private BigDecimal	THIRD_TRAN_MORE_1000K_INWHIGH_TRAN_AMT;
	private String	THIRD_TRAN_MORE_1000K_OUT_PRODUCT;
	private BigDecimal	THIRD_TRAN_MORE_1000K_OUT_LOW_TRAN_COUNT;
	private BigDecimal	THIRD_TRAN_MORE_1000K_OUT_LOW_TRAN_AMT;
	private BigDecimal	THIRD_TRAN_MORE_1000K_OUTMED_TRAN_COUNT;
	private BigDecimal	THIRD_TRAN_MORE_1000K_OUTMED_TRAN_AMT;
	private BigDecimal	THIRD_TRAN_MORE_1000K_OUTHIGH_TRAN_COUNT;
	private BigDecimal	THIRD_TRAN_MORE_1000K_OUTHIGH_TRAN_AMT;
	private String	DEBIT_CARD_PRODUCT;
	private BigDecimal	DEBIT_CARD_LOW_TRAN_COUNT;
	private BigDecimal	DEBIT_CARD_LOW_TRAN_AMT;
	private BigDecimal	DEBIT_CARDMED_TRAN_COUNT;
	private BigDecimal	DEBIT_CARDMED_TRAN_AMT;
	private BigDecimal	DEBIT_CARDHIGH_TRAN_COUNT;
	private BigDecimal	DEBIT_CARDHIGH_TRAN_AMT;
	private String	CREDIT_CARD_PRODUCT;
	private BigDecimal	CREDIT_CARD_LOW_TRAN_COUNT;
	private BigDecimal	CREDIT_CARD_LOW_TRAN_AMT;
	private BigDecimal	CREDIT_CARDMED_TRAN_COUNT;
	private BigDecimal	CREDIT_CARDMED_TRAN_AMT;
	private BigDecimal	CREDIT_CARDHIGH_TRAN_COUNT;
	private BigDecimal	CREDIT_CARDHIGH_TRAN_AMT;
	private String	PREPAID_CARD_PRODUCT;
	private BigDecimal	PREPAID_CARD_LOW_TRAN_COUNT;
	private BigDecimal	PREPAID_CARD_LOW_TRAN_AMT;
	private BigDecimal	PREPAID_CARDMED_TRAN_COUNT;
	private BigDecimal	PREPAID_CARDMED_TRAN_AMT;
	private BigDecimal	PREPAID_CARDHIGH_TRAN_COUNT;
	private BigDecimal	PREPAID_CARDHIGH_TRAN_AMT;
	private String	MOB_BANKING_INW_PRODUCT;
	private BigDecimal	MOB_BANKING_INW_LOW_TRAN_COUNT;
	private BigDecimal	MOB_BANKING_INW_LOW_TRAN_AMT;
	private BigDecimal	MOB_BANKING_INWMED_TRAN_COUNT;
	private BigDecimal	MOB_BANKING_INWMED_TRAN_AMT;
	private BigDecimal	MOB_BANKING_INWHIGH_TRAN_COUNT;
	private BigDecimal	MOB_BANKING_INWHIGH_TRAN_AMT;
	private String	MOB_BANKING_OUT_PRODUCT;
	private BigDecimal	MOB_BANKING_OUT_LOW_TRAN_COUNT;
	private BigDecimal	MOB_BANKING_OUT_LOW_TRAN_AMT;
	private BigDecimal	MOB_BANKING_OUTMED_TRAN_COUNT;
	private BigDecimal	MOB_BANKING_OUTMED_TRAN_AMT;
	private BigDecimal	MOB_BANKING_OUTHIGH_TRAN_COUNT;
	private BigDecimal	MOB_BANKING_OUTHIGH_TRAN_AMT;
	private String	INTERNET_INW_PRODUCT;
	private BigDecimal	INTERNET_INW_LOW_TRAN_COUNT;
	private BigDecimal	INTERNET_INW_LOW_TRAN_AMT;
	private BigDecimal	INTERNET_INWMED_TRAN_COUNT;
	private BigDecimal	INTERNET_INWMED_TRAN_AMT;
	private BigDecimal	INTERNET_INWHIGH_TRAN_COUNT;
	private BigDecimal	INTERNET_INWHIGH_TRAN_AMT;
	private String	INTERNET_OUT_PRODUCT;
	private BigDecimal	INTERNET_OUT_LOW_TRAN_COUNT;
	private BigDecimal	INTERNET_OUT_LOW_TRAN_AMT;
	private BigDecimal	INTERNET_OUTMED_TRAN_COUNT;
	private BigDecimal	INTERNET_OUTMED_TRAN_AMT;
	private BigDecimal	INTERNET_OUTHIGH_TRAN_COUNT;
	private BigDecimal	INTERNET_OUTHIGH_TRAN_AMT;
	private String	REPORT_CODE;
	private String	REPORT_NAME;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	@Id
	private Date	REPORT_DATE;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	REPORT_DUE_DATE;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	REP_SUBMIT_DATE;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	REP_PERIOD_FROM;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	REP_PERIOD_TO;
	private String	REP_FREQ;
	private String	NIL_REPORT_FLG;
	private String	ARCH_FLG;
	public String getCASH_DEP_PRODUCT() {
		return CASH_DEP_PRODUCT;
	}
	public void setCASH_DEP_PRODUCT(String cASH_DEP_PRODUCT) {
		CASH_DEP_PRODUCT = cASH_DEP_PRODUCT;
	}
	public BigDecimal getCASH_DEP_LOW_TRAN_COUNT() {
		return CASH_DEP_LOW_TRAN_COUNT;
	}
	public void setCASH_DEP_LOW_TRAN_COUNT(BigDecimal cASH_DEP_LOW_TRAN_COUNT) {
		CASH_DEP_LOW_TRAN_COUNT = cASH_DEP_LOW_TRAN_COUNT;
	}
	public BigDecimal getCASH_DEP_LOW_TRAN_AMT() {
		return CASH_DEP_LOW_TRAN_AMT;
	}
	public void setCASH_DEP_LOW_TRAN_AMT(BigDecimal cASH_DEP_LOW_TRAN_AMT) {
		CASH_DEP_LOW_TRAN_AMT = cASH_DEP_LOW_TRAN_AMT;
	}
	public BigDecimal getCASH_DEPMED_TRAN_COUNT() {
		return CASH_DEPMED_TRAN_COUNT;
	}
	public void setCASH_DEPMED_TRAN_COUNT(BigDecimal cASH_DEPMED_TRAN_COUNT) {
		CASH_DEPMED_TRAN_COUNT = cASH_DEPMED_TRAN_COUNT;
	}
	public BigDecimal getCASH_DEPMED_TRAN_AMT() {
		return CASH_DEPMED_TRAN_AMT;
	}
	public void setCASH_DEPMED_TRAN_AMT(BigDecimal cASH_DEPMED_TRAN_AMT) {
		CASH_DEPMED_TRAN_AMT = cASH_DEPMED_TRAN_AMT;
	}
	public BigDecimal getCASH_DEPHIGH_TRAN_COUNT() {
		return CASH_DEPHIGH_TRAN_COUNT;
	}
	public void setCASH_DEPHIGH_TRAN_COUNT(BigDecimal cASH_DEPHIGH_TRAN_COUNT) {
		CASH_DEPHIGH_TRAN_COUNT = cASH_DEPHIGH_TRAN_COUNT;
	}
	public BigDecimal getCASH_DEPHIGH_TRAN_AMT() {
		return CASH_DEPHIGH_TRAN_AMT;
	}
	public void setCASH_DEPHIGH_TRAN_AMT(BigDecimal cASH_DEPHIGH_TRAN_AMT) {
		CASH_DEPHIGH_TRAN_AMT = cASH_DEPHIGH_TRAN_AMT;
	}
	public String getCASH_WITHD_PRODUCT() {
		return CASH_WITHD_PRODUCT;
	}
	public void setCASH_WITHD_PRODUCT(String cASH_WITHD_PRODUCT) {
		CASH_WITHD_PRODUCT = cASH_WITHD_PRODUCT;
	}
	public BigDecimal getCASH_WITHD_LOW_TRAN_COUNT() {
		return CASH_WITHD_LOW_TRAN_COUNT;
	}
	public void setCASH_WITHD_LOW_TRAN_COUNT(BigDecimal cASH_WITHD_LOW_TRAN_COUNT) {
		CASH_WITHD_LOW_TRAN_COUNT = cASH_WITHD_LOW_TRAN_COUNT;
	}
	public BigDecimal getCASH_WITHD_LOW_TRAN_AMT() {
		return CASH_WITHD_LOW_TRAN_AMT;
	}
	public void setCASH_WITHD_LOW_TRAN_AMT(BigDecimal cASH_WITHD_LOW_TRAN_AMT) {
		CASH_WITHD_LOW_TRAN_AMT = cASH_WITHD_LOW_TRAN_AMT;
	}
	public BigDecimal getCASH_WITHDMED_TRAN_COUNT() {
		return CASH_WITHDMED_TRAN_COUNT;
	}
	public void setCASH_WITHDMED_TRAN_COUNT(BigDecimal cASH_WITHDMED_TRAN_COUNT) {
		CASH_WITHDMED_TRAN_COUNT = cASH_WITHDMED_TRAN_COUNT;
	}
	public BigDecimal getCASH_WITHDMED_TRAN_AMT() {
		return CASH_WITHDMED_TRAN_AMT;
	}
	public void setCASH_WITHDMED_TRAN_AMT(BigDecimal cASH_WITHDMED_TRAN_AMT) {
		CASH_WITHDMED_TRAN_AMT = cASH_WITHDMED_TRAN_AMT;
	}
	public BigDecimal getCASH_WITHDHIGH_TRAN_COUNT() {
		return CASH_WITHDHIGH_TRAN_COUNT;
	}
	public void setCASH_WITHDHIGH_TRAN_COUNT(BigDecimal cASH_WITHDHIGH_TRAN_COUNT) {
		CASH_WITHDHIGH_TRAN_COUNT = cASH_WITHDHIGH_TRAN_COUNT;
	}
	public BigDecimal getCASH_WITHDHIGH_TRAN_AMT() {
		return CASH_WITHDHIGH_TRAN_AMT;
	}
	public void setCASH_WITHDHIGH_TRAN_AMT(BigDecimal cASH_WITHDHIGH_TRAN_AMT) {
		CASH_WITHDHIGH_TRAN_AMT = cASH_WITHDHIGH_TRAN_AMT;
	}
	public String getFX_SALE_EQL_PRODUCT() {
		return FX_SALE_EQL_PRODUCT;
	}
	public void setFX_SALE_EQL_PRODUCT(String fX_SALE_EQL_PRODUCT) {
		FX_SALE_EQL_PRODUCT = fX_SALE_EQL_PRODUCT;
	}
	public BigDecimal getFX_SALE_EQL_LOW_TRAN_COUNT() {
		return FX_SALE_EQL_LOW_TRAN_COUNT;
	}
	public void setFX_SALE_EQL_LOW_TRAN_COUNT(BigDecimal fX_SALE_EQL_LOW_TRAN_COUNT) {
		FX_SALE_EQL_LOW_TRAN_COUNT = fX_SALE_EQL_LOW_TRAN_COUNT;
	}
	public BigDecimal getFX_SALE_EQL_LOW_TRAN_AMT() {
		return FX_SALE_EQL_LOW_TRAN_AMT;
	}
	public void setFX_SALE_EQL_LOW_TRAN_AMT(BigDecimal fX_SALE_EQL_LOW_TRAN_AMT) {
		FX_SALE_EQL_LOW_TRAN_AMT = fX_SALE_EQL_LOW_TRAN_AMT;
	}
	public BigDecimal getFX_SALE_EQLMED_TRAN_COUNT() {
		return FX_SALE_EQLMED_TRAN_COUNT;
	}
	public void setFX_SALE_EQLMED_TRAN_COUNT(BigDecimal fX_SALE_EQLMED_TRAN_COUNT) {
		FX_SALE_EQLMED_TRAN_COUNT = fX_SALE_EQLMED_TRAN_COUNT;
	}
	public BigDecimal getFX_SALE_EQLMED_TRAN_AMT() {
		return FX_SALE_EQLMED_TRAN_AMT;
	}
	public void setFX_SALE_EQLMED_TRAN_AMT(BigDecimal fX_SALE_EQLMED_TRAN_AMT) {
		FX_SALE_EQLMED_TRAN_AMT = fX_SALE_EQLMED_TRAN_AMT;
	}
	public BigDecimal getFX_SALE_EQLHIGH_TRAN_COUNT() {
		return FX_SALE_EQLHIGH_TRAN_COUNT;
	}
	public void setFX_SALE_EQLHIGH_TRAN_COUNT(BigDecimal fX_SALE_EQLHIGH_TRAN_COUNT) {
		FX_SALE_EQLHIGH_TRAN_COUNT = fX_SALE_EQLHIGH_TRAN_COUNT;
	}
	public BigDecimal getFX_SALE_EQLHIGH_TRAN_AMT() {
		return FX_SALE_EQLHIGH_TRAN_AMT;
	}
	public void setFX_SALE_EQLHIGH_TRAN_AMT(BigDecimal fX_SALE_EQLHIGH_TRAN_AMT) {
		FX_SALE_EQLHIGH_TRAN_AMT = fX_SALE_EQLHIGH_TRAN_AMT;
	}
	public String getFX_SALE_MORE_PRODUCT() {
		return FX_SALE_MORE_PRODUCT;
	}
	public void setFX_SALE_MORE_PRODUCT(String fX_SALE_MORE_PRODUCT) {
		FX_SALE_MORE_PRODUCT = fX_SALE_MORE_PRODUCT;
	}
	public BigDecimal getFX_SALE_MORE_LOW_TRAN_COUNT() {
		return FX_SALE_MORE_LOW_TRAN_COUNT;
	}
	public void setFX_SALE_MORE_LOW_TRAN_COUNT(BigDecimal fX_SALE_MORE_LOW_TRAN_COUNT) {
		FX_SALE_MORE_LOW_TRAN_COUNT = fX_SALE_MORE_LOW_TRAN_COUNT;
	}
	public BigDecimal getFX_SALE_MORE_LOW_TRAN_AMT() {
		return FX_SALE_MORE_LOW_TRAN_AMT;
	}
	public void setFX_SALE_MORE_LOW_TRAN_AMT(BigDecimal fX_SALE_MORE_LOW_TRAN_AMT) {
		FX_SALE_MORE_LOW_TRAN_AMT = fX_SALE_MORE_LOW_TRAN_AMT;
	}
	public BigDecimal getFX_SALE_MOREMED_TRAN_COUNT() {
		return FX_SALE_MOREMED_TRAN_COUNT;
	}
	public void setFX_SALE_MOREMED_TRAN_COUNT(BigDecimal fX_SALE_MOREMED_TRAN_COUNT) {
		FX_SALE_MOREMED_TRAN_COUNT = fX_SALE_MOREMED_TRAN_COUNT;
	}
	public BigDecimal getFX_SALE_MOREMED_TRAN_AMT() {
		return FX_SALE_MOREMED_TRAN_AMT;
	}
	public void setFX_SALE_MOREMED_TRAN_AMT(BigDecimal fX_SALE_MOREMED_TRAN_AMT) {
		FX_SALE_MOREMED_TRAN_AMT = fX_SALE_MOREMED_TRAN_AMT;
	}
	public BigDecimal getFX_SALE_MOREHIGH_TRAN_COUNT() {
		return FX_SALE_MOREHIGH_TRAN_COUNT;
	}
	public void setFX_SALE_MOREHIGH_TRAN_COUNT(BigDecimal fX_SALE_MOREHIGH_TRAN_COUNT) {
		FX_SALE_MOREHIGH_TRAN_COUNT = fX_SALE_MOREHIGH_TRAN_COUNT;
	}
	public BigDecimal getFX_SALE_MOREHIGH_TRAN_AMT() {
		return FX_SALE_MOREHIGH_TRAN_AMT;
	}
	public void setFX_SALE_MOREHIGH_TRAN_AMT(BigDecimal fX_SALE_MOREHIGH_TRAN_AMT) {
		FX_SALE_MOREHIGH_TRAN_AMT = fX_SALE_MOREHIGH_TRAN_AMT;
	}
	public String getFX_PUR_EQL_PRODUCT() {
		return FX_PUR_EQL_PRODUCT;
	}
	public void setFX_PUR_EQL_PRODUCT(String fX_PUR_EQL_PRODUCT) {
		FX_PUR_EQL_PRODUCT = fX_PUR_EQL_PRODUCT;
	}
	public BigDecimal getFX_PUR_EQL_LOW_TRAN_COUNT() {
		return FX_PUR_EQL_LOW_TRAN_COUNT;
	}
	public void setFX_PUR_EQL_LOW_TRAN_COUNT(BigDecimal fX_PUR_EQL_LOW_TRAN_COUNT) {
		FX_PUR_EQL_LOW_TRAN_COUNT = fX_PUR_EQL_LOW_TRAN_COUNT;
	}
	public BigDecimal getFX_PUR_EQL_LOW_TRAN_AMT() {
		return FX_PUR_EQL_LOW_TRAN_AMT;
	}
	public void setFX_PUR_EQL_LOW_TRAN_AMT(BigDecimal fX_PUR_EQL_LOW_TRAN_AMT) {
		FX_PUR_EQL_LOW_TRAN_AMT = fX_PUR_EQL_LOW_TRAN_AMT;
	}
	public BigDecimal getFX_PUR_EQLMED_TRAN_COUNT() {
		return FX_PUR_EQLMED_TRAN_COUNT;
	}
	public void setFX_PUR_EQLMED_TRAN_COUNT(BigDecimal fX_PUR_EQLMED_TRAN_COUNT) {
		FX_PUR_EQLMED_TRAN_COUNT = fX_PUR_EQLMED_TRAN_COUNT;
	}
	public BigDecimal getFX_PUR_EQLMED_TRAN_AMT() {
		return FX_PUR_EQLMED_TRAN_AMT;
	}
	public void setFX_PUR_EQLMED_TRAN_AMT(BigDecimal fX_PUR_EQLMED_TRAN_AMT) {
		FX_PUR_EQLMED_TRAN_AMT = fX_PUR_EQLMED_TRAN_AMT;
	}
	public BigDecimal getFX_PUR_EQLHIGH_TRAN_COUNT() {
		return FX_PUR_EQLHIGH_TRAN_COUNT;
	}
	public void setFX_PUR_EQLHIGH_TRAN_COUNT(BigDecimal fX_PUR_EQLHIGH_TRAN_COUNT) {
		FX_PUR_EQLHIGH_TRAN_COUNT = fX_PUR_EQLHIGH_TRAN_COUNT;
	}
	public BigDecimal getFX_PUR_EQLHIGH_TRAN_AMT() {
		return FX_PUR_EQLHIGH_TRAN_AMT;
	}
	public void setFX_PUR_EQLHIGH_TRAN_AMT(BigDecimal fX_PUR_EQLHIGH_TRAN_AMT) {
		FX_PUR_EQLHIGH_TRAN_AMT = fX_PUR_EQLHIGH_TRAN_AMT;
	}
	public String getFX_PUR_MORE_PRODUCT() {
		return FX_PUR_MORE_PRODUCT;
	}
	public void setFX_PUR_MORE_PRODUCT(String fX_PUR_MORE_PRODUCT) {
		FX_PUR_MORE_PRODUCT = fX_PUR_MORE_PRODUCT;
	}
	public BigDecimal getFX_PUR_MORE_LOW_TRAN_COUNT() {
		return FX_PUR_MORE_LOW_TRAN_COUNT;
	}
	public void setFX_PUR_MORE_LOW_TRAN_COUNT(BigDecimal fX_PUR_MORE_LOW_TRAN_COUNT) {
		FX_PUR_MORE_LOW_TRAN_COUNT = fX_PUR_MORE_LOW_TRAN_COUNT;
	}
	public BigDecimal getFX_PUR_MORE_LOW_TRAN_AMT() {
		return FX_PUR_MORE_LOW_TRAN_AMT;
	}
	public void setFX_PUR_MORE_LOW_TRAN_AMT(BigDecimal fX_PUR_MORE_LOW_TRAN_AMT) {
		FX_PUR_MORE_LOW_TRAN_AMT = fX_PUR_MORE_LOW_TRAN_AMT;
	}
	public BigDecimal getFX_PUR_MOREMED_TRAN_COUNT() {
		return FX_PUR_MOREMED_TRAN_COUNT;
	}
	public void setFX_PUR_MOREMED_TRAN_COUNT(BigDecimal fX_PUR_MOREMED_TRAN_COUNT) {
		FX_PUR_MOREMED_TRAN_COUNT = fX_PUR_MOREMED_TRAN_COUNT;
	}
	public BigDecimal getFX_PUR_MOREMED_TRAN_AMT() {
		return FX_PUR_MOREMED_TRAN_AMT;
	}
	public void setFX_PUR_MOREMED_TRAN_AMT(BigDecimal fX_PUR_MOREMED_TRAN_AMT) {
		FX_PUR_MOREMED_TRAN_AMT = fX_PUR_MOREMED_TRAN_AMT;
	}
	public BigDecimal getFX_PUR_MOREHIGH_TRAN_COUNT() {
		return FX_PUR_MOREHIGH_TRAN_COUNT;
	}
	public void setFX_PUR_MOREHIGH_TRAN_COUNT(BigDecimal fX_PUR_MOREHIGH_TRAN_COUNT) {
		FX_PUR_MOREHIGH_TRAN_COUNT = fX_PUR_MOREHIGH_TRAN_COUNT;
	}
	public BigDecimal getFX_PUR_MOREHIGH_TRAN_AMT() {
		return FX_PUR_MOREHIGH_TRAN_AMT;
	}
	public void setFX_PUR_MOREHIGH_TRAN_AMT(BigDecimal fX_PUR_MOREHIGH_TRAN_AMT) {
		FX_PUR_MOREHIGH_TRAN_AMT = fX_PUR_MOREHIGH_TRAN_AMT;
	}
	public String getDOM_INW_PRODUCT() {
		return DOM_INW_PRODUCT;
	}
	public void setDOM_INW_PRODUCT(String dOM_INW_PRODUCT) {
		DOM_INW_PRODUCT = dOM_INW_PRODUCT;
	}
	public BigDecimal getDOM_INW_LOW_TRAN_COUNT() {
		return DOM_INW_LOW_TRAN_COUNT;
	}
	public void setDOM_INW_LOW_TRAN_COUNT(BigDecimal dOM_INW_LOW_TRAN_COUNT) {
		DOM_INW_LOW_TRAN_COUNT = dOM_INW_LOW_TRAN_COUNT;
	}
	public BigDecimal getDOM_INW_LOW_TRAN_AMT() {
		return DOM_INW_LOW_TRAN_AMT;
	}
	public void setDOM_INW_LOW_TRAN_AMT(BigDecimal dOM_INW_LOW_TRAN_AMT) {
		DOM_INW_LOW_TRAN_AMT = dOM_INW_LOW_TRAN_AMT;
	}
	public BigDecimal getDOM_INWMED_TRAN_COUNT() {
		return DOM_INWMED_TRAN_COUNT;
	}
	public void setDOM_INWMED_TRAN_COUNT(BigDecimal dOM_INWMED_TRAN_COUNT) {
		DOM_INWMED_TRAN_COUNT = dOM_INWMED_TRAN_COUNT;
	}
	public BigDecimal getDOM_INWMED_TRAN_AMT() {
		return DOM_INWMED_TRAN_AMT;
	}
	public void setDOM_INWMED_TRAN_AMT(BigDecimal dOM_INWMED_TRAN_AMT) {
		DOM_INWMED_TRAN_AMT = dOM_INWMED_TRAN_AMT;
	}
	public BigDecimal getDOM_INWHIGH_TRAN_COUNT() {
		return DOM_INWHIGH_TRAN_COUNT;
	}
	public void setDOM_INWHIGH_TRAN_COUNT(BigDecimal dOM_INWHIGH_TRAN_COUNT) {
		DOM_INWHIGH_TRAN_COUNT = dOM_INWHIGH_TRAN_COUNT;
	}
	public BigDecimal getDOM_INWHIGH_TRAN_AMT() {
		return DOM_INWHIGH_TRAN_AMT;
	}
	public void setDOM_INWHIGH_TRAN_AMT(BigDecimal dOM_INWHIGH_TRAN_AMT) {
		DOM_INWHIGH_TRAN_AMT = dOM_INWHIGH_TRAN_AMT;
	}
	public String getDOM_OUT_PRODUCT() {
		return DOM_OUT_PRODUCT;
	}
	public void setDOM_OUT_PRODUCT(String dOM_OUT_PRODUCT) {
		DOM_OUT_PRODUCT = dOM_OUT_PRODUCT;
	}
	public BigDecimal getDOM_OUT_LOW_TRAN_COUNT() {
		return DOM_OUT_LOW_TRAN_COUNT;
	}
	public void setDOM_OUT_LOW_TRAN_COUNT(BigDecimal dOM_OUT_LOW_TRAN_COUNT) {
		DOM_OUT_LOW_TRAN_COUNT = dOM_OUT_LOW_TRAN_COUNT;
	}
	public BigDecimal getDOM_OUT_LOW_TRAN_AMT() {
		return DOM_OUT_LOW_TRAN_AMT;
	}
	public void setDOM_OUT_LOW_TRAN_AMT(BigDecimal dOM_OUT_LOW_TRAN_AMT) {
		DOM_OUT_LOW_TRAN_AMT = dOM_OUT_LOW_TRAN_AMT;
	}
	public BigDecimal getDOM_OUTMED_TRAN_COUNT() {
		return DOM_OUTMED_TRAN_COUNT;
	}
	public void setDOM_OUTMED_TRAN_COUNT(BigDecimal dOM_OUTMED_TRAN_COUNT) {
		DOM_OUTMED_TRAN_COUNT = dOM_OUTMED_TRAN_COUNT;
	}
	public BigDecimal getDOM_OUTMED_TRAN_AMT() {
		return DOM_OUTMED_TRAN_AMT;
	}
	public void setDOM_OUTMED_TRAN_AMT(BigDecimal dOM_OUTMED_TRAN_AMT) {
		DOM_OUTMED_TRAN_AMT = dOM_OUTMED_TRAN_AMT;
	}
	public BigDecimal getDOM_OUTHIGH_TRAN_COUNT() {
		return DOM_OUTHIGH_TRAN_COUNT;
	}
	public void setDOM_OUTHIGH_TRAN_COUNT(BigDecimal dOM_OUTHIGH_TRAN_COUNT) {
		DOM_OUTHIGH_TRAN_COUNT = dOM_OUTHIGH_TRAN_COUNT;
	}
	public BigDecimal getDOM_OUTHIGH_TRAN_AMT() {
		return DOM_OUTHIGH_TRAN_AMT;
	}
	public void setDOM_OUTHIGH_TRAN_AMT(BigDecimal dOM_OUTHIGH_TRAN_AMT) {
		DOM_OUTHIGH_TRAN_AMT = dOM_OUTHIGH_TRAN_AMT;
	}
	public String getINT_TRADE_INW_PRODUCT() {
		return INT_TRADE_INW_PRODUCT;
	}
	public void setINT_TRADE_INW_PRODUCT(String iNT_TRADE_INW_PRODUCT) {
		INT_TRADE_INW_PRODUCT = iNT_TRADE_INW_PRODUCT;
	}
	public BigDecimal getINT_TRADE_INW_LOW_TRAN_COUNT() {
		return INT_TRADE_INW_LOW_TRAN_COUNT;
	}
	public void setINT_TRADE_INW_LOW_TRAN_COUNT(BigDecimal iNT_TRADE_INW_LOW_TRAN_COUNT) {
		INT_TRADE_INW_LOW_TRAN_COUNT = iNT_TRADE_INW_LOW_TRAN_COUNT;
	}
	public BigDecimal getINT_TRADE_INW_LOW_TRAN_AMT() {
		return INT_TRADE_INW_LOW_TRAN_AMT;
	}
	public void setINT_TRADE_INW_LOW_TRAN_AMT(BigDecimal iNT_TRADE_INW_LOW_TRAN_AMT) {
		INT_TRADE_INW_LOW_TRAN_AMT = iNT_TRADE_INW_LOW_TRAN_AMT;
	}
	public BigDecimal getINT_TRADE_INWMED_TRAN_COUNT() {
		return INT_TRADE_INWMED_TRAN_COUNT;
	}
	public void setINT_TRADE_INWMED_TRAN_COUNT(BigDecimal iNT_TRADE_INWMED_TRAN_COUNT) {
		INT_TRADE_INWMED_TRAN_COUNT = iNT_TRADE_INWMED_TRAN_COUNT;
	}
	public BigDecimal getINT_TRADE_INWMED_TRAN_AMT() {
		return INT_TRADE_INWMED_TRAN_AMT;
	}
	public void setINT_TRADE_INWMED_TRAN_AMT(BigDecimal iNT_TRADE_INWMED_TRAN_AMT) {
		INT_TRADE_INWMED_TRAN_AMT = iNT_TRADE_INWMED_TRAN_AMT;
	}
	public BigDecimal getINT_TRADE_INWHIGH_TRAN_COUNT() {
		return INT_TRADE_INWHIGH_TRAN_COUNT;
	}
	public void setINT_TRADE_INWHIGH_TRAN_COUNT(BigDecimal iNT_TRADE_INWHIGH_TRAN_COUNT) {
		INT_TRADE_INWHIGH_TRAN_COUNT = iNT_TRADE_INWHIGH_TRAN_COUNT;
	}
	public BigDecimal getINT_TRADE_INWHIGH_TRAN_AMT() {
		return INT_TRADE_INWHIGH_TRAN_AMT;
	}
	public void setINT_TRADE_INWHIGH_TRAN_AMT(BigDecimal iNT_TRADE_INWHIGH_TRAN_AMT) {
		INT_TRADE_INWHIGH_TRAN_AMT = iNT_TRADE_INWHIGH_TRAN_AMT;
	}
	public String getINT_TRADE_OUT_PRODUCT() {
		return INT_TRADE_OUT_PRODUCT;
	}
	public void setINT_TRADE_OUT_PRODUCT(String iNT_TRADE_OUT_PRODUCT) {
		INT_TRADE_OUT_PRODUCT = iNT_TRADE_OUT_PRODUCT;
	}
	public BigDecimal getINT_TRADE_OUT_LOW_TRAN_COUNT() {
		return INT_TRADE_OUT_LOW_TRAN_COUNT;
	}
	public void setINT_TRADE_OUT_LOW_TRAN_COUNT(BigDecimal iNT_TRADE_OUT_LOW_TRAN_COUNT) {
		INT_TRADE_OUT_LOW_TRAN_COUNT = iNT_TRADE_OUT_LOW_TRAN_COUNT;
	}
	public BigDecimal getINT_TRADE_OUT_LOW_TRAN_AMT() {
		return INT_TRADE_OUT_LOW_TRAN_AMT;
	}
	public void setINT_TRADE_OUT_LOW_TRAN_AMT(BigDecimal iNT_TRADE_OUT_LOW_TRAN_AMT) {
		INT_TRADE_OUT_LOW_TRAN_AMT = iNT_TRADE_OUT_LOW_TRAN_AMT;
	}
	public BigDecimal getINT_TRADE_OUTMED_TRAN_COUNT() {
		return INT_TRADE_OUTMED_TRAN_COUNT;
	}
	public void setINT_TRADE_OUTMED_TRAN_COUNT(BigDecimal iNT_TRADE_OUTMED_TRAN_COUNT) {
		INT_TRADE_OUTMED_TRAN_COUNT = iNT_TRADE_OUTMED_TRAN_COUNT;
	}
	public BigDecimal getINT_TRADE_OUTMED_TRAN_AMT() {
		return INT_TRADE_OUTMED_TRAN_AMT;
	}
	public void setINT_TRADE_OUTMED_TRAN_AMT(BigDecimal iNT_TRADE_OUTMED_TRAN_AMT) {
		INT_TRADE_OUTMED_TRAN_AMT = iNT_TRADE_OUTMED_TRAN_AMT;
	}
	public BigDecimal getINT_TRADE_OUTHIGH_TRAN_COUNT() {
		return INT_TRADE_OUTHIGH_TRAN_COUNT;
	}
	public void setINT_TRADE_OUTHIGH_TRAN_COUNT(BigDecimal iNT_TRADE_OUTHIGH_TRAN_COUNT) {
		INT_TRADE_OUTHIGH_TRAN_COUNT = iNT_TRADE_OUTHIGH_TRAN_COUNT;
	}
	public BigDecimal getINT_TRADE_OUTHIGH_TRAN_AMT() {
		return INT_TRADE_OUTHIGH_TRAN_AMT;
	}
	public void setINT_TRADE_OUTHIGH_TRAN_AMT(BigDecimal iNT_TRADE_OUTHIGH_TRAN_AMT) {
		INT_TRADE_OUTHIGH_TRAN_AMT = iNT_TRADE_OUTHIGH_TRAN_AMT;
	}
	public String getINT_NON_TRADE_INW_PRODUCT() {
		return INT_NON_TRADE_INW_PRODUCT;
	}
	public void setINT_NON_TRADE_INW_PRODUCT(String iNT_NON_TRADE_INW_PRODUCT) {
		INT_NON_TRADE_INW_PRODUCT = iNT_NON_TRADE_INW_PRODUCT;
	}
	public BigDecimal getINT_NON_TRADE_INW_LOW_TRAN_COUNT() {
		return INT_NON_TRADE_INW_LOW_TRAN_COUNT;
	}
	public void setINT_NON_TRADE_INW_LOW_TRAN_COUNT(BigDecimal iNT_NON_TRADE_INW_LOW_TRAN_COUNT) {
		INT_NON_TRADE_INW_LOW_TRAN_COUNT = iNT_NON_TRADE_INW_LOW_TRAN_COUNT;
	}
	public BigDecimal getINT_NON_TRADE_INW_LOW_TRAN_AMT() {
		return INT_NON_TRADE_INW_LOW_TRAN_AMT;
	}
	public void setINT_NON_TRADE_INW_LOW_TRAN_AMT(BigDecimal iNT_NON_TRADE_INW_LOW_TRAN_AMT) {
		INT_NON_TRADE_INW_LOW_TRAN_AMT = iNT_NON_TRADE_INW_LOW_TRAN_AMT;
	}
	public BigDecimal getINT_NON_TRADE_INWMED_TRAN_COUNT() {
		return INT_NON_TRADE_INWMED_TRAN_COUNT;
	}
	public void setINT_NON_TRADE_INWMED_TRAN_COUNT(BigDecimal iNT_NON_TRADE_INWMED_TRAN_COUNT) {
		INT_NON_TRADE_INWMED_TRAN_COUNT = iNT_NON_TRADE_INWMED_TRAN_COUNT;
	}
	public BigDecimal getINT_NON_TRADE_INWMED_TRAN_AMT() {
		return INT_NON_TRADE_INWMED_TRAN_AMT;
	}
	public void setINT_NON_TRADE_INWMED_TRAN_AMT(BigDecimal iNT_NON_TRADE_INWMED_TRAN_AMT) {
		INT_NON_TRADE_INWMED_TRAN_AMT = iNT_NON_TRADE_INWMED_TRAN_AMT;
	}
	public BigDecimal getINT_NON_TRADE_INWHIGH_TRAN_COUNT() {
		return INT_NON_TRADE_INWHIGH_TRAN_COUNT;
	}
	public void setINT_NON_TRADE_INWHIGH_TRAN_COUNT(BigDecimal iNT_NON_TRADE_INWHIGH_TRAN_COUNT) {
		INT_NON_TRADE_INWHIGH_TRAN_COUNT = iNT_NON_TRADE_INWHIGH_TRAN_COUNT;
	}
	public BigDecimal getINT_NON_TRADE_INWHIGH_TRAN_AMT() {
		return INT_NON_TRADE_INWHIGH_TRAN_AMT;
	}
	public void setINT_NON_TRADE_INWHIGH_TRAN_AMT(BigDecimal iNT_NON_TRADE_INWHIGH_TRAN_AMT) {
		INT_NON_TRADE_INWHIGH_TRAN_AMT = iNT_NON_TRADE_INWHIGH_TRAN_AMT;
	}
	public String getINT_NON_TRADE_OUT_PRODUCT() {
		return INT_NON_TRADE_OUT_PRODUCT;
	}
	public void setINT_NON_TRADE_OUT_PRODUCT(String iNT_NON_TRADE_OUT_PRODUCT) {
		INT_NON_TRADE_OUT_PRODUCT = iNT_NON_TRADE_OUT_PRODUCT;
	}
	public BigDecimal getINT_NON_TRADE_OUT_LOW_TRAN_COUNT() {
		return INT_NON_TRADE_OUT_LOW_TRAN_COUNT;
	}
	public void setINT_NON_TRADE_OUT_LOW_TRAN_COUNT(BigDecimal iNT_NON_TRADE_OUT_LOW_TRAN_COUNT) {
		INT_NON_TRADE_OUT_LOW_TRAN_COUNT = iNT_NON_TRADE_OUT_LOW_TRAN_COUNT;
	}
	public BigDecimal getINT_NON_TRADE_OUT_LOW_TRAN_AMT() {
		return INT_NON_TRADE_OUT_LOW_TRAN_AMT;
	}
	public void setINT_NON_TRADE_OUT_LOW_TRAN_AMT(BigDecimal iNT_NON_TRADE_OUT_LOW_TRAN_AMT) {
		INT_NON_TRADE_OUT_LOW_TRAN_AMT = iNT_NON_TRADE_OUT_LOW_TRAN_AMT;
	}
	public BigDecimal getINT_NON_TRADE_OUTMED_TRAN_COUNT() {
		return INT_NON_TRADE_OUTMED_TRAN_COUNT;
	}
	public void setINT_NON_TRADE_OUTMED_TRAN_COUNT(BigDecimal iNT_NON_TRADE_OUTMED_TRAN_COUNT) {
		INT_NON_TRADE_OUTMED_TRAN_COUNT = iNT_NON_TRADE_OUTMED_TRAN_COUNT;
	}
	public BigDecimal getINT_NON_TRADE_OUTMED_TRAN_AMT() {
		return INT_NON_TRADE_OUTMED_TRAN_AMT;
	}
	public void setINT_NON_TRADE_OUTMED_TRAN_AMT(BigDecimal iNT_NON_TRADE_OUTMED_TRAN_AMT) {
		INT_NON_TRADE_OUTMED_TRAN_AMT = iNT_NON_TRADE_OUTMED_TRAN_AMT;
	}
	public BigDecimal getINT_NON_TRADE_OUTHIGH_TRAN_COUNT() {
		return INT_NON_TRADE_OUTHIGH_TRAN_COUNT;
	}
	public void setINT_NON_TRADE_OUTHIGH_TRAN_COUNT(BigDecimal iNT_NON_TRADE_OUTHIGH_TRAN_COUNT) {
		INT_NON_TRADE_OUTHIGH_TRAN_COUNT = iNT_NON_TRADE_OUTHIGH_TRAN_COUNT;
	}
	public BigDecimal getINT_NON_TRADE_OUTHIGH_TRAN_AMT() {
		return INT_NON_TRADE_OUTHIGH_TRAN_AMT;
	}
	public void setINT_NON_TRADE_OUTHIGH_TRAN_AMT(BigDecimal iNT_NON_TRADE_OUTHIGH_TRAN_AMT) {
		INT_NON_TRADE_OUTHIGH_TRAN_AMT = iNT_NON_TRADE_OUTHIGH_TRAN_AMT;
	}
	public String getALL_OTH_TRANSFER_DEB_PRODUCT() {
		return ALL_OTH_TRANSFER_DEB_PRODUCT;
	}
	public void setALL_OTH_TRANSFER_DEB_PRODUCT(String aLL_OTH_TRANSFER_DEB_PRODUCT) {
		ALL_OTH_TRANSFER_DEB_PRODUCT = aLL_OTH_TRANSFER_DEB_PRODUCT;
	}
	public BigDecimal getALL_OTH_TRANSFER_DEB_LOW_TRAN_COUNT() {
		return ALL_OTH_TRANSFER_DEB_LOW_TRAN_COUNT;
	}
	public void setALL_OTH_TRANSFER_DEB_LOW_TRAN_COUNT(BigDecimal aLL_OTH_TRANSFER_DEB_LOW_TRAN_COUNT) {
		ALL_OTH_TRANSFER_DEB_LOW_TRAN_COUNT = aLL_OTH_TRANSFER_DEB_LOW_TRAN_COUNT;
	}
	public BigDecimal getALL_OTH_TRANSFER_DEB_LOW_TRAN_AMT() {
		return ALL_OTH_TRANSFER_DEB_LOW_TRAN_AMT;
	}
	public void setALL_OTH_TRANSFER_DEB_LOW_TRAN_AMT(BigDecimal aLL_OTH_TRANSFER_DEB_LOW_TRAN_AMT) {
		ALL_OTH_TRANSFER_DEB_LOW_TRAN_AMT = aLL_OTH_TRANSFER_DEB_LOW_TRAN_AMT;
	}
	public BigDecimal getALL_OTH_TRANSFER_DEBMED_TRAN_COUNT() {
		return ALL_OTH_TRANSFER_DEBMED_TRAN_COUNT;
	}
	public void setALL_OTH_TRANSFER_DEBMED_TRAN_COUNT(BigDecimal aLL_OTH_TRANSFER_DEBMED_TRAN_COUNT) {
		ALL_OTH_TRANSFER_DEBMED_TRAN_COUNT = aLL_OTH_TRANSFER_DEBMED_TRAN_COUNT;
	}
	public BigDecimal getALL_OTH_TRANSFER_DEBMED_TRAN_AMT() {
		return ALL_OTH_TRANSFER_DEBMED_TRAN_AMT;
	}
	public void setALL_OTH_TRANSFER_DEBMED_TRAN_AMT(BigDecimal aLL_OTH_TRANSFER_DEBMED_TRAN_AMT) {
		ALL_OTH_TRANSFER_DEBMED_TRAN_AMT = aLL_OTH_TRANSFER_DEBMED_TRAN_AMT;
	}
	public BigDecimal getALL_OTH_TRANSFER_DEBHIGH_TRAN_COUNT() {
		return ALL_OTH_TRANSFER_DEBHIGH_TRAN_COUNT;
	}
	public void setALL_OTH_TRANSFER_DEBHIGH_TRAN_COUNT(BigDecimal aLL_OTH_TRANSFER_DEBHIGH_TRAN_COUNT) {
		ALL_OTH_TRANSFER_DEBHIGH_TRAN_COUNT = aLL_OTH_TRANSFER_DEBHIGH_TRAN_COUNT;
	}
	public BigDecimal getALL_OTH_TRANSFER_DEBHIGH_TRAN_AMT() {
		return ALL_OTH_TRANSFER_DEBHIGH_TRAN_AMT;
	}
	public void setALL_OTH_TRANSFER_DEBHIGH_TRAN_AMT(BigDecimal aLL_OTH_TRANSFER_DEBHIGH_TRAN_AMT) {
		ALL_OTH_TRANSFER_DEBHIGH_TRAN_AMT = aLL_OTH_TRANSFER_DEBHIGH_TRAN_AMT;
	}
	public String getALL_OTH_TRANSFER_CRED_PRODUCT() {
		return ALL_OTH_TRANSFER_CRED_PRODUCT;
	}
	public void setALL_OTH_TRANSFER_CRED_PRODUCT(String aLL_OTH_TRANSFER_CRED_PRODUCT) {
		ALL_OTH_TRANSFER_CRED_PRODUCT = aLL_OTH_TRANSFER_CRED_PRODUCT;
	}
	public BigDecimal getALL_OTH_TRANSFER_CRED_LOW_TRAN_COUNT() {
		return ALL_OTH_TRANSFER_CRED_LOW_TRAN_COUNT;
	}
	public void setALL_OTH_TRANSFER_CRED_LOW_TRAN_COUNT(BigDecimal aLL_OTH_TRANSFER_CRED_LOW_TRAN_COUNT) {
		ALL_OTH_TRANSFER_CRED_LOW_TRAN_COUNT = aLL_OTH_TRANSFER_CRED_LOW_TRAN_COUNT;
	}
	public BigDecimal getALL_OTH_TRANSFER_CRED_LOW_TRAN_AMT() {
		return ALL_OTH_TRANSFER_CRED_LOW_TRAN_AMT;
	}
	public void setALL_OTH_TRANSFER_CRED_LOW_TRAN_AMT(BigDecimal aLL_OTH_TRANSFER_CRED_LOW_TRAN_AMT) {
		ALL_OTH_TRANSFER_CRED_LOW_TRAN_AMT = aLL_OTH_TRANSFER_CRED_LOW_TRAN_AMT;
	}
	public BigDecimal getALL_OTH_TRANSFER_CREDMED_TRAN_COUNT() {
		return ALL_OTH_TRANSFER_CREDMED_TRAN_COUNT;
	}
	public void setALL_OTH_TRANSFER_CREDMED_TRAN_COUNT(BigDecimal aLL_OTH_TRANSFER_CREDMED_TRAN_COUNT) {
		ALL_OTH_TRANSFER_CREDMED_TRAN_COUNT = aLL_OTH_TRANSFER_CREDMED_TRAN_COUNT;
	}
	public BigDecimal getALL_OTH_TRANSFER_CREDMED_TRAN_AMT() {
		return ALL_OTH_TRANSFER_CREDMED_TRAN_AMT;
	}
	public void setALL_OTH_TRANSFER_CREDMED_TRAN_AMT(BigDecimal aLL_OTH_TRANSFER_CREDMED_TRAN_AMT) {
		ALL_OTH_TRANSFER_CREDMED_TRAN_AMT = aLL_OTH_TRANSFER_CREDMED_TRAN_AMT;
	}
	public BigDecimal getALL_OTH_TRANSFER_CREDHIGH_TRAN_COUNT() {
		return ALL_OTH_TRANSFER_CREDHIGH_TRAN_COUNT;
	}
	public void setALL_OTH_TRANSFER_CREDHIGH_TRAN_COUNT(BigDecimal aLL_OTH_TRANSFER_CREDHIGH_TRAN_COUNT) {
		ALL_OTH_TRANSFER_CREDHIGH_TRAN_COUNT = aLL_OTH_TRANSFER_CREDHIGH_TRAN_COUNT;
	}
	public BigDecimal getALL_OTH_TRANSFER_CREDHIGH_TRAN_AMT() {
		return ALL_OTH_TRANSFER_CREDHIGH_TRAN_AMT;
	}
	public void setALL_OTH_TRANSFER_CREDHIGH_TRAN_AMT(BigDecimal aLL_OTH_TRANSFER_CREDHIGH_TRAN_AMT) {
		ALL_OTH_TRANSFER_CREDHIGH_TRAN_AMT = aLL_OTH_TRANSFER_CREDHIGH_TRAN_AMT;
	}
	public String getALL_OTH_INW_PRODUCT() {
		return ALL_OTH_INW_PRODUCT;
	}
	public void setALL_OTH_INW_PRODUCT(String aLL_OTH_INW_PRODUCT) {
		ALL_OTH_INW_PRODUCT = aLL_OTH_INW_PRODUCT;
	}
	public BigDecimal getALL_OTH_INW_LOW_TRAN_COUNT() {
		return ALL_OTH_INW_LOW_TRAN_COUNT;
	}
	public void setALL_OTH_INW_LOW_TRAN_COUNT(BigDecimal aLL_OTH_INW_LOW_TRAN_COUNT) {
		ALL_OTH_INW_LOW_TRAN_COUNT = aLL_OTH_INW_LOW_TRAN_COUNT;
	}
	public BigDecimal getALL_OTH_INW_LOW_TRAN_AMT() {
		return ALL_OTH_INW_LOW_TRAN_AMT;
	}
	public void setALL_OTH_INW_LOW_TRAN_AMT(BigDecimal aLL_OTH_INW_LOW_TRAN_AMT) {
		ALL_OTH_INW_LOW_TRAN_AMT = aLL_OTH_INW_LOW_TRAN_AMT;
	}
	public BigDecimal getALL_OTH_INWMED_TRAN_COUNT() {
		return ALL_OTH_INWMED_TRAN_COUNT;
	}
	public void setALL_OTH_INWMED_TRAN_COUNT(BigDecimal aLL_OTH_INWMED_TRAN_COUNT) {
		ALL_OTH_INWMED_TRAN_COUNT = aLL_OTH_INWMED_TRAN_COUNT;
	}
	public BigDecimal getALL_OTH_INWMED_TRAN_AMT() {
		return ALL_OTH_INWMED_TRAN_AMT;
	}
	public void setALL_OTH_INWMED_TRAN_AMT(BigDecimal aLL_OTH_INWMED_TRAN_AMT) {
		ALL_OTH_INWMED_TRAN_AMT = aLL_OTH_INWMED_TRAN_AMT;
	}
	public BigDecimal getALL_OTH_INWHIGH_TRAN_COUNT() {
		return ALL_OTH_INWHIGH_TRAN_COUNT;
	}
	public void setALL_OTH_INWHIGH_TRAN_COUNT(BigDecimal aLL_OTH_INWHIGH_TRAN_COUNT) {
		ALL_OTH_INWHIGH_TRAN_COUNT = aLL_OTH_INWHIGH_TRAN_COUNT;
	}
	public BigDecimal getALL_OTH_INWHIGH_TRAN_AMT() {
		return ALL_OTH_INWHIGH_TRAN_AMT;
	}
	public void setALL_OTH_INWHIGH_TRAN_AMT(BigDecimal aLL_OTH_INWHIGH_TRAN_AMT) {
		ALL_OTH_INWHIGH_TRAN_AMT = aLL_OTH_INWHIGH_TRAN_AMT;
	}
	public String getALL_OTH_OUT_PRODUCT() {
		return ALL_OTH_OUT_PRODUCT;
	}
	public void setALL_OTH_OUT_PRODUCT(String aLL_OTH_OUT_PRODUCT) {
		ALL_OTH_OUT_PRODUCT = aLL_OTH_OUT_PRODUCT;
	}
	public BigDecimal getALL_OTH_OUT_LOW_TRAN_COUNT() {
		return ALL_OTH_OUT_LOW_TRAN_COUNT;
	}
	public void setALL_OTH_OUT_LOW_TRAN_COUNT(BigDecimal aLL_OTH_OUT_LOW_TRAN_COUNT) {
		ALL_OTH_OUT_LOW_TRAN_COUNT = aLL_OTH_OUT_LOW_TRAN_COUNT;
	}
	public BigDecimal getALL_OTH_OUT_LOW_TRAN_AMT() {
		return ALL_OTH_OUT_LOW_TRAN_AMT;
	}
	public void setALL_OTH_OUT_LOW_TRAN_AMT(BigDecimal aLL_OTH_OUT_LOW_TRAN_AMT) {
		ALL_OTH_OUT_LOW_TRAN_AMT = aLL_OTH_OUT_LOW_TRAN_AMT;
	}
	public BigDecimal getALL_OTH_OUTMED_TRAN_COUNT() {
		return ALL_OTH_OUTMED_TRAN_COUNT;
	}
	public void setALL_OTH_OUTMED_TRAN_COUNT(BigDecimal aLL_OTH_OUTMED_TRAN_COUNT) {
		ALL_OTH_OUTMED_TRAN_COUNT = aLL_OTH_OUTMED_TRAN_COUNT;
	}
	public BigDecimal getALL_OTH_OUTMED_TRAN_AMT() {
		return ALL_OTH_OUTMED_TRAN_AMT;
	}
	public void setALL_OTH_OUTMED_TRAN_AMT(BigDecimal aLL_OTH_OUTMED_TRAN_AMT) {
		ALL_OTH_OUTMED_TRAN_AMT = aLL_OTH_OUTMED_TRAN_AMT;
	}
	public BigDecimal getALL_OTH_OUTHIGH_TRAN_COUNT() {
		return ALL_OTH_OUTHIGH_TRAN_COUNT;
	}
	public void setALL_OTH_OUTHIGH_TRAN_COUNT(BigDecimal aLL_OTH_OUTHIGH_TRAN_COUNT) {
		ALL_OTH_OUTHIGH_TRAN_COUNT = aLL_OTH_OUTHIGH_TRAN_COUNT;
	}
	public BigDecimal getALL_OTH_OUTHIGH_TRAN_AMT() {
		return ALL_OTH_OUTHIGH_TRAN_AMT;
	}
	public void setALL_OTH_OUTHIGH_TRAN_AMT(BigDecimal aLL_OTH_OUTHIGH_TRAN_AMT) {
		ALL_OTH_OUTHIGH_TRAN_AMT = aLL_OTH_OUTHIGH_TRAN_AMT;
	}
	public String getOTHER_FEES_PRODUCT() {
		return OTHER_FEES_PRODUCT;
	}
	public void setOTHER_FEES_PRODUCT(String oTHER_FEES_PRODUCT) {
		OTHER_FEES_PRODUCT = oTHER_FEES_PRODUCT;
	}
	public BigDecimal getOTHER_FEES_LOW_TRAN_COUNT() {
		return OTHER_FEES_LOW_TRAN_COUNT;
	}
	public void setOTHER_FEES_LOW_TRAN_COUNT(BigDecimal oTHER_FEES_LOW_TRAN_COUNT) {
		OTHER_FEES_LOW_TRAN_COUNT = oTHER_FEES_LOW_TRAN_COUNT;
	}
	public BigDecimal getOTHER_FEES_LOW_TRAN_AMT() {
		return OTHER_FEES_LOW_TRAN_AMT;
	}
	public void setOTHER_FEES_LOW_TRAN_AMT(BigDecimal oTHER_FEES_LOW_TRAN_AMT) {
		OTHER_FEES_LOW_TRAN_AMT = oTHER_FEES_LOW_TRAN_AMT;
	}
	public BigDecimal getOTHER_FEESMED_TRAN_COUNT() {
		return OTHER_FEESMED_TRAN_COUNT;
	}
	public void setOTHER_FEESMED_TRAN_COUNT(BigDecimal oTHER_FEESMED_TRAN_COUNT) {
		OTHER_FEESMED_TRAN_COUNT = oTHER_FEESMED_TRAN_COUNT;
	}
	public BigDecimal getOTHER_FEESMED_TRAN_AMT() {
		return OTHER_FEESMED_TRAN_AMT;
	}
	public void setOTHER_FEESMED_TRAN_AMT(BigDecimal oTHER_FEESMED_TRAN_AMT) {
		OTHER_FEESMED_TRAN_AMT = oTHER_FEESMED_TRAN_AMT;
	}
	public BigDecimal getOTHER_FEESHIGH_TRAN_COUNT() {
		return OTHER_FEESHIGH_TRAN_COUNT;
	}
	public void setOTHER_FEESHIGH_TRAN_COUNT(BigDecimal oTHER_FEESHIGH_TRAN_COUNT) {
		OTHER_FEESHIGH_TRAN_COUNT = oTHER_FEESHIGH_TRAN_COUNT;
	}
	public BigDecimal getOTHER_FEESHIGH_TRAN_AMT() {
		return OTHER_FEESHIGH_TRAN_AMT;
	}
	public void setOTHER_FEESHIGH_TRAN_AMT(BigDecimal oTHER_FEESHIGH_TRAN_AMT) {
		OTHER_FEESHIGH_TRAN_AMT = oTHER_FEESHIGH_TRAN_AMT;
	}
	public String getTOTAL_SUM_PRODUCT() {
		return TOTAL_SUM_PRODUCT;
	}
	public void setTOTAL_SUM_PRODUCT(String tOTAL_SUM_PRODUCT) {
		TOTAL_SUM_PRODUCT = tOTAL_SUM_PRODUCT;
	}
	public BigDecimal getTOTAL_SUM_LOW_TRAN_COUNT() {
		return TOTAL_SUM_LOW_TRAN_COUNT;
	}
	public void setTOTAL_SUM_LOW_TRAN_COUNT(BigDecimal tOTAL_SUM_LOW_TRAN_COUNT) {
		TOTAL_SUM_LOW_TRAN_COUNT = tOTAL_SUM_LOW_TRAN_COUNT;
	}
	public BigDecimal getTOTAL_SUM_LOW_TRAN_AMT() {
		return TOTAL_SUM_LOW_TRAN_AMT;
	}
	public void setTOTAL_SUM_LOW_TRAN_AMT(BigDecimal tOTAL_SUM_LOW_TRAN_AMT) {
		TOTAL_SUM_LOW_TRAN_AMT = tOTAL_SUM_LOW_TRAN_AMT;
	}
	public BigDecimal getTOTAL_SUMMED_TRAN_COUNT() {
		return TOTAL_SUMMED_TRAN_COUNT;
	}
	public void setTOTAL_SUMMED_TRAN_COUNT(BigDecimal tOTAL_SUMMED_TRAN_COUNT) {
		TOTAL_SUMMED_TRAN_COUNT = tOTAL_SUMMED_TRAN_COUNT;
	}
	public BigDecimal getTOTAL_SUMMED_TRAN_AMT() {
		return TOTAL_SUMMED_TRAN_AMT;
	}
	public void setTOTAL_SUMMED_TRAN_AMT(BigDecimal tOTAL_SUMMED_TRAN_AMT) {
		TOTAL_SUMMED_TRAN_AMT = tOTAL_SUMMED_TRAN_AMT;
	}
	public BigDecimal getTOTAL_SUMHIGH_TRAN_COUNT() {
		return TOTAL_SUMHIGH_TRAN_COUNT;
	}
	public void setTOTAL_SUMHIGH_TRAN_COUNT(BigDecimal tOTAL_SUMHIGH_TRAN_COUNT) {
		TOTAL_SUMHIGH_TRAN_COUNT = tOTAL_SUMHIGH_TRAN_COUNT;
	}
	public BigDecimal getTOTAL_SUMHIGH_TRAN_AMT() {
		return TOTAL_SUMHIGH_TRAN_AMT;
	}
	public void setTOTAL_SUMHIGH_TRAN_AMT(BigDecimal tOTAL_SUMHIGH_TRAN_AMT) {
		TOTAL_SUMHIGH_TRAN_AMT = tOTAL_SUMHIGH_TRAN_AMT;
	}
	public String getTHIRD_TRAN_500K_INW_PRODUCT() {
		return THIRD_TRAN_500K_INW_PRODUCT;
	}
	public void setTHIRD_TRAN_500K_INW_PRODUCT(String tHIRD_TRAN_500K_INW_PRODUCT) {
		THIRD_TRAN_500K_INW_PRODUCT = tHIRD_TRAN_500K_INW_PRODUCT;
	}
	public BigDecimal getTHIRD_TRAN_500K_INW_LOW_TRAN_COUNT() {
		return THIRD_TRAN_500K_INW_LOW_TRAN_COUNT;
	}
	public void setTHIRD_TRAN_500K_INW_LOW_TRAN_COUNT(BigDecimal tHIRD_TRAN_500K_INW_LOW_TRAN_COUNT) {
		THIRD_TRAN_500K_INW_LOW_TRAN_COUNT = tHIRD_TRAN_500K_INW_LOW_TRAN_COUNT;
	}
	public BigDecimal getTHIRD_TRAN_500K_INW_LOW_TRAN_AMT() {
		return THIRD_TRAN_500K_INW_LOW_TRAN_AMT;
	}
	public void setTHIRD_TRAN_500K_INW_LOW_TRAN_AMT(BigDecimal tHIRD_TRAN_500K_INW_LOW_TRAN_AMT) {
		THIRD_TRAN_500K_INW_LOW_TRAN_AMT = tHIRD_TRAN_500K_INW_LOW_TRAN_AMT;
	}
	public BigDecimal getTHIRD_TRAN_500K_INWMED_TRAN_COUNT() {
		return THIRD_TRAN_500K_INWMED_TRAN_COUNT;
	}
	public void setTHIRD_TRAN_500K_INWMED_TRAN_COUNT(BigDecimal tHIRD_TRAN_500K_INWMED_TRAN_COUNT) {
		THIRD_TRAN_500K_INWMED_TRAN_COUNT = tHIRD_TRAN_500K_INWMED_TRAN_COUNT;
	}
	public BigDecimal getTHIRD_TRAN_500K_INWMED_TRAN_AMT() {
		return THIRD_TRAN_500K_INWMED_TRAN_AMT;
	}
	public void setTHIRD_TRAN_500K_INWMED_TRAN_AMT(BigDecimal tHIRD_TRAN_500K_INWMED_TRAN_AMT) {
		THIRD_TRAN_500K_INWMED_TRAN_AMT = tHIRD_TRAN_500K_INWMED_TRAN_AMT;
	}
	public BigDecimal getTHIRD_TRAN_500K_INWHIGH_TRAN_COUNT() {
		return THIRD_TRAN_500K_INWHIGH_TRAN_COUNT;
	}
	public void setTHIRD_TRAN_500K_INWHIGH_TRAN_COUNT(BigDecimal tHIRD_TRAN_500K_INWHIGH_TRAN_COUNT) {
		THIRD_TRAN_500K_INWHIGH_TRAN_COUNT = tHIRD_TRAN_500K_INWHIGH_TRAN_COUNT;
	}
	public BigDecimal getTHIRD_TRAN_500K_INWHIGH_TRAN_AMT() {
		return THIRD_TRAN_500K_INWHIGH_TRAN_AMT;
	}
	public void setTHIRD_TRAN_500K_INWHIGH_TRAN_AMT(BigDecimal tHIRD_TRAN_500K_INWHIGH_TRAN_AMT) {
		THIRD_TRAN_500K_INWHIGH_TRAN_AMT = tHIRD_TRAN_500K_INWHIGH_TRAN_AMT;
	}
	public String getTHIRD_TRAN_500K_OUT_PRODUCT() {
		return THIRD_TRAN_500K_OUT_PRODUCT;
	}
	public void setTHIRD_TRAN_500K_OUT_PRODUCT(String tHIRD_TRAN_500K_OUT_PRODUCT) {
		THIRD_TRAN_500K_OUT_PRODUCT = tHIRD_TRAN_500K_OUT_PRODUCT;
	}
	public BigDecimal getTHIRD_TRAN_500K_OUT_LOW_TRAN_COUNT() {
		return THIRD_TRAN_500K_OUT_LOW_TRAN_COUNT;
	}
	public void setTHIRD_TRAN_500K_OUT_LOW_TRAN_COUNT(BigDecimal tHIRD_TRAN_500K_OUT_LOW_TRAN_COUNT) {
		THIRD_TRAN_500K_OUT_LOW_TRAN_COUNT = tHIRD_TRAN_500K_OUT_LOW_TRAN_COUNT;
	}
	public BigDecimal getTHIRD_TRAN_500K_OUT_LOW_TRAN_AMT() {
		return THIRD_TRAN_500K_OUT_LOW_TRAN_AMT;
	}
	public void setTHIRD_TRAN_500K_OUT_LOW_TRAN_AMT(BigDecimal tHIRD_TRAN_500K_OUT_LOW_TRAN_AMT) {
		THIRD_TRAN_500K_OUT_LOW_TRAN_AMT = tHIRD_TRAN_500K_OUT_LOW_TRAN_AMT;
	}
	public BigDecimal getTHIRD_TRAN_500K_OUTMED_TRAN_COUNT() {
		return THIRD_TRAN_500K_OUTMED_TRAN_COUNT;
	}
	public void setTHIRD_TRAN_500K_OUTMED_TRAN_COUNT(BigDecimal tHIRD_TRAN_500K_OUTMED_TRAN_COUNT) {
		THIRD_TRAN_500K_OUTMED_TRAN_COUNT = tHIRD_TRAN_500K_OUTMED_TRAN_COUNT;
	}
	public BigDecimal getTHIRD_TRAN_500K_OUTMED_TRAN_AMT() {
		return THIRD_TRAN_500K_OUTMED_TRAN_AMT;
	}
	public void setTHIRD_TRAN_500K_OUTMED_TRAN_AMT(BigDecimal tHIRD_TRAN_500K_OUTMED_TRAN_AMT) {
		THIRD_TRAN_500K_OUTMED_TRAN_AMT = tHIRD_TRAN_500K_OUTMED_TRAN_AMT;
	}
	public BigDecimal getTHIRD_TRAN_500K_OUTHIGH_TRAN_COUNT() {
		return THIRD_TRAN_500K_OUTHIGH_TRAN_COUNT;
	}
	public void setTHIRD_TRAN_500K_OUTHIGH_TRAN_COUNT(BigDecimal tHIRD_TRAN_500K_OUTHIGH_TRAN_COUNT) {
		THIRD_TRAN_500K_OUTHIGH_TRAN_COUNT = tHIRD_TRAN_500K_OUTHIGH_TRAN_COUNT;
	}
	public BigDecimal getTHIRD_TRAN_500K_OUTHIGH_TRAN_AMT() {
		return THIRD_TRAN_500K_OUTHIGH_TRAN_AMT;
	}
	public void setTHIRD_TRAN_500K_OUTHIGH_TRAN_AMT(BigDecimal tHIRD_TRAN_500K_OUTHIGH_TRAN_AMT) {
		THIRD_TRAN_500K_OUTHIGH_TRAN_AMT = tHIRD_TRAN_500K_OUTHIGH_TRAN_AMT;
	}
	public String getTHIRD_TRAN_1000K_INW_PRODUCT() {
		return THIRD_TRAN_1000K_INW_PRODUCT;
	}
	public void setTHIRD_TRAN_1000K_INW_PRODUCT(String tHIRD_TRAN_1000K_INW_PRODUCT) {
		THIRD_TRAN_1000K_INW_PRODUCT = tHIRD_TRAN_1000K_INW_PRODUCT;
	}
	public BigDecimal getTHIRD_TRAN_1000K_INW_LOW_TRAN_COUNT() {
		return THIRD_TRAN_1000K_INW_LOW_TRAN_COUNT;
	}
	public void setTHIRD_TRAN_1000K_INW_LOW_TRAN_COUNT(BigDecimal tHIRD_TRAN_1000K_INW_LOW_TRAN_COUNT) {
		THIRD_TRAN_1000K_INW_LOW_TRAN_COUNT = tHIRD_TRAN_1000K_INW_LOW_TRAN_COUNT;
	}
	public BigDecimal getTHIRD_TRAN_1000K_INW_LOW_TRAN_AMT() {
		return THIRD_TRAN_1000K_INW_LOW_TRAN_AMT;
	}
	public void setTHIRD_TRAN_1000K_INW_LOW_TRAN_AMT(BigDecimal tHIRD_TRAN_1000K_INW_LOW_TRAN_AMT) {
		THIRD_TRAN_1000K_INW_LOW_TRAN_AMT = tHIRD_TRAN_1000K_INW_LOW_TRAN_AMT;
	}
	public BigDecimal getTHIRD_TRAN_1000K_INWMED_TRAN_COUNT() {
		return THIRD_TRAN_1000K_INWMED_TRAN_COUNT;
	}
	public void setTHIRD_TRAN_1000K_INWMED_TRAN_COUNT(BigDecimal tHIRD_TRAN_1000K_INWMED_TRAN_COUNT) {
		THIRD_TRAN_1000K_INWMED_TRAN_COUNT = tHIRD_TRAN_1000K_INWMED_TRAN_COUNT;
	}
	public BigDecimal getTHIRD_TRAN_1000K_INWMED_TRAN_AMT() {
		return THIRD_TRAN_1000K_INWMED_TRAN_AMT;
	}
	public void setTHIRD_TRAN_1000K_INWMED_TRAN_AMT(BigDecimal tHIRD_TRAN_1000K_INWMED_TRAN_AMT) {
		THIRD_TRAN_1000K_INWMED_TRAN_AMT = tHIRD_TRAN_1000K_INWMED_TRAN_AMT;
	}
	public BigDecimal getTHIRD_TRAN_1000K_INWHIGH_TRAN_COUNT() {
		return THIRD_TRAN_1000K_INWHIGH_TRAN_COUNT;
	}
	public void setTHIRD_TRAN_1000K_INWHIGH_TRAN_COUNT(BigDecimal tHIRD_TRAN_1000K_INWHIGH_TRAN_COUNT) {
		THIRD_TRAN_1000K_INWHIGH_TRAN_COUNT = tHIRD_TRAN_1000K_INWHIGH_TRAN_COUNT;
	}
	public BigDecimal getTHIRD_TRAN_1000K_INWHIGH_TRAN_AMT() {
		return THIRD_TRAN_1000K_INWHIGH_TRAN_AMT;
	}
	public void setTHIRD_TRAN_1000K_INWHIGH_TRAN_AMT(BigDecimal tHIRD_TRAN_1000K_INWHIGH_TRAN_AMT) {
		THIRD_TRAN_1000K_INWHIGH_TRAN_AMT = tHIRD_TRAN_1000K_INWHIGH_TRAN_AMT;
	}
	public String getTHIRD_TRAN_1000K_OUT_PRODUCT() {
		return THIRD_TRAN_1000K_OUT_PRODUCT;
	}
	public void setTHIRD_TRAN_1000K_OUT_PRODUCT(String tHIRD_TRAN_1000K_OUT_PRODUCT) {
		THIRD_TRAN_1000K_OUT_PRODUCT = tHIRD_TRAN_1000K_OUT_PRODUCT;
	}
	public BigDecimal getTHIRD_TRAN_1000K_OUT_LOW_TRAN_COUNT() {
		return THIRD_TRAN_1000K_OUT_LOW_TRAN_COUNT;
	}
	public void setTHIRD_TRAN_1000K_OUT_LOW_TRAN_COUNT(BigDecimal tHIRD_TRAN_1000K_OUT_LOW_TRAN_COUNT) {
		THIRD_TRAN_1000K_OUT_LOW_TRAN_COUNT = tHIRD_TRAN_1000K_OUT_LOW_TRAN_COUNT;
	}
	public BigDecimal getTHIRD_TRAN_1000K_OUT_LOW_TRAN_AMT() {
		return THIRD_TRAN_1000K_OUT_LOW_TRAN_AMT;
	}
	public void setTHIRD_TRAN_1000K_OUT_LOW_TRAN_AMT(BigDecimal tHIRD_TRAN_1000K_OUT_LOW_TRAN_AMT) {
		THIRD_TRAN_1000K_OUT_LOW_TRAN_AMT = tHIRD_TRAN_1000K_OUT_LOW_TRAN_AMT;
	}
	public BigDecimal getTHIRD_TRAN_1000K_OUTMED_TRAN_COUNT() {
		return THIRD_TRAN_1000K_OUTMED_TRAN_COUNT;
	}
	public void setTHIRD_TRAN_1000K_OUTMED_TRAN_COUNT(BigDecimal tHIRD_TRAN_1000K_OUTMED_TRAN_COUNT) {
		THIRD_TRAN_1000K_OUTMED_TRAN_COUNT = tHIRD_TRAN_1000K_OUTMED_TRAN_COUNT;
	}
	public BigDecimal getTHIRD_TRAN_1000K_OUTMED_TRAN_AMT() {
		return THIRD_TRAN_1000K_OUTMED_TRAN_AMT;
	}
	public void setTHIRD_TRAN_1000K_OUTMED_TRAN_AMT(BigDecimal tHIRD_TRAN_1000K_OUTMED_TRAN_AMT) {
		THIRD_TRAN_1000K_OUTMED_TRAN_AMT = tHIRD_TRAN_1000K_OUTMED_TRAN_AMT;
	}
	public BigDecimal getTHIRD_TRAN_1000K_OUTHIGH_TRAN_COUNT() {
		return THIRD_TRAN_1000K_OUTHIGH_TRAN_COUNT;
	}
	public void setTHIRD_TRAN_1000K_OUTHIGH_TRAN_COUNT(BigDecimal tHIRD_TRAN_1000K_OUTHIGH_TRAN_COUNT) {
		THIRD_TRAN_1000K_OUTHIGH_TRAN_COUNT = tHIRD_TRAN_1000K_OUTHIGH_TRAN_COUNT;
	}
	public BigDecimal getTHIRD_TRAN_1000K_OUTHIGH_TRAN_AMT() {
		return THIRD_TRAN_1000K_OUTHIGH_TRAN_AMT;
	}
	public void setTHIRD_TRAN_1000K_OUTHIGH_TRAN_AMT(BigDecimal tHIRD_TRAN_1000K_OUTHIGH_TRAN_AMT) {
		THIRD_TRAN_1000K_OUTHIGH_TRAN_AMT = tHIRD_TRAN_1000K_OUTHIGH_TRAN_AMT;
	}
	public String getTHIRD_TRAN_MORE_1000K_INW_PRODUCT() {
		return THIRD_TRAN_MORE_1000K_INW_PRODUCT;
	}
	public void setTHIRD_TRAN_MORE_1000K_INW_PRODUCT(String tHIRD_TRAN_MORE_1000K_INW_PRODUCT) {
		THIRD_TRAN_MORE_1000K_INW_PRODUCT = tHIRD_TRAN_MORE_1000K_INW_PRODUCT;
	}
	public BigDecimal getTHIRD_TRAN_MORE_1000K_INW_LOW_TRAN_COUNT() {
		return THIRD_TRAN_MORE_1000K_INW_LOW_TRAN_COUNT;
	}
	public void setTHIRD_TRAN_MORE_1000K_INW_LOW_TRAN_COUNT(BigDecimal tHIRD_TRAN_MORE_1000K_INW_LOW_TRAN_COUNT) {
		THIRD_TRAN_MORE_1000K_INW_LOW_TRAN_COUNT = tHIRD_TRAN_MORE_1000K_INW_LOW_TRAN_COUNT;
	}
	public BigDecimal getTHIRD_TRAN_MORE_1000K_INW_LOW_TRAN_AMT() {
		return THIRD_TRAN_MORE_1000K_INW_LOW_TRAN_AMT;
	}
	public void setTHIRD_TRAN_MORE_1000K_INW_LOW_TRAN_AMT(BigDecimal tHIRD_TRAN_MORE_1000K_INW_LOW_TRAN_AMT) {
		THIRD_TRAN_MORE_1000K_INW_LOW_TRAN_AMT = tHIRD_TRAN_MORE_1000K_INW_LOW_TRAN_AMT;
	}
	public BigDecimal getTHIRD_TRAN_MORE_1000K_INWMED_TRAN_COUNT() {
		return THIRD_TRAN_MORE_1000K_INWMED_TRAN_COUNT;
	}
	public void setTHIRD_TRAN_MORE_1000K_INWMED_TRAN_COUNT(BigDecimal tHIRD_TRAN_MORE_1000K_INWMED_TRAN_COUNT) {
		THIRD_TRAN_MORE_1000K_INWMED_TRAN_COUNT = tHIRD_TRAN_MORE_1000K_INWMED_TRAN_COUNT;
	}
	public BigDecimal getTHIRD_TRAN_MORE_1000K_INWMED_TRAN_AMT() {
		return THIRD_TRAN_MORE_1000K_INWMED_TRAN_AMT;
	}
	public void setTHIRD_TRAN_MORE_1000K_INWMED_TRAN_AMT(BigDecimal tHIRD_TRAN_MORE_1000K_INWMED_TRAN_AMT) {
		THIRD_TRAN_MORE_1000K_INWMED_TRAN_AMT = tHIRD_TRAN_MORE_1000K_INWMED_TRAN_AMT;
	}
	public BigDecimal getTHIRD_TRAN_MORE_1000K_INWHIGH_TRAN_COUNT() {
		return THIRD_TRAN_MORE_1000K_INWHIGH_TRAN_COUNT;
	}
	public void setTHIRD_TRAN_MORE_1000K_INWHIGH_TRAN_COUNT(BigDecimal tHIRD_TRAN_MORE_1000K_INWHIGH_TRAN_COUNT) {
		THIRD_TRAN_MORE_1000K_INWHIGH_TRAN_COUNT = tHIRD_TRAN_MORE_1000K_INWHIGH_TRAN_COUNT;
	}
	public BigDecimal getTHIRD_TRAN_MORE_1000K_INWHIGH_TRAN_AMT() {
		return THIRD_TRAN_MORE_1000K_INWHIGH_TRAN_AMT;
	}
	public void setTHIRD_TRAN_MORE_1000K_INWHIGH_TRAN_AMT(BigDecimal tHIRD_TRAN_MORE_1000K_INWHIGH_TRAN_AMT) {
		THIRD_TRAN_MORE_1000K_INWHIGH_TRAN_AMT = tHIRD_TRAN_MORE_1000K_INWHIGH_TRAN_AMT;
	}
	public String getTHIRD_TRAN_MORE_1000K_OUT_PRODUCT() {
		return THIRD_TRAN_MORE_1000K_OUT_PRODUCT;
	}
	public void setTHIRD_TRAN_MORE_1000K_OUT_PRODUCT(String tHIRD_TRAN_MORE_1000K_OUT_PRODUCT) {
		THIRD_TRAN_MORE_1000K_OUT_PRODUCT = tHIRD_TRAN_MORE_1000K_OUT_PRODUCT;
	}
	public BigDecimal getTHIRD_TRAN_MORE_1000K_OUT_LOW_TRAN_COUNT() {
		return THIRD_TRAN_MORE_1000K_OUT_LOW_TRAN_COUNT;
	}
	public void setTHIRD_TRAN_MORE_1000K_OUT_LOW_TRAN_COUNT(BigDecimal tHIRD_TRAN_MORE_1000K_OUT_LOW_TRAN_COUNT) {
		THIRD_TRAN_MORE_1000K_OUT_LOW_TRAN_COUNT = tHIRD_TRAN_MORE_1000K_OUT_LOW_TRAN_COUNT;
	}
	public BigDecimal getTHIRD_TRAN_MORE_1000K_OUT_LOW_TRAN_AMT() {
		return THIRD_TRAN_MORE_1000K_OUT_LOW_TRAN_AMT;
	}
	public void setTHIRD_TRAN_MORE_1000K_OUT_LOW_TRAN_AMT(BigDecimal tHIRD_TRAN_MORE_1000K_OUT_LOW_TRAN_AMT) {
		THIRD_TRAN_MORE_1000K_OUT_LOW_TRAN_AMT = tHIRD_TRAN_MORE_1000K_OUT_LOW_TRAN_AMT;
	}
	public BigDecimal getTHIRD_TRAN_MORE_1000K_OUTMED_TRAN_COUNT() {
		return THIRD_TRAN_MORE_1000K_OUTMED_TRAN_COUNT;
	}
	public void setTHIRD_TRAN_MORE_1000K_OUTMED_TRAN_COUNT(BigDecimal tHIRD_TRAN_MORE_1000K_OUTMED_TRAN_COUNT) {
		THIRD_TRAN_MORE_1000K_OUTMED_TRAN_COUNT = tHIRD_TRAN_MORE_1000K_OUTMED_TRAN_COUNT;
	}
	public BigDecimal getTHIRD_TRAN_MORE_1000K_OUTMED_TRAN_AMT() {
		return THIRD_TRAN_MORE_1000K_OUTMED_TRAN_AMT;
	}
	public void setTHIRD_TRAN_MORE_1000K_OUTMED_TRAN_AMT(BigDecimal tHIRD_TRAN_MORE_1000K_OUTMED_TRAN_AMT) {
		THIRD_TRAN_MORE_1000K_OUTMED_TRAN_AMT = tHIRD_TRAN_MORE_1000K_OUTMED_TRAN_AMT;
	}
	public BigDecimal getTHIRD_TRAN_MORE_1000K_OUTHIGH_TRAN_COUNT() {
		return THIRD_TRAN_MORE_1000K_OUTHIGH_TRAN_COUNT;
	}
	public void setTHIRD_TRAN_MORE_1000K_OUTHIGH_TRAN_COUNT(BigDecimal tHIRD_TRAN_MORE_1000K_OUTHIGH_TRAN_COUNT) {
		THIRD_TRAN_MORE_1000K_OUTHIGH_TRAN_COUNT = tHIRD_TRAN_MORE_1000K_OUTHIGH_TRAN_COUNT;
	}
	public BigDecimal getTHIRD_TRAN_MORE_1000K_OUTHIGH_TRAN_AMT() {
		return THIRD_TRAN_MORE_1000K_OUTHIGH_TRAN_AMT;
	}
	public void setTHIRD_TRAN_MORE_1000K_OUTHIGH_TRAN_AMT(BigDecimal tHIRD_TRAN_MORE_1000K_OUTHIGH_TRAN_AMT) {
		THIRD_TRAN_MORE_1000K_OUTHIGH_TRAN_AMT = tHIRD_TRAN_MORE_1000K_OUTHIGH_TRAN_AMT;
	}
	public String getDEBIT_CARD_PRODUCT() {
		return DEBIT_CARD_PRODUCT;
	}
	public void setDEBIT_CARD_PRODUCT(String dEBIT_CARD_PRODUCT) {
		DEBIT_CARD_PRODUCT = dEBIT_CARD_PRODUCT;
	}
	public BigDecimal getDEBIT_CARD_LOW_TRAN_COUNT() {
		return DEBIT_CARD_LOW_TRAN_COUNT;
	}
	public void setDEBIT_CARD_LOW_TRAN_COUNT(BigDecimal dEBIT_CARD_LOW_TRAN_COUNT) {
		DEBIT_CARD_LOW_TRAN_COUNT = dEBIT_CARD_LOW_TRAN_COUNT;
	}
	public BigDecimal getDEBIT_CARD_LOW_TRAN_AMT() {
		return DEBIT_CARD_LOW_TRAN_AMT;
	}
	public void setDEBIT_CARD_LOW_TRAN_AMT(BigDecimal dEBIT_CARD_LOW_TRAN_AMT) {
		DEBIT_CARD_LOW_TRAN_AMT = dEBIT_CARD_LOW_TRAN_AMT;
	}
	public BigDecimal getDEBIT_CARDMED_TRAN_COUNT() {
		return DEBIT_CARDMED_TRAN_COUNT;
	}
	public void setDEBIT_CARDMED_TRAN_COUNT(BigDecimal dEBIT_CARDMED_TRAN_COUNT) {
		DEBIT_CARDMED_TRAN_COUNT = dEBIT_CARDMED_TRAN_COUNT;
	}
	public BigDecimal getDEBIT_CARDMED_TRAN_AMT() {
		return DEBIT_CARDMED_TRAN_AMT;
	}
	public void setDEBIT_CARDMED_TRAN_AMT(BigDecimal dEBIT_CARDMED_TRAN_AMT) {
		DEBIT_CARDMED_TRAN_AMT = dEBIT_CARDMED_TRAN_AMT;
	}
	public BigDecimal getDEBIT_CARDHIGH_TRAN_COUNT() {
		return DEBIT_CARDHIGH_TRAN_COUNT;
	}
	public void setDEBIT_CARDHIGH_TRAN_COUNT(BigDecimal dEBIT_CARDHIGH_TRAN_COUNT) {
		DEBIT_CARDHIGH_TRAN_COUNT = dEBIT_CARDHIGH_TRAN_COUNT;
	}
	public BigDecimal getDEBIT_CARDHIGH_TRAN_AMT() {
		return DEBIT_CARDHIGH_TRAN_AMT;
	}
	public void setDEBIT_CARDHIGH_TRAN_AMT(BigDecimal dEBIT_CARDHIGH_TRAN_AMT) {
		DEBIT_CARDHIGH_TRAN_AMT = dEBIT_CARDHIGH_TRAN_AMT;
	}
	public String getCREDIT_CARD_PRODUCT() {
		return CREDIT_CARD_PRODUCT;
	}
	public void setCREDIT_CARD_PRODUCT(String cREDIT_CARD_PRODUCT) {
		CREDIT_CARD_PRODUCT = cREDIT_CARD_PRODUCT;
	}
	public BigDecimal getCREDIT_CARD_LOW_TRAN_COUNT() {
		return CREDIT_CARD_LOW_TRAN_COUNT;
	}
	public void setCREDIT_CARD_LOW_TRAN_COUNT(BigDecimal cREDIT_CARD_LOW_TRAN_COUNT) {
		CREDIT_CARD_LOW_TRAN_COUNT = cREDIT_CARD_LOW_TRAN_COUNT;
	}
	public BigDecimal getCREDIT_CARD_LOW_TRAN_AMT() {
		return CREDIT_CARD_LOW_TRAN_AMT;
	}
	public void setCREDIT_CARD_LOW_TRAN_AMT(BigDecimal cREDIT_CARD_LOW_TRAN_AMT) {
		CREDIT_CARD_LOW_TRAN_AMT = cREDIT_CARD_LOW_TRAN_AMT;
	}
	public BigDecimal getCREDIT_CARDMED_TRAN_COUNT() {
		return CREDIT_CARDMED_TRAN_COUNT;
	}
	public void setCREDIT_CARDMED_TRAN_COUNT(BigDecimal cREDIT_CARDMED_TRAN_COUNT) {
		CREDIT_CARDMED_TRAN_COUNT = cREDIT_CARDMED_TRAN_COUNT;
	}
	public BigDecimal getCREDIT_CARDMED_TRAN_AMT() {
		return CREDIT_CARDMED_TRAN_AMT;
	}
	public void setCREDIT_CARDMED_TRAN_AMT(BigDecimal cREDIT_CARDMED_TRAN_AMT) {
		CREDIT_CARDMED_TRAN_AMT = cREDIT_CARDMED_TRAN_AMT;
	}
	public BigDecimal getCREDIT_CARDHIGH_TRAN_COUNT() {
		return CREDIT_CARDHIGH_TRAN_COUNT;
	}
	public void setCREDIT_CARDHIGH_TRAN_COUNT(BigDecimal cREDIT_CARDHIGH_TRAN_COUNT) {
		CREDIT_CARDHIGH_TRAN_COUNT = cREDIT_CARDHIGH_TRAN_COUNT;
	}
	public BigDecimal getCREDIT_CARDHIGH_TRAN_AMT() {
		return CREDIT_CARDHIGH_TRAN_AMT;
	}
	public void setCREDIT_CARDHIGH_TRAN_AMT(BigDecimal cREDIT_CARDHIGH_TRAN_AMT) {
		CREDIT_CARDHIGH_TRAN_AMT = cREDIT_CARDHIGH_TRAN_AMT;
	}
	public String getPREPAID_CARD_PRODUCT() {
		return PREPAID_CARD_PRODUCT;
	}
	public void setPREPAID_CARD_PRODUCT(String pREPAID_CARD_PRODUCT) {
		PREPAID_CARD_PRODUCT = pREPAID_CARD_PRODUCT;
	}
	public BigDecimal getPREPAID_CARD_LOW_TRAN_COUNT() {
		return PREPAID_CARD_LOW_TRAN_COUNT;
	}
	public void setPREPAID_CARD_LOW_TRAN_COUNT(BigDecimal pREPAID_CARD_LOW_TRAN_COUNT) {
		PREPAID_CARD_LOW_TRAN_COUNT = pREPAID_CARD_LOW_TRAN_COUNT;
	}
	public BigDecimal getPREPAID_CARD_LOW_TRAN_AMT() {
		return PREPAID_CARD_LOW_TRAN_AMT;
	}
	public void setPREPAID_CARD_LOW_TRAN_AMT(BigDecimal pREPAID_CARD_LOW_TRAN_AMT) {
		PREPAID_CARD_LOW_TRAN_AMT = pREPAID_CARD_LOW_TRAN_AMT;
	}
	public BigDecimal getPREPAID_CARDMED_TRAN_COUNT() {
		return PREPAID_CARDMED_TRAN_COUNT;
	}
	public void setPREPAID_CARDMED_TRAN_COUNT(BigDecimal pREPAID_CARDMED_TRAN_COUNT) {
		PREPAID_CARDMED_TRAN_COUNT = pREPAID_CARDMED_TRAN_COUNT;
	}
	public BigDecimal getPREPAID_CARDMED_TRAN_AMT() {
		return PREPAID_CARDMED_TRAN_AMT;
	}
	public void setPREPAID_CARDMED_TRAN_AMT(BigDecimal pREPAID_CARDMED_TRAN_AMT) {
		PREPAID_CARDMED_TRAN_AMT = pREPAID_CARDMED_TRAN_AMT;
	}
	public BigDecimal getPREPAID_CARDHIGH_TRAN_COUNT() {
		return PREPAID_CARDHIGH_TRAN_COUNT;
	}
	public void setPREPAID_CARDHIGH_TRAN_COUNT(BigDecimal pREPAID_CARDHIGH_TRAN_COUNT) {
		PREPAID_CARDHIGH_TRAN_COUNT = pREPAID_CARDHIGH_TRAN_COUNT;
	}
	public BigDecimal getPREPAID_CARDHIGH_TRAN_AMT() {
		return PREPAID_CARDHIGH_TRAN_AMT;
	}
	public void setPREPAID_CARDHIGH_TRAN_AMT(BigDecimal pREPAID_CARDHIGH_TRAN_AMT) {
		PREPAID_CARDHIGH_TRAN_AMT = pREPAID_CARDHIGH_TRAN_AMT;
	}
	public String getMOB_BANKING_INW_PRODUCT() {
		return MOB_BANKING_INW_PRODUCT;
	}
	public void setMOB_BANKING_INW_PRODUCT(String mOB_BANKING_INW_PRODUCT) {
		MOB_BANKING_INW_PRODUCT = mOB_BANKING_INW_PRODUCT;
	}
	public BigDecimal getMOB_BANKING_INW_LOW_TRAN_COUNT() {
		return MOB_BANKING_INW_LOW_TRAN_COUNT;
	}
	public void setMOB_BANKING_INW_LOW_TRAN_COUNT(BigDecimal mOB_BANKING_INW_LOW_TRAN_COUNT) {
		MOB_BANKING_INW_LOW_TRAN_COUNT = mOB_BANKING_INW_LOW_TRAN_COUNT;
	}
	public BigDecimal getMOB_BANKING_INW_LOW_TRAN_AMT() {
		return MOB_BANKING_INW_LOW_TRAN_AMT;
	}
	public void setMOB_BANKING_INW_LOW_TRAN_AMT(BigDecimal mOB_BANKING_INW_LOW_TRAN_AMT) {
		MOB_BANKING_INW_LOW_TRAN_AMT = mOB_BANKING_INW_LOW_TRAN_AMT;
	}
	public BigDecimal getMOB_BANKING_INWMED_TRAN_COUNT() {
		return MOB_BANKING_INWMED_TRAN_COUNT;
	}
	public void setMOB_BANKING_INWMED_TRAN_COUNT(BigDecimal mOB_BANKING_INWMED_TRAN_COUNT) {
		MOB_BANKING_INWMED_TRAN_COUNT = mOB_BANKING_INWMED_TRAN_COUNT;
	}
	public BigDecimal getMOB_BANKING_INWMED_TRAN_AMT() {
		return MOB_BANKING_INWMED_TRAN_AMT;
	}
	public void setMOB_BANKING_INWMED_TRAN_AMT(BigDecimal mOB_BANKING_INWMED_TRAN_AMT) {
		MOB_BANKING_INWMED_TRAN_AMT = mOB_BANKING_INWMED_TRAN_AMT;
	}
	public BigDecimal getMOB_BANKING_INWHIGH_TRAN_COUNT() {
		return MOB_BANKING_INWHIGH_TRAN_COUNT;
	}
	public void setMOB_BANKING_INWHIGH_TRAN_COUNT(BigDecimal mOB_BANKING_INWHIGH_TRAN_COUNT) {
		MOB_BANKING_INWHIGH_TRAN_COUNT = mOB_BANKING_INWHIGH_TRAN_COUNT;
	}
	public BigDecimal getMOB_BANKING_INWHIGH_TRAN_AMT() {
		return MOB_BANKING_INWHIGH_TRAN_AMT;
	}
	public void setMOB_BANKING_INWHIGH_TRAN_AMT(BigDecimal mOB_BANKING_INWHIGH_TRAN_AMT) {
		MOB_BANKING_INWHIGH_TRAN_AMT = mOB_BANKING_INWHIGH_TRAN_AMT;
	}
	public String getMOB_BANKING_OUT_PRODUCT() {
		return MOB_BANKING_OUT_PRODUCT;
	}
	public void setMOB_BANKING_OUT_PRODUCT(String mOB_BANKING_OUT_PRODUCT) {
		MOB_BANKING_OUT_PRODUCT = mOB_BANKING_OUT_PRODUCT;
	}
	public BigDecimal getMOB_BANKING_OUT_LOW_TRAN_COUNT() {
		return MOB_BANKING_OUT_LOW_TRAN_COUNT;
	}
	public void setMOB_BANKING_OUT_LOW_TRAN_COUNT(BigDecimal mOB_BANKING_OUT_LOW_TRAN_COUNT) {
		MOB_BANKING_OUT_LOW_TRAN_COUNT = mOB_BANKING_OUT_LOW_TRAN_COUNT;
	}
	public BigDecimal getMOB_BANKING_OUT_LOW_TRAN_AMT() {
		return MOB_BANKING_OUT_LOW_TRAN_AMT;
	}
	public void setMOB_BANKING_OUT_LOW_TRAN_AMT(BigDecimal mOB_BANKING_OUT_LOW_TRAN_AMT) {
		MOB_BANKING_OUT_LOW_TRAN_AMT = mOB_BANKING_OUT_LOW_TRAN_AMT;
	}
	public BigDecimal getMOB_BANKING_OUTMED_TRAN_COUNT() {
		return MOB_BANKING_OUTMED_TRAN_COUNT;
	}
	public void setMOB_BANKING_OUTMED_TRAN_COUNT(BigDecimal mOB_BANKING_OUTMED_TRAN_COUNT) {
		MOB_BANKING_OUTMED_TRAN_COUNT = mOB_BANKING_OUTMED_TRAN_COUNT;
	}
	public BigDecimal getMOB_BANKING_OUTMED_TRAN_AMT() {
		return MOB_BANKING_OUTMED_TRAN_AMT;
	}
	public void setMOB_BANKING_OUTMED_TRAN_AMT(BigDecimal mOB_BANKING_OUTMED_TRAN_AMT) {
		MOB_BANKING_OUTMED_TRAN_AMT = mOB_BANKING_OUTMED_TRAN_AMT;
	}
	public BigDecimal getMOB_BANKING_OUTHIGH_TRAN_COUNT() {
		return MOB_BANKING_OUTHIGH_TRAN_COUNT;
	}
	public void setMOB_BANKING_OUTHIGH_TRAN_COUNT(BigDecimal mOB_BANKING_OUTHIGH_TRAN_COUNT) {
		MOB_BANKING_OUTHIGH_TRAN_COUNT = mOB_BANKING_OUTHIGH_TRAN_COUNT;
	}
	public BigDecimal getMOB_BANKING_OUTHIGH_TRAN_AMT() {
		return MOB_BANKING_OUTHIGH_TRAN_AMT;
	}
	public void setMOB_BANKING_OUTHIGH_TRAN_AMT(BigDecimal mOB_BANKING_OUTHIGH_TRAN_AMT) {
		MOB_BANKING_OUTHIGH_TRAN_AMT = mOB_BANKING_OUTHIGH_TRAN_AMT;
	}
	public String getINTERNET_INW_PRODUCT() {
		return INTERNET_INW_PRODUCT;
	}
	public void setINTERNET_INW_PRODUCT(String iNTERNET_INW_PRODUCT) {
		INTERNET_INW_PRODUCT = iNTERNET_INW_PRODUCT;
	}
	public BigDecimal getINTERNET_INW_LOW_TRAN_COUNT() {
		return INTERNET_INW_LOW_TRAN_COUNT;
	}
	public void setINTERNET_INW_LOW_TRAN_COUNT(BigDecimal iNTERNET_INW_LOW_TRAN_COUNT) {
		INTERNET_INW_LOW_TRAN_COUNT = iNTERNET_INW_LOW_TRAN_COUNT;
	}
	public BigDecimal getINTERNET_INW_LOW_TRAN_AMT() {
		return INTERNET_INW_LOW_TRAN_AMT;
	}
	public void setINTERNET_INW_LOW_TRAN_AMT(BigDecimal iNTERNET_INW_LOW_TRAN_AMT) {
		INTERNET_INW_LOW_TRAN_AMT = iNTERNET_INW_LOW_TRAN_AMT;
	}
	public BigDecimal getINTERNET_INWMED_TRAN_COUNT() {
		return INTERNET_INWMED_TRAN_COUNT;
	}
	public void setINTERNET_INWMED_TRAN_COUNT(BigDecimal iNTERNET_INWMED_TRAN_COUNT) {
		INTERNET_INWMED_TRAN_COUNT = iNTERNET_INWMED_TRAN_COUNT;
	}
	public BigDecimal getINTERNET_INWMED_TRAN_AMT() {
		return INTERNET_INWMED_TRAN_AMT;
	}
	public void setINTERNET_INWMED_TRAN_AMT(BigDecimal iNTERNET_INWMED_TRAN_AMT) {
		INTERNET_INWMED_TRAN_AMT = iNTERNET_INWMED_TRAN_AMT;
	}
	public BigDecimal getINTERNET_INWHIGH_TRAN_COUNT() {
		return INTERNET_INWHIGH_TRAN_COUNT;
	}
	public void setINTERNET_INWHIGH_TRAN_COUNT(BigDecimal iNTERNET_INWHIGH_TRAN_COUNT) {
		INTERNET_INWHIGH_TRAN_COUNT = iNTERNET_INWHIGH_TRAN_COUNT;
	}
	public BigDecimal getINTERNET_INWHIGH_TRAN_AMT() {
		return INTERNET_INWHIGH_TRAN_AMT;
	}
	public void setINTERNET_INWHIGH_TRAN_AMT(BigDecimal iNTERNET_INWHIGH_TRAN_AMT) {
		INTERNET_INWHIGH_TRAN_AMT = iNTERNET_INWHIGH_TRAN_AMT;
	}
	public String getINTERNET_OUT_PRODUCT() {
		return INTERNET_OUT_PRODUCT;
	}
	public void setINTERNET_OUT_PRODUCT(String iNTERNET_OUT_PRODUCT) {
		INTERNET_OUT_PRODUCT = iNTERNET_OUT_PRODUCT;
	}
	public BigDecimal getINTERNET_OUT_LOW_TRAN_COUNT() {
		return INTERNET_OUT_LOW_TRAN_COUNT;
	}
	public void setINTERNET_OUT_LOW_TRAN_COUNT(BigDecimal iNTERNET_OUT_LOW_TRAN_COUNT) {
		INTERNET_OUT_LOW_TRAN_COUNT = iNTERNET_OUT_LOW_TRAN_COUNT;
	}
	public BigDecimal getINTERNET_OUT_LOW_TRAN_AMT() {
		return INTERNET_OUT_LOW_TRAN_AMT;
	}
	public void setINTERNET_OUT_LOW_TRAN_AMT(BigDecimal iNTERNET_OUT_LOW_TRAN_AMT) {
		INTERNET_OUT_LOW_TRAN_AMT = iNTERNET_OUT_LOW_TRAN_AMT;
	}
	public BigDecimal getINTERNET_OUTMED_TRAN_COUNT() {
		return INTERNET_OUTMED_TRAN_COUNT;
	}
	public void setINTERNET_OUTMED_TRAN_COUNT(BigDecimal iNTERNET_OUTMED_TRAN_COUNT) {
		INTERNET_OUTMED_TRAN_COUNT = iNTERNET_OUTMED_TRAN_COUNT;
	}
	public BigDecimal getINTERNET_OUTMED_TRAN_AMT() {
		return INTERNET_OUTMED_TRAN_AMT;
	}
	public void setINTERNET_OUTMED_TRAN_AMT(BigDecimal iNTERNET_OUTMED_TRAN_AMT) {
		INTERNET_OUTMED_TRAN_AMT = iNTERNET_OUTMED_TRAN_AMT;
	}
	public BigDecimal getINTERNET_OUTHIGH_TRAN_COUNT() {
		return INTERNET_OUTHIGH_TRAN_COUNT;
	}
	public void setINTERNET_OUTHIGH_TRAN_COUNT(BigDecimal iNTERNET_OUTHIGH_TRAN_COUNT) {
		INTERNET_OUTHIGH_TRAN_COUNT = iNTERNET_OUTHIGH_TRAN_COUNT;
	}
	public BigDecimal getINTERNET_OUTHIGH_TRAN_AMT() {
		return INTERNET_OUTHIGH_TRAN_AMT;
	}
	public void setINTERNET_OUTHIGH_TRAN_AMT(BigDecimal iNTERNET_OUTHIGH_TRAN_AMT) {
		INTERNET_OUTHIGH_TRAN_AMT = iNTERNET_OUTHIGH_TRAN_AMT;
	}
	public String getREPORT_CODE() {
		return REPORT_CODE;
	}
	public void setREPORT_CODE(String rEPORT_CODE) {
		REPORT_CODE = rEPORT_CODE;
	}
	public String getREPORT_NAME() {
		return REPORT_NAME;
	}
	public void setREPORT_NAME(String rEPORT_NAME) {
		REPORT_NAME = rEPORT_NAME;
	}
	public Date getREPORT_DATE() {
		return REPORT_DATE;
	}
	public void setREPORT_DATE(Date rEPORT_DATE) {
		REPORT_DATE = rEPORT_DATE;
	}
	public Date getREPORT_DUE_DATE() {
		return REPORT_DUE_DATE;
	}
	public void setREPORT_DUE_DATE(Date rEPORT_DUE_DATE) {
		REPORT_DUE_DATE = rEPORT_DUE_DATE;
	}
	public Date getREP_SUBMIT_DATE() {
		return REP_SUBMIT_DATE;
	}
	public void setREP_SUBMIT_DATE(Date rEP_SUBMIT_DATE) {
		REP_SUBMIT_DATE = rEP_SUBMIT_DATE;
	}
	public Date getREP_PERIOD_FROM() {
		return REP_PERIOD_FROM;
	}
	public void setREP_PERIOD_FROM(Date rEP_PERIOD_FROM) {
		REP_PERIOD_FROM = rEP_PERIOD_FROM;
	}
	public Date getREP_PERIOD_TO() {
		return REP_PERIOD_TO;
	}
	public void setREP_PERIOD_TO(Date rEP_PERIOD_TO) {
		REP_PERIOD_TO = rEP_PERIOD_TO;
	}
	public String getREP_FREQ() {
		return REP_FREQ;
	}
	public void setREP_FREQ(String rEP_FREQ) {
		REP_FREQ = rEP_FREQ;
	}
	public String getNIL_REPORT_FLG() {
		return NIL_REPORT_FLG;
	}
	public void setNIL_REPORT_FLG(String nIL_REPORT_FLG) {
		NIL_REPORT_FLG = nIL_REPORT_FLG;
	}
	public String getARCH_FLG() {
		return ARCH_FLG;
	}
	public void setARCH_FLG(String aRCH_FLG) {
		ARCH_FLG = aRCH_FLG;
	}
	public T12AReport(String cASH_DEP_PRODUCT, BigDecimal cASH_DEP_LOW_TRAN_COUNT, BigDecimal cASH_DEP_LOW_TRAN_AMT,
			BigDecimal cASH_DEPMED_TRAN_COUNT, BigDecimal cASH_DEPMED_TRAN_AMT, BigDecimal cASH_DEPHIGH_TRAN_COUNT,
			BigDecimal cASH_DEPHIGH_TRAN_AMT, String cASH_WITHD_PRODUCT, BigDecimal cASH_WITHD_LOW_TRAN_COUNT,
			BigDecimal cASH_WITHD_LOW_TRAN_AMT, BigDecimal cASH_WITHDMED_TRAN_COUNT, BigDecimal cASH_WITHDMED_TRAN_AMT,
			BigDecimal cASH_WITHDHIGH_TRAN_COUNT, BigDecimal cASH_WITHDHIGH_TRAN_AMT, String fX_SALE_EQL_PRODUCT,
			BigDecimal fX_SALE_EQL_LOW_TRAN_COUNT, BigDecimal fX_SALE_EQL_LOW_TRAN_AMT,
			BigDecimal fX_SALE_EQLMED_TRAN_COUNT, BigDecimal fX_SALE_EQLMED_TRAN_AMT,
			BigDecimal fX_SALE_EQLHIGH_TRAN_COUNT, BigDecimal fX_SALE_EQLHIGH_TRAN_AMT, String fX_SALE_MORE_PRODUCT,
			BigDecimal fX_SALE_MORE_LOW_TRAN_COUNT, BigDecimal fX_SALE_MORE_LOW_TRAN_AMT,
			BigDecimal fX_SALE_MOREMED_TRAN_COUNT, BigDecimal fX_SALE_MOREMED_TRAN_AMT,
			BigDecimal fX_SALE_MOREHIGH_TRAN_COUNT, BigDecimal fX_SALE_MOREHIGH_TRAN_AMT, String fX_PUR_EQL_PRODUCT,
			BigDecimal fX_PUR_EQL_LOW_TRAN_COUNT, BigDecimal fX_PUR_EQL_LOW_TRAN_AMT,
			BigDecimal fX_PUR_EQLMED_TRAN_COUNT, BigDecimal fX_PUR_EQLMED_TRAN_AMT,
			BigDecimal fX_PUR_EQLHIGH_TRAN_COUNT, BigDecimal fX_PUR_EQLHIGH_TRAN_AMT, String fX_PUR_MORE_PRODUCT,
			BigDecimal fX_PUR_MORE_LOW_TRAN_COUNT, BigDecimal fX_PUR_MORE_LOW_TRAN_AMT,
			BigDecimal fX_PUR_MOREMED_TRAN_COUNT, BigDecimal fX_PUR_MOREMED_TRAN_AMT,
			BigDecimal fX_PUR_MOREHIGH_TRAN_COUNT, BigDecimal fX_PUR_MOREHIGH_TRAN_AMT, String dOM_INW_PRODUCT,
			BigDecimal dOM_INW_LOW_TRAN_COUNT, BigDecimal dOM_INW_LOW_TRAN_AMT, BigDecimal dOM_INWMED_TRAN_COUNT,
			BigDecimal dOM_INWMED_TRAN_AMT, BigDecimal dOM_INWHIGH_TRAN_COUNT, BigDecimal dOM_INWHIGH_TRAN_AMT,
			String dOM_OUT_PRODUCT, BigDecimal dOM_OUT_LOW_TRAN_COUNT, BigDecimal dOM_OUT_LOW_TRAN_AMT,
			BigDecimal dOM_OUTMED_TRAN_COUNT, BigDecimal dOM_OUTMED_TRAN_AMT, BigDecimal dOM_OUTHIGH_TRAN_COUNT,
			BigDecimal dOM_OUTHIGH_TRAN_AMT, String iNT_TRADE_INW_PRODUCT, BigDecimal iNT_TRADE_INW_LOW_TRAN_COUNT,
			BigDecimal iNT_TRADE_INW_LOW_TRAN_AMT, BigDecimal iNT_TRADE_INWMED_TRAN_COUNT,
			BigDecimal iNT_TRADE_INWMED_TRAN_AMT, BigDecimal iNT_TRADE_INWHIGH_TRAN_COUNT,
			BigDecimal iNT_TRADE_INWHIGH_TRAN_AMT, String iNT_TRADE_OUT_PRODUCT,
			BigDecimal iNT_TRADE_OUT_LOW_TRAN_COUNT, BigDecimal iNT_TRADE_OUT_LOW_TRAN_AMT,
			BigDecimal iNT_TRADE_OUTMED_TRAN_COUNT, BigDecimal iNT_TRADE_OUTMED_TRAN_AMT,
			BigDecimal iNT_TRADE_OUTHIGH_TRAN_COUNT, BigDecimal iNT_TRADE_OUTHIGH_TRAN_AMT,
			String iNT_NON_TRADE_INW_PRODUCT, BigDecimal iNT_NON_TRADE_INW_LOW_TRAN_COUNT,
			BigDecimal iNT_NON_TRADE_INW_LOW_TRAN_AMT, BigDecimal iNT_NON_TRADE_INWMED_TRAN_COUNT,
			BigDecimal iNT_NON_TRADE_INWMED_TRAN_AMT, BigDecimal iNT_NON_TRADE_INWHIGH_TRAN_COUNT,
			BigDecimal iNT_NON_TRADE_INWHIGH_TRAN_AMT, String iNT_NON_TRADE_OUT_PRODUCT,
			BigDecimal iNT_NON_TRADE_OUT_LOW_TRAN_COUNT, BigDecimal iNT_NON_TRADE_OUT_LOW_TRAN_AMT,
			BigDecimal iNT_NON_TRADE_OUTMED_TRAN_COUNT, BigDecimal iNT_NON_TRADE_OUTMED_TRAN_AMT,
			BigDecimal iNT_NON_TRADE_OUTHIGH_TRAN_COUNT, BigDecimal iNT_NON_TRADE_OUTHIGH_TRAN_AMT,
			String aLL_OTH_TRANSFER_DEB_PRODUCT, BigDecimal aLL_OTH_TRANSFER_DEB_LOW_TRAN_COUNT,
			BigDecimal aLL_OTH_TRANSFER_DEB_LOW_TRAN_AMT, BigDecimal aLL_OTH_TRANSFER_DEBMED_TRAN_COUNT,
			BigDecimal aLL_OTH_TRANSFER_DEBMED_TRAN_AMT, BigDecimal aLL_OTH_TRANSFER_DEBHIGH_TRAN_COUNT,
			BigDecimal aLL_OTH_TRANSFER_DEBHIGH_TRAN_AMT, String aLL_OTH_TRANSFER_CRED_PRODUCT,
			BigDecimal aLL_OTH_TRANSFER_CRED_LOW_TRAN_COUNT, BigDecimal aLL_OTH_TRANSFER_CRED_LOW_TRAN_AMT,
			BigDecimal aLL_OTH_TRANSFER_CREDMED_TRAN_COUNT, BigDecimal aLL_OTH_TRANSFER_CREDMED_TRAN_AMT,
			BigDecimal aLL_OTH_TRANSFER_CREDHIGH_TRAN_COUNT, BigDecimal aLL_OTH_TRANSFER_CREDHIGH_TRAN_AMT,
			String aLL_OTH_INW_PRODUCT, BigDecimal aLL_OTH_INW_LOW_TRAN_COUNT, BigDecimal aLL_OTH_INW_LOW_TRAN_AMT,
			BigDecimal aLL_OTH_INWMED_TRAN_COUNT, BigDecimal aLL_OTH_INWMED_TRAN_AMT,
			BigDecimal aLL_OTH_INWHIGH_TRAN_COUNT, BigDecimal aLL_OTH_INWHIGH_TRAN_AMT, String aLL_OTH_OUT_PRODUCT,
			BigDecimal aLL_OTH_OUT_LOW_TRAN_COUNT, BigDecimal aLL_OTH_OUT_LOW_TRAN_AMT,
			BigDecimal aLL_OTH_OUTMED_TRAN_COUNT, BigDecimal aLL_OTH_OUTMED_TRAN_AMT,
			BigDecimal aLL_OTH_OUTHIGH_TRAN_COUNT, BigDecimal aLL_OTH_OUTHIGH_TRAN_AMT, String oTHER_FEES_PRODUCT,
			BigDecimal oTHER_FEES_LOW_TRAN_COUNT, BigDecimal oTHER_FEES_LOW_TRAN_AMT,
			BigDecimal oTHER_FEESMED_TRAN_COUNT, BigDecimal oTHER_FEESMED_TRAN_AMT,
			BigDecimal oTHER_FEESHIGH_TRAN_COUNT, BigDecimal oTHER_FEESHIGH_TRAN_AMT, String tOTAL_SUM_PRODUCT,
			BigDecimal tOTAL_SUM_LOW_TRAN_COUNT, BigDecimal tOTAL_SUM_LOW_TRAN_AMT, BigDecimal tOTAL_SUMMED_TRAN_COUNT,
			BigDecimal tOTAL_SUMMED_TRAN_AMT, BigDecimal tOTAL_SUMHIGH_TRAN_COUNT, BigDecimal tOTAL_SUMHIGH_TRAN_AMT,
			String tHIRD_TRAN_500K_INW_PRODUCT, BigDecimal tHIRD_TRAN_500K_INW_LOW_TRAN_COUNT,
			BigDecimal tHIRD_TRAN_500K_INW_LOW_TRAN_AMT, BigDecimal tHIRD_TRAN_500K_INWMED_TRAN_COUNT,
			BigDecimal tHIRD_TRAN_500K_INWMED_TRAN_AMT, BigDecimal tHIRD_TRAN_500K_INWHIGH_TRAN_COUNT,
			BigDecimal tHIRD_TRAN_500K_INWHIGH_TRAN_AMT, String tHIRD_TRAN_500K_OUT_PRODUCT,
			BigDecimal tHIRD_TRAN_500K_OUT_LOW_TRAN_COUNT, BigDecimal tHIRD_TRAN_500K_OUT_LOW_TRAN_AMT,
			BigDecimal tHIRD_TRAN_500K_OUTMED_TRAN_COUNT, BigDecimal tHIRD_TRAN_500K_OUTMED_TRAN_AMT,
			BigDecimal tHIRD_TRAN_500K_OUTHIGH_TRAN_COUNT, BigDecimal tHIRD_TRAN_500K_OUTHIGH_TRAN_AMT,
			String tHIRD_TRAN_1000K_INW_PRODUCT, BigDecimal tHIRD_TRAN_1000K_INW_LOW_TRAN_COUNT,
			BigDecimal tHIRD_TRAN_1000K_INW_LOW_TRAN_AMT, BigDecimal tHIRD_TRAN_1000K_INWMED_TRAN_COUNT,
			BigDecimal tHIRD_TRAN_1000K_INWMED_TRAN_AMT, BigDecimal tHIRD_TRAN_1000K_INWHIGH_TRAN_COUNT,
			BigDecimal tHIRD_TRAN_1000K_INWHIGH_TRAN_AMT, String tHIRD_TRAN_1000K_OUT_PRODUCT,
			BigDecimal tHIRD_TRAN_1000K_OUT_LOW_TRAN_COUNT, BigDecimal tHIRD_TRAN_1000K_OUT_LOW_TRAN_AMT,
			BigDecimal tHIRD_TRAN_1000K_OUTMED_TRAN_COUNT, BigDecimal tHIRD_TRAN_1000K_OUTMED_TRAN_AMT,
			BigDecimal tHIRD_TRAN_1000K_OUTHIGH_TRAN_COUNT, BigDecimal tHIRD_TRAN_1000K_OUTHIGH_TRAN_AMT,
			String tHIRD_TRAN_MORE_1000K_INW_PRODUCT, BigDecimal tHIRD_TRAN_MORE_1000K_INW_LOW_TRAN_COUNT,
			BigDecimal tHIRD_TRAN_MORE_1000K_INW_LOW_TRAN_AMT, BigDecimal tHIRD_TRAN_MORE_1000K_INWMED_TRAN_COUNT,
			BigDecimal tHIRD_TRAN_MORE_1000K_INWMED_TRAN_AMT, BigDecimal tHIRD_TRAN_MORE_1000K_INWHIGH_TRAN_COUNT,
			BigDecimal tHIRD_TRAN_MORE_1000K_INWHIGH_TRAN_AMT, String tHIRD_TRAN_MORE_1000K_OUT_PRODUCT,
			BigDecimal tHIRD_TRAN_MORE_1000K_OUT_LOW_TRAN_COUNT, BigDecimal tHIRD_TRAN_MORE_1000K_OUT_LOW_TRAN_AMT,
			BigDecimal tHIRD_TRAN_MORE_1000K_OUTMED_TRAN_COUNT, BigDecimal tHIRD_TRAN_MORE_1000K_OUTMED_TRAN_AMT,
			BigDecimal tHIRD_TRAN_MORE_1000K_OUTHIGH_TRAN_COUNT, BigDecimal tHIRD_TRAN_MORE_1000K_OUTHIGH_TRAN_AMT,
			String dEBIT_CARD_PRODUCT, BigDecimal dEBIT_CARD_LOW_TRAN_COUNT, BigDecimal dEBIT_CARD_LOW_TRAN_AMT,
			BigDecimal dEBIT_CARDMED_TRAN_COUNT, BigDecimal dEBIT_CARDMED_TRAN_AMT,
			BigDecimal dEBIT_CARDHIGH_TRAN_COUNT, BigDecimal dEBIT_CARDHIGH_TRAN_AMT, String cREDIT_CARD_PRODUCT,
			BigDecimal cREDIT_CARD_LOW_TRAN_COUNT, BigDecimal cREDIT_CARD_LOW_TRAN_AMT,
			BigDecimal cREDIT_CARDMED_TRAN_COUNT, BigDecimal cREDIT_CARDMED_TRAN_AMT,
			BigDecimal cREDIT_CARDHIGH_TRAN_COUNT, BigDecimal cREDIT_CARDHIGH_TRAN_AMT, String pREPAID_CARD_PRODUCT,
			BigDecimal pREPAID_CARD_LOW_TRAN_COUNT, BigDecimal pREPAID_CARD_LOW_TRAN_AMT,
			BigDecimal pREPAID_CARDMED_TRAN_COUNT, BigDecimal pREPAID_CARDMED_TRAN_AMT,
			BigDecimal pREPAID_CARDHIGH_TRAN_COUNT, BigDecimal pREPAID_CARDHIGH_TRAN_AMT,
			String mOB_BANKING_INW_PRODUCT, BigDecimal mOB_BANKING_INW_LOW_TRAN_COUNT,
			BigDecimal mOB_BANKING_INW_LOW_TRAN_AMT, BigDecimal mOB_BANKING_INWMED_TRAN_COUNT,
			BigDecimal mOB_BANKING_INWMED_TRAN_AMT, BigDecimal mOB_BANKING_INWHIGH_TRAN_COUNT,
			BigDecimal mOB_BANKING_INWHIGH_TRAN_AMT, String mOB_BANKING_OUT_PRODUCT,
			BigDecimal mOB_BANKING_OUT_LOW_TRAN_COUNT, BigDecimal mOB_BANKING_OUT_LOW_TRAN_AMT,
			BigDecimal mOB_BANKING_OUTMED_TRAN_COUNT, BigDecimal mOB_BANKING_OUTMED_TRAN_AMT,
			BigDecimal mOB_BANKING_OUTHIGH_TRAN_COUNT, BigDecimal mOB_BANKING_OUTHIGH_TRAN_AMT,
			String iNTERNET_INW_PRODUCT, BigDecimal iNTERNET_INW_LOW_TRAN_COUNT, BigDecimal iNTERNET_INW_LOW_TRAN_AMT,
			BigDecimal iNTERNET_INWMED_TRAN_COUNT, BigDecimal iNTERNET_INWMED_TRAN_AMT,
			BigDecimal iNTERNET_INWHIGH_TRAN_COUNT, BigDecimal iNTERNET_INWHIGH_TRAN_AMT, String iNTERNET_OUT_PRODUCT,
			BigDecimal iNTERNET_OUT_LOW_TRAN_COUNT, BigDecimal iNTERNET_OUT_LOW_TRAN_AMT,
			BigDecimal iNTERNET_OUTMED_TRAN_COUNT, BigDecimal iNTERNET_OUTMED_TRAN_AMT,
			BigDecimal iNTERNET_OUTHIGH_TRAN_COUNT, BigDecimal iNTERNET_OUTHIGH_TRAN_AMT, String rEPORT_CODE,
			String rEPORT_NAME, Date rEPORT_DATE, Date rEPORT_DUE_DATE, Date rEP_SUBMIT_DATE, Date rEP_PERIOD_FROM,
			Date rEP_PERIOD_TO, String rEP_FREQ, String nIL_REPORT_FLG, String aRCH_FLG) {
		super();
		CASH_DEP_PRODUCT = cASH_DEP_PRODUCT;
		CASH_DEP_LOW_TRAN_COUNT = cASH_DEP_LOW_TRAN_COUNT;
		CASH_DEP_LOW_TRAN_AMT = cASH_DEP_LOW_TRAN_AMT;
		CASH_DEPMED_TRAN_COUNT = cASH_DEPMED_TRAN_COUNT;
		CASH_DEPMED_TRAN_AMT = cASH_DEPMED_TRAN_AMT;
		CASH_DEPHIGH_TRAN_COUNT = cASH_DEPHIGH_TRAN_COUNT;
		CASH_DEPHIGH_TRAN_AMT = cASH_DEPHIGH_TRAN_AMT;
		CASH_WITHD_PRODUCT = cASH_WITHD_PRODUCT;
		CASH_WITHD_LOW_TRAN_COUNT = cASH_WITHD_LOW_TRAN_COUNT;
		CASH_WITHD_LOW_TRAN_AMT = cASH_WITHD_LOW_TRAN_AMT;
		CASH_WITHDMED_TRAN_COUNT = cASH_WITHDMED_TRAN_COUNT;
		CASH_WITHDMED_TRAN_AMT = cASH_WITHDMED_TRAN_AMT;
		CASH_WITHDHIGH_TRAN_COUNT = cASH_WITHDHIGH_TRAN_COUNT;
		CASH_WITHDHIGH_TRAN_AMT = cASH_WITHDHIGH_TRAN_AMT;
		FX_SALE_EQL_PRODUCT = fX_SALE_EQL_PRODUCT;
		FX_SALE_EQL_LOW_TRAN_COUNT = fX_SALE_EQL_LOW_TRAN_COUNT;
		FX_SALE_EQL_LOW_TRAN_AMT = fX_SALE_EQL_LOW_TRAN_AMT;
		FX_SALE_EQLMED_TRAN_COUNT = fX_SALE_EQLMED_TRAN_COUNT;
		FX_SALE_EQLMED_TRAN_AMT = fX_SALE_EQLMED_TRAN_AMT;
		FX_SALE_EQLHIGH_TRAN_COUNT = fX_SALE_EQLHIGH_TRAN_COUNT;
		FX_SALE_EQLHIGH_TRAN_AMT = fX_SALE_EQLHIGH_TRAN_AMT;
		FX_SALE_MORE_PRODUCT = fX_SALE_MORE_PRODUCT;
		FX_SALE_MORE_LOW_TRAN_COUNT = fX_SALE_MORE_LOW_TRAN_COUNT;
		FX_SALE_MORE_LOW_TRAN_AMT = fX_SALE_MORE_LOW_TRAN_AMT;
		FX_SALE_MOREMED_TRAN_COUNT = fX_SALE_MOREMED_TRAN_COUNT;
		FX_SALE_MOREMED_TRAN_AMT = fX_SALE_MOREMED_TRAN_AMT;
		FX_SALE_MOREHIGH_TRAN_COUNT = fX_SALE_MOREHIGH_TRAN_COUNT;
		FX_SALE_MOREHIGH_TRAN_AMT = fX_SALE_MOREHIGH_TRAN_AMT;
		FX_PUR_EQL_PRODUCT = fX_PUR_EQL_PRODUCT;
		FX_PUR_EQL_LOW_TRAN_COUNT = fX_PUR_EQL_LOW_TRAN_COUNT;
		FX_PUR_EQL_LOW_TRAN_AMT = fX_PUR_EQL_LOW_TRAN_AMT;
		FX_PUR_EQLMED_TRAN_COUNT = fX_PUR_EQLMED_TRAN_COUNT;
		FX_PUR_EQLMED_TRAN_AMT = fX_PUR_EQLMED_TRAN_AMT;
		FX_PUR_EQLHIGH_TRAN_COUNT = fX_PUR_EQLHIGH_TRAN_COUNT;
		FX_PUR_EQLHIGH_TRAN_AMT = fX_PUR_EQLHIGH_TRAN_AMT;
		FX_PUR_MORE_PRODUCT = fX_PUR_MORE_PRODUCT;
		FX_PUR_MORE_LOW_TRAN_COUNT = fX_PUR_MORE_LOW_TRAN_COUNT;
		FX_PUR_MORE_LOW_TRAN_AMT = fX_PUR_MORE_LOW_TRAN_AMT;
		FX_PUR_MOREMED_TRAN_COUNT = fX_PUR_MOREMED_TRAN_COUNT;
		FX_PUR_MOREMED_TRAN_AMT = fX_PUR_MOREMED_TRAN_AMT;
		FX_PUR_MOREHIGH_TRAN_COUNT = fX_PUR_MOREHIGH_TRAN_COUNT;
		FX_PUR_MOREHIGH_TRAN_AMT = fX_PUR_MOREHIGH_TRAN_AMT;
		DOM_INW_PRODUCT = dOM_INW_PRODUCT;
		DOM_INW_LOW_TRAN_COUNT = dOM_INW_LOW_TRAN_COUNT;
		DOM_INW_LOW_TRAN_AMT = dOM_INW_LOW_TRAN_AMT;
		DOM_INWMED_TRAN_COUNT = dOM_INWMED_TRAN_COUNT;
		DOM_INWMED_TRAN_AMT = dOM_INWMED_TRAN_AMT;
		DOM_INWHIGH_TRAN_COUNT = dOM_INWHIGH_TRAN_COUNT;
		DOM_INWHIGH_TRAN_AMT = dOM_INWHIGH_TRAN_AMT;
		DOM_OUT_PRODUCT = dOM_OUT_PRODUCT;
		DOM_OUT_LOW_TRAN_COUNT = dOM_OUT_LOW_TRAN_COUNT;
		DOM_OUT_LOW_TRAN_AMT = dOM_OUT_LOW_TRAN_AMT;
		DOM_OUTMED_TRAN_COUNT = dOM_OUTMED_TRAN_COUNT;
		DOM_OUTMED_TRAN_AMT = dOM_OUTMED_TRAN_AMT;
		DOM_OUTHIGH_TRAN_COUNT = dOM_OUTHIGH_TRAN_COUNT;
		DOM_OUTHIGH_TRAN_AMT = dOM_OUTHIGH_TRAN_AMT;
		INT_TRADE_INW_PRODUCT = iNT_TRADE_INW_PRODUCT;
		INT_TRADE_INW_LOW_TRAN_COUNT = iNT_TRADE_INW_LOW_TRAN_COUNT;
		INT_TRADE_INW_LOW_TRAN_AMT = iNT_TRADE_INW_LOW_TRAN_AMT;
		INT_TRADE_INWMED_TRAN_COUNT = iNT_TRADE_INWMED_TRAN_COUNT;
		INT_TRADE_INWMED_TRAN_AMT = iNT_TRADE_INWMED_TRAN_AMT;
		INT_TRADE_INWHIGH_TRAN_COUNT = iNT_TRADE_INWHIGH_TRAN_COUNT;
		INT_TRADE_INWHIGH_TRAN_AMT = iNT_TRADE_INWHIGH_TRAN_AMT;
		INT_TRADE_OUT_PRODUCT = iNT_TRADE_OUT_PRODUCT;
		INT_TRADE_OUT_LOW_TRAN_COUNT = iNT_TRADE_OUT_LOW_TRAN_COUNT;
		INT_TRADE_OUT_LOW_TRAN_AMT = iNT_TRADE_OUT_LOW_TRAN_AMT;
		INT_TRADE_OUTMED_TRAN_COUNT = iNT_TRADE_OUTMED_TRAN_COUNT;
		INT_TRADE_OUTMED_TRAN_AMT = iNT_TRADE_OUTMED_TRAN_AMT;
		INT_TRADE_OUTHIGH_TRAN_COUNT = iNT_TRADE_OUTHIGH_TRAN_COUNT;
		INT_TRADE_OUTHIGH_TRAN_AMT = iNT_TRADE_OUTHIGH_TRAN_AMT;
		INT_NON_TRADE_INW_PRODUCT = iNT_NON_TRADE_INW_PRODUCT;
		INT_NON_TRADE_INW_LOW_TRAN_COUNT = iNT_NON_TRADE_INW_LOW_TRAN_COUNT;
		INT_NON_TRADE_INW_LOW_TRAN_AMT = iNT_NON_TRADE_INW_LOW_TRAN_AMT;
		INT_NON_TRADE_INWMED_TRAN_COUNT = iNT_NON_TRADE_INWMED_TRAN_COUNT;
		INT_NON_TRADE_INWMED_TRAN_AMT = iNT_NON_TRADE_INWMED_TRAN_AMT;
		INT_NON_TRADE_INWHIGH_TRAN_COUNT = iNT_NON_TRADE_INWHIGH_TRAN_COUNT;
		INT_NON_TRADE_INWHIGH_TRAN_AMT = iNT_NON_TRADE_INWHIGH_TRAN_AMT;
		INT_NON_TRADE_OUT_PRODUCT = iNT_NON_TRADE_OUT_PRODUCT;
		INT_NON_TRADE_OUT_LOW_TRAN_COUNT = iNT_NON_TRADE_OUT_LOW_TRAN_COUNT;
		INT_NON_TRADE_OUT_LOW_TRAN_AMT = iNT_NON_TRADE_OUT_LOW_TRAN_AMT;
		INT_NON_TRADE_OUTMED_TRAN_COUNT = iNT_NON_TRADE_OUTMED_TRAN_COUNT;
		INT_NON_TRADE_OUTMED_TRAN_AMT = iNT_NON_TRADE_OUTMED_TRAN_AMT;
		INT_NON_TRADE_OUTHIGH_TRAN_COUNT = iNT_NON_TRADE_OUTHIGH_TRAN_COUNT;
		INT_NON_TRADE_OUTHIGH_TRAN_AMT = iNT_NON_TRADE_OUTHIGH_TRAN_AMT;
		ALL_OTH_TRANSFER_DEB_PRODUCT = aLL_OTH_TRANSFER_DEB_PRODUCT;
		ALL_OTH_TRANSFER_DEB_LOW_TRAN_COUNT = aLL_OTH_TRANSFER_DEB_LOW_TRAN_COUNT;
		ALL_OTH_TRANSFER_DEB_LOW_TRAN_AMT = aLL_OTH_TRANSFER_DEB_LOW_TRAN_AMT;
		ALL_OTH_TRANSFER_DEBMED_TRAN_COUNT = aLL_OTH_TRANSFER_DEBMED_TRAN_COUNT;
		ALL_OTH_TRANSFER_DEBMED_TRAN_AMT = aLL_OTH_TRANSFER_DEBMED_TRAN_AMT;
		ALL_OTH_TRANSFER_DEBHIGH_TRAN_COUNT = aLL_OTH_TRANSFER_DEBHIGH_TRAN_COUNT;
		ALL_OTH_TRANSFER_DEBHIGH_TRAN_AMT = aLL_OTH_TRANSFER_DEBHIGH_TRAN_AMT;
		ALL_OTH_TRANSFER_CRED_PRODUCT = aLL_OTH_TRANSFER_CRED_PRODUCT;
		ALL_OTH_TRANSFER_CRED_LOW_TRAN_COUNT = aLL_OTH_TRANSFER_CRED_LOW_TRAN_COUNT;
		ALL_OTH_TRANSFER_CRED_LOW_TRAN_AMT = aLL_OTH_TRANSFER_CRED_LOW_TRAN_AMT;
		ALL_OTH_TRANSFER_CREDMED_TRAN_COUNT = aLL_OTH_TRANSFER_CREDMED_TRAN_COUNT;
		ALL_OTH_TRANSFER_CREDMED_TRAN_AMT = aLL_OTH_TRANSFER_CREDMED_TRAN_AMT;
		ALL_OTH_TRANSFER_CREDHIGH_TRAN_COUNT = aLL_OTH_TRANSFER_CREDHIGH_TRAN_COUNT;
		ALL_OTH_TRANSFER_CREDHIGH_TRAN_AMT = aLL_OTH_TRANSFER_CREDHIGH_TRAN_AMT;
		ALL_OTH_INW_PRODUCT = aLL_OTH_INW_PRODUCT;
		ALL_OTH_INW_LOW_TRAN_COUNT = aLL_OTH_INW_LOW_TRAN_COUNT;
		ALL_OTH_INW_LOW_TRAN_AMT = aLL_OTH_INW_LOW_TRAN_AMT;
		ALL_OTH_INWMED_TRAN_COUNT = aLL_OTH_INWMED_TRAN_COUNT;
		ALL_OTH_INWMED_TRAN_AMT = aLL_OTH_INWMED_TRAN_AMT;
		ALL_OTH_INWHIGH_TRAN_COUNT = aLL_OTH_INWHIGH_TRAN_COUNT;
		ALL_OTH_INWHIGH_TRAN_AMT = aLL_OTH_INWHIGH_TRAN_AMT;
		ALL_OTH_OUT_PRODUCT = aLL_OTH_OUT_PRODUCT;
		ALL_OTH_OUT_LOW_TRAN_COUNT = aLL_OTH_OUT_LOW_TRAN_COUNT;
		ALL_OTH_OUT_LOW_TRAN_AMT = aLL_OTH_OUT_LOW_TRAN_AMT;
		ALL_OTH_OUTMED_TRAN_COUNT = aLL_OTH_OUTMED_TRAN_COUNT;
		ALL_OTH_OUTMED_TRAN_AMT = aLL_OTH_OUTMED_TRAN_AMT;
		ALL_OTH_OUTHIGH_TRAN_COUNT = aLL_OTH_OUTHIGH_TRAN_COUNT;
		ALL_OTH_OUTHIGH_TRAN_AMT = aLL_OTH_OUTHIGH_TRAN_AMT;
		OTHER_FEES_PRODUCT = oTHER_FEES_PRODUCT;
		OTHER_FEES_LOW_TRAN_COUNT = oTHER_FEES_LOW_TRAN_COUNT;
		OTHER_FEES_LOW_TRAN_AMT = oTHER_FEES_LOW_TRAN_AMT;
		OTHER_FEESMED_TRAN_COUNT = oTHER_FEESMED_TRAN_COUNT;
		OTHER_FEESMED_TRAN_AMT = oTHER_FEESMED_TRAN_AMT;
		OTHER_FEESHIGH_TRAN_COUNT = oTHER_FEESHIGH_TRAN_COUNT;
		OTHER_FEESHIGH_TRAN_AMT = oTHER_FEESHIGH_TRAN_AMT;
		TOTAL_SUM_PRODUCT = tOTAL_SUM_PRODUCT;
		TOTAL_SUM_LOW_TRAN_COUNT = tOTAL_SUM_LOW_TRAN_COUNT;
		TOTAL_SUM_LOW_TRAN_AMT = tOTAL_SUM_LOW_TRAN_AMT;
		TOTAL_SUMMED_TRAN_COUNT = tOTAL_SUMMED_TRAN_COUNT;
		TOTAL_SUMMED_TRAN_AMT = tOTAL_SUMMED_TRAN_AMT;
		TOTAL_SUMHIGH_TRAN_COUNT = tOTAL_SUMHIGH_TRAN_COUNT;
		TOTAL_SUMHIGH_TRAN_AMT = tOTAL_SUMHIGH_TRAN_AMT;
		THIRD_TRAN_500K_INW_PRODUCT = tHIRD_TRAN_500K_INW_PRODUCT;
		THIRD_TRAN_500K_INW_LOW_TRAN_COUNT = tHIRD_TRAN_500K_INW_LOW_TRAN_COUNT;
		THIRD_TRAN_500K_INW_LOW_TRAN_AMT = tHIRD_TRAN_500K_INW_LOW_TRAN_AMT;
		THIRD_TRAN_500K_INWMED_TRAN_COUNT = tHIRD_TRAN_500K_INWMED_TRAN_COUNT;
		THIRD_TRAN_500K_INWMED_TRAN_AMT = tHIRD_TRAN_500K_INWMED_TRAN_AMT;
		THIRD_TRAN_500K_INWHIGH_TRAN_COUNT = tHIRD_TRAN_500K_INWHIGH_TRAN_COUNT;
		THIRD_TRAN_500K_INWHIGH_TRAN_AMT = tHIRD_TRAN_500K_INWHIGH_TRAN_AMT;
		THIRD_TRAN_500K_OUT_PRODUCT = tHIRD_TRAN_500K_OUT_PRODUCT;
		THIRD_TRAN_500K_OUT_LOW_TRAN_COUNT = tHIRD_TRAN_500K_OUT_LOW_TRAN_COUNT;
		THIRD_TRAN_500K_OUT_LOW_TRAN_AMT = tHIRD_TRAN_500K_OUT_LOW_TRAN_AMT;
		THIRD_TRAN_500K_OUTMED_TRAN_COUNT = tHIRD_TRAN_500K_OUTMED_TRAN_COUNT;
		THIRD_TRAN_500K_OUTMED_TRAN_AMT = tHIRD_TRAN_500K_OUTMED_TRAN_AMT;
		THIRD_TRAN_500K_OUTHIGH_TRAN_COUNT = tHIRD_TRAN_500K_OUTHIGH_TRAN_COUNT;
		THIRD_TRAN_500K_OUTHIGH_TRAN_AMT = tHIRD_TRAN_500K_OUTHIGH_TRAN_AMT;
		THIRD_TRAN_1000K_INW_PRODUCT = tHIRD_TRAN_1000K_INW_PRODUCT;
		THIRD_TRAN_1000K_INW_LOW_TRAN_COUNT = tHIRD_TRAN_1000K_INW_LOW_TRAN_COUNT;
		THIRD_TRAN_1000K_INW_LOW_TRAN_AMT = tHIRD_TRAN_1000K_INW_LOW_TRAN_AMT;
		THIRD_TRAN_1000K_INWMED_TRAN_COUNT = tHIRD_TRAN_1000K_INWMED_TRAN_COUNT;
		THIRD_TRAN_1000K_INWMED_TRAN_AMT = tHIRD_TRAN_1000K_INWMED_TRAN_AMT;
		THIRD_TRAN_1000K_INWHIGH_TRAN_COUNT = tHIRD_TRAN_1000K_INWHIGH_TRAN_COUNT;
		THIRD_TRAN_1000K_INWHIGH_TRAN_AMT = tHIRD_TRAN_1000K_INWHIGH_TRAN_AMT;
		THIRD_TRAN_1000K_OUT_PRODUCT = tHIRD_TRAN_1000K_OUT_PRODUCT;
		THIRD_TRAN_1000K_OUT_LOW_TRAN_COUNT = tHIRD_TRAN_1000K_OUT_LOW_TRAN_COUNT;
		THIRD_TRAN_1000K_OUT_LOW_TRAN_AMT = tHIRD_TRAN_1000K_OUT_LOW_TRAN_AMT;
		THIRD_TRAN_1000K_OUTMED_TRAN_COUNT = tHIRD_TRAN_1000K_OUTMED_TRAN_COUNT;
		THIRD_TRAN_1000K_OUTMED_TRAN_AMT = tHIRD_TRAN_1000K_OUTMED_TRAN_AMT;
		THIRD_TRAN_1000K_OUTHIGH_TRAN_COUNT = tHIRD_TRAN_1000K_OUTHIGH_TRAN_COUNT;
		THIRD_TRAN_1000K_OUTHIGH_TRAN_AMT = tHIRD_TRAN_1000K_OUTHIGH_TRAN_AMT;
		THIRD_TRAN_MORE_1000K_INW_PRODUCT = tHIRD_TRAN_MORE_1000K_INW_PRODUCT;
		THIRD_TRAN_MORE_1000K_INW_LOW_TRAN_COUNT = tHIRD_TRAN_MORE_1000K_INW_LOW_TRAN_COUNT;
		THIRD_TRAN_MORE_1000K_INW_LOW_TRAN_AMT = tHIRD_TRAN_MORE_1000K_INW_LOW_TRAN_AMT;
		THIRD_TRAN_MORE_1000K_INWMED_TRAN_COUNT = tHIRD_TRAN_MORE_1000K_INWMED_TRAN_COUNT;
		THIRD_TRAN_MORE_1000K_INWMED_TRAN_AMT = tHIRD_TRAN_MORE_1000K_INWMED_TRAN_AMT;
		THIRD_TRAN_MORE_1000K_INWHIGH_TRAN_COUNT = tHIRD_TRAN_MORE_1000K_INWHIGH_TRAN_COUNT;
		THIRD_TRAN_MORE_1000K_INWHIGH_TRAN_AMT = tHIRD_TRAN_MORE_1000K_INWHIGH_TRAN_AMT;
		THIRD_TRAN_MORE_1000K_OUT_PRODUCT = tHIRD_TRAN_MORE_1000K_OUT_PRODUCT;
		THIRD_TRAN_MORE_1000K_OUT_LOW_TRAN_COUNT = tHIRD_TRAN_MORE_1000K_OUT_LOW_TRAN_COUNT;
		THIRD_TRAN_MORE_1000K_OUT_LOW_TRAN_AMT = tHIRD_TRAN_MORE_1000K_OUT_LOW_TRAN_AMT;
		THIRD_TRAN_MORE_1000K_OUTMED_TRAN_COUNT = tHIRD_TRAN_MORE_1000K_OUTMED_TRAN_COUNT;
		THIRD_TRAN_MORE_1000K_OUTMED_TRAN_AMT = tHIRD_TRAN_MORE_1000K_OUTMED_TRAN_AMT;
		THIRD_TRAN_MORE_1000K_OUTHIGH_TRAN_COUNT = tHIRD_TRAN_MORE_1000K_OUTHIGH_TRAN_COUNT;
		THIRD_TRAN_MORE_1000K_OUTHIGH_TRAN_AMT = tHIRD_TRAN_MORE_1000K_OUTHIGH_TRAN_AMT;
		DEBIT_CARD_PRODUCT = dEBIT_CARD_PRODUCT;
		DEBIT_CARD_LOW_TRAN_COUNT = dEBIT_CARD_LOW_TRAN_COUNT;
		DEBIT_CARD_LOW_TRAN_AMT = dEBIT_CARD_LOW_TRAN_AMT;
		DEBIT_CARDMED_TRAN_COUNT = dEBIT_CARDMED_TRAN_COUNT;
		DEBIT_CARDMED_TRAN_AMT = dEBIT_CARDMED_TRAN_AMT;
		DEBIT_CARDHIGH_TRAN_COUNT = dEBIT_CARDHIGH_TRAN_COUNT;
		DEBIT_CARDHIGH_TRAN_AMT = dEBIT_CARDHIGH_TRAN_AMT;
		CREDIT_CARD_PRODUCT = cREDIT_CARD_PRODUCT;
		CREDIT_CARD_LOW_TRAN_COUNT = cREDIT_CARD_LOW_TRAN_COUNT;
		CREDIT_CARD_LOW_TRAN_AMT = cREDIT_CARD_LOW_TRAN_AMT;
		CREDIT_CARDMED_TRAN_COUNT = cREDIT_CARDMED_TRAN_COUNT;
		CREDIT_CARDMED_TRAN_AMT = cREDIT_CARDMED_TRAN_AMT;
		CREDIT_CARDHIGH_TRAN_COUNT = cREDIT_CARDHIGH_TRAN_COUNT;
		CREDIT_CARDHIGH_TRAN_AMT = cREDIT_CARDHIGH_TRAN_AMT;
		PREPAID_CARD_PRODUCT = pREPAID_CARD_PRODUCT;
		PREPAID_CARD_LOW_TRAN_COUNT = pREPAID_CARD_LOW_TRAN_COUNT;
		PREPAID_CARD_LOW_TRAN_AMT = pREPAID_CARD_LOW_TRAN_AMT;
		PREPAID_CARDMED_TRAN_COUNT = pREPAID_CARDMED_TRAN_COUNT;
		PREPAID_CARDMED_TRAN_AMT = pREPAID_CARDMED_TRAN_AMT;
		PREPAID_CARDHIGH_TRAN_COUNT = pREPAID_CARDHIGH_TRAN_COUNT;
		PREPAID_CARDHIGH_TRAN_AMT = pREPAID_CARDHIGH_TRAN_AMT;
		MOB_BANKING_INW_PRODUCT = mOB_BANKING_INW_PRODUCT;
		MOB_BANKING_INW_LOW_TRAN_COUNT = mOB_BANKING_INW_LOW_TRAN_COUNT;
		MOB_BANKING_INW_LOW_TRAN_AMT = mOB_BANKING_INW_LOW_TRAN_AMT;
		MOB_BANKING_INWMED_TRAN_COUNT = mOB_BANKING_INWMED_TRAN_COUNT;
		MOB_BANKING_INWMED_TRAN_AMT = mOB_BANKING_INWMED_TRAN_AMT;
		MOB_BANKING_INWHIGH_TRAN_COUNT = mOB_BANKING_INWHIGH_TRAN_COUNT;
		MOB_BANKING_INWHIGH_TRAN_AMT = mOB_BANKING_INWHIGH_TRAN_AMT;
		MOB_BANKING_OUT_PRODUCT = mOB_BANKING_OUT_PRODUCT;
		MOB_BANKING_OUT_LOW_TRAN_COUNT = mOB_BANKING_OUT_LOW_TRAN_COUNT;
		MOB_BANKING_OUT_LOW_TRAN_AMT = mOB_BANKING_OUT_LOW_TRAN_AMT;
		MOB_BANKING_OUTMED_TRAN_COUNT = mOB_BANKING_OUTMED_TRAN_COUNT;
		MOB_BANKING_OUTMED_TRAN_AMT = mOB_BANKING_OUTMED_TRAN_AMT;
		MOB_BANKING_OUTHIGH_TRAN_COUNT = mOB_BANKING_OUTHIGH_TRAN_COUNT;
		MOB_BANKING_OUTHIGH_TRAN_AMT = mOB_BANKING_OUTHIGH_TRAN_AMT;
		INTERNET_INW_PRODUCT = iNTERNET_INW_PRODUCT;
		INTERNET_INW_LOW_TRAN_COUNT = iNTERNET_INW_LOW_TRAN_COUNT;
		INTERNET_INW_LOW_TRAN_AMT = iNTERNET_INW_LOW_TRAN_AMT;
		INTERNET_INWMED_TRAN_COUNT = iNTERNET_INWMED_TRAN_COUNT;
		INTERNET_INWMED_TRAN_AMT = iNTERNET_INWMED_TRAN_AMT;
		INTERNET_INWHIGH_TRAN_COUNT = iNTERNET_INWHIGH_TRAN_COUNT;
		INTERNET_INWHIGH_TRAN_AMT = iNTERNET_INWHIGH_TRAN_AMT;
		INTERNET_OUT_PRODUCT = iNTERNET_OUT_PRODUCT;
		INTERNET_OUT_LOW_TRAN_COUNT = iNTERNET_OUT_LOW_TRAN_COUNT;
		INTERNET_OUT_LOW_TRAN_AMT = iNTERNET_OUT_LOW_TRAN_AMT;
		INTERNET_OUTMED_TRAN_COUNT = iNTERNET_OUTMED_TRAN_COUNT;
		INTERNET_OUTMED_TRAN_AMT = iNTERNET_OUTMED_TRAN_AMT;
		INTERNET_OUTHIGH_TRAN_COUNT = iNTERNET_OUTHIGH_TRAN_COUNT;
		INTERNET_OUTHIGH_TRAN_AMT = iNTERNET_OUTHIGH_TRAN_AMT;
		REPORT_CODE = rEPORT_CODE;
		REPORT_NAME = rEPORT_NAME;
		REPORT_DATE = rEPORT_DATE;
		REPORT_DUE_DATE = rEPORT_DUE_DATE;
		REP_SUBMIT_DATE = rEP_SUBMIT_DATE;
		REP_PERIOD_FROM = rEP_PERIOD_FROM;
		REP_PERIOD_TO = rEP_PERIOD_TO;
		REP_FREQ = rEP_FREQ;
		NIL_REPORT_FLG = nIL_REPORT_FLG;
		ARCH_FLG = aRCH_FLG;
	}
	public T12AReport() {
		super();
		// TODO Auto-generated constructor stub
	}

	
}
