package com.bornfire.xbrl.entities.BRSS;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;
@Entity
@Table(name="T15_OR_MODEL_DEPLOYMENT_ENDQUARTER_TABLE")
public class T15ORReport {
	private String	A1_PRODUCT;
	private String	A1_INT_NUMBER;
	private String	A1_INT_NO_OF_BUSINESS_RELEVANT;
	private String	A1_INT_BUSINESS_LINES_RELEVANT;
	private String	A1_EXT_NUMBER;
	private String	A1_EXT_NO_OF_BUSINESS_RELEVANT;
	private String	A1_EXT_BUSINESS_LINES_RELEVANT;
	private String	A1_TOTAL_NO_MODELS;
	private String	A1_TOTAL_NO_BUSINESS_LINES;
	private String	A2_PRODUCT;
	private String	A2_INT_NUMBER;
	private String	A2_INT_NO_OF_BUSINESS_RELEVANT;
	private String	A2_INT_BUSINESS_LINES_RELEVANT;
	private String	A2_EXT_NUMBER;
	private String	A2_EXT_NO_OF_BUSINESS_RELEVANT;
	private String	A2_EXT_BUSINESS_LINES_RELEVANT;
	private String	A2_TOTAL_NO_MODELS;
	private String	A2_TOTAL_NO_BUSINESS_LINES;
	private String	A3_PRODUCT;
	private String	A3_INT_NUMBER;
	private String	A3_INT_NO_OF_BUSINESS_RELEVANT;
	private String	A3_INT_BUSINESS_LINES_RELEVANT;
	private String	A3_EXT_NUMBER;
	private String	A3_EXT_NO_OF_BUSINESS_RELEVANT;
	private String	A3_EXT_BUSINESS_LINES_RELEVANT;
	private String	A3_TOTAL_NO_MODELS;
	private String	A3_TOTAL_NO_BUSINESS_LINES;
	private String	A4_PRODUCT;
	private String	A4_INT_NUMBER;
	private String	A4_INT_NO_OF_BUSINESS_RELEVANT;
	private String	A4_INT_BUSINESS_LINES_RELEVANT;
	private String	A4_EXT_NUMBER;
	private String	A4_EXT_NO_OF_BUSINESS_RELEVANT;
	private String	A4_EXT_BUSINESS_LINES_RELEVANT;
	private String	A4_TOTAL_NO_MODELS;
	private String	A4_TOTAL_NO_BUSINESS_LINES;
	private String	A5_PRODUCT;
	private String	A5_INT_NUMBER;
	private String	A5_INT_NO_OF_BUSINESS_RELEVANT;
	private String	A5_INT_BUSINESS_LINES_RELEVANT;
	private String	A5_EXT_NUMBER;
	private String	A5_EXT_NO_OF_BUSINESS_RELEVANT;
	private String	A5_EXT_BUSINESS_LINES_RELEVANT;
	private String	A5_TOTAL_NO_MODELS;
	private String	A5_TOTAL_NO_BUSINESS_LINES;
	private String	A6_PRODUCT;
	private String	A6_INT_NUMBER;
	private String	A6_INT_NO_OF_BUSINESS_RELEVANT;
	private String	A6_INT_BUSINESS_LINES_RELEVANT;
	private String	A6_EXT_NUMBER;
	private String	A6_EXT_NO_OF_BUSINESS_RELEVANT;
	private String	A6_EXT_BUSINESS_LINES_RELEVANT;
	private String	A6_TOTAL_NO_MODELS;
	private String	A6_TOTAL_NO_BUSINESS_LINES;
	private String	A7_PRODUCT;
	private String	A7_INT_NUMBER;
	private String	A7_INT_NO_OF_BUSINESS_RELEVANT;
	private String	A7_INT_BUSINESS_LINES_RELEVANT;
	private String	A7_EXT_NUMBER;
	private String	A7_EXT_NO_OF_BUSINESS_RELEVANT;
	private String	A7_EXT_BUSINESS_LINES_RELEVANT;
	private String	A7_TOTAL_NO_MODELS;
	private String	A7_TOTAL_NO_BUSINESS_LINES;
	private String	A8_PRODUCT;
	private String	A8_INT_NUMBER;
	private String	A8_INT_NO_OF_BUSINESS_RELEVANT;
	private String	A8_INT_BUSINESS_LINES_RELEVANT;
	private String	A8_EXT_NUMBER;
	private String	A8_EXT_NO_OF_BUSINESS_RELEVANT;
	private String	A8_EXT_BUSINESS_LINES_RELEVANT;
	private String	A8_TOTAL_NO_MODELS;
	private String	A8_TOTAL_NO_BUSINESS_LINES;
	private String	A9_PRODUCT;
	private String	A9_INT_NUMBER;
	private String	A9_INT_NO_OF_BUSINESS_RELEVANT;
	private String	A9_INT_BUSINESS_LINES_RELEVANT;
	private String	A9_EXT_NUMBER;
	private String	A9_EXT_NO_OF_BUSINESS_RELEVANT;
	private String	A9_EXT_BUSINESS_LINES_RELEVANT;
	private String	A9_TOTAL_NO_MODELS;
	private String	A9_TOTAL_NO_BUSINESS_LINES;
	private String	A10_PRODUCT;
	private String	A10_INT_NUMBER;
	private String	A10_INT_NO_OF_BUSINESS_RELEVANT;
	private String	A10_INT_BUSINESS_LINES_RELEVANT;
	private String	A10_EXT_NUMBER;
	private String	A10_EXT_NO_OF_BUSINESS_RELEVANT;
	private String	A10_EXT_BUSINESS_LINES_RELEVANT;
	private String	A10_TOTAL_NO_MODELS;
	private String	A10_TOTAL_NO_BUSINESS_LINES;
	private String	REPORT_CODE;
	private String	REPORT_NAME;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	@Id
	private Date	REPORT_DATE;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	REPORT_DUE_DATE;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	REP_SUBMIT_DATE;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	REP_PERIOD_FROM;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	REP_PERIOD_TO;
	private String	REP_FREQ;
	private String	NIL_REPORT_FLG;
	private String	ARCH_FLG;
	private String	ENTITY_FLG;
	private String	DEL_FLG;
	private String	MODIFY_FLG;
	private String	ENTRY_USER;
	private String	MODIFY_USER;
	private String	VERIFY_USER;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	ENTRY_TIME;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	MODIFY_TIME;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	VERIFY_TIME;
	private String	QTR_FLG;
	public String getA1_PRODUCT() {
		return A1_PRODUCT;
	}
	public void setA1_PRODUCT(String a1_PRODUCT) {
		A1_PRODUCT = a1_PRODUCT;
	}
	public String getA1_INT_NUMBER() {
		return A1_INT_NUMBER;
	}
	public void setA1_INT_NUMBER(String a1_INT_NUMBER) {
		A1_INT_NUMBER = a1_INT_NUMBER;
	}
	public String getA1_INT_NO_OF_BUSINESS_RELEVANT() {
		return A1_INT_NO_OF_BUSINESS_RELEVANT;
	}
	public void setA1_INT_NO_OF_BUSINESS_RELEVANT(String a1_INT_NO_OF_BUSINESS_RELEVANT) {
		A1_INT_NO_OF_BUSINESS_RELEVANT = a1_INT_NO_OF_BUSINESS_RELEVANT;
	}
	public String getA1_INT_BUSINESS_LINES_RELEVANT() {
		return A1_INT_BUSINESS_LINES_RELEVANT;
	}
	public void setA1_INT_BUSINESS_LINES_RELEVANT(String a1_INT_BUSINESS_LINES_RELEVANT) {
		A1_INT_BUSINESS_LINES_RELEVANT = a1_INT_BUSINESS_LINES_RELEVANT;
	}
	public String getA1_EXT_NUMBER() {
		return A1_EXT_NUMBER;
	}
	public void setA1_EXT_NUMBER(String a1_EXT_NUMBER) {
		A1_EXT_NUMBER = a1_EXT_NUMBER;
	}
	public String getA1_EXT_NO_OF_BUSINESS_RELEVANT() {
		return A1_EXT_NO_OF_BUSINESS_RELEVANT;
	}
	public void setA1_EXT_NO_OF_BUSINESS_RELEVANT(String a1_EXT_NO_OF_BUSINESS_RELEVANT) {
		A1_EXT_NO_OF_BUSINESS_RELEVANT = a1_EXT_NO_OF_BUSINESS_RELEVANT;
	}
	public String getA1_EXT_BUSINESS_LINES_RELEVANT() {
		return A1_EXT_BUSINESS_LINES_RELEVANT;
	}
	public void setA1_EXT_BUSINESS_LINES_RELEVANT(String a1_EXT_BUSINESS_LINES_RELEVANT) {
		A1_EXT_BUSINESS_LINES_RELEVANT = a1_EXT_BUSINESS_LINES_RELEVANT;
	}
	public String getA1_TOTAL_NO_MODELS() {
		return A1_TOTAL_NO_MODELS;
	}
	public void setA1_TOTAL_NO_MODELS(String a1_TOTAL_NO_MODELS) {
		A1_TOTAL_NO_MODELS = a1_TOTAL_NO_MODELS;
	}
	public String getA1_TOTAL_NO_BUSINESS_LINES() {
		return A1_TOTAL_NO_BUSINESS_LINES;
	}
	public void setA1_TOTAL_NO_BUSINESS_LINES(String a1_TOTAL_NO_BUSINESS_LINES) {
		A1_TOTAL_NO_BUSINESS_LINES = a1_TOTAL_NO_BUSINESS_LINES;
	}
	public String getA2_PRODUCT() {
		return A2_PRODUCT;
	}
	public void setA2_PRODUCT(String a2_PRODUCT) {
		A2_PRODUCT = a2_PRODUCT;
	}
	public String getA2_INT_NUMBER() {
		return A2_INT_NUMBER;
	}
	public void setA2_INT_NUMBER(String a2_INT_NUMBER) {
		A2_INT_NUMBER = a2_INT_NUMBER;
	}
	public String getA2_INT_NO_OF_BUSINESS_RELEVANT() {
		return A2_INT_NO_OF_BUSINESS_RELEVANT;
	}
	public void setA2_INT_NO_OF_BUSINESS_RELEVANT(String a2_INT_NO_OF_BUSINESS_RELEVANT) {
		A2_INT_NO_OF_BUSINESS_RELEVANT = a2_INT_NO_OF_BUSINESS_RELEVANT;
	}
	public String getA2_INT_BUSINESS_LINES_RELEVANT() {
		return A2_INT_BUSINESS_LINES_RELEVANT;
	}
	public void setA2_INT_BUSINESS_LINES_RELEVANT(String a2_INT_BUSINESS_LINES_RELEVANT) {
		A2_INT_BUSINESS_LINES_RELEVANT = a2_INT_BUSINESS_LINES_RELEVANT;
	}
	public String getA2_EXT_NUMBER() {
		return A2_EXT_NUMBER;
	}
	public void setA2_EXT_NUMBER(String a2_EXT_NUMBER) {
		A2_EXT_NUMBER = a2_EXT_NUMBER;
	}
	public String getA2_EXT_NO_OF_BUSINESS_RELEVANT() {
		return A2_EXT_NO_OF_BUSINESS_RELEVANT;
	}
	public void setA2_EXT_NO_OF_BUSINESS_RELEVANT(String a2_EXT_NO_OF_BUSINESS_RELEVANT) {
		A2_EXT_NO_OF_BUSINESS_RELEVANT = a2_EXT_NO_OF_BUSINESS_RELEVANT;
	}
	public String getA2_EXT_BUSINESS_LINES_RELEVANT() {
		return A2_EXT_BUSINESS_LINES_RELEVANT;
	}
	public void setA2_EXT_BUSINESS_LINES_RELEVANT(String a2_EXT_BUSINESS_LINES_RELEVANT) {
		A2_EXT_BUSINESS_LINES_RELEVANT = a2_EXT_BUSINESS_LINES_RELEVANT;
	}
	public String getA2_TOTAL_NO_MODELS() {
		return A2_TOTAL_NO_MODELS;
	}
	public void setA2_TOTAL_NO_MODELS(String a2_TOTAL_NO_MODELS) {
		A2_TOTAL_NO_MODELS = a2_TOTAL_NO_MODELS;
	}
	public String getA2_TOTAL_NO_BUSINESS_LINES() {
		return A2_TOTAL_NO_BUSINESS_LINES;
	}
	public void setA2_TOTAL_NO_BUSINESS_LINES(String a2_TOTAL_NO_BUSINESS_LINES) {
		A2_TOTAL_NO_BUSINESS_LINES = a2_TOTAL_NO_BUSINESS_LINES;
	}
	public String getA3_PRODUCT() {
		return A3_PRODUCT;
	}
	public void setA3_PRODUCT(String a3_PRODUCT) {
		A3_PRODUCT = a3_PRODUCT;
	}
	public String getA3_INT_NUMBER() {
		return A3_INT_NUMBER;
	}
	public void setA3_INT_NUMBER(String a3_INT_NUMBER) {
		A3_INT_NUMBER = a3_INT_NUMBER;
	}
	public String getA3_INT_NO_OF_BUSINESS_RELEVANT() {
		return A3_INT_NO_OF_BUSINESS_RELEVANT;
	}
	public void setA3_INT_NO_OF_BUSINESS_RELEVANT(String a3_INT_NO_OF_BUSINESS_RELEVANT) {
		A3_INT_NO_OF_BUSINESS_RELEVANT = a3_INT_NO_OF_BUSINESS_RELEVANT;
	}
	public String getA3_INT_BUSINESS_LINES_RELEVANT() {
		return A3_INT_BUSINESS_LINES_RELEVANT;
	}
	public void setA3_INT_BUSINESS_LINES_RELEVANT(String a3_INT_BUSINESS_LINES_RELEVANT) {
		A3_INT_BUSINESS_LINES_RELEVANT = a3_INT_BUSINESS_LINES_RELEVANT;
	}
	public String getA3_EXT_NUMBER() {
		return A3_EXT_NUMBER;
	}
	public void setA3_EXT_NUMBER(String a3_EXT_NUMBER) {
		A3_EXT_NUMBER = a3_EXT_NUMBER;
	}
	public String getA3_EXT_NO_OF_BUSINESS_RELEVANT() {
		return A3_EXT_NO_OF_BUSINESS_RELEVANT;
	}
	public void setA3_EXT_NO_OF_BUSINESS_RELEVANT(String a3_EXT_NO_OF_BUSINESS_RELEVANT) {
		A3_EXT_NO_OF_BUSINESS_RELEVANT = a3_EXT_NO_OF_BUSINESS_RELEVANT;
	}
	public String getA3_EXT_BUSINESS_LINES_RELEVANT() {
		return A3_EXT_BUSINESS_LINES_RELEVANT;
	}
	public void setA3_EXT_BUSINESS_LINES_RELEVANT(String a3_EXT_BUSINESS_LINES_RELEVANT) {
		A3_EXT_BUSINESS_LINES_RELEVANT = a3_EXT_BUSINESS_LINES_RELEVANT;
	}
	public String getA3_TOTAL_NO_MODELS() {
		return A3_TOTAL_NO_MODELS;
	}
	public void setA3_TOTAL_NO_MODELS(String a3_TOTAL_NO_MODELS) {
		A3_TOTAL_NO_MODELS = a3_TOTAL_NO_MODELS;
	}
	public String getA3_TOTAL_NO_BUSINESS_LINES() {
		return A3_TOTAL_NO_BUSINESS_LINES;
	}
	public void setA3_TOTAL_NO_BUSINESS_LINES(String a3_TOTAL_NO_BUSINESS_LINES) {
		A3_TOTAL_NO_BUSINESS_LINES = a3_TOTAL_NO_BUSINESS_LINES;
	}
	public String getA4_PRODUCT() {
		return A4_PRODUCT;
	}
	public void setA4_PRODUCT(String a4_PRODUCT) {
		A4_PRODUCT = a4_PRODUCT;
	}
	public String getA4_INT_NUMBER() {
		return A4_INT_NUMBER;
	}
	public void setA4_INT_NUMBER(String a4_INT_NUMBER) {
		A4_INT_NUMBER = a4_INT_NUMBER;
	}
	public String getA4_INT_NO_OF_BUSINESS_RELEVANT() {
		return A4_INT_NO_OF_BUSINESS_RELEVANT;
	}
	public void setA4_INT_NO_OF_BUSINESS_RELEVANT(String a4_INT_NO_OF_BUSINESS_RELEVANT) {
		A4_INT_NO_OF_BUSINESS_RELEVANT = a4_INT_NO_OF_BUSINESS_RELEVANT;
	}
	public String getA4_INT_BUSINESS_LINES_RELEVANT() {
		return A4_INT_BUSINESS_LINES_RELEVANT;
	}
	public void setA4_INT_BUSINESS_LINES_RELEVANT(String a4_INT_BUSINESS_LINES_RELEVANT) {
		A4_INT_BUSINESS_LINES_RELEVANT = a4_INT_BUSINESS_LINES_RELEVANT;
	}
	public String getA4_EXT_NUMBER() {
		return A4_EXT_NUMBER;
	}
	public void setA4_EXT_NUMBER(String a4_EXT_NUMBER) {
		A4_EXT_NUMBER = a4_EXT_NUMBER;
	}
	public String getA4_EXT_NO_OF_BUSINESS_RELEVANT() {
		return A4_EXT_NO_OF_BUSINESS_RELEVANT;
	}
	public void setA4_EXT_NO_OF_BUSINESS_RELEVANT(String a4_EXT_NO_OF_BUSINESS_RELEVANT) {
		A4_EXT_NO_OF_BUSINESS_RELEVANT = a4_EXT_NO_OF_BUSINESS_RELEVANT;
	}
	public String getA4_EXT_BUSINESS_LINES_RELEVANT() {
		return A4_EXT_BUSINESS_LINES_RELEVANT;
	}
	public void setA4_EXT_BUSINESS_LINES_RELEVANT(String a4_EXT_BUSINESS_LINES_RELEVANT) {
		A4_EXT_BUSINESS_LINES_RELEVANT = a4_EXT_BUSINESS_LINES_RELEVANT;
	}
	public String getA4_TOTAL_NO_MODELS() {
		return A4_TOTAL_NO_MODELS;
	}
	public void setA4_TOTAL_NO_MODELS(String a4_TOTAL_NO_MODELS) {
		A4_TOTAL_NO_MODELS = a4_TOTAL_NO_MODELS;
	}
	public String getA4_TOTAL_NO_BUSINESS_LINES() {
		return A4_TOTAL_NO_BUSINESS_LINES;
	}
	public void setA4_TOTAL_NO_BUSINESS_LINES(String a4_TOTAL_NO_BUSINESS_LINES) {
		A4_TOTAL_NO_BUSINESS_LINES = a4_TOTAL_NO_BUSINESS_LINES;
	}
	public String getA5_PRODUCT() {
		return A5_PRODUCT;
	}
	public void setA5_PRODUCT(String a5_PRODUCT) {
		A5_PRODUCT = a5_PRODUCT;
	}
	public String getA5_INT_NUMBER() {
		return A5_INT_NUMBER;
	}
	public void setA5_INT_NUMBER(String a5_INT_NUMBER) {
		A5_INT_NUMBER = a5_INT_NUMBER;
	}
	public String getA5_INT_NO_OF_BUSINESS_RELEVANT() {
		return A5_INT_NO_OF_BUSINESS_RELEVANT;
	}
	public void setA5_INT_NO_OF_BUSINESS_RELEVANT(String a5_INT_NO_OF_BUSINESS_RELEVANT) {
		A5_INT_NO_OF_BUSINESS_RELEVANT = a5_INT_NO_OF_BUSINESS_RELEVANT;
	}
	public String getA5_INT_BUSINESS_LINES_RELEVANT() {
		return A5_INT_BUSINESS_LINES_RELEVANT;
	}
	public void setA5_INT_BUSINESS_LINES_RELEVANT(String a5_INT_BUSINESS_LINES_RELEVANT) {
		A5_INT_BUSINESS_LINES_RELEVANT = a5_INT_BUSINESS_LINES_RELEVANT;
	}
	public String getA5_EXT_NUMBER() {
		return A5_EXT_NUMBER;
	}
	public void setA5_EXT_NUMBER(String a5_EXT_NUMBER) {
		A5_EXT_NUMBER = a5_EXT_NUMBER;
	}
	public String getA5_EXT_NO_OF_BUSINESS_RELEVANT() {
		return A5_EXT_NO_OF_BUSINESS_RELEVANT;
	}
	public void setA5_EXT_NO_OF_BUSINESS_RELEVANT(String a5_EXT_NO_OF_BUSINESS_RELEVANT) {
		A5_EXT_NO_OF_BUSINESS_RELEVANT = a5_EXT_NO_OF_BUSINESS_RELEVANT;
	}
	public String getA5_EXT_BUSINESS_LINES_RELEVANT() {
		return A5_EXT_BUSINESS_LINES_RELEVANT;
	}
	public void setA5_EXT_BUSINESS_LINES_RELEVANT(String a5_EXT_BUSINESS_LINES_RELEVANT) {
		A5_EXT_BUSINESS_LINES_RELEVANT = a5_EXT_BUSINESS_LINES_RELEVANT;
	}
	public String getA5_TOTAL_NO_MODELS() {
		return A5_TOTAL_NO_MODELS;
	}
	public void setA5_TOTAL_NO_MODELS(String a5_TOTAL_NO_MODELS) {
		A5_TOTAL_NO_MODELS = a5_TOTAL_NO_MODELS;
	}
	public String getA5_TOTAL_NO_BUSINESS_LINES() {
		return A5_TOTAL_NO_BUSINESS_LINES;
	}
	public void setA5_TOTAL_NO_BUSINESS_LINES(String a5_TOTAL_NO_BUSINESS_LINES) {
		A5_TOTAL_NO_BUSINESS_LINES = a5_TOTAL_NO_BUSINESS_LINES;
	}
	public String getA6_PRODUCT() {
		return A6_PRODUCT;
	}
	public void setA6_PRODUCT(String a6_PRODUCT) {
		A6_PRODUCT = a6_PRODUCT;
	}
	public String getA6_INT_NUMBER() {
		return A6_INT_NUMBER;
	}
	public void setA6_INT_NUMBER(String a6_INT_NUMBER) {
		A6_INT_NUMBER = a6_INT_NUMBER;
	}
	public String getA6_INT_NO_OF_BUSINESS_RELEVANT() {
		return A6_INT_NO_OF_BUSINESS_RELEVANT;
	}
	public void setA6_INT_NO_OF_BUSINESS_RELEVANT(String a6_INT_NO_OF_BUSINESS_RELEVANT) {
		A6_INT_NO_OF_BUSINESS_RELEVANT = a6_INT_NO_OF_BUSINESS_RELEVANT;
	}
	public String getA6_INT_BUSINESS_LINES_RELEVANT() {
		return A6_INT_BUSINESS_LINES_RELEVANT;
	}
	public void setA6_INT_BUSINESS_LINES_RELEVANT(String a6_INT_BUSINESS_LINES_RELEVANT) {
		A6_INT_BUSINESS_LINES_RELEVANT = a6_INT_BUSINESS_LINES_RELEVANT;
	}
	public String getA6_EXT_NUMBER() {
		return A6_EXT_NUMBER;
	}
	public void setA6_EXT_NUMBER(String a6_EXT_NUMBER) {
		A6_EXT_NUMBER = a6_EXT_NUMBER;
	}
	public String getA6_EXT_NO_OF_BUSINESS_RELEVANT() {
		return A6_EXT_NO_OF_BUSINESS_RELEVANT;
	}
	public void setA6_EXT_NO_OF_BUSINESS_RELEVANT(String a6_EXT_NO_OF_BUSINESS_RELEVANT) {
		A6_EXT_NO_OF_BUSINESS_RELEVANT = a6_EXT_NO_OF_BUSINESS_RELEVANT;
	}
	public String getA6_EXT_BUSINESS_LINES_RELEVANT() {
		return A6_EXT_BUSINESS_LINES_RELEVANT;
	}
	public void setA6_EXT_BUSINESS_LINES_RELEVANT(String a6_EXT_BUSINESS_LINES_RELEVANT) {
		A6_EXT_BUSINESS_LINES_RELEVANT = a6_EXT_BUSINESS_LINES_RELEVANT;
	}
	public String getA6_TOTAL_NO_MODELS() {
		return A6_TOTAL_NO_MODELS;
	}
	public void setA6_TOTAL_NO_MODELS(String a6_TOTAL_NO_MODELS) {
		A6_TOTAL_NO_MODELS = a6_TOTAL_NO_MODELS;
	}
	public String getA6_TOTAL_NO_BUSINESS_LINES() {
		return A6_TOTAL_NO_BUSINESS_LINES;
	}
	public void setA6_TOTAL_NO_BUSINESS_LINES(String a6_TOTAL_NO_BUSINESS_LINES) {
		A6_TOTAL_NO_BUSINESS_LINES = a6_TOTAL_NO_BUSINESS_LINES;
	}
	public String getA7_PRODUCT() {
		return A7_PRODUCT;
	}
	public void setA7_PRODUCT(String a7_PRODUCT) {
		A7_PRODUCT = a7_PRODUCT;
	}
	public String getA7_INT_NUMBER() {
		return A7_INT_NUMBER;
	}
	public void setA7_INT_NUMBER(String a7_INT_NUMBER) {
		A7_INT_NUMBER = a7_INT_NUMBER;
	}
	public String getA7_INT_NO_OF_BUSINESS_RELEVANT() {
		return A7_INT_NO_OF_BUSINESS_RELEVANT;
	}
	public void setA7_INT_NO_OF_BUSINESS_RELEVANT(String a7_INT_NO_OF_BUSINESS_RELEVANT) {
		A7_INT_NO_OF_BUSINESS_RELEVANT = a7_INT_NO_OF_BUSINESS_RELEVANT;
	}
	public String getA7_INT_BUSINESS_LINES_RELEVANT() {
		return A7_INT_BUSINESS_LINES_RELEVANT;
	}
	public void setA7_INT_BUSINESS_LINES_RELEVANT(String a7_INT_BUSINESS_LINES_RELEVANT) {
		A7_INT_BUSINESS_LINES_RELEVANT = a7_INT_BUSINESS_LINES_RELEVANT;
	}
	public String getA7_EXT_NUMBER() {
		return A7_EXT_NUMBER;
	}
	public void setA7_EXT_NUMBER(String a7_EXT_NUMBER) {
		A7_EXT_NUMBER = a7_EXT_NUMBER;
	}
	public String getA7_EXT_NO_OF_BUSINESS_RELEVANT() {
		return A7_EXT_NO_OF_BUSINESS_RELEVANT;
	}
	public void setA7_EXT_NO_OF_BUSINESS_RELEVANT(String a7_EXT_NO_OF_BUSINESS_RELEVANT) {
		A7_EXT_NO_OF_BUSINESS_RELEVANT = a7_EXT_NO_OF_BUSINESS_RELEVANT;
	}
	public String getA7_EXT_BUSINESS_LINES_RELEVANT() {
		return A7_EXT_BUSINESS_LINES_RELEVANT;
	}
	public void setA7_EXT_BUSINESS_LINES_RELEVANT(String a7_EXT_BUSINESS_LINES_RELEVANT) {
		A7_EXT_BUSINESS_LINES_RELEVANT = a7_EXT_BUSINESS_LINES_RELEVANT;
	}
	public String getA7_TOTAL_NO_MODELS() {
		return A7_TOTAL_NO_MODELS;
	}
	public void setA7_TOTAL_NO_MODELS(String a7_TOTAL_NO_MODELS) {
		A7_TOTAL_NO_MODELS = a7_TOTAL_NO_MODELS;
	}
	public String getA7_TOTAL_NO_BUSINESS_LINES() {
		return A7_TOTAL_NO_BUSINESS_LINES;
	}
	public void setA7_TOTAL_NO_BUSINESS_LINES(String a7_TOTAL_NO_BUSINESS_LINES) {
		A7_TOTAL_NO_BUSINESS_LINES = a7_TOTAL_NO_BUSINESS_LINES;
	}
	public String getA8_PRODUCT() {
		return A8_PRODUCT;
	}
	public void setA8_PRODUCT(String a8_PRODUCT) {
		A8_PRODUCT = a8_PRODUCT;
	}
	public String getA8_INT_NUMBER() {
		return A8_INT_NUMBER;
	}
	public void setA8_INT_NUMBER(String a8_INT_NUMBER) {
		A8_INT_NUMBER = a8_INT_NUMBER;
	}
	public String getA8_INT_NO_OF_BUSINESS_RELEVANT() {
		return A8_INT_NO_OF_BUSINESS_RELEVANT;
	}
	public void setA8_INT_NO_OF_BUSINESS_RELEVANT(String a8_INT_NO_OF_BUSINESS_RELEVANT) {
		A8_INT_NO_OF_BUSINESS_RELEVANT = a8_INT_NO_OF_BUSINESS_RELEVANT;
	}
	public String getA8_INT_BUSINESS_LINES_RELEVANT() {
		return A8_INT_BUSINESS_LINES_RELEVANT;
	}
	public void setA8_INT_BUSINESS_LINES_RELEVANT(String a8_INT_BUSINESS_LINES_RELEVANT) {
		A8_INT_BUSINESS_LINES_RELEVANT = a8_INT_BUSINESS_LINES_RELEVANT;
	}
	public String getA8_EXT_NUMBER() {
		return A8_EXT_NUMBER;
	}
	public void setA8_EXT_NUMBER(String a8_EXT_NUMBER) {
		A8_EXT_NUMBER = a8_EXT_NUMBER;
	}
	public String getA8_EXT_NO_OF_BUSINESS_RELEVANT() {
		return A8_EXT_NO_OF_BUSINESS_RELEVANT;
	}
	public void setA8_EXT_NO_OF_BUSINESS_RELEVANT(String a8_EXT_NO_OF_BUSINESS_RELEVANT) {
		A8_EXT_NO_OF_BUSINESS_RELEVANT = a8_EXT_NO_OF_BUSINESS_RELEVANT;
	}
	public String getA8_EXT_BUSINESS_LINES_RELEVANT() {
		return A8_EXT_BUSINESS_LINES_RELEVANT;
	}
	public void setA8_EXT_BUSINESS_LINES_RELEVANT(String a8_EXT_BUSINESS_LINES_RELEVANT) {
		A8_EXT_BUSINESS_LINES_RELEVANT = a8_EXT_BUSINESS_LINES_RELEVANT;
	}
	public String getA8_TOTAL_NO_MODELS() {
		return A8_TOTAL_NO_MODELS;
	}
	public void setA8_TOTAL_NO_MODELS(String a8_TOTAL_NO_MODELS) {
		A8_TOTAL_NO_MODELS = a8_TOTAL_NO_MODELS;
	}
	public String getA8_TOTAL_NO_BUSINESS_LINES() {
		return A8_TOTAL_NO_BUSINESS_LINES;
	}
	public void setA8_TOTAL_NO_BUSINESS_LINES(String a8_TOTAL_NO_BUSINESS_LINES) {
		A8_TOTAL_NO_BUSINESS_LINES = a8_TOTAL_NO_BUSINESS_LINES;
	}
	public String getA9_PRODUCT() {
		return A9_PRODUCT;
	}
	public void setA9_PRODUCT(String a9_PRODUCT) {
		A9_PRODUCT = a9_PRODUCT;
	}
	public String getA9_INT_NUMBER() {
		return A9_INT_NUMBER;
	}
	public void setA9_INT_NUMBER(String a9_INT_NUMBER) {
		A9_INT_NUMBER = a9_INT_NUMBER;
	}
	public String getA9_INT_NO_OF_BUSINESS_RELEVANT() {
		return A9_INT_NO_OF_BUSINESS_RELEVANT;
	}
	public void setA9_INT_NO_OF_BUSINESS_RELEVANT(String a9_INT_NO_OF_BUSINESS_RELEVANT) {
		A9_INT_NO_OF_BUSINESS_RELEVANT = a9_INT_NO_OF_BUSINESS_RELEVANT;
	}
	public String getA9_INT_BUSINESS_LINES_RELEVANT() {
		return A9_INT_BUSINESS_LINES_RELEVANT;
	}
	public void setA9_INT_BUSINESS_LINES_RELEVANT(String a9_INT_BUSINESS_LINES_RELEVANT) {
		A9_INT_BUSINESS_LINES_RELEVANT = a9_INT_BUSINESS_LINES_RELEVANT;
	}
	public String getA9_EXT_NUMBER() {
		return A9_EXT_NUMBER;
	}
	public void setA9_EXT_NUMBER(String a9_EXT_NUMBER) {
		A9_EXT_NUMBER = a9_EXT_NUMBER;
	}
	public String getA9_EXT_NO_OF_BUSINESS_RELEVANT() {
		return A9_EXT_NO_OF_BUSINESS_RELEVANT;
	}
	public void setA9_EXT_NO_OF_BUSINESS_RELEVANT(String a9_EXT_NO_OF_BUSINESS_RELEVANT) {
		A9_EXT_NO_OF_BUSINESS_RELEVANT = a9_EXT_NO_OF_BUSINESS_RELEVANT;
	}
	public String getA9_EXT_BUSINESS_LINES_RELEVANT() {
		return A9_EXT_BUSINESS_LINES_RELEVANT;
	}
	public void setA9_EXT_BUSINESS_LINES_RELEVANT(String a9_EXT_BUSINESS_LINES_RELEVANT) {
		A9_EXT_BUSINESS_LINES_RELEVANT = a9_EXT_BUSINESS_LINES_RELEVANT;
	}
	public String getA9_TOTAL_NO_MODELS() {
		return A9_TOTAL_NO_MODELS;
	}
	public void setA9_TOTAL_NO_MODELS(String a9_TOTAL_NO_MODELS) {
		A9_TOTAL_NO_MODELS = a9_TOTAL_NO_MODELS;
	}
	public String getA9_TOTAL_NO_BUSINESS_LINES() {
		return A9_TOTAL_NO_BUSINESS_LINES;
	}
	public void setA9_TOTAL_NO_BUSINESS_LINES(String a9_TOTAL_NO_BUSINESS_LINES) {
		A9_TOTAL_NO_BUSINESS_LINES = a9_TOTAL_NO_BUSINESS_LINES;
	}
	public String getA10_PRODUCT() {
		return A10_PRODUCT;
	}
	public void setA10_PRODUCT(String a10_PRODUCT) {
		A10_PRODUCT = a10_PRODUCT;
	}
	public String getA10_INT_NUMBER() {
		return A10_INT_NUMBER;
	}
	public void setA10_INT_NUMBER(String a10_INT_NUMBER) {
		A10_INT_NUMBER = a10_INT_NUMBER;
	}
	public String getA10_INT_NO_OF_BUSINESS_RELEVANT() {
		return A10_INT_NO_OF_BUSINESS_RELEVANT;
	}
	public void setA10_INT_NO_OF_BUSINESS_RELEVANT(String a10_INT_NO_OF_BUSINESS_RELEVANT) {
		A10_INT_NO_OF_BUSINESS_RELEVANT = a10_INT_NO_OF_BUSINESS_RELEVANT;
	}
	public String getA10_INT_BUSINESS_LINES_RELEVANT() {
		return A10_INT_BUSINESS_LINES_RELEVANT;
	}
	public void setA10_INT_BUSINESS_LINES_RELEVANT(String a10_INT_BUSINESS_LINES_RELEVANT) {
		A10_INT_BUSINESS_LINES_RELEVANT = a10_INT_BUSINESS_LINES_RELEVANT;
	}
	public String getA10_EXT_NUMBER() {
		return A10_EXT_NUMBER;
	}
	public void setA10_EXT_NUMBER(String a10_EXT_NUMBER) {
		A10_EXT_NUMBER = a10_EXT_NUMBER;
	}
	public String getA10_EXT_NO_OF_BUSINESS_RELEVANT() {
		return A10_EXT_NO_OF_BUSINESS_RELEVANT;
	}
	public void setA10_EXT_NO_OF_BUSINESS_RELEVANT(String a10_EXT_NO_OF_BUSINESS_RELEVANT) {
		A10_EXT_NO_OF_BUSINESS_RELEVANT = a10_EXT_NO_OF_BUSINESS_RELEVANT;
	}
	public String getA10_EXT_BUSINESS_LINES_RELEVANT() {
		return A10_EXT_BUSINESS_LINES_RELEVANT;
	}
	public void setA10_EXT_BUSINESS_LINES_RELEVANT(String a10_EXT_BUSINESS_LINES_RELEVANT) {
		A10_EXT_BUSINESS_LINES_RELEVANT = a10_EXT_BUSINESS_LINES_RELEVANT;
	}
	public String getA10_TOTAL_NO_MODELS() {
		return A10_TOTAL_NO_MODELS;
	}
	public void setA10_TOTAL_NO_MODELS(String a10_TOTAL_NO_MODELS) {
		A10_TOTAL_NO_MODELS = a10_TOTAL_NO_MODELS;
	}
	public String getA10_TOTAL_NO_BUSINESS_LINES() {
		return A10_TOTAL_NO_BUSINESS_LINES;
	}
	public void setA10_TOTAL_NO_BUSINESS_LINES(String a10_TOTAL_NO_BUSINESS_LINES) {
		A10_TOTAL_NO_BUSINESS_LINES = a10_TOTAL_NO_BUSINESS_LINES;
	}
	public String getREPORT_CODE() {
		return REPORT_CODE;
	}
	public void setREPORT_CODE(String rEPORT_CODE) {
		REPORT_CODE = rEPORT_CODE;
	}
	public String getREPORT_NAME() {
		return REPORT_NAME;
	}
	public void setREPORT_NAME(String rEPORT_NAME) {
		REPORT_NAME = rEPORT_NAME;
	}
	public Date getREPORT_DATE() {
		return REPORT_DATE;
	}
	public void setREPORT_DATE(Date rEPORT_DATE) {
		REPORT_DATE = rEPORT_DATE;
	}
	public Date getREPORT_DUE_DATE() {
		return REPORT_DUE_DATE;
	}
	public void setREPORT_DUE_DATE(Date rEPORT_DUE_DATE) {
		REPORT_DUE_DATE = rEPORT_DUE_DATE;
	}
	public Date getREP_SUBMIT_DATE() {
		return REP_SUBMIT_DATE;
	}
	public void setREP_SUBMIT_DATE(Date rEP_SUBMIT_DATE) {
		REP_SUBMIT_DATE = rEP_SUBMIT_DATE;
	}
	public Date getREP_PERIOD_FROM() {
		return REP_PERIOD_FROM;
	}
	public void setREP_PERIOD_FROM(Date rEP_PERIOD_FROM) {
		REP_PERIOD_FROM = rEP_PERIOD_FROM;
	}
	public Date getREP_PERIOD_TO() {
		return REP_PERIOD_TO;
	}
	public void setREP_PERIOD_TO(Date rEP_PERIOD_TO) {
		REP_PERIOD_TO = rEP_PERIOD_TO;
	}
	public String getREP_FREQ() {
		return REP_FREQ;
	}
	public void setREP_FREQ(String rEP_FREQ) {
		REP_FREQ = rEP_FREQ;
	}
	public String getNIL_REPORT_FLG() {
		return NIL_REPORT_FLG;
	}
	public void setNIL_REPORT_FLG(String nIL_REPORT_FLG) {
		NIL_REPORT_FLG = nIL_REPORT_FLG;
	}
	public String getARCH_FLG() {
		return ARCH_FLG;
	}
	public void setARCH_FLG(String aRCH_FLG) {
		ARCH_FLG = aRCH_FLG;
	}
	public String getENTITY_FLG() {
		return ENTITY_FLG;
	}
	public void setENTITY_FLG(String eNTITY_FLG) {
		ENTITY_FLG = eNTITY_FLG;
	}
	public String getDEL_FLG() {
		return DEL_FLG;
	}
	public void setDEL_FLG(String dEL_FLG) {
		DEL_FLG = dEL_FLG;
	}
	public String getMODIFY_FLG() {
		return MODIFY_FLG;
	}
	public void setMODIFY_FLG(String mODIFY_FLG) {
		MODIFY_FLG = mODIFY_FLG;
	}
	public String getENTRY_USER() {
		return ENTRY_USER;
	}
	public void setENTRY_USER(String eNTRY_USER) {
		ENTRY_USER = eNTRY_USER;
	}
	public String getMODIFY_USER() {
		return MODIFY_USER;
	}
	public void setMODIFY_USER(String mODIFY_USER) {
		MODIFY_USER = mODIFY_USER;
	}
	public String getVERIFY_USER() {
		return VERIFY_USER;
	}
	public void setVERIFY_USER(String vERIFY_USER) {
		VERIFY_USER = vERIFY_USER;
	}
	public Date getENTRY_TIME() {
		return ENTRY_TIME;
	}
	public void setENTRY_TIME(Date eNTRY_TIME) {
		ENTRY_TIME = eNTRY_TIME;
	}
	public Date getMODIFY_TIME() {
		return MODIFY_TIME;
	}
	public void setMODIFY_TIME(Date mODIFY_TIME) {
		MODIFY_TIME = mODIFY_TIME;
	}
	public Date getVERIFY_TIME() {
		return VERIFY_TIME;
	}
	public void setVERIFY_TIME(Date vERIFY_TIME) {
		VERIFY_TIME = vERIFY_TIME;
	}
	public String getQTR_FLG() {
		return QTR_FLG;
	}
	public void setQTR_FLG(String qTR_FLG) {
		QTR_FLG = qTR_FLG;
	}
	public T15ORReport(String a1_PRODUCT, String a1_INT_NUMBER, String a1_INT_NO_OF_BUSINESS_RELEVANT,
			String a1_INT_BUSINESS_LINES_RELEVANT, String a1_EXT_NUMBER, String a1_EXT_NO_OF_BUSINESS_RELEVANT,
			String a1_EXT_BUSINESS_LINES_RELEVANT, String a1_TOTAL_NO_MODELS, String a1_TOTAL_NO_BUSINESS_LINES,
			String a2_PRODUCT, String a2_INT_NUMBER, String a2_INT_NO_OF_BUSINESS_RELEVANT,
			String a2_INT_BUSINESS_LINES_RELEVANT, String a2_EXT_NUMBER, String a2_EXT_NO_OF_BUSINESS_RELEVANT,
			String a2_EXT_BUSINESS_LINES_RELEVANT, String a2_TOTAL_NO_MODELS, String a2_TOTAL_NO_BUSINESS_LINES,
			String a3_PRODUCT, String a3_INT_NUMBER, String a3_INT_NO_OF_BUSINESS_RELEVANT,
			String a3_INT_BUSINESS_LINES_RELEVANT, String a3_EXT_NUMBER, String a3_EXT_NO_OF_BUSINESS_RELEVANT,
			String a3_EXT_BUSINESS_LINES_RELEVANT, String a3_TOTAL_NO_MODELS, String a3_TOTAL_NO_BUSINESS_LINES,
			String a4_PRODUCT, String a4_INT_NUMBER, String a4_INT_NO_OF_BUSINESS_RELEVANT,
			String a4_INT_BUSINESS_LINES_RELEVANT, String a4_EXT_NUMBER, String a4_EXT_NO_OF_BUSINESS_RELEVANT,
			String a4_EXT_BUSINESS_LINES_RELEVANT, String a4_TOTAL_NO_MODELS, String a4_TOTAL_NO_BUSINESS_LINES,
			String a5_PRODUCT, String a5_INT_NUMBER, String a5_INT_NO_OF_BUSINESS_RELEVANT,
			String a5_INT_BUSINESS_LINES_RELEVANT, String a5_EXT_NUMBER, String a5_EXT_NO_OF_BUSINESS_RELEVANT,
			String a5_EXT_BUSINESS_LINES_RELEVANT, String a5_TOTAL_NO_MODELS, String a5_TOTAL_NO_BUSINESS_LINES,
			String a6_PRODUCT, String a6_INT_NUMBER, String a6_INT_NO_OF_BUSINESS_RELEVANT,
			String a6_INT_BUSINESS_LINES_RELEVANT, String a6_EXT_NUMBER, String a6_EXT_NO_OF_BUSINESS_RELEVANT,
			String a6_EXT_BUSINESS_LINES_RELEVANT, String a6_TOTAL_NO_MODELS, String a6_TOTAL_NO_BUSINESS_LINES,
			String a7_PRODUCT, String a7_INT_NUMBER, String a7_INT_NO_OF_BUSINESS_RELEVANT,
			String a7_INT_BUSINESS_LINES_RELEVANT, String a7_EXT_NUMBER, String a7_EXT_NO_OF_BUSINESS_RELEVANT,
			String a7_EXT_BUSINESS_LINES_RELEVANT, String a7_TOTAL_NO_MODELS, String a7_TOTAL_NO_BUSINESS_LINES,
			String a8_PRODUCT, String a8_INT_NUMBER, String a8_INT_NO_OF_BUSINESS_RELEVANT,
			String a8_INT_BUSINESS_LINES_RELEVANT, String a8_EXT_NUMBER, String a8_EXT_NO_OF_BUSINESS_RELEVANT,
			String a8_EXT_BUSINESS_LINES_RELEVANT, String a8_TOTAL_NO_MODELS, String a8_TOTAL_NO_BUSINESS_LINES,
			String a9_PRODUCT, String a9_INT_NUMBER, String a9_INT_NO_OF_BUSINESS_RELEVANT,
			String a9_INT_BUSINESS_LINES_RELEVANT, String a9_EXT_NUMBER, String a9_EXT_NO_OF_BUSINESS_RELEVANT,
			String a9_EXT_BUSINESS_LINES_RELEVANT, String a9_TOTAL_NO_MODELS, String a9_TOTAL_NO_BUSINESS_LINES,
			String a10_PRODUCT, String a10_INT_NUMBER, String a10_INT_NO_OF_BUSINESS_RELEVANT,
			String a10_INT_BUSINESS_LINES_RELEVANT, String a10_EXT_NUMBER, String a10_EXT_NO_OF_BUSINESS_RELEVANT,
			String a10_EXT_BUSINESS_LINES_RELEVANT, String a10_TOTAL_NO_MODELS, String a10_TOTAL_NO_BUSINESS_LINES,
			String rEPORT_CODE, String rEPORT_NAME, Date rEPORT_DATE, Date rEPORT_DUE_DATE, Date rEP_SUBMIT_DATE,
			Date rEP_PERIOD_FROM, Date rEP_PERIOD_TO, String rEP_FREQ, String nIL_REPORT_FLG, String aRCH_FLG,
			String eNTITY_FLG, String dEL_FLG, String mODIFY_FLG, String eNTRY_USER, String mODIFY_USER,
			String vERIFY_USER, Date eNTRY_TIME, Date mODIFY_TIME, Date vERIFY_TIME, String qTR_FLG) {
		super();
		A1_PRODUCT = a1_PRODUCT;
		A1_INT_NUMBER = a1_INT_NUMBER;
		A1_INT_NO_OF_BUSINESS_RELEVANT = a1_INT_NO_OF_BUSINESS_RELEVANT;
		A1_INT_BUSINESS_LINES_RELEVANT = a1_INT_BUSINESS_LINES_RELEVANT;
		A1_EXT_NUMBER = a1_EXT_NUMBER;
		A1_EXT_NO_OF_BUSINESS_RELEVANT = a1_EXT_NO_OF_BUSINESS_RELEVANT;
		A1_EXT_BUSINESS_LINES_RELEVANT = a1_EXT_BUSINESS_LINES_RELEVANT;
		A1_TOTAL_NO_MODELS = a1_TOTAL_NO_MODELS;
		A1_TOTAL_NO_BUSINESS_LINES = a1_TOTAL_NO_BUSINESS_LINES;
		A2_PRODUCT = a2_PRODUCT;
		A2_INT_NUMBER = a2_INT_NUMBER;
		A2_INT_NO_OF_BUSINESS_RELEVANT = a2_INT_NO_OF_BUSINESS_RELEVANT;
		A2_INT_BUSINESS_LINES_RELEVANT = a2_INT_BUSINESS_LINES_RELEVANT;
		A2_EXT_NUMBER = a2_EXT_NUMBER;
		A2_EXT_NO_OF_BUSINESS_RELEVANT = a2_EXT_NO_OF_BUSINESS_RELEVANT;
		A2_EXT_BUSINESS_LINES_RELEVANT = a2_EXT_BUSINESS_LINES_RELEVANT;
		A2_TOTAL_NO_MODELS = a2_TOTAL_NO_MODELS;
		A2_TOTAL_NO_BUSINESS_LINES = a2_TOTAL_NO_BUSINESS_LINES;
		A3_PRODUCT = a3_PRODUCT;
		A3_INT_NUMBER = a3_INT_NUMBER;
		A3_INT_NO_OF_BUSINESS_RELEVANT = a3_INT_NO_OF_BUSINESS_RELEVANT;
		A3_INT_BUSINESS_LINES_RELEVANT = a3_INT_BUSINESS_LINES_RELEVANT;
		A3_EXT_NUMBER = a3_EXT_NUMBER;
		A3_EXT_NO_OF_BUSINESS_RELEVANT = a3_EXT_NO_OF_BUSINESS_RELEVANT;
		A3_EXT_BUSINESS_LINES_RELEVANT = a3_EXT_BUSINESS_LINES_RELEVANT;
		A3_TOTAL_NO_MODELS = a3_TOTAL_NO_MODELS;
		A3_TOTAL_NO_BUSINESS_LINES = a3_TOTAL_NO_BUSINESS_LINES;
		A4_PRODUCT = a4_PRODUCT;
		A4_INT_NUMBER = a4_INT_NUMBER;
		A4_INT_NO_OF_BUSINESS_RELEVANT = a4_INT_NO_OF_BUSINESS_RELEVANT;
		A4_INT_BUSINESS_LINES_RELEVANT = a4_INT_BUSINESS_LINES_RELEVANT;
		A4_EXT_NUMBER = a4_EXT_NUMBER;
		A4_EXT_NO_OF_BUSINESS_RELEVANT = a4_EXT_NO_OF_BUSINESS_RELEVANT;
		A4_EXT_BUSINESS_LINES_RELEVANT = a4_EXT_BUSINESS_LINES_RELEVANT;
		A4_TOTAL_NO_MODELS = a4_TOTAL_NO_MODELS;
		A4_TOTAL_NO_BUSINESS_LINES = a4_TOTAL_NO_BUSINESS_LINES;
		A5_PRODUCT = a5_PRODUCT;
		A5_INT_NUMBER = a5_INT_NUMBER;
		A5_INT_NO_OF_BUSINESS_RELEVANT = a5_INT_NO_OF_BUSINESS_RELEVANT;
		A5_INT_BUSINESS_LINES_RELEVANT = a5_INT_BUSINESS_LINES_RELEVANT;
		A5_EXT_NUMBER = a5_EXT_NUMBER;
		A5_EXT_NO_OF_BUSINESS_RELEVANT = a5_EXT_NO_OF_BUSINESS_RELEVANT;
		A5_EXT_BUSINESS_LINES_RELEVANT = a5_EXT_BUSINESS_LINES_RELEVANT;
		A5_TOTAL_NO_MODELS = a5_TOTAL_NO_MODELS;
		A5_TOTAL_NO_BUSINESS_LINES = a5_TOTAL_NO_BUSINESS_LINES;
		A6_PRODUCT = a6_PRODUCT;
		A6_INT_NUMBER = a6_INT_NUMBER;
		A6_INT_NO_OF_BUSINESS_RELEVANT = a6_INT_NO_OF_BUSINESS_RELEVANT;
		A6_INT_BUSINESS_LINES_RELEVANT = a6_INT_BUSINESS_LINES_RELEVANT;
		A6_EXT_NUMBER = a6_EXT_NUMBER;
		A6_EXT_NO_OF_BUSINESS_RELEVANT = a6_EXT_NO_OF_BUSINESS_RELEVANT;
		A6_EXT_BUSINESS_LINES_RELEVANT = a6_EXT_BUSINESS_LINES_RELEVANT;
		A6_TOTAL_NO_MODELS = a6_TOTAL_NO_MODELS;
		A6_TOTAL_NO_BUSINESS_LINES = a6_TOTAL_NO_BUSINESS_LINES;
		A7_PRODUCT = a7_PRODUCT;
		A7_INT_NUMBER = a7_INT_NUMBER;
		A7_INT_NO_OF_BUSINESS_RELEVANT = a7_INT_NO_OF_BUSINESS_RELEVANT;
		A7_INT_BUSINESS_LINES_RELEVANT = a7_INT_BUSINESS_LINES_RELEVANT;
		A7_EXT_NUMBER = a7_EXT_NUMBER;
		A7_EXT_NO_OF_BUSINESS_RELEVANT = a7_EXT_NO_OF_BUSINESS_RELEVANT;
		A7_EXT_BUSINESS_LINES_RELEVANT = a7_EXT_BUSINESS_LINES_RELEVANT;
		A7_TOTAL_NO_MODELS = a7_TOTAL_NO_MODELS;
		A7_TOTAL_NO_BUSINESS_LINES = a7_TOTAL_NO_BUSINESS_LINES;
		A8_PRODUCT = a8_PRODUCT;
		A8_INT_NUMBER = a8_INT_NUMBER;
		A8_INT_NO_OF_BUSINESS_RELEVANT = a8_INT_NO_OF_BUSINESS_RELEVANT;
		A8_INT_BUSINESS_LINES_RELEVANT = a8_INT_BUSINESS_LINES_RELEVANT;
		A8_EXT_NUMBER = a8_EXT_NUMBER;
		A8_EXT_NO_OF_BUSINESS_RELEVANT = a8_EXT_NO_OF_BUSINESS_RELEVANT;
		A8_EXT_BUSINESS_LINES_RELEVANT = a8_EXT_BUSINESS_LINES_RELEVANT;
		A8_TOTAL_NO_MODELS = a8_TOTAL_NO_MODELS;
		A8_TOTAL_NO_BUSINESS_LINES = a8_TOTAL_NO_BUSINESS_LINES;
		A9_PRODUCT = a9_PRODUCT;
		A9_INT_NUMBER = a9_INT_NUMBER;
		A9_INT_NO_OF_BUSINESS_RELEVANT = a9_INT_NO_OF_BUSINESS_RELEVANT;
		A9_INT_BUSINESS_LINES_RELEVANT = a9_INT_BUSINESS_LINES_RELEVANT;
		A9_EXT_NUMBER = a9_EXT_NUMBER;
		A9_EXT_NO_OF_BUSINESS_RELEVANT = a9_EXT_NO_OF_BUSINESS_RELEVANT;
		A9_EXT_BUSINESS_LINES_RELEVANT = a9_EXT_BUSINESS_LINES_RELEVANT;
		A9_TOTAL_NO_MODELS = a9_TOTAL_NO_MODELS;
		A9_TOTAL_NO_BUSINESS_LINES = a9_TOTAL_NO_BUSINESS_LINES;
		A10_PRODUCT = a10_PRODUCT;
		A10_INT_NUMBER = a10_INT_NUMBER;
		A10_INT_NO_OF_BUSINESS_RELEVANT = a10_INT_NO_OF_BUSINESS_RELEVANT;
		A10_INT_BUSINESS_LINES_RELEVANT = a10_INT_BUSINESS_LINES_RELEVANT;
		A10_EXT_NUMBER = a10_EXT_NUMBER;
		A10_EXT_NO_OF_BUSINESS_RELEVANT = a10_EXT_NO_OF_BUSINESS_RELEVANT;
		A10_EXT_BUSINESS_LINES_RELEVANT = a10_EXT_BUSINESS_LINES_RELEVANT;
		A10_TOTAL_NO_MODELS = a10_TOTAL_NO_MODELS;
		A10_TOTAL_NO_BUSINESS_LINES = a10_TOTAL_NO_BUSINESS_LINES;
		REPORT_CODE = rEPORT_CODE;
		REPORT_NAME = rEPORT_NAME;
		REPORT_DATE = rEPORT_DATE;
		REPORT_DUE_DATE = rEPORT_DUE_DATE;
		REP_SUBMIT_DATE = rEP_SUBMIT_DATE;
		REP_PERIOD_FROM = rEP_PERIOD_FROM;
		REP_PERIOD_TO = rEP_PERIOD_TO;
		REP_FREQ = rEP_FREQ;
		NIL_REPORT_FLG = nIL_REPORT_FLG;
		ARCH_FLG = aRCH_FLG;
		ENTITY_FLG = eNTITY_FLG;
		DEL_FLG = dEL_FLG;
		MODIFY_FLG = mODIFY_FLG;
		ENTRY_USER = eNTRY_USER;
		MODIFY_USER = mODIFY_USER;
		VERIFY_USER = vERIFY_USER;
		ENTRY_TIME = eNTRY_TIME;
		MODIFY_TIME = mODIFY_TIME;
		VERIFY_TIME = vERIFY_TIME;
		QTR_FLG = qTR_FLG;
	}
	public T15ORReport() {
		super();
		// TODO Auto-generated constructor stub
	}
	
}
