package com.bornfire.xbrl.entities.BRSS;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;
@Entity
@Table(name = "T16C_IND_CASH_EXEMPT_RISK_TABLE")
public class T16CReport {

	private String	DEPOSIT_COUNT_PRODUCT;
	private BigDecimal	DEPOSIT_COUNT_LOW_RISK;
	private BigDecimal	DEPOSIT_COUNT_MEDIUM_RISK;
	private BigDecimal	DEPOSIT_COUNT_HIGH_RISK;
	private String	DEPOSIT_AMOUNT_PRODUCT;
	private BigDecimal	DEPOSIT_AMOUNT_LOW_RISK;
	private BigDecimal	DEPOSIT_AMOUNT_MEDIUM_RISK;
	private BigDecimal	DEPOSIT_AMOUNT_HIGH_RISK;
	private String	WITHDRAW_COUNT_PRODUCT;
	private BigDecimal	WITHDRAW_COUNT_LOW_RISK;
	private BigDecimal	WITHDRAW_COUNT_MEDIUM_RISK;
	private BigDecimal	WITHDRAW_COUNT_HIGH_RISK;
	private String	WITHDRAW_AMOUNT_PRODUCT;
	private BigDecimal	WITHDRAW_AMOUNT_LOW_RISK;
	private BigDecimal	WITHDRAW_AMOUNT_MEDIUM_RISK;
	private BigDecimal	WITHDRAW_AMOUNT_HIGH_RISK;
	private String	REPORT_CODE;
	private String	REPORT_NAME;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	@Id
	private Date	REPORT_DATE;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	REPORT_DUE_DATE;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	REP_SUBMIT_DATE;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	REP_PERIOD_FROM;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	REP_PERIOD_TO;
	private String	REP_FREQ;
	private String	NIL_REPORT_FLG;
	private String	ARCH_FLG;
	public String getDEPOSIT_COUNT_PRODUCT() {
		return DEPOSIT_COUNT_PRODUCT;
	}
	public void setDEPOSIT_COUNT_PRODUCT(String dEPOSIT_COUNT_PRODUCT) {
		DEPOSIT_COUNT_PRODUCT = dEPOSIT_COUNT_PRODUCT;
	}
	public BigDecimal getDEPOSIT_COUNT_LOW_RISK() {
		return DEPOSIT_COUNT_LOW_RISK;
	}
	public void setDEPOSIT_COUNT_LOW_RISK(BigDecimal dEPOSIT_COUNT_LOW_RISK) {
		DEPOSIT_COUNT_LOW_RISK = dEPOSIT_COUNT_LOW_RISK;
	}
	public BigDecimal getDEPOSIT_COUNT_MEDIUM_RISK() {
		return DEPOSIT_COUNT_MEDIUM_RISK;
	}
	public void setDEPOSIT_COUNT_MEDIUM_RISK(BigDecimal dEPOSIT_COUNT_MEDIUM_RISK) {
		DEPOSIT_COUNT_MEDIUM_RISK = dEPOSIT_COUNT_MEDIUM_RISK;
	}
	public BigDecimal getDEPOSIT_COUNT_HIGH_RISK() {
		return DEPOSIT_COUNT_HIGH_RISK;
	}
	public void setDEPOSIT_COUNT_HIGH_RISK(BigDecimal dEPOSIT_COUNT_HIGH_RISK) {
		DEPOSIT_COUNT_HIGH_RISK = dEPOSIT_COUNT_HIGH_RISK;
	}
	public String getDEPOSIT_AMOUNT_PRODUCT() {
		return DEPOSIT_AMOUNT_PRODUCT;
	}
	public void setDEPOSIT_AMOUNT_PRODUCT(String dEPOSIT_AMOUNT_PRODUCT) {
		DEPOSIT_AMOUNT_PRODUCT = dEPOSIT_AMOUNT_PRODUCT;
	}
	public BigDecimal getDEPOSIT_AMOUNT_LOW_RISK() {
		return DEPOSIT_AMOUNT_LOW_RISK;
	}
	public void setDEPOSIT_AMOUNT_LOW_RISK(BigDecimal dEPOSIT_AMOUNT_LOW_RISK) {
		DEPOSIT_AMOUNT_LOW_RISK = dEPOSIT_AMOUNT_LOW_RISK;
	}
	public BigDecimal getDEPOSIT_AMOUNT_MEDIUM_RISK() {
		return DEPOSIT_AMOUNT_MEDIUM_RISK;
	}
	public void setDEPOSIT_AMOUNT_MEDIUM_RISK(BigDecimal dEPOSIT_AMOUNT_MEDIUM_RISK) {
		DEPOSIT_AMOUNT_MEDIUM_RISK = dEPOSIT_AMOUNT_MEDIUM_RISK;
	}
	public BigDecimal getDEPOSIT_AMOUNT_HIGH_RISK() {
		return DEPOSIT_AMOUNT_HIGH_RISK;
	}
	public void setDEPOSIT_AMOUNT_HIGH_RISK(BigDecimal dEPOSIT_AMOUNT_HIGH_RISK) {
		DEPOSIT_AMOUNT_HIGH_RISK = dEPOSIT_AMOUNT_HIGH_RISK;
	}
	public String getWITHDRAW_COUNT_PRODUCT() {
		return WITHDRAW_COUNT_PRODUCT;
	}
	public void setWITHDRAW_COUNT_PRODUCT(String wITHDRAW_COUNT_PRODUCT) {
		WITHDRAW_COUNT_PRODUCT = wITHDRAW_COUNT_PRODUCT;
	}
	public BigDecimal getWITHDRAW_COUNT_LOW_RISK() {
		return WITHDRAW_COUNT_LOW_RISK;
	}
	public void setWITHDRAW_COUNT_LOW_RISK(BigDecimal wITHDRAW_COUNT_LOW_RISK) {
		WITHDRAW_COUNT_LOW_RISK = wITHDRAW_COUNT_LOW_RISK;
	}
	public BigDecimal getWITHDRAW_COUNT_MEDIUM_RISK() {
		return WITHDRAW_COUNT_MEDIUM_RISK;
	}
	public void setWITHDRAW_COUNT_MEDIUM_RISK(BigDecimal wITHDRAW_COUNT_MEDIUM_RISK) {
		WITHDRAW_COUNT_MEDIUM_RISK = wITHDRAW_COUNT_MEDIUM_RISK;
	}
	public BigDecimal getWITHDRAW_COUNT_HIGH_RISK() {
		return WITHDRAW_COUNT_HIGH_RISK;
	}
	public void setWITHDRAW_COUNT_HIGH_RISK(BigDecimal wITHDRAW_COUNT_HIGH_RISK) {
		WITHDRAW_COUNT_HIGH_RISK = wITHDRAW_COUNT_HIGH_RISK;
	}
	public String getWITHDRAW_AMOUNT_PRODUCT() {
		return WITHDRAW_AMOUNT_PRODUCT;
	}
	public void setWITHDRAW_AMOUNT_PRODUCT(String wITHDRAW_AMOUNT_PRODUCT) {
		WITHDRAW_AMOUNT_PRODUCT = wITHDRAW_AMOUNT_PRODUCT;
	}
	public BigDecimal getWITHDRAW_AMOUNT_LOW_RISK() {
		return WITHDRAW_AMOUNT_LOW_RISK;
	}
	public void setWITHDRAW_AMOUNT_LOW_RISK(BigDecimal wITHDRAW_AMOUNT_LOW_RISK) {
		WITHDRAW_AMOUNT_LOW_RISK = wITHDRAW_AMOUNT_LOW_RISK;
	}
	public BigDecimal getWITHDRAW_AMOUNT_MEDIUM_RISK() {
		return WITHDRAW_AMOUNT_MEDIUM_RISK;
	}
	public void setWITHDRAW_AMOUNT_MEDIUM_RISK(BigDecimal wITHDRAW_AMOUNT_MEDIUM_RISK) {
		WITHDRAW_AMOUNT_MEDIUM_RISK = wITHDRAW_AMOUNT_MEDIUM_RISK;
	}
	public BigDecimal getWITHDRAW_AMOUNT_HIGH_RISK() {
		return WITHDRAW_AMOUNT_HIGH_RISK;
	}
	public void setWITHDRAW_AMOUNT_HIGH_RISK(BigDecimal wITHDRAW_AMOUNT_HIGH_RISK) {
		WITHDRAW_AMOUNT_HIGH_RISK = wITHDRAW_AMOUNT_HIGH_RISK;
	}
	public String getREPORT_CODE() {
		return REPORT_CODE;
	}
	public void setREPORT_CODE(String rEPORT_CODE) {
		REPORT_CODE = rEPORT_CODE;
	}
	public String getREPORT_NAME() {
		return REPORT_NAME;
	}
	public void setREPORT_NAME(String rEPORT_NAME) {
		REPORT_NAME = rEPORT_NAME;
	}
	public Date getREPORT_DATE() {
		return REPORT_DATE;
	}
	public void setREPORT_DATE(Date rEPORT_DATE) {
		REPORT_DATE = rEPORT_DATE;
	}
	public Date getREPORT_DUE_DATE() {
		return REPORT_DUE_DATE;
	}
	public void setREPORT_DUE_DATE(Date rEPORT_DUE_DATE) {
		REPORT_DUE_DATE = rEPORT_DUE_DATE;
	}
	public Date getREP_SUBMIT_DATE() {
		return REP_SUBMIT_DATE;
	}
	public void setREP_SUBMIT_DATE(Date rEP_SUBMIT_DATE) {
		REP_SUBMIT_DATE = rEP_SUBMIT_DATE;
	}
	public Date getREP_PERIOD_FROM() {
		return REP_PERIOD_FROM;
	}
	public void setREP_PERIOD_FROM(Date rEP_PERIOD_FROM) {
		REP_PERIOD_FROM = rEP_PERIOD_FROM;
	}
	public Date getREP_PERIOD_TO() {
		return REP_PERIOD_TO;
	}
	public void setREP_PERIOD_TO(Date rEP_PERIOD_TO) {
		REP_PERIOD_TO = rEP_PERIOD_TO;
	}
	public String getREP_FREQ() {
		return REP_FREQ;
	}
	public void setREP_FREQ(String rEP_FREQ) {
		REP_FREQ = rEP_FREQ;
	}
	public String getNIL_REPORT_FLG() {
		return NIL_REPORT_FLG;
	}
	public void setNIL_REPORT_FLG(String nIL_REPORT_FLG) {
		NIL_REPORT_FLG = nIL_REPORT_FLG;
	}
	public String getARCH_FLG() {
		return ARCH_FLG;
	}
	public void setARCH_FLG(String aRCH_FLG) {
		ARCH_FLG = aRCH_FLG;
	}
	public T16CReport(String dEPOSIT_COUNT_PRODUCT, BigDecimal dEPOSIT_COUNT_LOW_RISK,
			BigDecimal dEPOSIT_COUNT_MEDIUM_RISK, BigDecimal dEPOSIT_COUNT_HIGH_RISK, String dEPOSIT_AMOUNT_PRODUCT,
			BigDecimal dEPOSIT_AMOUNT_LOW_RISK, BigDecimal dEPOSIT_AMOUNT_MEDIUM_RISK,
			BigDecimal dEPOSIT_AMOUNT_HIGH_RISK, String wITHDRAW_COUNT_PRODUCT, BigDecimal wITHDRAW_COUNT_LOW_RISK,
			BigDecimal wITHDRAW_COUNT_MEDIUM_RISK, BigDecimal wITHDRAW_COUNT_HIGH_RISK, String wITHDRAW_AMOUNT_PRODUCT,
			BigDecimal wITHDRAW_AMOUNT_LOW_RISK, BigDecimal wITHDRAW_AMOUNT_MEDIUM_RISK,
			BigDecimal wITHDRAW_AMOUNT_HIGH_RISK, String rEPORT_CODE, String rEPORT_NAME, Date rEPORT_DATE,
			Date rEPORT_DUE_DATE, Date rEP_SUBMIT_DATE, Date rEP_PERIOD_FROM, Date rEP_PERIOD_TO, String rEP_FREQ,
			String nIL_REPORT_FLG, String aRCH_FLG) {
		super();
		DEPOSIT_COUNT_PRODUCT = dEPOSIT_COUNT_PRODUCT;
		DEPOSIT_COUNT_LOW_RISK = dEPOSIT_COUNT_LOW_RISK;
		DEPOSIT_COUNT_MEDIUM_RISK = dEPOSIT_COUNT_MEDIUM_RISK;
		DEPOSIT_COUNT_HIGH_RISK = dEPOSIT_COUNT_HIGH_RISK;
		DEPOSIT_AMOUNT_PRODUCT = dEPOSIT_AMOUNT_PRODUCT;
		DEPOSIT_AMOUNT_LOW_RISK = dEPOSIT_AMOUNT_LOW_RISK;
		DEPOSIT_AMOUNT_MEDIUM_RISK = dEPOSIT_AMOUNT_MEDIUM_RISK;
		DEPOSIT_AMOUNT_HIGH_RISK = dEPOSIT_AMOUNT_HIGH_RISK;
		WITHDRAW_COUNT_PRODUCT = wITHDRAW_COUNT_PRODUCT;
		WITHDRAW_COUNT_LOW_RISK = wITHDRAW_COUNT_LOW_RISK;
		WITHDRAW_COUNT_MEDIUM_RISK = wITHDRAW_COUNT_MEDIUM_RISK;
		WITHDRAW_COUNT_HIGH_RISK = wITHDRAW_COUNT_HIGH_RISK;
		WITHDRAW_AMOUNT_PRODUCT = wITHDRAW_AMOUNT_PRODUCT;
		WITHDRAW_AMOUNT_LOW_RISK = wITHDRAW_AMOUNT_LOW_RISK;
		WITHDRAW_AMOUNT_MEDIUM_RISK = wITHDRAW_AMOUNT_MEDIUM_RISK;
		WITHDRAW_AMOUNT_HIGH_RISK = wITHDRAW_AMOUNT_HIGH_RISK;
		REPORT_CODE = rEPORT_CODE;
		REPORT_NAME = rEPORT_NAME;
		REPORT_DATE = rEPORT_DATE;
		REPORT_DUE_DATE = rEPORT_DUE_DATE;
		REP_SUBMIT_DATE = rEP_SUBMIT_DATE;
		REP_PERIOD_FROM = rEP_PERIOD_FROM;
		REP_PERIOD_TO = rEP_PERIOD_TO;
		REP_FREQ = rEP_FREQ;
		NIL_REPORT_FLG = nIL_REPORT_FLG;
		ARCH_FLG = aRCH_FLG;
	}
	public T16CReport() {
		super();
		// TODO Auto-generated constructor stub
	}

	
}
