package com.bornfire.xbrl.entities.BRSS;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

@Entity
@Table(name = "T17_TRANSACTION_MONITORING_SYSTEM")
public class T17Report {

	private String	A1_PRODUCT;
	private String	A2_PRODUCT;
	private String	A3_PRODUCT;
	private String	A4_PRODUCT;
	private String	A5_PRODUCT;
	private String	A6_PRODUCT;
	private String	A7_PRODUCT;
	private String	A8_PRODUCT;
	private String	A9_PRODUCT;
	private String	A10_PRODUCT;
	private String	A11_PRODUCT;
	private String	A12_PRODUCT;
	private String	A13_PRODUCT;
	private String	A14_PRODUCT;
	private String	A15_PRODUCT;
	private String	A16_PRODUCT;
	private String	A17_PRODUCT;
	private String	A18_PRODUCT;
	private String	A19_PRODUCT;
	private String	A20_PRODUCT;
	private String	A21_PRODUCT;
	private String	A22_PRODUCT;
	private String	A23_PRODUCT;
	private String	A24_PRODUCT;
	private String	A25_PRODUCT;
	private String	A26_PRODUCT;
	private String	A27_PRODUCT;
	private String	B1_PARALLEL_MONITORING;
	private String	B2_PARALLEL_MONITORING;
	private String	B3_PARALLEL_MONITORING;
	private String	B4_PARALLEL_MONITORING;
	private String	B5_PARALLEL_MONITORING;
	private String	B6_PARALLEL_MONITORING;
	private String	B7_PARALLEL_MONITORING;
	private String	B8_PARALLEL_MONITORING;
	private String	B9_PARALLEL_MONITORING;
	private String	B10_PARALLEL_MONITORING;
	private String	B11_PARALLEL_MONITORING;
	private String	B12_PARALLEL_MONITORING;
	private String	B13_PARALLEL_MONITORING;
	private String	B14_PARALLEL_MONITORING;
	private String	B15_PARALLEL_MONITORING;
	private String	B16_PARALLEL_MONITORING;
	private String	B17_PARALLEL_MONITORING;
	private String	B18_PARALLEL_MONITORING;
	private String	B19_PARALLEL_MONITORING;
	private String	B20_PARALLEL_MONITORING;
	private String	B21_PARALLEL_MONITORING;
	private String	B22_PARALLEL_MONITORING;
	private String	B23_PARALLEL_MONITORING;
	private String	B24_PARALLEL_MONITORING;
	private String	B25_PARALLEL_MONITORING;
	private String	B26_PARALLEL_MONITORING;
	private String	B27_PARALLEL_MONITORING;
	private String	C1_AVERAGE_TIME;
	private String	C2_AVERAGE_TIME;
	private String	C3_AVERAGE_TIME;
	private String	C4_AVERAGE_TIME;
	private String	C5_AVERAGE_TIME;
	private String	C6_AVERAGE_TIME;
	private String	C7_AVERAGE_TIME;
	private String	C8_AVERAGE_TIME;
	private String	C9_AVERAGE_TIME;
	private String	C10_AVERAGE_TIME;
	private String	C11_AVERAGE_TIME;
	private String	C12_AVERAGE_TIME;
	private String	C13_AVERAGE_TIME;
	private String	C14_AVERAGE_TIME;
	private String	C15_AVERAGE_TIME;
	private String	C16_AVERAGE_TIME;
	private String	C17_AVERAGE_TIME;
	private String	C18_AVERAGE_TIME;
	private String	C19_AVERAGE_TIME;
	private String	C20_AVERAGE_TIME;
	private String	C21_AVERAGE_TIME;
	private String	C22_AVERAGE_TIME;
	private String	C23_AVERAGE_TIME;
	private String	C24_AVERAGE_TIME;
	private String	C25_AVERAGE_TIME;
	private String	C26_AVERAGE_TIME;
	private String	C27_AVERAGE_TIME;
	private String	D1_MANUAL_MONITORING;
	private String	D2_MANUAL_MONITORING;
	private String	D3_MANUAL_MONITORING;
	private String	D4_MANUAL_MONITORING;
	private String	D5_MANUAL_MONITORING;
	private String	D6_MANUAL_MONITORING;
	private String	D7_MANUAL_MONITORING;
	private String	D8_MANUAL_MONITORING;
	private String	D9_MANUAL_MONITORING;
	private String	D10_MANUAL_MONITORING;
	private String	D11_MANUAL_MONITORING;
	private String	D12_MANUAL_MONITORING;
	private String	D13_MANUAL_MONITORING;
	private String	D14_MANUAL_MONITORING;
	private String	D15_MANUAL_MONITORING;
	private String	D16_MANUAL_MONITORING;
	private String	D17_MANUAL_MONITORING;
	private String	D18_MANUAL_MONITORING;
	private String	D19_MANUAL_MONITORING;
	private String	D20_MANUAL_MONITORING;
	private String	D21_MANUAL_MONITORING;
	private String	D22_MANUAL_MONITORING;
	private String	D23_MANUAL_MONITORING;
	private String	D24_MANUAL_MONITORING;
	private String	D25_MANUAL_MONITORING;
	private String	D26_MANUAL_MONITORING;
	private String	D27_MANUAL_MONITORING;
	private String	E1_HOUSE_OUTSOURCED;
	private String	E2_HOUSE_OUTSOURCED;
	private String	E3_HOUSE_OUTSOURCED;
	private String	E4_HOUSE_OUTSOURCED;
	private String	E5_HOUSE_OUTSOURCED;
	private String	E6_HOUSE_OUTSOURCED;
	private String	E7_HOUSE_OUTSOURCED;
	private String	E8_HOUSE_OUTSOURCED;
	private String	E9_HOUSE_OUTSOURCED;
	private String	E10_HOUSE_OUTSOURCED;
	private String	E11_HOUSE_OUTSOURCED;
	private String	E12_HOUSE_OUTSOURCED;
	private String	E13_HOUSE_OUTSOURCED;
	private String	E14_HOUSE_OUTSOURCED;
	private String	E15_HOUSE_OUTSOURCED;
	private String	E16_HOUSE_OUTSOURCED;
	private String	E17_HOUSE_OUTSOURCED;
	private String	E18_HOUSE_OUTSOURCED;
	private String	E19_HOUSE_OUTSOURCED;
	private String	E20_HOUSE_OUTSOURCED;
	private String	E21_HOUSE_OUTSOURCED;
	private String	E22_HOUSE_OUTSOURCED;
	private String	E23_HOUSE_OUTSOURCED;
	private String	E24_HOUSE_OUTSOURCED;
	private String	E25_HOUSE_OUTSOURCED;
	private String	E26_HOUSE_OUTSOURCED;
	private String	E27_HOUSE_OUTSOURCED;
	private String	REPORT_CODE;
	private String	REPORT_NAME;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	@Id
	private Date	REPORT_DATE;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	REPORT_DUE_DATE;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	REP_SUBMIT_DATE;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	REP_PERIOD_FROM;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	REP_PERIOD_TO;
	private String	REP_FREQ;
	private String	NIL_REPORT_FLG;
	private String	ARCH_FLG;
	private String	ENTITY_FLG;
	private String	MODIFY_FLG;
	private String	VERIFY_FLG;
	private String	ENTRY_USER;
	private String	MODIFY_USER;
	private String	VERIFY_USER;
	private Date	ENTRY_TIME;
	private Date	MODIFY_TIME;
	private Date	VERIFY_TIME;

	public String getA1_PRODUCT() {
		return A1_PRODUCT;
	}
	public void setA1_PRODUCT(String a1_PRODUCT) {
		A1_PRODUCT = a1_PRODUCT;
	}
	public String getA2_PRODUCT() {
		return A2_PRODUCT;
	}
	public void setA2_PRODUCT(String a2_PRODUCT) {
		A2_PRODUCT = a2_PRODUCT;
	}
	public String getA3_PRODUCT() {
		return A3_PRODUCT;
	}
	public void setA3_PRODUCT(String a3_PRODUCT) {
		A3_PRODUCT = a3_PRODUCT;
	}
	public String getA4_PRODUCT() {
		return A4_PRODUCT;
	}
	public void setA4_PRODUCT(String a4_PRODUCT) {
		A4_PRODUCT = a4_PRODUCT;
	}
	public String getA5_PRODUCT() {
		return A5_PRODUCT;
	}
	public void setA5_PRODUCT(String a5_PRODUCT) {
		A5_PRODUCT = a5_PRODUCT;
	}
	public String getA6_PRODUCT() {
		return A6_PRODUCT;
	}
	public void setA6_PRODUCT(String a6_PRODUCT) {
		A6_PRODUCT = a6_PRODUCT;
	}
	public String getA7_PRODUCT() {
		return A7_PRODUCT;
	}
	public void setA7_PRODUCT(String a7_PRODUCT) {
		A7_PRODUCT = a7_PRODUCT;
	}
	public String getA8_PRODUCT() {
		return A8_PRODUCT;
	}
	public void setA8_PRODUCT(String a8_PRODUCT) {
		A8_PRODUCT = a8_PRODUCT;
	}
	public String getA9_PRODUCT() {
		return A9_PRODUCT;
	}
	public void setA9_PRODUCT(String a9_PRODUCT) {
		A9_PRODUCT = a9_PRODUCT;
	}
	public String getA10_PRODUCT() {
		return A10_PRODUCT;
	}
	public void setA10_PRODUCT(String a10_PRODUCT) {
		A10_PRODUCT = a10_PRODUCT;
	}
	public String getA11_PRODUCT() {
		return A11_PRODUCT;
	}
	public void setA11_PRODUCT(String a11_PRODUCT) {
		A11_PRODUCT = a11_PRODUCT;
	}
	public String getA12_PRODUCT() {
		return A12_PRODUCT;
	}
	public void setA12_PRODUCT(String a12_PRODUCT) {
		A12_PRODUCT = a12_PRODUCT;
	}
	public String getA13_PRODUCT() {
		return A13_PRODUCT;
	}
	public void setA13_PRODUCT(String a13_PRODUCT) {
		A13_PRODUCT = a13_PRODUCT;
	}
	public String getA14_PRODUCT() {
		return A14_PRODUCT;
	}
	public void setA14_PRODUCT(String a14_PRODUCT) {
		A14_PRODUCT = a14_PRODUCT;
	}
	public String getA15_PRODUCT() {
		return A15_PRODUCT;
	}
	public void setA15_PRODUCT(String a15_PRODUCT) {
		A15_PRODUCT = a15_PRODUCT;
	}
	public String getA16_PRODUCT() {
		return A16_PRODUCT;
	}
	public void setA16_PRODUCT(String a16_PRODUCT) {
		A16_PRODUCT = a16_PRODUCT;
	}
	public String getA17_PRODUCT() {
		return A17_PRODUCT;
	}
	public void setA17_PRODUCT(String a17_PRODUCT) {
		A17_PRODUCT = a17_PRODUCT;
	}
	public String getA18_PRODUCT() {
		return A18_PRODUCT;
	}
	public void setA18_PRODUCT(String a18_PRODUCT) {
		A18_PRODUCT = a18_PRODUCT;
	}
	public String getA19_PRODUCT() {
		return A19_PRODUCT;
	}
	public void setA19_PRODUCT(String a19_PRODUCT) {
		A19_PRODUCT = a19_PRODUCT;
	}
	public String getA20_PRODUCT() {
		return A20_PRODUCT;
	}
	public void setA20_PRODUCT(String a20_PRODUCT) {
		A20_PRODUCT = a20_PRODUCT;
	}
	public String getA21_PRODUCT() {
		return A21_PRODUCT;
	}
	public void setA21_PRODUCT(String a21_PRODUCT) {
		A21_PRODUCT = a21_PRODUCT;
	}
	public String getA22_PRODUCT() {
		return A22_PRODUCT;
	}
	public void setA22_PRODUCT(String a22_PRODUCT) {
		A22_PRODUCT = a22_PRODUCT;
	}
	public String getA23_PRODUCT() {
		return A23_PRODUCT;
	}
	public void setA23_PRODUCT(String a23_PRODUCT) {
		A23_PRODUCT = a23_PRODUCT;
	}
	public String getA24_PRODUCT() {
		return A24_PRODUCT;
	}
	public void setA24_PRODUCT(String a24_PRODUCT) {
		A24_PRODUCT = a24_PRODUCT;
	}
	public String getA25_PRODUCT() {
		return A25_PRODUCT;
	}
	public void setA25_PRODUCT(String a25_PRODUCT) {
		A25_PRODUCT = a25_PRODUCT;
	}
	public String getA26_PRODUCT() {
		return A26_PRODUCT;
	}
	public void setA26_PRODUCT(String a26_PRODUCT) {
		A26_PRODUCT = a26_PRODUCT;
	}
	public String getA27_PRODUCT() {
		return A27_PRODUCT;
	}
	public void setA27_PRODUCT(String a27_PRODUCT) {
		A27_PRODUCT = a27_PRODUCT;
	}
	public String getB1_PARALLEL_MONITORING() {
		return B1_PARALLEL_MONITORING;
	}
	public void setB1_PARALLEL_MONITORING(String b1_PARALLEL_MONITORING) {
		B1_PARALLEL_MONITORING = b1_PARALLEL_MONITORING;
	}
	public String getB2_PARALLEL_MONITORING() {
		return B2_PARALLEL_MONITORING;
	}
	public void setB2_PARALLEL_MONITORING(String b2_PARALLEL_MONITORING) {
		B2_PARALLEL_MONITORING = b2_PARALLEL_MONITORING;
	}
	public String getB3_PARALLEL_MONITORING() {
		return B3_PARALLEL_MONITORING;
	}
	public void setB3_PARALLEL_MONITORING(String b3_PARALLEL_MONITORING) {
		B3_PARALLEL_MONITORING = b3_PARALLEL_MONITORING;
	}
	public String getB4_PARALLEL_MONITORING() {
		return B4_PARALLEL_MONITORING;
	}
	public void setB4_PARALLEL_MONITORING(String b4_PARALLEL_MONITORING) {
		B4_PARALLEL_MONITORING = b4_PARALLEL_MONITORING;
	}
	public String getB5_PARALLEL_MONITORING() {
		return B5_PARALLEL_MONITORING;
	}
	public void setB5_PARALLEL_MONITORING(String b5_PARALLEL_MONITORING) {
		B5_PARALLEL_MONITORING = b5_PARALLEL_MONITORING;
	}
	public String getB6_PARALLEL_MONITORING() {
		return B6_PARALLEL_MONITORING;
	}
	public void setB6_PARALLEL_MONITORING(String b6_PARALLEL_MONITORING) {
		B6_PARALLEL_MONITORING = b6_PARALLEL_MONITORING;
	}
	public String getB7_PARALLEL_MONITORING() {
		return B7_PARALLEL_MONITORING;
	}
	public void setB7_PARALLEL_MONITORING(String b7_PARALLEL_MONITORING) {
		B7_PARALLEL_MONITORING = b7_PARALLEL_MONITORING;
	}
	public String getB8_PARALLEL_MONITORING() {
		return B8_PARALLEL_MONITORING;
	}
	public void setB8_PARALLEL_MONITORING(String b8_PARALLEL_MONITORING) {
		B8_PARALLEL_MONITORING = b8_PARALLEL_MONITORING;
	}
	public String getB9_PARALLEL_MONITORING() {
		return B9_PARALLEL_MONITORING;
	}
	public void setB9_PARALLEL_MONITORING(String b9_PARALLEL_MONITORING) {
		B9_PARALLEL_MONITORING = b9_PARALLEL_MONITORING;
	}
	public String getB10_PARALLEL_MONITORING() {
		return B10_PARALLEL_MONITORING;
	}
	public void setB10_PARALLEL_MONITORING(String b10_PARALLEL_MONITORING) {
		B10_PARALLEL_MONITORING = b10_PARALLEL_MONITORING;
	}
	public String getB11_PARALLEL_MONITORING() {
		return B11_PARALLEL_MONITORING;
	}
	public void setB11_PARALLEL_MONITORING(String b11_PARALLEL_MONITORING) {
		B11_PARALLEL_MONITORING = b11_PARALLEL_MONITORING;
	}
	public String getB12_PARALLEL_MONITORING() {
		return B12_PARALLEL_MONITORING;
	}
	public void setB12_PARALLEL_MONITORING(String b12_PARALLEL_MONITORING) {
		B12_PARALLEL_MONITORING = b12_PARALLEL_MONITORING;
	}
	public String getB13_PARALLEL_MONITORING() {
		return B13_PARALLEL_MONITORING;
	}
	public void setB13_PARALLEL_MONITORING(String b13_PARALLEL_MONITORING) {
		B13_PARALLEL_MONITORING = b13_PARALLEL_MONITORING;
	}
	public String getB14_PARALLEL_MONITORING() {
		return B14_PARALLEL_MONITORING;
	}
	public void setB14_PARALLEL_MONITORING(String b14_PARALLEL_MONITORING) {
		B14_PARALLEL_MONITORING = b14_PARALLEL_MONITORING;
	}
	public String getB15_PARALLEL_MONITORING() {
		return B15_PARALLEL_MONITORING;
	}
	public void setB15_PARALLEL_MONITORING(String b15_PARALLEL_MONITORING) {
		B15_PARALLEL_MONITORING = b15_PARALLEL_MONITORING;
	}
	public String getB16_PARALLEL_MONITORING() {
		return B16_PARALLEL_MONITORING;
	}
	public void setB16_PARALLEL_MONITORING(String b16_PARALLEL_MONITORING) {
		B16_PARALLEL_MONITORING = b16_PARALLEL_MONITORING;
	}
	public String getB17_PARALLEL_MONITORING() {
		return B17_PARALLEL_MONITORING;
	}
	public void setB17_PARALLEL_MONITORING(String b17_PARALLEL_MONITORING) {
		B17_PARALLEL_MONITORING = b17_PARALLEL_MONITORING;
	}
	public String getB18_PARALLEL_MONITORING() {
		return B18_PARALLEL_MONITORING;
	}
	public void setB18_PARALLEL_MONITORING(String b18_PARALLEL_MONITORING) {
		B18_PARALLEL_MONITORING = b18_PARALLEL_MONITORING;
	}
	public String getB19_PARALLEL_MONITORING() {
		return B19_PARALLEL_MONITORING;
	}
	public void setB19_PARALLEL_MONITORING(String b19_PARALLEL_MONITORING) {
		B19_PARALLEL_MONITORING = b19_PARALLEL_MONITORING;
	}
	public String getB20_PARALLEL_MONITORING() {
		return B20_PARALLEL_MONITORING;
	}
	public void setB20_PARALLEL_MONITORING(String b20_PARALLEL_MONITORING) {
		B20_PARALLEL_MONITORING = b20_PARALLEL_MONITORING;
	}
	public String getB21_PARALLEL_MONITORING() {
		return B21_PARALLEL_MONITORING;
	}
	public void setB21_PARALLEL_MONITORING(String b21_PARALLEL_MONITORING) {
		B21_PARALLEL_MONITORING = b21_PARALLEL_MONITORING;
	}
	public String getB22_PARALLEL_MONITORING() {
		return B22_PARALLEL_MONITORING;
	}
	public void setB22_PARALLEL_MONITORING(String b22_PARALLEL_MONITORING) {
		B22_PARALLEL_MONITORING = b22_PARALLEL_MONITORING;
	}
	public String getB23_PARALLEL_MONITORING() {
		return B23_PARALLEL_MONITORING;
	}
	public void setB23_PARALLEL_MONITORING(String b23_PARALLEL_MONITORING) {
		B23_PARALLEL_MONITORING = b23_PARALLEL_MONITORING;
	}
	public String getB24_PARALLEL_MONITORING() {
		return B24_PARALLEL_MONITORING;
	}
	public void setB24_PARALLEL_MONITORING(String b24_PARALLEL_MONITORING) {
		B24_PARALLEL_MONITORING = b24_PARALLEL_MONITORING;
	}
	public String getB25_PARALLEL_MONITORING() {
		return B25_PARALLEL_MONITORING;
	}
	public void setB25_PARALLEL_MONITORING(String b25_PARALLEL_MONITORING) {
		B25_PARALLEL_MONITORING = b25_PARALLEL_MONITORING;
	}
	public String getB26_PARALLEL_MONITORING() {
		return B26_PARALLEL_MONITORING;
	}
	public void setB26_PARALLEL_MONITORING(String b26_PARALLEL_MONITORING) {
		B26_PARALLEL_MONITORING = b26_PARALLEL_MONITORING;
	}
	public String getB27_PARALLEL_MONITORING() {
		return B27_PARALLEL_MONITORING;
	}
	public void setB27_PARALLEL_MONITORING(String b27_PARALLEL_MONITORING) {
		B27_PARALLEL_MONITORING = b27_PARALLEL_MONITORING;
	}
	public String getC1_AVERAGE_TIME() {
		return C1_AVERAGE_TIME;
	}
	public void setC1_AVERAGE_TIME(String c1_AVERAGE_TIME) {
		C1_AVERAGE_TIME = c1_AVERAGE_TIME;
	}
	public String getC2_AVERAGE_TIME() {
		return C2_AVERAGE_TIME;
	}
	public void setC2_AVERAGE_TIME(String c2_AVERAGE_TIME) {
		C2_AVERAGE_TIME = c2_AVERAGE_TIME;
	}
	public String getC3_AVERAGE_TIME() {
		return C3_AVERAGE_TIME;
	}
	public void setC3_AVERAGE_TIME(String c3_AVERAGE_TIME) {
		C3_AVERAGE_TIME = c3_AVERAGE_TIME;
	}
	public String getC4_AVERAGE_TIME() {
		return C4_AVERAGE_TIME;
	}
	public void setC4_AVERAGE_TIME(String c4_AVERAGE_TIME) {
		C4_AVERAGE_TIME = c4_AVERAGE_TIME;
	}
	public String getC5_AVERAGE_TIME() {
		return C5_AVERAGE_TIME;
	}
	public void setC5_AVERAGE_TIME(String c5_AVERAGE_TIME) {
		C5_AVERAGE_TIME = c5_AVERAGE_TIME;
	}
	public String getC6_AVERAGE_TIME() {
		return C6_AVERAGE_TIME;
	}
	public void setC6_AVERAGE_TIME(String c6_AVERAGE_TIME) {
		C6_AVERAGE_TIME = c6_AVERAGE_TIME;
	}
	public String getC7_AVERAGE_TIME() {
		return C7_AVERAGE_TIME;
	}
	public void setC7_AVERAGE_TIME(String c7_AVERAGE_TIME) {
		C7_AVERAGE_TIME = c7_AVERAGE_TIME;
	}
	public String getC8_AVERAGE_TIME() {
		return C8_AVERAGE_TIME;
	}
	public void setC8_AVERAGE_TIME(String c8_AVERAGE_TIME) {
		C8_AVERAGE_TIME = c8_AVERAGE_TIME;
	}
	public String getC9_AVERAGE_TIME() {
		return C9_AVERAGE_TIME;
	}
	public void setC9_AVERAGE_TIME(String c9_AVERAGE_TIME) {
		C9_AVERAGE_TIME = c9_AVERAGE_TIME;
	}
	public String getC10_AVERAGE_TIME() {
		return C10_AVERAGE_TIME;
	}
	public void setC10_AVERAGE_TIME(String c10_AVERAGE_TIME) {
		C10_AVERAGE_TIME = c10_AVERAGE_TIME;
	}
	public String getC11_AVERAGE_TIME() {
		return C11_AVERAGE_TIME;
	}
	public void setC11_AVERAGE_TIME(String c11_AVERAGE_TIME) {
		C11_AVERAGE_TIME = c11_AVERAGE_TIME;
	}
	public String getC12_AVERAGE_TIME() {
		return C12_AVERAGE_TIME;
	}
	public void setC12_AVERAGE_TIME(String c12_AVERAGE_TIME) {
		C12_AVERAGE_TIME = c12_AVERAGE_TIME;
	}
	public String getC13_AVERAGE_TIME() {
		return C13_AVERAGE_TIME;
	}
	public void setC13_AVERAGE_TIME(String c13_AVERAGE_TIME) {
		C13_AVERAGE_TIME = c13_AVERAGE_TIME;
	}
	public String getC14_AVERAGE_TIME() {
		return C14_AVERAGE_TIME;
	}
	public void setC14_AVERAGE_TIME(String c14_AVERAGE_TIME) {
		C14_AVERAGE_TIME = c14_AVERAGE_TIME;
	}
	public String getC15_AVERAGE_TIME() {
		return C15_AVERAGE_TIME;
	}
	public void setC15_AVERAGE_TIME(String c15_AVERAGE_TIME) {
		C15_AVERAGE_TIME = c15_AVERAGE_TIME;
	}
	public String getC16_AVERAGE_TIME() {
		return C16_AVERAGE_TIME;
	}
	public void setC16_AVERAGE_TIME(String c16_AVERAGE_TIME) {
		C16_AVERAGE_TIME = c16_AVERAGE_TIME;
	}
	public String getC17_AVERAGE_TIME() {
		return C17_AVERAGE_TIME;
	}
	public void setC17_AVERAGE_TIME(String c17_AVERAGE_TIME) {
		C17_AVERAGE_TIME = c17_AVERAGE_TIME;
	}
	public String getC18_AVERAGE_TIME() {
		return C18_AVERAGE_TIME;
	}
	public void setC18_AVERAGE_TIME(String c18_AVERAGE_TIME) {
		C18_AVERAGE_TIME = c18_AVERAGE_TIME;
	}
	public String getC19_AVERAGE_TIME() {
		return C19_AVERAGE_TIME;
	}
	public void setC19_AVERAGE_TIME(String c19_AVERAGE_TIME) {
		C19_AVERAGE_TIME = c19_AVERAGE_TIME;
	}
	public String getC20_AVERAGE_TIME() {
		return C20_AVERAGE_TIME;
	}
	public void setC20_AVERAGE_TIME(String c20_AVERAGE_TIME) {
		C20_AVERAGE_TIME = c20_AVERAGE_TIME;
	}
	public String getC21_AVERAGE_TIME() {
		return C21_AVERAGE_TIME;
	}
	public void setC21_AVERAGE_TIME(String c21_AVERAGE_TIME) {
		C21_AVERAGE_TIME = c21_AVERAGE_TIME;
	}
	public String getC22_AVERAGE_TIME() {
		return C22_AVERAGE_TIME;
	}
	public void setC22_AVERAGE_TIME(String c22_AVERAGE_TIME) {
		C22_AVERAGE_TIME = c22_AVERAGE_TIME;
	}
	public String getC23_AVERAGE_TIME() {
		return C23_AVERAGE_TIME;
	}
	public void setC23_AVERAGE_TIME(String c23_AVERAGE_TIME) {
		C23_AVERAGE_TIME = c23_AVERAGE_TIME;
	}
	public String getC24_AVERAGE_TIME() {
		return C24_AVERAGE_TIME;
	}
	public void setC24_AVERAGE_TIME(String c24_AVERAGE_TIME) {
		C24_AVERAGE_TIME = c24_AVERAGE_TIME;
	}
	public String getC25_AVERAGE_TIME() {
		return C25_AVERAGE_TIME;
	}
	public void setC25_AVERAGE_TIME(String c25_AVERAGE_TIME) {
		C25_AVERAGE_TIME = c25_AVERAGE_TIME;
	}
	public String getC26_AVERAGE_TIME() {
		return C26_AVERAGE_TIME;
	}
	public void setC26_AVERAGE_TIME(String c26_AVERAGE_TIME) {
		C26_AVERAGE_TIME = c26_AVERAGE_TIME;
	}
	public String getC27_AVERAGE_TIME() {
		return C27_AVERAGE_TIME;
	}
	public void setC27_AVERAGE_TIME(String c27_AVERAGE_TIME) {
		C27_AVERAGE_TIME = c27_AVERAGE_TIME;
	}
	public String getD1_MANUAL_MONITORING() {
		return D1_MANUAL_MONITORING;
	}
	public void setD1_MANUAL_MONITORING(String d1_MANUAL_MONITORING) {
		D1_MANUAL_MONITORING = d1_MANUAL_MONITORING;
	}
	public String getD2_MANUAL_MONITORING() {
		return D2_MANUAL_MONITORING;
	}
	public void setD2_MANUAL_MONITORING(String d2_MANUAL_MONITORING) {
		D2_MANUAL_MONITORING = d2_MANUAL_MONITORING;
	}
	public String getD3_MANUAL_MONITORING() {
		return D3_MANUAL_MONITORING;
	}
	public void setD3_MANUAL_MONITORING(String d3_MANUAL_MONITORING) {
		D3_MANUAL_MONITORING = d3_MANUAL_MONITORING;
	}
	public String getD4_MANUAL_MONITORING() {
		return D4_MANUAL_MONITORING;
	}
	public void setD4_MANUAL_MONITORING(String d4_MANUAL_MONITORING) {
		D4_MANUAL_MONITORING = d4_MANUAL_MONITORING;
	}
	public String getD5_MANUAL_MONITORING() {
		return D5_MANUAL_MONITORING;
	}
	public void setD5_MANUAL_MONITORING(String d5_MANUAL_MONITORING) {
		D5_MANUAL_MONITORING = d5_MANUAL_MONITORING;
	}
	public String getD6_MANUAL_MONITORING() {
		return D6_MANUAL_MONITORING;
	}
	public void setD6_MANUAL_MONITORING(String d6_MANUAL_MONITORING) {
		D6_MANUAL_MONITORING = d6_MANUAL_MONITORING;
	}
	public String getD7_MANUAL_MONITORING() {
		return D7_MANUAL_MONITORING;
	}
	public void setD7_MANUAL_MONITORING(String d7_MANUAL_MONITORING) {
		D7_MANUAL_MONITORING = d7_MANUAL_MONITORING;
	}
	public String getD8_MANUAL_MONITORING() {
		return D8_MANUAL_MONITORING;
	}
	public void setD8_MANUAL_MONITORING(String d8_MANUAL_MONITORING) {
		D8_MANUAL_MONITORING = d8_MANUAL_MONITORING;
	}
	public String getD9_MANUAL_MONITORING() {
		return D9_MANUAL_MONITORING;
	}
	public void setD9_MANUAL_MONITORING(String d9_MANUAL_MONITORING) {
		D9_MANUAL_MONITORING = d9_MANUAL_MONITORING;
	}
	public String getD10_MANUAL_MONITORING() {
		return D10_MANUAL_MONITORING;
	}
	public void setD10_MANUAL_MONITORING(String d10_MANUAL_MONITORING) {
		D10_MANUAL_MONITORING = d10_MANUAL_MONITORING;
	}
	public String getD11_MANUAL_MONITORING() {
		return D11_MANUAL_MONITORING;
	}
	public void setD11_MANUAL_MONITORING(String d11_MANUAL_MONITORING) {
		D11_MANUAL_MONITORING = d11_MANUAL_MONITORING;
	}
	public String getD12_MANUAL_MONITORING() {
		return D12_MANUAL_MONITORING;
	}
	public void setD12_MANUAL_MONITORING(String d12_MANUAL_MONITORING) {
		D12_MANUAL_MONITORING = d12_MANUAL_MONITORING;
	}
	public String getD13_MANUAL_MONITORING() {
		return D13_MANUAL_MONITORING;
	}
	public void setD13_MANUAL_MONITORING(String d13_MANUAL_MONITORING) {
		D13_MANUAL_MONITORING = d13_MANUAL_MONITORING;
	}
	public String getD14_MANUAL_MONITORING() {
		return D14_MANUAL_MONITORING;
	}
	public void setD14_MANUAL_MONITORING(String d14_MANUAL_MONITORING) {
		D14_MANUAL_MONITORING = d14_MANUAL_MONITORING;
	}
	public String getD15_MANUAL_MONITORING() {
		return D15_MANUAL_MONITORING;
	}
	public void setD15_MANUAL_MONITORING(String d15_MANUAL_MONITORING) {
		D15_MANUAL_MONITORING = d15_MANUAL_MONITORING;
	}
	public String getD16_MANUAL_MONITORING() {
		return D16_MANUAL_MONITORING;
	}
	public void setD16_MANUAL_MONITORING(String d16_MANUAL_MONITORING) {
		D16_MANUAL_MONITORING = d16_MANUAL_MONITORING;
	}
	public String getD17_MANUAL_MONITORING() {
		return D17_MANUAL_MONITORING;
	}
	public void setD17_MANUAL_MONITORING(String d17_MANUAL_MONITORING) {
		D17_MANUAL_MONITORING = d17_MANUAL_MONITORING;
	}
	public String getD18_MANUAL_MONITORING() {
		return D18_MANUAL_MONITORING;
	}
	public void setD18_MANUAL_MONITORING(String d18_MANUAL_MONITORING) {
		D18_MANUAL_MONITORING = d18_MANUAL_MONITORING;
	}
	public String getD19_MANUAL_MONITORING() {
		return D19_MANUAL_MONITORING;
	}
	public void setD19_MANUAL_MONITORING(String d19_MANUAL_MONITORING) {
		D19_MANUAL_MONITORING = d19_MANUAL_MONITORING;
	}
	public String getD20_MANUAL_MONITORING() {
		return D20_MANUAL_MONITORING;
	}
	public void setD20_MANUAL_MONITORING(String d20_MANUAL_MONITORING) {
		D20_MANUAL_MONITORING = d20_MANUAL_MONITORING;
	}
	public String getD21_MANUAL_MONITORING() {
		return D21_MANUAL_MONITORING;
	}
	public void setD21_MANUAL_MONITORING(String d21_MANUAL_MONITORING) {
		D21_MANUAL_MONITORING = d21_MANUAL_MONITORING;
	}
	public String getD22_MANUAL_MONITORING() {
		return D22_MANUAL_MONITORING;
	}
	public void setD22_MANUAL_MONITORING(String d22_MANUAL_MONITORING) {
		D22_MANUAL_MONITORING = d22_MANUAL_MONITORING;
	}
	public String getD23_MANUAL_MONITORING() {
		return D23_MANUAL_MONITORING;
	}
	public void setD23_MANUAL_MONITORING(String d23_MANUAL_MONITORING) {
		D23_MANUAL_MONITORING = d23_MANUAL_MONITORING;
	}
	public String getD24_MANUAL_MONITORING() {
		return D24_MANUAL_MONITORING;
	}
	public void setD24_MANUAL_MONITORING(String d24_MANUAL_MONITORING) {
		D24_MANUAL_MONITORING = d24_MANUAL_MONITORING;
	}
	public String getD25_MANUAL_MONITORING() {
		return D25_MANUAL_MONITORING;
	}
	public void setD25_MANUAL_MONITORING(String d25_MANUAL_MONITORING) {
		D25_MANUAL_MONITORING = d25_MANUAL_MONITORING;
	}
	public String getD26_MANUAL_MONITORING() {
		return D26_MANUAL_MONITORING;
	}
	public void setD26_MANUAL_MONITORING(String d26_MANUAL_MONITORING) {
		D26_MANUAL_MONITORING = d26_MANUAL_MONITORING;
	}
	public String getD27_MANUAL_MONITORING() {
		return D27_MANUAL_MONITORING;
	}
	public void setD27_MANUAL_MONITORING(String d27_MANUAL_MONITORING) {
		D27_MANUAL_MONITORING = d27_MANUAL_MONITORING;
	}
	public String getE1_HOUSE_OUTSOURCED() {
		return E1_HOUSE_OUTSOURCED;
	}
	public void setE1_HOUSE_OUTSOURCED(String e1_HOUSE_OUTSOURCED) {
		E1_HOUSE_OUTSOURCED = e1_HOUSE_OUTSOURCED;
	}
	public String getE2_HOUSE_OUTSOURCED() {
		return E2_HOUSE_OUTSOURCED;
	}
	public void setE2_HOUSE_OUTSOURCED(String e2_HOUSE_OUTSOURCED) {
		E2_HOUSE_OUTSOURCED = e2_HOUSE_OUTSOURCED;
	}
	public String getE3_HOUSE_OUTSOURCED() {
		return E3_HOUSE_OUTSOURCED;
	}
	public void setE3_HOUSE_OUTSOURCED(String e3_HOUSE_OUTSOURCED) {
		E3_HOUSE_OUTSOURCED = e3_HOUSE_OUTSOURCED;
	}
	public String getE4_HOUSE_OUTSOURCED() {
		return E4_HOUSE_OUTSOURCED;
	}
	public void setE4_HOUSE_OUTSOURCED(String e4_HOUSE_OUTSOURCED) {
		E4_HOUSE_OUTSOURCED = e4_HOUSE_OUTSOURCED;
	}
	public String getE5_HOUSE_OUTSOURCED() {
		return E5_HOUSE_OUTSOURCED;
	}
	public void setE5_HOUSE_OUTSOURCED(String e5_HOUSE_OUTSOURCED) {
		E5_HOUSE_OUTSOURCED = e5_HOUSE_OUTSOURCED;
	}
	public String getE6_HOUSE_OUTSOURCED() {
		return E6_HOUSE_OUTSOURCED;
	}
	public void setE6_HOUSE_OUTSOURCED(String e6_HOUSE_OUTSOURCED) {
		E6_HOUSE_OUTSOURCED = e6_HOUSE_OUTSOURCED;
	}
	public String getE7_HOUSE_OUTSOURCED() {
		return E7_HOUSE_OUTSOURCED;
	}
	public void setE7_HOUSE_OUTSOURCED(String e7_HOUSE_OUTSOURCED) {
		E7_HOUSE_OUTSOURCED = e7_HOUSE_OUTSOURCED;
	}
	public String getE8_HOUSE_OUTSOURCED() {
		return E8_HOUSE_OUTSOURCED;
	}
	public void setE8_HOUSE_OUTSOURCED(String e8_HOUSE_OUTSOURCED) {
		E8_HOUSE_OUTSOURCED = e8_HOUSE_OUTSOURCED;
	}
	public String getE9_HOUSE_OUTSOURCED() {
		return E9_HOUSE_OUTSOURCED;
	}
	public void setE9_HOUSE_OUTSOURCED(String e9_HOUSE_OUTSOURCED) {
		E9_HOUSE_OUTSOURCED = e9_HOUSE_OUTSOURCED;
	}
	public String getE10_HOUSE_OUTSOURCED() {
		return E10_HOUSE_OUTSOURCED;
	}
	public void setE10_HOUSE_OUTSOURCED(String e10_HOUSE_OUTSOURCED) {
		E10_HOUSE_OUTSOURCED = e10_HOUSE_OUTSOURCED;
	}
	public String getE11_HOUSE_OUTSOURCED() {
		return E11_HOUSE_OUTSOURCED;
	}
	public void setE11_HOUSE_OUTSOURCED(String e11_HOUSE_OUTSOURCED) {
		E11_HOUSE_OUTSOURCED = e11_HOUSE_OUTSOURCED;
	}
	public String getE12_HOUSE_OUTSOURCED() {
		return E12_HOUSE_OUTSOURCED;
	}
	public void setE12_HOUSE_OUTSOURCED(String e12_HOUSE_OUTSOURCED) {
		E12_HOUSE_OUTSOURCED = e12_HOUSE_OUTSOURCED;
	}
	public String getE13_HOUSE_OUTSOURCED() {
		return E13_HOUSE_OUTSOURCED;
	}
	public void setE13_HOUSE_OUTSOURCED(String e13_HOUSE_OUTSOURCED) {
		E13_HOUSE_OUTSOURCED = e13_HOUSE_OUTSOURCED;
	}
	public String getE14_HOUSE_OUTSOURCED() {
		return E14_HOUSE_OUTSOURCED;
	}
	public void setE14_HOUSE_OUTSOURCED(String e14_HOUSE_OUTSOURCED) {
		E14_HOUSE_OUTSOURCED = e14_HOUSE_OUTSOURCED;
	}
	public String getE15_HOUSE_OUTSOURCED() {
		return E15_HOUSE_OUTSOURCED;
	}
	public void setE15_HOUSE_OUTSOURCED(String e15_HOUSE_OUTSOURCED) {
		E15_HOUSE_OUTSOURCED = e15_HOUSE_OUTSOURCED;
	}
	public String getE16_HOUSE_OUTSOURCED() {
		return E16_HOUSE_OUTSOURCED;
	}
	public void setE16_HOUSE_OUTSOURCED(String e16_HOUSE_OUTSOURCED) {
		E16_HOUSE_OUTSOURCED = e16_HOUSE_OUTSOURCED;
	}
	public String getE17_HOUSE_OUTSOURCED() {
		return E17_HOUSE_OUTSOURCED;
	}
	public void setE17_HOUSE_OUTSOURCED(String e17_HOUSE_OUTSOURCED) {
		E17_HOUSE_OUTSOURCED = e17_HOUSE_OUTSOURCED;
	}
	public String getE18_HOUSE_OUTSOURCED() {
		return E18_HOUSE_OUTSOURCED;
	}
	public void setE18_HOUSE_OUTSOURCED(String e18_HOUSE_OUTSOURCED) {
		E18_HOUSE_OUTSOURCED = e18_HOUSE_OUTSOURCED;
	}
	public String getE19_HOUSE_OUTSOURCED() {
		return E19_HOUSE_OUTSOURCED;
	}
	public void setE19_HOUSE_OUTSOURCED(String e19_HOUSE_OUTSOURCED) {
		E19_HOUSE_OUTSOURCED = e19_HOUSE_OUTSOURCED;
	}
	public String getE20_HOUSE_OUTSOURCED() {
		return E20_HOUSE_OUTSOURCED;
	}
	public void setE20_HOUSE_OUTSOURCED(String e20_HOUSE_OUTSOURCED) {
		E20_HOUSE_OUTSOURCED = e20_HOUSE_OUTSOURCED;
	}
	public String getE21_HOUSE_OUTSOURCED() {
		return E21_HOUSE_OUTSOURCED;
	}
	public void setE21_HOUSE_OUTSOURCED(String e21_HOUSE_OUTSOURCED) {
		E21_HOUSE_OUTSOURCED = e21_HOUSE_OUTSOURCED;
	}
	public String getE22_HOUSE_OUTSOURCED() {
		return E22_HOUSE_OUTSOURCED;
	}
	public void setE22_HOUSE_OUTSOURCED(String e22_HOUSE_OUTSOURCED) {
		E22_HOUSE_OUTSOURCED = e22_HOUSE_OUTSOURCED;
	}
	public String getE23_HOUSE_OUTSOURCED() {
		return E23_HOUSE_OUTSOURCED;
	}
	public void setE23_HOUSE_OUTSOURCED(String e23_HOUSE_OUTSOURCED) {
		E23_HOUSE_OUTSOURCED = e23_HOUSE_OUTSOURCED;
	}
	public String getE24_HOUSE_OUTSOURCED() {
		return E24_HOUSE_OUTSOURCED;
	}
	public void setE24_HOUSE_OUTSOURCED(String e24_HOUSE_OUTSOURCED) {
		E24_HOUSE_OUTSOURCED = e24_HOUSE_OUTSOURCED;
	}
	public String getE25_HOUSE_OUTSOURCED() {
		return E25_HOUSE_OUTSOURCED;
	}
	public void setE25_HOUSE_OUTSOURCED(String e25_HOUSE_OUTSOURCED) {
		E25_HOUSE_OUTSOURCED = e25_HOUSE_OUTSOURCED;
	}
	public String getE26_HOUSE_OUTSOURCED() {
		return E26_HOUSE_OUTSOURCED;
	}
	public void setE26_HOUSE_OUTSOURCED(String e26_HOUSE_OUTSOURCED) {
		E26_HOUSE_OUTSOURCED = e26_HOUSE_OUTSOURCED;
	}
	public String getE27_HOUSE_OUTSOURCED() {
		return E27_HOUSE_OUTSOURCED;
	}
	public void setE27_HOUSE_OUTSOURCED(String e27_HOUSE_OUTSOURCED) {
		E27_HOUSE_OUTSOURCED = e27_HOUSE_OUTSOURCED;
	}
	public String getREPORT_CODE() {
		return REPORT_CODE;
	}
	public void setREPORT_CODE(String rEPORT_CODE) {
		REPORT_CODE = rEPORT_CODE;
	}
	public String getREPORT_NAME() {
		return REPORT_NAME;
	}
	public void setREPORT_NAME(String rEPORT_NAME) {
		REPORT_NAME = rEPORT_NAME;
	}
	public Date getREPORT_DATE() {
		return REPORT_DATE;
	}
	public void setREPORT_DATE(Date rEPORT_DATE) {
		REPORT_DATE = rEPORT_DATE;
	}
	public Date getREPORT_DUE_DATE() {
		return REPORT_DUE_DATE;
	}
	public void setREPORT_DUE_DATE(Date rEPORT_DUE_DATE) {
		REPORT_DUE_DATE = rEPORT_DUE_DATE;
	}
	public Date getREP_SUBMIT_DATE() {
		return REP_SUBMIT_DATE;
	}
	public void setREP_SUBMIT_DATE(Date rEP_SUBMIT_DATE) {
		REP_SUBMIT_DATE = rEP_SUBMIT_DATE;
	}
	public Date getREP_PERIOD_FROM() {
		return REP_PERIOD_FROM;
	}
	public void setREP_PERIOD_FROM(Date rEP_PERIOD_FROM) {
		REP_PERIOD_FROM = rEP_PERIOD_FROM;
	}
	public Date getREP_PERIOD_TO() {
		return REP_PERIOD_TO;
	}
	public void setREP_PERIOD_TO(Date rEP_PERIOD_TO) {
		REP_PERIOD_TO = rEP_PERIOD_TO;
	}
	public String getREP_FREQ() {
		return REP_FREQ;
	}
	public void setREP_FREQ(String rEP_FREQ) {
		REP_FREQ = rEP_FREQ;
	}
	public String getNIL_REPORT_FLG() {
		return NIL_REPORT_FLG;
	}
	public void setNIL_REPORT_FLG(String nIL_REPORT_FLG) {
		NIL_REPORT_FLG = nIL_REPORT_FLG;
	}
	public String getARCH_FLG() {
		return ARCH_FLG;
	}
	public void setARCH_FLG(String aRCH_FLG) {
		ARCH_FLG = aRCH_FLG;
	}
	public String getENTITY_FLG() {
		return ENTITY_FLG;
	}
	public void setENTITY_FLG(String eNTITY_FLG) {
		ENTITY_FLG = eNTITY_FLG;
	}
	public String getMODIFY_FLG() {
		return MODIFY_FLG;
	}
	public void setMODIFY_FLG(String mODIFY_FLG) {
		MODIFY_FLG = mODIFY_FLG;
	}
	public String getVERIFY_FLG() {
		return VERIFY_FLG;
	}
	public void setVERIFY_FLG(String vERIFY_FLG) {
		VERIFY_FLG = vERIFY_FLG;
	}
	public String getENTRY_USER() {
		return ENTRY_USER;
	}
	public void setENTRY_USER(String eNTRY_USER) {
		ENTRY_USER = eNTRY_USER;
	}
	public String getMODIFY_USER() {
		return MODIFY_USER;
	}
	public void setMODIFY_USER(String mODIFY_USER) {
		MODIFY_USER = mODIFY_USER;
	}
	public String getVERIFY_USER() {
		return VERIFY_USER;
	}
	public void setVERIFY_USER(String vERIFY_USER) {
		VERIFY_USER = vERIFY_USER;
	}
	public Date getENTRY_TIME() {
		return ENTRY_TIME;
	}
	public void setENTRY_TIME(Date eNTRY_TIME) {
		ENTRY_TIME = eNTRY_TIME;
	}
	public Date getMODIFY_TIME() {
		return MODIFY_TIME;
	}
	public void setMODIFY_TIME(Date mODIFY_TIME) {
		MODIFY_TIME = mODIFY_TIME;
	}
	public Date getVERIFY_TIME() {
		return VERIFY_TIME;
	}
	public void setVERIFY_TIME(Date vERIFY_TIME) {
		VERIFY_TIME = vERIFY_TIME;
	}
	public T17Report(String a1_PRODUCT, String a2_PRODUCT, String a3_PRODUCT, String a4_PRODUCT, String a5_PRODUCT,
			String a6_PRODUCT, String a7_PRODUCT, String a8_PRODUCT, String a9_PRODUCT, String a10_PRODUCT,
			String a11_PRODUCT, String a12_PRODUCT, String a13_PRODUCT, String a14_PRODUCT, String a15_PRODUCT,
			String a16_PRODUCT, String a17_PRODUCT, String a18_PRODUCT, String a19_PRODUCT, String a20_PRODUCT,
			String a21_PRODUCT, String a22_PRODUCT, String a23_PRODUCT, String a24_PRODUCT, String a25_PRODUCT,
			String a26_PRODUCT, String a27_PRODUCT, String b1_PARALLEL_MONITORING, String b2_PARALLEL_MONITORING,
			String b3_PARALLEL_MONITORING, String b4_PARALLEL_MONITORING, String b5_PARALLEL_MONITORING,
			String b6_PARALLEL_MONITORING, String b7_PARALLEL_MONITORING, String b8_PARALLEL_MONITORING,
			String b9_PARALLEL_MONITORING, String b10_PARALLEL_MONITORING, String b11_PARALLEL_MONITORING,
			String b12_PARALLEL_MONITORING, String b13_PARALLEL_MONITORING, String b14_PARALLEL_MONITORING,
			String b15_PARALLEL_MONITORING, String b16_PARALLEL_MONITORING, String b17_PARALLEL_MONITORING,
			String b18_PARALLEL_MONITORING, String b19_PARALLEL_MONITORING, String b20_PARALLEL_MONITORING,
			String b21_PARALLEL_MONITORING, String b22_PARALLEL_MONITORING, String b23_PARALLEL_MONITORING,
			String b24_PARALLEL_MONITORING, String b25_PARALLEL_MONITORING, String b26_PARALLEL_MONITORING,
			String b27_PARALLEL_MONITORING, String c1_AVERAGE_TIME, String c2_AVERAGE_TIME, String c3_AVERAGE_TIME,
			String c4_AVERAGE_TIME, String c5_AVERAGE_TIME, String c6_AVERAGE_TIME, String c7_AVERAGE_TIME,
			String c8_AVERAGE_TIME, String c9_AVERAGE_TIME, String c10_AVERAGE_TIME, String c11_AVERAGE_TIME,
			String c12_AVERAGE_TIME, String c13_AVERAGE_TIME, String c14_AVERAGE_TIME, String c15_AVERAGE_TIME,
			String c16_AVERAGE_TIME, String c17_AVERAGE_TIME, String c18_AVERAGE_TIME, String c19_AVERAGE_TIME,
			String c20_AVERAGE_TIME, String c21_AVERAGE_TIME, String c22_AVERAGE_TIME, String c23_AVERAGE_TIME,
			String c24_AVERAGE_TIME, String c25_AVERAGE_TIME, String c26_AVERAGE_TIME, String c27_AVERAGE_TIME,
			String d1_MANUAL_MONITORING, String d2_MANUAL_MONITORING, String d3_MANUAL_MONITORING,
			String d4_MANUAL_MONITORING, String d5_MANUAL_MONITORING, String d6_MANUAL_MONITORING,
			String d7_MANUAL_MONITORING, String d8_MANUAL_MONITORING, String d9_MANUAL_MONITORING,
			String d10_MANUAL_MONITORING, String d11_MANUAL_MONITORING, String d12_MANUAL_MONITORING,
			String d13_MANUAL_MONITORING, String d14_MANUAL_MONITORING, String d15_MANUAL_MONITORING,
			String d16_MANUAL_MONITORING, String d17_MANUAL_MONITORING, String d18_MANUAL_MONITORING,
			String d19_MANUAL_MONITORING, String d20_MANUAL_MONITORING, String d21_MANUAL_MONITORING,
			String d22_MANUAL_MONITORING, String d23_MANUAL_MONITORING, String d24_MANUAL_MONITORING,
			String d25_MANUAL_MONITORING, String d26_MANUAL_MONITORING, String d27_MANUAL_MONITORING,
			String e1_HOUSE_OUTSOURCED, String e2_HOUSE_OUTSOURCED, String e3_HOUSE_OUTSOURCED,
			String e4_HOUSE_OUTSOURCED, String e5_HOUSE_OUTSOURCED, String e6_HOUSE_OUTSOURCED,
			String e7_HOUSE_OUTSOURCED, String e8_HOUSE_OUTSOURCED, String e9_HOUSE_OUTSOURCED,
			String e10_HOUSE_OUTSOURCED, String e11_HOUSE_OUTSOURCED, String e12_HOUSE_OUTSOURCED,
			String e13_HOUSE_OUTSOURCED, String e14_HOUSE_OUTSOURCED, String e15_HOUSE_OUTSOURCED,
			String e16_HOUSE_OUTSOURCED, String e17_HOUSE_OUTSOURCED, String e18_HOUSE_OUTSOURCED,
			String e19_HOUSE_OUTSOURCED, String e20_HOUSE_OUTSOURCED, String e21_HOUSE_OUTSOURCED,
			String e22_HOUSE_OUTSOURCED, String e23_HOUSE_OUTSOURCED, String e24_HOUSE_OUTSOURCED,
			String e25_HOUSE_OUTSOURCED, String e26_HOUSE_OUTSOURCED, String e27_HOUSE_OUTSOURCED, String rEPORT_CODE,
			String rEPORT_NAME, Date rEPORT_DATE, Date rEPORT_DUE_DATE, Date rEP_SUBMIT_DATE, Date rEP_PERIOD_FROM,
			Date rEP_PERIOD_TO, String rEP_FREQ, String nIL_REPORT_FLG, String aRCH_FLG, String eNTITY_FLG,
			String mODIFY_FLG, String vERIFY_FLG, String eNTRY_USER, String mODIFY_USER, String vERIFY_USER,
			Date eNTRY_TIME, Date mODIFY_TIME, Date vERIFY_TIME) {
		super();
		A1_PRODUCT = a1_PRODUCT;
		A2_PRODUCT = a2_PRODUCT;
		A3_PRODUCT = a3_PRODUCT;
		A4_PRODUCT = a4_PRODUCT;
		A5_PRODUCT = a5_PRODUCT;
		A6_PRODUCT = a6_PRODUCT;
		A7_PRODUCT = a7_PRODUCT;
		A8_PRODUCT = a8_PRODUCT;
		A9_PRODUCT = a9_PRODUCT;
		A10_PRODUCT = a10_PRODUCT;
		A11_PRODUCT = a11_PRODUCT;
		A12_PRODUCT = a12_PRODUCT;
		A13_PRODUCT = a13_PRODUCT;
		A14_PRODUCT = a14_PRODUCT;
		A15_PRODUCT = a15_PRODUCT;
		A16_PRODUCT = a16_PRODUCT;
		A17_PRODUCT = a17_PRODUCT;
		A18_PRODUCT = a18_PRODUCT;
		A19_PRODUCT = a19_PRODUCT;
		A20_PRODUCT = a20_PRODUCT;
		A21_PRODUCT = a21_PRODUCT;
		A22_PRODUCT = a22_PRODUCT;
		A23_PRODUCT = a23_PRODUCT;
		A24_PRODUCT = a24_PRODUCT;
		A25_PRODUCT = a25_PRODUCT;
		A26_PRODUCT = a26_PRODUCT;
		A27_PRODUCT = a27_PRODUCT;
		B1_PARALLEL_MONITORING = b1_PARALLEL_MONITORING;
		B2_PARALLEL_MONITORING = b2_PARALLEL_MONITORING;
		B3_PARALLEL_MONITORING = b3_PARALLEL_MONITORING;
		B4_PARALLEL_MONITORING = b4_PARALLEL_MONITORING;
		B5_PARALLEL_MONITORING = b5_PARALLEL_MONITORING;
		B6_PARALLEL_MONITORING = b6_PARALLEL_MONITORING;
		B7_PARALLEL_MONITORING = b7_PARALLEL_MONITORING;
		B8_PARALLEL_MONITORING = b8_PARALLEL_MONITORING;
		B9_PARALLEL_MONITORING = b9_PARALLEL_MONITORING;
		B10_PARALLEL_MONITORING = b10_PARALLEL_MONITORING;
		B11_PARALLEL_MONITORING = b11_PARALLEL_MONITORING;
		B12_PARALLEL_MONITORING = b12_PARALLEL_MONITORING;
		B13_PARALLEL_MONITORING = b13_PARALLEL_MONITORING;
		B14_PARALLEL_MONITORING = b14_PARALLEL_MONITORING;
		B15_PARALLEL_MONITORING = b15_PARALLEL_MONITORING;
		B16_PARALLEL_MONITORING = b16_PARALLEL_MONITORING;
		B17_PARALLEL_MONITORING = b17_PARALLEL_MONITORING;
		B18_PARALLEL_MONITORING = b18_PARALLEL_MONITORING;
		B19_PARALLEL_MONITORING = b19_PARALLEL_MONITORING;
		B20_PARALLEL_MONITORING = b20_PARALLEL_MONITORING;
		B21_PARALLEL_MONITORING = b21_PARALLEL_MONITORING;
		B22_PARALLEL_MONITORING = b22_PARALLEL_MONITORING;
		B23_PARALLEL_MONITORING = b23_PARALLEL_MONITORING;
		B24_PARALLEL_MONITORING = b24_PARALLEL_MONITORING;
		B25_PARALLEL_MONITORING = b25_PARALLEL_MONITORING;
		B26_PARALLEL_MONITORING = b26_PARALLEL_MONITORING;
		B27_PARALLEL_MONITORING = b27_PARALLEL_MONITORING;
		C1_AVERAGE_TIME = c1_AVERAGE_TIME;
		C2_AVERAGE_TIME = c2_AVERAGE_TIME;
		C3_AVERAGE_TIME = c3_AVERAGE_TIME;
		C4_AVERAGE_TIME = c4_AVERAGE_TIME;
		C5_AVERAGE_TIME = c5_AVERAGE_TIME;
		C6_AVERAGE_TIME = c6_AVERAGE_TIME;
		C7_AVERAGE_TIME = c7_AVERAGE_TIME;
		C8_AVERAGE_TIME = c8_AVERAGE_TIME;
		C9_AVERAGE_TIME = c9_AVERAGE_TIME;
		C10_AVERAGE_TIME = c10_AVERAGE_TIME;
		C11_AVERAGE_TIME = c11_AVERAGE_TIME;
		C12_AVERAGE_TIME = c12_AVERAGE_TIME;
		C13_AVERAGE_TIME = c13_AVERAGE_TIME;
		C14_AVERAGE_TIME = c14_AVERAGE_TIME;
		C15_AVERAGE_TIME = c15_AVERAGE_TIME;
		C16_AVERAGE_TIME = c16_AVERAGE_TIME;
		C17_AVERAGE_TIME = c17_AVERAGE_TIME;
		C18_AVERAGE_TIME = c18_AVERAGE_TIME;
		C19_AVERAGE_TIME = c19_AVERAGE_TIME;
		C20_AVERAGE_TIME = c20_AVERAGE_TIME;
		C21_AVERAGE_TIME = c21_AVERAGE_TIME;
		C22_AVERAGE_TIME = c22_AVERAGE_TIME;
		C23_AVERAGE_TIME = c23_AVERAGE_TIME;
		C24_AVERAGE_TIME = c24_AVERAGE_TIME;
		C25_AVERAGE_TIME = c25_AVERAGE_TIME;
		C26_AVERAGE_TIME = c26_AVERAGE_TIME;
		C27_AVERAGE_TIME = c27_AVERAGE_TIME;
		D1_MANUAL_MONITORING = d1_MANUAL_MONITORING;
		D2_MANUAL_MONITORING = d2_MANUAL_MONITORING;
		D3_MANUAL_MONITORING = d3_MANUAL_MONITORING;
		D4_MANUAL_MONITORING = d4_MANUAL_MONITORING;
		D5_MANUAL_MONITORING = d5_MANUAL_MONITORING;
		D6_MANUAL_MONITORING = d6_MANUAL_MONITORING;
		D7_MANUAL_MONITORING = d7_MANUAL_MONITORING;
		D8_MANUAL_MONITORING = d8_MANUAL_MONITORING;
		D9_MANUAL_MONITORING = d9_MANUAL_MONITORING;
		D10_MANUAL_MONITORING = d10_MANUAL_MONITORING;
		D11_MANUAL_MONITORING = d11_MANUAL_MONITORING;
		D12_MANUAL_MONITORING = d12_MANUAL_MONITORING;
		D13_MANUAL_MONITORING = d13_MANUAL_MONITORING;
		D14_MANUAL_MONITORING = d14_MANUAL_MONITORING;
		D15_MANUAL_MONITORING = d15_MANUAL_MONITORING;
		D16_MANUAL_MONITORING = d16_MANUAL_MONITORING;
		D17_MANUAL_MONITORING = d17_MANUAL_MONITORING;
		D18_MANUAL_MONITORING = d18_MANUAL_MONITORING;
		D19_MANUAL_MONITORING = d19_MANUAL_MONITORING;
		D20_MANUAL_MONITORING = d20_MANUAL_MONITORING;
		D21_MANUAL_MONITORING = d21_MANUAL_MONITORING;
		D22_MANUAL_MONITORING = d22_MANUAL_MONITORING;
		D23_MANUAL_MONITORING = d23_MANUAL_MONITORING;
		D24_MANUAL_MONITORING = d24_MANUAL_MONITORING;
		D25_MANUAL_MONITORING = d25_MANUAL_MONITORING;
		D26_MANUAL_MONITORING = d26_MANUAL_MONITORING;
		D27_MANUAL_MONITORING = d27_MANUAL_MONITORING;
		E1_HOUSE_OUTSOURCED = e1_HOUSE_OUTSOURCED;
		E2_HOUSE_OUTSOURCED = e2_HOUSE_OUTSOURCED;
		E3_HOUSE_OUTSOURCED = e3_HOUSE_OUTSOURCED;
		E4_HOUSE_OUTSOURCED = e4_HOUSE_OUTSOURCED;
		E5_HOUSE_OUTSOURCED = e5_HOUSE_OUTSOURCED;
		E6_HOUSE_OUTSOURCED = e6_HOUSE_OUTSOURCED;
		E7_HOUSE_OUTSOURCED = e7_HOUSE_OUTSOURCED;
		E8_HOUSE_OUTSOURCED = e8_HOUSE_OUTSOURCED;
		E9_HOUSE_OUTSOURCED = e9_HOUSE_OUTSOURCED;
		E10_HOUSE_OUTSOURCED = e10_HOUSE_OUTSOURCED;
		E11_HOUSE_OUTSOURCED = e11_HOUSE_OUTSOURCED;
		E12_HOUSE_OUTSOURCED = e12_HOUSE_OUTSOURCED;
		E13_HOUSE_OUTSOURCED = e13_HOUSE_OUTSOURCED;
		E14_HOUSE_OUTSOURCED = e14_HOUSE_OUTSOURCED;
		E15_HOUSE_OUTSOURCED = e15_HOUSE_OUTSOURCED;
		E16_HOUSE_OUTSOURCED = e16_HOUSE_OUTSOURCED;
		E17_HOUSE_OUTSOURCED = e17_HOUSE_OUTSOURCED;
		E18_HOUSE_OUTSOURCED = e18_HOUSE_OUTSOURCED;
		E19_HOUSE_OUTSOURCED = e19_HOUSE_OUTSOURCED;
		E20_HOUSE_OUTSOURCED = e20_HOUSE_OUTSOURCED;
		E21_HOUSE_OUTSOURCED = e21_HOUSE_OUTSOURCED;
		E22_HOUSE_OUTSOURCED = e22_HOUSE_OUTSOURCED;
		E23_HOUSE_OUTSOURCED = e23_HOUSE_OUTSOURCED;
		E24_HOUSE_OUTSOURCED = e24_HOUSE_OUTSOURCED;
		E25_HOUSE_OUTSOURCED = e25_HOUSE_OUTSOURCED;
		E26_HOUSE_OUTSOURCED = e26_HOUSE_OUTSOURCED;
		E27_HOUSE_OUTSOURCED = e27_HOUSE_OUTSOURCED;
		REPORT_CODE = rEPORT_CODE;
		REPORT_NAME = rEPORT_NAME;
		REPORT_DATE = rEPORT_DATE;
		REPORT_DUE_DATE = rEPORT_DUE_DATE;
		REP_SUBMIT_DATE = rEP_SUBMIT_DATE;
		REP_PERIOD_FROM = rEP_PERIOD_FROM;
		REP_PERIOD_TO = rEP_PERIOD_TO;
		REP_FREQ = rEP_FREQ;
		NIL_REPORT_FLG = nIL_REPORT_FLG;
		ARCH_FLG = aRCH_FLG;
		ENTITY_FLG = eNTITY_FLG;
		MODIFY_FLG = mODIFY_FLG;
		VERIFY_FLG = vERIFY_FLG;
		ENTRY_USER = eNTRY_USER;
		MODIFY_USER = mODIFY_USER;
		VERIFY_USER = vERIFY_USER;
		ENTRY_TIME = eNTRY_TIME;
		MODIFY_TIME = mODIFY_TIME;
		VERIFY_TIME = vERIFY_TIME;
	}
	public T17Report() {
		super();
		// TODO Auto-generated constructor stub
	}
	
	
}
