package com.bornfire.xbrl.entities.BRSS;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

@Entity
@Table(name="T19_OR_COURTCASES_AGAINST_BANK_TABLE")
public class T19ORReport {
	private String	A1_PRODUCT;
	private String	A2_PRODUCT;
	private BigDecimal	A2_NO_OF_COURT_CASES;
	private BigDecimal	A2_AMT_OF_PENALTIES_IN_FAVOR;
	private BigDecimal	A2_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A2_AMT_OF_PENALTIES_AGAINST_BANK;
	private BigDecimal	A2_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	private BigDecimal	A2_NO_OF_COURT_POLICIES;
	private String	A3_PRODUCT;
	private BigDecimal	A3_NO_OF_COURT_CASES;
	private BigDecimal	A3_AMT_OF_PENALTIES_IN_FAVOR;
	private BigDecimal	A3_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A3_AMT_OF_PENALTIES_AGAINST_BANK;
	private BigDecimal	A3_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	private BigDecimal	A3_NO_OF_COURT_POLICIES;
	private String	A4_PRODUCT;
	private BigDecimal	A4_NO_OF_COURT_CASES;
	private BigDecimal	A4_AMT_OF_PENALTIES_IN_FAVOR;
	private BigDecimal	A4_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A4_AMT_OF_PENALTIES_AGAINST_BANK;
	private BigDecimal	A4_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	private BigDecimal	A4_NO_OF_COURT_POLICIES;
	private String	A5_PRODUCT;
	private BigDecimal	A5_NO_OF_COURT_CASES;
	private BigDecimal	A5_AMT_OF_PENALTIES_IN_FAVOR;
	private BigDecimal	A5_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A5_AMT_OF_PENALTIES_AGAINST_BANK;
	private BigDecimal	A5_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	private BigDecimal	A5_NO_OF_COURT_POLICIES;
	private String	A6_PRODUCT;
	private BigDecimal	A6_NO_OF_COURT_CASES;
	private BigDecimal	A6_AMT_OF_PENALTIES_IN_FAVOR;
	private BigDecimal	A6_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A6_AMT_OF_PENALTIES_AGAINST_BANK;
	private BigDecimal	A6_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	private BigDecimal	A6_NO_OF_COURT_POLICIES;
	private String	A7_PRODUCT;
	private String	A8_PRODUCT;
	private BigDecimal	A8_NO_OF_COURT_CASES;
	private BigDecimal	A8_AMT_OF_PENALTIES_IN_FAVOR;
	private BigDecimal	A8_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A8_AMT_OF_PENALTIES_AGAINST_BANK;
	private BigDecimal	A8_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	private BigDecimal	A8_NO_OF_COURT_POLICIES;
	private String	A9_PRODUCT;
	private BigDecimal	A9_NO_OF_COURT_CASES;
	private BigDecimal	A9_AMT_OF_PENALTIES_IN_FAVOR;
	private BigDecimal	A9_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A9_AMT_OF_PENALTIES_AGAINST_BANK;
	private BigDecimal	A9_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	private BigDecimal	A9_NO_OF_COURT_POLICIES;
	private String	A10_PRODUCT;
	private BigDecimal	A10_NO_OF_COURT_CASES;
	private BigDecimal	A10_AMT_OF_PENALTIES_IN_FAVOR;
	private BigDecimal	A10_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A10_AMT_OF_PENALTIES_AGAINST_BANK;
	private BigDecimal	A10_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	private BigDecimal	A10_NO_OF_COURT_POLICIES;
	private String	A11_PRODUCT;
	private BigDecimal	A11_NO_OF_COURT_CASES;
	private BigDecimal	A11_AMT_OF_PENALTIES_IN_FAVOR;
	private BigDecimal	A11_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A11_AMT_OF_PENALTIES_AGAINST_BANK;
	private BigDecimal	A11_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	private BigDecimal	A11_NO_OF_COURT_POLICIES;
	private String	A12_PRODUCT;
	private BigDecimal	A12_NO_OF_COURT_CASES;
	private BigDecimal	A12_AMT_OF_PENALTIES_IN_FAVOR;
	private BigDecimal	A12_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A12_AMT_OF_PENALTIES_AGAINST_BANK;
	private BigDecimal	A12_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	private BigDecimal	A12_NO_OF_COURT_POLICIES;
	private String	A13_PRODUCT;
	private String	A14_PRODUCT;
	private BigDecimal	A14_NO_OF_COURT_CASES;
	private BigDecimal	A14_AMT_OF_PENALTIES_IN_FAVOR;
	private BigDecimal	A14_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A14_AMT_OF_PENALTIES_AGAINST_BANK;
	private BigDecimal	A14_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	private BigDecimal	A14_NO_OF_COURT_POLICIES;
	private String	A15_PRODUCT;
	private BigDecimal	A15_NO_OF_COURT_CASES;
	private BigDecimal	A15_AMT_OF_PENALTIES_IN_FAVOR;
	private BigDecimal	A15_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A15_AMT_OF_PENALTIES_AGAINST_BANK;
	private BigDecimal	A15_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	private BigDecimal	A15_NO_OF_COURT_POLICIES;
	private String	A16_PRODUCT;
	private BigDecimal	A16_NO_OF_COURT_CASES;
	private BigDecimal	A16_AMT_OF_PENALTIES_IN_FAVOR;
	private BigDecimal	A16_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A16_AMT_OF_PENALTIES_AGAINST_BANK;
	private BigDecimal	A16_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	private BigDecimal	A16_NO_OF_COURT_POLICIES;
	private String	A17_PRODUCT;
	private BigDecimal	A17_NO_OF_COURT_CASES;
	private BigDecimal	A17_AMT_OF_PENALTIES_IN_FAVOR;
	private BigDecimal	A17_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A17_AMT_OF_PENALTIES_AGAINST_BANK;
	private BigDecimal	A17_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	private BigDecimal	A17_NO_OF_COURT_POLICIES;
	private String	A18_PRODUCT;
	private BigDecimal	A18_NO_OF_COURT_CASES;
	private BigDecimal	A18_AMT_OF_PENALTIES_IN_FAVOR;
	private BigDecimal	A18_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A18_AMT_OF_PENALTIES_AGAINST_BANK;
	private BigDecimal	A18_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	private BigDecimal	A18_NO_OF_COURT_POLICIES;
	private String	A19_PRODUCT;
	private String	A20_PRODUCT;
	private BigDecimal	A20_NO_OF_COURT_CASES;
	private BigDecimal	A20_AMT_OF_PENALTIES_IN_FAVOR;
	private BigDecimal	A20_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A20_AMT_OF_PENALTIES_AGAINST_BANK;
	private BigDecimal	A20_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	private BigDecimal	A20_NO_OF_COURT_POLICIES;
	private String	A21_PRODUCT;
	private BigDecimal	A21_NO_OF_COURT_CASES;
	private BigDecimal	A21_AMT_OF_PENALTIES_IN_FAVOR;
	private BigDecimal	A21_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A21_AMT_OF_PENALTIES_AGAINST_BANK;
	private BigDecimal	A21_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	private BigDecimal	A21_NO_OF_COURT_POLICIES;
	private String	A22_PRODUCT;
	private BigDecimal	A22_NO_OF_COURT_CASES;
	private BigDecimal	A22_AMT_OF_PENALTIES_IN_FAVOR;
	private BigDecimal	A22_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A22_AMT_OF_PENALTIES_AGAINST_BANK;
	private BigDecimal	A22_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	private BigDecimal	A22_NO_OF_COURT_POLICIES;
	private String	A23_PRODUCT;
	private BigDecimal	A23_NO_OF_COURT_CASES;
	private BigDecimal	A23_AMT_OF_PENALTIES_IN_FAVOR;
	private BigDecimal	A23_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A23_AMT_OF_PENALTIES_AGAINST_BANK;
	private BigDecimal	A23_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	private BigDecimal	A23_NO_OF_COURT_POLICIES;
	private String	A24_PRODUCT;
	private BigDecimal	A24_NO_OF_COURT_CASES;
	private BigDecimal	A24_AMT_OF_PENALTIES_IN_FAVOR;
	private BigDecimal	A24_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A24_AMT_OF_PENALTIES_AGAINST_BANK;
	private BigDecimal	A24_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	private BigDecimal	A24_NO_OF_COURT_POLICIES;
	private String	A25_PRODUCT;
	private String	A26_PRODUCT;
	private BigDecimal	A26_NO_OF_COURT_CASES;
	private BigDecimal	A26_AMT_OF_PENALTIES_IN_FAVOR;
	private BigDecimal	A26_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A26_AMT_OF_PENALTIES_AGAINST_BANK;
	private BigDecimal	A26_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	private BigDecimal	A26_NO_OF_COURT_POLICIES;
	private String	A27_PRODUCT;
	private BigDecimal	A27_NO_OF_COURT_CASES;
	private BigDecimal	A27_AMT_OF_PENALTIES_IN_FAVOR;
	private BigDecimal	A27_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A27_AMT_OF_PENALTIES_AGAINST_BANK;
	private BigDecimal	A27_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	private BigDecimal	A27_NO_OF_COURT_POLICIES;
	private String	A28_PRODUCT;
	private BigDecimal	A28_NO_OF_COURT_CASES;
	private BigDecimal	A28_AMT_OF_PENALTIES_IN_FAVOR;
	private BigDecimal	A28_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A28_AMT_OF_PENALTIES_AGAINST_BANK;
	private BigDecimal	A28_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	private BigDecimal	A28_NO_OF_COURT_POLICIES;
	private String	A29_PRODUCT;
	private BigDecimal	A29_NO_OF_COURT_CASES;
	private BigDecimal	A29_AMT_OF_PENALTIES_IN_FAVOR;
	private BigDecimal	A29_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A29_AMT_OF_PENALTIES_AGAINST_BANK;
	private BigDecimal	A29_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	private BigDecimal	A29_NO_OF_COURT_POLICIES;
	private String	A30_PRODUCT;
	private BigDecimal	A30_NO_OF_COURT_CASES;
	private BigDecimal	A30_AMT_OF_PENALTIES_IN_FAVOR;
	private BigDecimal	A30_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A30_AMT_OF_PENALTIES_AGAINST_BANK;
	private BigDecimal	A30_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	private BigDecimal	A30_NO_OF_COURT_POLICIES;
	private String	A31_PRODUCT;
	private String	A32_PRODUCT;
	private BigDecimal	A32_NO_OF_COURT_CASES;
	private BigDecimal	A32_AMT_OF_PENALTIES_IN_FAVOR;
	private BigDecimal	A32_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A32_AMT_OF_PENALTIES_AGAINST_BANK;
	private BigDecimal	A32_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	private BigDecimal	A32_NO_OF_COURT_POLICIES;
	private String	A33_PRODUCT;
	private BigDecimal	A33_NO_OF_COURT_CASES;
	private BigDecimal	A33_AMT_OF_PENALTIES_IN_FAVOR;
	private BigDecimal	A33_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A33_AMT_OF_PENALTIES_AGAINST_BANK;
	private BigDecimal	A33_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	private BigDecimal	A33_NO_OF_COURT_POLICIES;
	private String	A34_PRODUCT;
	private BigDecimal	A34_NO_OF_COURT_CASES;
	private BigDecimal	A34_AMT_OF_PENALTIES_IN_FAVOR;
	private BigDecimal	A34_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A34_AMT_OF_PENALTIES_AGAINST_BANK;
	private BigDecimal	A34_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	private BigDecimal	A34_NO_OF_COURT_POLICIES;
	private String	A35_PRODUCT;
	private BigDecimal	A35_NO_OF_COURT_CASES;
	private BigDecimal	A35_AMT_OF_PENALTIES_IN_FAVOR;
	private BigDecimal	A35_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A35_AMT_OF_PENALTIES_AGAINST_BANK;
	private BigDecimal	A35_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	private BigDecimal	A35_NO_OF_COURT_POLICIES;
	private String	A36_PRODUCT;
	private BigDecimal	A36_NO_OF_COURT_CASES;
	private BigDecimal	A36_AMT_OF_PENALTIES_IN_FAVOR;
	private BigDecimal	A36_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A36_AMT_OF_PENALTIES_AGAINST_BANK;
	private BigDecimal	A36_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	private BigDecimal	A36_NO_OF_COURT_POLICIES;
	private String	REPORT_CODE;
	private String	REPORT_NAME;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	@Id
	private Date	REPORT_DATE;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	REPORT_DUE_DATE;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	REP_SUBMIT_DATE;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	REP_PERIOD_FROM;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	REP_PERIOD_TO;
	private String	REP_FREQ;
	private String	NIL_REPORT_FLG;
	private String	ARCH_FLG;
	private String	ENTITY_FLG;
	private String	DEL_FLG;
	private String	MODIFY_FLG;
	private String	ENTRY_USER;
	private String	MODIFY_USER;
	private String	VERIFY_USER;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	ENTRY_TIME;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	MODIFY_TIME;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	VERIFY_TIME;
	private String	QTR_FLG;
	public String getA1_PRODUCT() {
		return A1_PRODUCT;
	}
	public void setA1_PRODUCT(String a1_PRODUCT) {
		A1_PRODUCT = a1_PRODUCT;
	}
	public String getA2_PRODUCT() {
		return A2_PRODUCT;
	}
	public void setA2_PRODUCT(String a2_PRODUCT) {
		A2_PRODUCT = a2_PRODUCT;
	}
	public BigDecimal getA2_NO_OF_COURT_CASES() {
		return A2_NO_OF_COURT_CASES;
	}
	public void setA2_NO_OF_COURT_CASES(BigDecimal a2_NO_OF_COURT_CASES) {
		A2_NO_OF_COURT_CASES = a2_NO_OF_COURT_CASES;
	}
	public BigDecimal getA2_AMT_OF_PENALTIES_IN_FAVOR() {
		return A2_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public void setA2_AMT_OF_PENALTIES_IN_FAVOR(BigDecimal a2_AMT_OF_PENALTIES_IN_FAVOR) {
		A2_AMT_OF_PENALTIES_IN_FAVOR = a2_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public BigDecimal getA2_NO_OF_PENDING_COURT_CASES() {
		return A2_NO_OF_PENDING_COURT_CASES;
	}
	public void setA2_NO_OF_PENDING_COURT_CASES(BigDecimal a2_NO_OF_PENDING_COURT_CASES) {
		A2_NO_OF_PENDING_COURT_CASES = a2_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA2_AMT_OF_PENALTIES_AGAINST_BANK() {
		return A2_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public void setA2_AMT_OF_PENALTIES_AGAINST_BANK(BigDecimal a2_AMT_OF_PENALTIES_AGAINST_BANK) {
		A2_AMT_OF_PENALTIES_AGAINST_BANK = a2_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA2_AMT_OF_PREV_PENALTIES_AGAINST_BANK() {
		return A2_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public void setA2_AMT_OF_PREV_PENALTIES_AGAINST_BANK(BigDecimal a2_AMT_OF_PREV_PENALTIES_AGAINST_BANK) {
		A2_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a2_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA2_NO_OF_COURT_POLICIES() {
		return A2_NO_OF_COURT_POLICIES;
	}
	public void setA2_NO_OF_COURT_POLICIES(BigDecimal a2_NO_OF_COURT_POLICIES) {
		A2_NO_OF_COURT_POLICIES = a2_NO_OF_COURT_POLICIES;
	}
	public String getA3_PRODUCT() {
		return A3_PRODUCT;
	}
	public void setA3_PRODUCT(String a3_PRODUCT) {
		A3_PRODUCT = a3_PRODUCT;
	}
	public BigDecimal getA3_NO_OF_COURT_CASES() {
		return A3_NO_OF_COURT_CASES;
	}
	public void setA3_NO_OF_COURT_CASES(BigDecimal a3_NO_OF_COURT_CASES) {
		A3_NO_OF_COURT_CASES = a3_NO_OF_COURT_CASES;
	}
	public BigDecimal getA3_AMT_OF_PENALTIES_IN_FAVOR() {
		return A3_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public void setA3_AMT_OF_PENALTIES_IN_FAVOR(BigDecimal a3_AMT_OF_PENALTIES_IN_FAVOR) {
		A3_AMT_OF_PENALTIES_IN_FAVOR = a3_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public BigDecimal getA3_NO_OF_PENDING_COURT_CASES() {
		return A3_NO_OF_PENDING_COURT_CASES;
	}
	public void setA3_NO_OF_PENDING_COURT_CASES(BigDecimal a3_NO_OF_PENDING_COURT_CASES) {
		A3_NO_OF_PENDING_COURT_CASES = a3_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA3_AMT_OF_PENALTIES_AGAINST_BANK() {
		return A3_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public void setA3_AMT_OF_PENALTIES_AGAINST_BANK(BigDecimal a3_AMT_OF_PENALTIES_AGAINST_BANK) {
		A3_AMT_OF_PENALTIES_AGAINST_BANK = a3_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA3_AMT_OF_PREV_PENALTIES_AGAINST_BANK() {
		return A3_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public void setA3_AMT_OF_PREV_PENALTIES_AGAINST_BANK(BigDecimal a3_AMT_OF_PREV_PENALTIES_AGAINST_BANK) {
		A3_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a3_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA3_NO_OF_COURT_POLICIES() {
		return A3_NO_OF_COURT_POLICIES;
	}
	public void setA3_NO_OF_COURT_POLICIES(BigDecimal a3_NO_OF_COURT_POLICIES) {
		A3_NO_OF_COURT_POLICIES = a3_NO_OF_COURT_POLICIES;
	}
	public String getA4_PRODUCT() {
		return A4_PRODUCT;
	}
	public void setA4_PRODUCT(String a4_PRODUCT) {
		A4_PRODUCT = a4_PRODUCT;
	}
	public BigDecimal getA4_NO_OF_COURT_CASES() {
		return A4_NO_OF_COURT_CASES;
	}
	public void setA4_NO_OF_COURT_CASES(BigDecimal a4_NO_OF_COURT_CASES) {
		A4_NO_OF_COURT_CASES = a4_NO_OF_COURT_CASES;
	}
	public BigDecimal getA4_AMT_OF_PENALTIES_IN_FAVOR() {
		return A4_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public void setA4_AMT_OF_PENALTIES_IN_FAVOR(BigDecimal a4_AMT_OF_PENALTIES_IN_FAVOR) {
		A4_AMT_OF_PENALTIES_IN_FAVOR = a4_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public BigDecimal getA4_NO_OF_PENDING_COURT_CASES() {
		return A4_NO_OF_PENDING_COURT_CASES;
	}
	public void setA4_NO_OF_PENDING_COURT_CASES(BigDecimal a4_NO_OF_PENDING_COURT_CASES) {
		A4_NO_OF_PENDING_COURT_CASES = a4_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA4_AMT_OF_PENALTIES_AGAINST_BANK() {
		return A4_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public void setA4_AMT_OF_PENALTIES_AGAINST_BANK(BigDecimal a4_AMT_OF_PENALTIES_AGAINST_BANK) {
		A4_AMT_OF_PENALTIES_AGAINST_BANK = a4_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA4_AMT_OF_PREV_PENALTIES_AGAINST_BANK() {
		return A4_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public void setA4_AMT_OF_PREV_PENALTIES_AGAINST_BANK(BigDecimal a4_AMT_OF_PREV_PENALTIES_AGAINST_BANK) {
		A4_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a4_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA4_NO_OF_COURT_POLICIES() {
		return A4_NO_OF_COURT_POLICIES;
	}
	public void setA4_NO_OF_COURT_POLICIES(BigDecimal a4_NO_OF_COURT_POLICIES) {
		A4_NO_OF_COURT_POLICIES = a4_NO_OF_COURT_POLICIES;
	}
	public String getA5_PRODUCT() {
		return A5_PRODUCT;
	}
	public void setA5_PRODUCT(String a5_PRODUCT) {
		A5_PRODUCT = a5_PRODUCT;
	}
	public BigDecimal getA5_NO_OF_COURT_CASES() {
		return A5_NO_OF_COURT_CASES;
	}
	public void setA5_NO_OF_COURT_CASES(BigDecimal a5_NO_OF_COURT_CASES) {
		A5_NO_OF_COURT_CASES = a5_NO_OF_COURT_CASES;
	}
	public BigDecimal getA5_AMT_OF_PENALTIES_IN_FAVOR() {
		return A5_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public void setA5_AMT_OF_PENALTIES_IN_FAVOR(BigDecimal a5_AMT_OF_PENALTIES_IN_FAVOR) {
		A5_AMT_OF_PENALTIES_IN_FAVOR = a5_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public BigDecimal getA5_NO_OF_PENDING_COURT_CASES() {
		return A5_NO_OF_PENDING_COURT_CASES;
	}
	public void setA5_NO_OF_PENDING_COURT_CASES(BigDecimal a5_NO_OF_PENDING_COURT_CASES) {
		A5_NO_OF_PENDING_COURT_CASES = a5_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA5_AMT_OF_PENALTIES_AGAINST_BANK() {
		return A5_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public void setA5_AMT_OF_PENALTIES_AGAINST_BANK(BigDecimal a5_AMT_OF_PENALTIES_AGAINST_BANK) {
		A5_AMT_OF_PENALTIES_AGAINST_BANK = a5_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA5_AMT_OF_PREV_PENALTIES_AGAINST_BANK() {
		return A5_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public void setA5_AMT_OF_PREV_PENALTIES_AGAINST_BANK(BigDecimal a5_AMT_OF_PREV_PENALTIES_AGAINST_BANK) {
		A5_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a5_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA5_NO_OF_COURT_POLICIES() {
		return A5_NO_OF_COURT_POLICIES;
	}
	public void setA5_NO_OF_COURT_POLICIES(BigDecimal a5_NO_OF_COURT_POLICIES) {
		A5_NO_OF_COURT_POLICIES = a5_NO_OF_COURT_POLICIES;
	}
	public String getA6_PRODUCT() {
		return A6_PRODUCT;
	}
	public void setA6_PRODUCT(String a6_PRODUCT) {
		A6_PRODUCT = a6_PRODUCT;
	}
	public BigDecimal getA6_NO_OF_COURT_CASES() {
		return A6_NO_OF_COURT_CASES;
	}
	public void setA6_NO_OF_COURT_CASES(BigDecimal a6_NO_OF_COURT_CASES) {
		A6_NO_OF_COURT_CASES = a6_NO_OF_COURT_CASES;
	}
	public BigDecimal getA6_AMT_OF_PENALTIES_IN_FAVOR() {
		return A6_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public void setA6_AMT_OF_PENALTIES_IN_FAVOR(BigDecimal a6_AMT_OF_PENALTIES_IN_FAVOR) {
		A6_AMT_OF_PENALTIES_IN_FAVOR = a6_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public BigDecimal getA6_NO_OF_PENDING_COURT_CASES() {
		return A6_NO_OF_PENDING_COURT_CASES;
	}
	public void setA6_NO_OF_PENDING_COURT_CASES(BigDecimal a6_NO_OF_PENDING_COURT_CASES) {
		A6_NO_OF_PENDING_COURT_CASES = a6_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA6_AMT_OF_PENALTIES_AGAINST_BANK() {
		return A6_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public void setA6_AMT_OF_PENALTIES_AGAINST_BANK(BigDecimal a6_AMT_OF_PENALTIES_AGAINST_BANK) {
		A6_AMT_OF_PENALTIES_AGAINST_BANK = a6_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA6_AMT_OF_PREV_PENALTIES_AGAINST_BANK() {
		return A6_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public void setA6_AMT_OF_PREV_PENALTIES_AGAINST_BANK(BigDecimal a6_AMT_OF_PREV_PENALTIES_AGAINST_BANK) {
		A6_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a6_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA6_NO_OF_COURT_POLICIES() {
		return A6_NO_OF_COURT_POLICIES;
	}
	public void setA6_NO_OF_COURT_POLICIES(BigDecimal a6_NO_OF_COURT_POLICIES) {
		A6_NO_OF_COURT_POLICIES = a6_NO_OF_COURT_POLICIES;
	}
	public String getA7_PRODUCT() {
		return A7_PRODUCT;
	}
	public void setA7_PRODUCT(String a7_PRODUCT) {
		A7_PRODUCT = a7_PRODUCT;
	}
	public String getA8_PRODUCT() {
		return A8_PRODUCT;
	}
	public void setA8_PRODUCT(String a8_PRODUCT) {
		A8_PRODUCT = a8_PRODUCT;
	}
	public BigDecimal getA8_NO_OF_COURT_CASES() {
		return A8_NO_OF_COURT_CASES;
	}
	public void setA8_NO_OF_COURT_CASES(BigDecimal a8_NO_OF_COURT_CASES) {
		A8_NO_OF_COURT_CASES = a8_NO_OF_COURT_CASES;
	}
	public BigDecimal getA8_AMT_OF_PENALTIES_IN_FAVOR() {
		return A8_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public void setA8_AMT_OF_PENALTIES_IN_FAVOR(BigDecimal a8_AMT_OF_PENALTIES_IN_FAVOR) {
		A8_AMT_OF_PENALTIES_IN_FAVOR = a8_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public BigDecimal getA8_NO_OF_PENDING_COURT_CASES() {
		return A8_NO_OF_PENDING_COURT_CASES;
	}
	public void setA8_NO_OF_PENDING_COURT_CASES(BigDecimal a8_NO_OF_PENDING_COURT_CASES) {
		A8_NO_OF_PENDING_COURT_CASES = a8_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA8_AMT_OF_PENALTIES_AGAINST_BANK() {
		return A8_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public void setA8_AMT_OF_PENALTIES_AGAINST_BANK(BigDecimal a8_AMT_OF_PENALTIES_AGAINST_BANK) {
		A8_AMT_OF_PENALTIES_AGAINST_BANK = a8_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA8_AMT_OF_PREV_PENALTIES_AGAINST_BANK() {
		return A8_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public void setA8_AMT_OF_PREV_PENALTIES_AGAINST_BANK(BigDecimal a8_AMT_OF_PREV_PENALTIES_AGAINST_BANK) {
		A8_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a8_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA8_NO_OF_COURT_POLICIES() {
		return A8_NO_OF_COURT_POLICIES;
	}
	public void setA8_NO_OF_COURT_POLICIES(BigDecimal a8_NO_OF_COURT_POLICIES) {
		A8_NO_OF_COURT_POLICIES = a8_NO_OF_COURT_POLICIES;
	}
	public String getA9_PRODUCT() {
		return A9_PRODUCT;
	}
	public void setA9_PRODUCT(String a9_PRODUCT) {
		A9_PRODUCT = a9_PRODUCT;
	}
	public BigDecimal getA9_NO_OF_COURT_CASES() {
		return A9_NO_OF_COURT_CASES;
	}
	public void setA9_NO_OF_COURT_CASES(BigDecimal a9_NO_OF_COURT_CASES) {
		A9_NO_OF_COURT_CASES = a9_NO_OF_COURT_CASES;
	}
	public BigDecimal getA9_AMT_OF_PENALTIES_IN_FAVOR() {
		return A9_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public void setA9_AMT_OF_PENALTIES_IN_FAVOR(BigDecimal a9_AMT_OF_PENALTIES_IN_FAVOR) {
		A9_AMT_OF_PENALTIES_IN_FAVOR = a9_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public BigDecimal getA9_NO_OF_PENDING_COURT_CASES() {
		return A9_NO_OF_PENDING_COURT_CASES;
	}
	public void setA9_NO_OF_PENDING_COURT_CASES(BigDecimal a9_NO_OF_PENDING_COURT_CASES) {
		A9_NO_OF_PENDING_COURT_CASES = a9_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA9_AMT_OF_PENALTIES_AGAINST_BANK() {
		return A9_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public void setA9_AMT_OF_PENALTIES_AGAINST_BANK(BigDecimal a9_AMT_OF_PENALTIES_AGAINST_BANK) {
		A9_AMT_OF_PENALTIES_AGAINST_BANK = a9_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA9_AMT_OF_PREV_PENALTIES_AGAINST_BANK() {
		return A9_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public void setA9_AMT_OF_PREV_PENALTIES_AGAINST_BANK(BigDecimal a9_AMT_OF_PREV_PENALTIES_AGAINST_BANK) {
		A9_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a9_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA9_NO_OF_COURT_POLICIES() {
		return A9_NO_OF_COURT_POLICIES;
	}
	public void setA9_NO_OF_COURT_POLICIES(BigDecimal a9_NO_OF_COURT_POLICIES) {
		A9_NO_OF_COURT_POLICIES = a9_NO_OF_COURT_POLICIES;
	}
	public String getA10_PRODUCT() {
		return A10_PRODUCT;
	}
	public void setA10_PRODUCT(String a10_PRODUCT) {
		A10_PRODUCT = a10_PRODUCT;
	}
	public BigDecimal getA10_NO_OF_COURT_CASES() {
		return A10_NO_OF_COURT_CASES;
	}
	public void setA10_NO_OF_COURT_CASES(BigDecimal a10_NO_OF_COURT_CASES) {
		A10_NO_OF_COURT_CASES = a10_NO_OF_COURT_CASES;
	}
	public BigDecimal getA10_AMT_OF_PENALTIES_IN_FAVOR() {
		return A10_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public void setA10_AMT_OF_PENALTIES_IN_FAVOR(BigDecimal a10_AMT_OF_PENALTIES_IN_FAVOR) {
		A10_AMT_OF_PENALTIES_IN_FAVOR = a10_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public BigDecimal getA10_NO_OF_PENDING_COURT_CASES() {
		return A10_NO_OF_PENDING_COURT_CASES;
	}
	public void setA10_NO_OF_PENDING_COURT_CASES(BigDecimal a10_NO_OF_PENDING_COURT_CASES) {
		A10_NO_OF_PENDING_COURT_CASES = a10_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA10_AMT_OF_PENALTIES_AGAINST_BANK() {
		return A10_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public void setA10_AMT_OF_PENALTIES_AGAINST_BANK(BigDecimal a10_AMT_OF_PENALTIES_AGAINST_BANK) {
		A10_AMT_OF_PENALTIES_AGAINST_BANK = a10_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA10_AMT_OF_PREV_PENALTIES_AGAINST_BANK() {
		return A10_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public void setA10_AMT_OF_PREV_PENALTIES_AGAINST_BANK(BigDecimal a10_AMT_OF_PREV_PENALTIES_AGAINST_BANK) {
		A10_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a10_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA10_NO_OF_COURT_POLICIES() {
		return A10_NO_OF_COURT_POLICIES;
	}
	public void setA10_NO_OF_COURT_POLICIES(BigDecimal a10_NO_OF_COURT_POLICIES) {
		A10_NO_OF_COURT_POLICIES = a10_NO_OF_COURT_POLICIES;
	}
	public String getA11_PRODUCT() {
		return A11_PRODUCT;
	}
	public void setA11_PRODUCT(String a11_PRODUCT) {
		A11_PRODUCT = a11_PRODUCT;
	}
	public BigDecimal getA11_NO_OF_COURT_CASES() {
		return A11_NO_OF_COURT_CASES;
	}
	public void setA11_NO_OF_COURT_CASES(BigDecimal a11_NO_OF_COURT_CASES) {
		A11_NO_OF_COURT_CASES = a11_NO_OF_COURT_CASES;
	}
	public BigDecimal getA11_AMT_OF_PENALTIES_IN_FAVOR() {
		return A11_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public void setA11_AMT_OF_PENALTIES_IN_FAVOR(BigDecimal a11_AMT_OF_PENALTIES_IN_FAVOR) {
		A11_AMT_OF_PENALTIES_IN_FAVOR = a11_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public BigDecimal getA11_NO_OF_PENDING_COURT_CASES() {
		return A11_NO_OF_PENDING_COURT_CASES;
	}
	public void setA11_NO_OF_PENDING_COURT_CASES(BigDecimal a11_NO_OF_PENDING_COURT_CASES) {
		A11_NO_OF_PENDING_COURT_CASES = a11_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA11_AMT_OF_PENALTIES_AGAINST_BANK() {
		return A11_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public void setA11_AMT_OF_PENALTIES_AGAINST_BANK(BigDecimal a11_AMT_OF_PENALTIES_AGAINST_BANK) {
		A11_AMT_OF_PENALTIES_AGAINST_BANK = a11_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA11_AMT_OF_PREV_PENALTIES_AGAINST_BANK() {
		return A11_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public void setA11_AMT_OF_PREV_PENALTIES_AGAINST_BANK(BigDecimal a11_AMT_OF_PREV_PENALTIES_AGAINST_BANK) {
		A11_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a11_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA11_NO_OF_COURT_POLICIES() {
		return A11_NO_OF_COURT_POLICIES;
	}
	public void setA11_NO_OF_COURT_POLICIES(BigDecimal a11_NO_OF_COURT_POLICIES) {
		A11_NO_OF_COURT_POLICIES = a11_NO_OF_COURT_POLICIES;
	}
	public String getA12_PRODUCT() {
		return A12_PRODUCT;
	}
	public void setA12_PRODUCT(String a12_PRODUCT) {
		A12_PRODUCT = a12_PRODUCT;
	}
	public BigDecimal getA12_NO_OF_COURT_CASES() {
		return A12_NO_OF_COURT_CASES;
	}
	public void setA12_NO_OF_COURT_CASES(BigDecimal a12_NO_OF_COURT_CASES) {
		A12_NO_OF_COURT_CASES = a12_NO_OF_COURT_CASES;
	}
	public BigDecimal getA12_AMT_OF_PENALTIES_IN_FAVOR() {
		return A12_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public void setA12_AMT_OF_PENALTIES_IN_FAVOR(BigDecimal a12_AMT_OF_PENALTIES_IN_FAVOR) {
		A12_AMT_OF_PENALTIES_IN_FAVOR = a12_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public BigDecimal getA12_NO_OF_PENDING_COURT_CASES() {
		return A12_NO_OF_PENDING_COURT_CASES;
	}
	public void setA12_NO_OF_PENDING_COURT_CASES(BigDecimal a12_NO_OF_PENDING_COURT_CASES) {
		A12_NO_OF_PENDING_COURT_CASES = a12_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA12_AMT_OF_PENALTIES_AGAINST_BANK() {
		return A12_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public void setA12_AMT_OF_PENALTIES_AGAINST_BANK(BigDecimal a12_AMT_OF_PENALTIES_AGAINST_BANK) {
		A12_AMT_OF_PENALTIES_AGAINST_BANK = a12_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA12_AMT_OF_PREV_PENALTIES_AGAINST_BANK() {
		return A12_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public void setA12_AMT_OF_PREV_PENALTIES_AGAINST_BANK(BigDecimal a12_AMT_OF_PREV_PENALTIES_AGAINST_BANK) {
		A12_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a12_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA12_NO_OF_COURT_POLICIES() {
		return A12_NO_OF_COURT_POLICIES;
	}
	public void setA12_NO_OF_COURT_POLICIES(BigDecimal a12_NO_OF_COURT_POLICIES) {
		A12_NO_OF_COURT_POLICIES = a12_NO_OF_COURT_POLICIES;
	}
	public String getA13_PRODUCT() {
		return A13_PRODUCT;
	}
	public void setA13_PRODUCT(String a13_PRODUCT) {
		A13_PRODUCT = a13_PRODUCT;
	}
	public String getA14_PRODUCT() {
		return A14_PRODUCT;
	}
	public void setA14_PRODUCT(String a14_PRODUCT) {
		A14_PRODUCT = a14_PRODUCT;
	}
	public BigDecimal getA14_NO_OF_COURT_CASES() {
		return A14_NO_OF_COURT_CASES;
	}
	public void setA14_NO_OF_COURT_CASES(BigDecimal a14_NO_OF_COURT_CASES) {
		A14_NO_OF_COURT_CASES = a14_NO_OF_COURT_CASES;
	}
	public BigDecimal getA14_AMT_OF_PENALTIES_IN_FAVOR() {
		return A14_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public void setA14_AMT_OF_PENALTIES_IN_FAVOR(BigDecimal a14_AMT_OF_PENALTIES_IN_FAVOR) {
		A14_AMT_OF_PENALTIES_IN_FAVOR = a14_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public BigDecimal getA14_NO_OF_PENDING_COURT_CASES() {
		return A14_NO_OF_PENDING_COURT_CASES;
	}
	public void setA14_NO_OF_PENDING_COURT_CASES(BigDecimal a14_NO_OF_PENDING_COURT_CASES) {
		A14_NO_OF_PENDING_COURT_CASES = a14_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA14_AMT_OF_PENALTIES_AGAINST_BANK() {
		return A14_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public void setA14_AMT_OF_PENALTIES_AGAINST_BANK(BigDecimal a14_AMT_OF_PENALTIES_AGAINST_BANK) {
		A14_AMT_OF_PENALTIES_AGAINST_BANK = a14_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA14_AMT_OF_PREV_PENALTIES_AGAINST_BANK() {
		return A14_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public void setA14_AMT_OF_PREV_PENALTIES_AGAINST_BANK(BigDecimal a14_AMT_OF_PREV_PENALTIES_AGAINST_BANK) {
		A14_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a14_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA14_NO_OF_COURT_POLICIES() {
		return A14_NO_OF_COURT_POLICIES;
	}
	public void setA14_NO_OF_COURT_POLICIES(BigDecimal a14_NO_OF_COURT_POLICIES) {
		A14_NO_OF_COURT_POLICIES = a14_NO_OF_COURT_POLICIES;
	}
	public String getA15_PRODUCT() {
		return A15_PRODUCT;
	}
	public void setA15_PRODUCT(String a15_PRODUCT) {
		A15_PRODUCT = a15_PRODUCT;
	}
	public BigDecimal getA15_NO_OF_COURT_CASES() {
		return A15_NO_OF_COURT_CASES;
	}
	public void setA15_NO_OF_COURT_CASES(BigDecimal a15_NO_OF_COURT_CASES) {
		A15_NO_OF_COURT_CASES = a15_NO_OF_COURT_CASES;
	}
	public BigDecimal getA15_AMT_OF_PENALTIES_IN_FAVOR() {
		return A15_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public void setA15_AMT_OF_PENALTIES_IN_FAVOR(BigDecimal a15_AMT_OF_PENALTIES_IN_FAVOR) {
		A15_AMT_OF_PENALTIES_IN_FAVOR = a15_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public BigDecimal getA15_NO_OF_PENDING_COURT_CASES() {
		return A15_NO_OF_PENDING_COURT_CASES;
	}
	public void setA15_NO_OF_PENDING_COURT_CASES(BigDecimal a15_NO_OF_PENDING_COURT_CASES) {
		A15_NO_OF_PENDING_COURT_CASES = a15_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA15_AMT_OF_PENALTIES_AGAINST_BANK() {
		return A15_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public void setA15_AMT_OF_PENALTIES_AGAINST_BANK(BigDecimal a15_AMT_OF_PENALTIES_AGAINST_BANK) {
		A15_AMT_OF_PENALTIES_AGAINST_BANK = a15_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA15_AMT_OF_PREV_PENALTIES_AGAINST_BANK() {
		return A15_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public void setA15_AMT_OF_PREV_PENALTIES_AGAINST_BANK(BigDecimal a15_AMT_OF_PREV_PENALTIES_AGAINST_BANK) {
		A15_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a15_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA15_NO_OF_COURT_POLICIES() {
		return A15_NO_OF_COURT_POLICIES;
	}
	public void setA15_NO_OF_COURT_POLICIES(BigDecimal a15_NO_OF_COURT_POLICIES) {
		A15_NO_OF_COURT_POLICIES = a15_NO_OF_COURT_POLICIES;
	}
	public String getA16_PRODUCT() {
		return A16_PRODUCT;
	}
	public void setA16_PRODUCT(String a16_PRODUCT) {
		A16_PRODUCT = a16_PRODUCT;
	}
	public BigDecimal getA16_NO_OF_COURT_CASES() {
		return A16_NO_OF_COURT_CASES;
	}
	public void setA16_NO_OF_COURT_CASES(BigDecimal a16_NO_OF_COURT_CASES) {
		A16_NO_OF_COURT_CASES = a16_NO_OF_COURT_CASES;
	}
	public BigDecimal getA16_AMT_OF_PENALTIES_IN_FAVOR() {
		return A16_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public void setA16_AMT_OF_PENALTIES_IN_FAVOR(BigDecimal a16_AMT_OF_PENALTIES_IN_FAVOR) {
		A16_AMT_OF_PENALTIES_IN_FAVOR = a16_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public BigDecimal getA16_NO_OF_PENDING_COURT_CASES() {
		return A16_NO_OF_PENDING_COURT_CASES;
	}
	public void setA16_NO_OF_PENDING_COURT_CASES(BigDecimal a16_NO_OF_PENDING_COURT_CASES) {
		A16_NO_OF_PENDING_COURT_CASES = a16_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA16_AMT_OF_PENALTIES_AGAINST_BANK() {
		return A16_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public void setA16_AMT_OF_PENALTIES_AGAINST_BANK(BigDecimal a16_AMT_OF_PENALTIES_AGAINST_BANK) {
		A16_AMT_OF_PENALTIES_AGAINST_BANK = a16_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA16_AMT_OF_PREV_PENALTIES_AGAINST_BANK() {
		return A16_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public void setA16_AMT_OF_PREV_PENALTIES_AGAINST_BANK(BigDecimal a16_AMT_OF_PREV_PENALTIES_AGAINST_BANK) {
		A16_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a16_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA16_NO_OF_COURT_POLICIES() {
		return A16_NO_OF_COURT_POLICIES;
	}
	public void setA16_NO_OF_COURT_POLICIES(BigDecimal a16_NO_OF_COURT_POLICIES) {
		A16_NO_OF_COURT_POLICIES = a16_NO_OF_COURT_POLICIES;
	}
	public String getA17_PRODUCT() {
		return A17_PRODUCT;
	}
	public void setA17_PRODUCT(String a17_PRODUCT) {
		A17_PRODUCT = a17_PRODUCT;
	}
	public BigDecimal getA17_NO_OF_COURT_CASES() {
		return A17_NO_OF_COURT_CASES;
	}
	public void setA17_NO_OF_COURT_CASES(BigDecimal a17_NO_OF_COURT_CASES) {
		A17_NO_OF_COURT_CASES = a17_NO_OF_COURT_CASES;
	}
	public BigDecimal getA17_AMT_OF_PENALTIES_IN_FAVOR() {
		return A17_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public void setA17_AMT_OF_PENALTIES_IN_FAVOR(BigDecimal a17_AMT_OF_PENALTIES_IN_FAVOR) {
		A17_AMT_OF_PENALTIES_IN_FAVOR = a17_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public BigDecimal getA17_NO_OF_PENDING_COURT_CASES() {
		return A17_NO_OF_PENDING_COURT_CASES;
	}
	public void setA17_NO_OF_PENDING_COURT_CASES(BigDecimal a17_NO_OF_PENDING_COURT_CASES) {
		A17_NO_OF_PENDING_COURT_CASES = a17_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA17_AMT_OF_PENALTIES_AGAINST_BANK() {
		return A17_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public void setA17_AMT_OF_PENALTIES_AGAINST_BANK(BigDecimal a17_AMT_OF_PENALTIES_AGAINST_BANK) {
		A17_AMT_OF_PENALTIES_AGAINST_BANK = a17_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA17_AMT_OF_PREV_PENALTIES_AGAINST_BANK() {
		return A17_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public void setA17_AMT_OF_PREV_PENALTIES_AGAINST_BANK(BigDecimal a17_AMT_OF_PREV_PENALTIES_AGAINST_BANK) {
		A17_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a17_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA17_NO_OF_COURT_POLICIES() {
		return A17_NO_OF_COURT_POLICIES;
	}
	public void setA17_NO_OF_COURT_POLICIES(BigDecimal a17_NO_OF_COURT_POLICIES) {
		A17_NO_OF_COURT_POLICIES = a17_NO_OF_COURT_POLICIES;
	}
	public String getA18_PRODUCT() {
		return A18_PRODUCT;
	}
	public void setA18_PRODUCT(String a18_PRODUCT) {
		A18_PRODUCT = a18_PRODUCT;
	}
	public BigDecimal getA18_NO_OF_COURT_CASES() {
		return A18_NO_OF_COURT_CASES;
	}
	public void setA18_NO_OF_COURT_CASES(BigDecimal a18_NO_OF_COURT_CASES) {
		A18_NO_OF_COURT_CASES = a18_NO_OF_COURT_CASES;
	}
	public BigDecimal getA18_AMT_OF_PENALTIES_IN_FAVOR() {
		return A18_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public void setA18_AMT_OF_PENALTIES_IN_FAVOR(BigDecimal a18_AMT_OF_PENALTIES_IN_FAVOR) {
		A18_AMT_OF_PENALTIES_IN_FAVOR = a18_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public BigDecimal getA18_NO_OF_PENDING_COURT_CASES() {
		return A18_NO_OF_PENDING_COURT_CASES;
	}
	public void setA18_NO_OF_PENDING_COURT_CASES(BigDecimal a18_NO_OF_PENDING_COURT_CASES) {
		A18_NO_OF_PENDING_COURT_CASES = a18_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA18_AMT_OF_PENALTIES_AGAINST_BANK() {
		return A18_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public void setA18_AMT_OF_PENALTIES_AGAINST_BANK(BigDecimal a18_AMT_OF_PENALTIES_AGAINST_BANK) {
		A18_AMT_OF_PENALTIES_AGAINST_BANK = a18_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA18_AMT_OF_PREV_PENALTIES_AGAINST_BANK() {
		return A18_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public void setA18_AMT_OF_PREV_PENALTIES_AGAINST_BANK(BigDecimal a18_AMT_OF_PREV_PENALTIES_AGAINST_BANK) {
		A18_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a18_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA18_NO_OF_COURT_POLICIES() {
		return A18_NO_OF_COURT_POLICIES;
	}
	public void setA18_NO_OF_COURT_POLICIES(BigDecimal a18_NO_OF_COURT_POLICIES) {
		A18_NO_OF_COURT_POLICIES = a18_NO_OF_COURT_POLICIES;
	}
	public String getA19_PRODUCT() {
		return A19_PRODUCT;
	}
	public void setA19_PRODUCT(String a19_PRODUCT) {
		A19_PRODUCT = a19_PRODUCT;
	}
	public String getA20_PRODUCT() {
		return A20_PRODUCT;
	}
	public void setA20_PRODUCT(String a20_PRODUCT) {
		A20_PRODUCT = a20_PRODUCT;
	}
	public BigDecimal getA20_NO_OF_COURT_CASES() {
		return A20_NO_OF_COURT_CASES;
	}
	public void setA20_NO_OF_COURT_CASES(BigDecimal a20_NO_OF_COURT_CASES) {
		A20_NO_OF_COURT_CASES = a20_NO_OF_COURT_CASES;
	}
	public BigDecimal getA20_AMT_OF_PENALTIES_IN_FAVOR() {
		return A20_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public void setA20_AMT_OF_PENALTIES_IN_FAVOR(BigDecimal a20_AMT_OF_PENALTIES_IN_FAVOR) {
		A20_AMT_OF_PENALTIES_IN_FAVOR = a20_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public BigDecimal getA20_NO_OF_PENDING_COURT_CASES() {
		return A20_NO_OF_PENDING_COURT_CASES;
	}
	public void setA20_NO_OF_PENDING_COURT_CASES(BigDecimal a20_NO_OF_PENDING_COURT_CASES) {
		A20_NO_OF_PENDING_COURT_CASES = a20_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA20_AMT_OF_PENALTIES_AGAINST_BANK() {
		return A20_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public void setA20_AMT_OF_PENALTIES_AGAINST_BANK(BigDecimal a20_AMT_OF_PENALTIES_AGAINST_BANK) {
		A20_AMT_OF_PENALTIES_AGAINST_BANK = a20_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA20_AMT_OF_PREV_PENALTIES_AGAINST_BANK() {
		return A20_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public void setA20_AMT_OF_PREV_PENALTIES_AGAINST_BANK(BigDecimal a20_AMT_OF_PREV_PENALTIES_AGAINST_BANK) {
		A20_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a20_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA20_NO_OF_COURT_POLICIES() {
		return A20_NO_OF_COURT_POLICIES;
	}
	public void setA20_NO_OF_COURT_POLICIES(BigDecimal a20_NO_OF_COURT_POLICIES) {
		A20_NO_OF_COURT_POLICIES = a20_NO_OF_COURT_POLICIES;
	}
	public String getA21_PRODUCT() {
		return A21_PRODUCT;
	}
	public void setA21_PRODUCT(String a21_PRODUCT) {
		A21_PRODUCT = a21_PRODUCT;
	}
	public BigDecimal getA21_NO_OF_COURT_CASES() {
		return A21_NO_OF_COURT_CASES;
	}
	public void setA21_NO_OF_COURT_CASES(BigDecimal a21_NO_OF_COURT_CASES) {
		A21_NO_OF_COURT_CASES = a21_NO_OF_COURT_CASES;
	}
	public BigDecimal getA21_AMT_OF_PENALTIES_IN_FAVOR() {
		return A21_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public void setA21_AMT_OF_PENALTIES_IN_FAVOR(BigDecimal a21_AMT_OF_PENALTIES_IN_FAVOR) {
		A21_AMT_OF_PENALTIES_IN_FAVOR = a21_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public BigDecimal getA21_NO_OF_PENDING_COURT_CASES() {
		return A21_NO_OF_PENDING_COURT_CASES;
	}
	public void setA21_NO_OF_PENDING_COURT_CASES(BigDecimal a21_NO_OF_PENDING_COURT_CASES) {
		A21_NO_OF_PENDING_COURT_CASES = a21_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA21_AMT_OF_PENALTIES_AGAINST_BANK() {
		return A21_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public void setA21_AMT_OF_PENALTIES_AGAINST_BANK(BigDecimal a21_AMT_OF_PENALTIES_AGAINST_BANK) {
		A21_AMT_OF_PENALTIES_AGAINST_BANK = a21_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA21_AMT_OF_PREV_PENALTIES_AGAINST_BANK() {
		return A21_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public void setA21_AMT_OF_PREV_PENALTIES_AGAINST_BANK(BigDecimal a21_AMT_OF_PREV_PENALTIES_AGAINST_BANK) {
		A21_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a21_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA21_NO_OF_COURT_POLICIES() {
		return A21_NO_OF_COURT_POLICIES;
	}
	public void setA21_NO_OF_COURT_POLICIES(BigDecimal a21_NO_OF_COURT_POLICIES) {
		A21_NO_OF_COURT_POLICIES = a21_NO_OF_COURT_POLICIES;
	}
	public String getA22_PRODUCT() {
		return A22_PRODUCT;
	}
	public void setA22_PRODUCT(String a22_PRODUCT) {
		A22_PRODUCT = a22_PRODUCT;
	}
	public BigDecimal getA22_NO_OF_COURT_CASES() {
		return A22_NO_OF_COURT_CASES;
	}
	public void setA22_NO_OF_COURT_CASES(BigDecimal a22_NO_OF_COURT_CASES) {
		A22_NO_OF_COURT_CASES = a22_NO_OF_COURT_CASES;
	}
	public BigDecimal getA22_AMT_OF_PENALTIES_IN_FAVOR() {
		return A22_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public void setA22_AMT_OF_PENALTIES_IN_FAVOR(BigDecimal a22_AMT_OF_PENALTIES_IN_FAVOR) {
		A22_AMT_OF_PENALTIES_IN_FAVOR = a22_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public BigDecimal getA22_NO_OF_PENDING_COURT_CASES() {
		return A22_NO_OF_PENDING_COURT_CASES;
	}
	public void setA22_NO_OF_PENDING_COURT_CASES(BigDecimal a22_NO_OF_PENDING_COURT_CASES) {
		A22_NO_OF_PENDING_COURT_CASES = a22_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA22_AMT_OF_PENALTIES_AGAINST_BANK() {
		return A22_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public void setA22_AMT_OF_PENALTIES_AGAINST_BANK(BigDecimal a22_AMT_OF_PENALTIES_AGAINST_BANK) {
		A22_AMT_OF_PENALTIES_AGAINST_BANK = a22_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA22_AMT_OF_PREV_PENALTIES_AGAINST_BANK() {
		return A22_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public void setA22_AMT_OF_PREV_PENALTIES_AGAINST_BANK(BigDecimal a22_AMT_OF_PREV_PENALTIES_AGAINST_BANK) {
		A22_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a22_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA22_NO_OF_COURT_POLICIES() {
		return A22_NO_OF_COURT_POLICIES;
	}
	public void setA22_NO_OF_COURT_POLICIES(BigDecimal a22_NO_OF_COURT_POLICIES) {
		A22_NO_OF_COURT_POLICIES = a22_NO_OF_COURT_POLICIES;
	}
	public String getA23_PRODUCT() {
		return A23_PRODUCT;
	}
	public void setA23_PRODUCT(String a23_PRODUCT) {
		A23_PRODUCT = a23_PRODUCT;
	}
	public BigDecimal getA23_NO_OF_COURT_CASES() {
		return A23_NO_OF_COURT_CASES;
	}
	public void setA23_NO_OF_COURT_CASES(BigDecimal a23_NO_OF_COURT_CASES) {
		A23_NO_OF_COURT_CASES = a23_NO_OF_COURT_CASES;
	}
	public BigDecimal getA23_AMT_OF_PENALTIES_IN_FAVOR() {
		return A23_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public void setA23_AMT_OF_PENALTIES_IN_FAVOR(BigDecimal a23_AMT_OF_PENALTIES_IN_FAVOR) {
		A23_AMT_OF_PENALTIES_IN_FAVOR = a23_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public BigDecimal getA23_NO_OF_PENDING_COURT_CASES() {
		return A23_NO_OF_PENDING_COURT_CASES;
	}
	public void setA23_NO_OF_PENDING_COURT_CASES(BigDecimal a23_NO_OF_PENDING_COURT_CASES) {
		A23_NO_OF_PENDING_COURT_CASES = a23_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA23_AMT_OF_PENALTIES_AGAINST_BANK() {
		return A23_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public void setA23_AMT_OF_PENALTIES_AGAINST_BANK(BigDecimal a23_AMT_OF_PENALTIES_AGAINST_BANK) {
		A23_AMT_OF_PENALTIES_AGAINST_BANK = a23_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA23_AMT_OF_PREV_PENALTIES_AGAINST_BANK() {
		return A23_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public void setA23_AMT_OF_PREV_PENALTIES_AGAINST_BANK(BigDecimal a23_AMT_OF_PREV_PENALTIES_AGAINST_BANK) {
		A23_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a23_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA23_NO_OF_COURT_POLICIES() {
		return A23_NO_OF_COURT_POLICIES;
	}
	public void setA23_NO_OF_COURT_POLICIES(BigDecimal a23_NO_OF_COURT_POLICIES) {
		A23_NO_OF_COURT_POLICIES = a23_NO_OF_COURT_POLICIES;
	}
	public String getA24_PRODUCT() {
		return A24_PRODUCT;
	}
	public void setA24_PRODUCT(String a24_PRODUCT) {
		A24_PRODUCT = a24_PRODUCT;
	}
	public BigDecimal getA24_NO_OF_COURT_CASES() {
		return A24_NO_OF_COURT_CASES;
	}
	public void setA24_NO_OF_COURT_CASES(BigDecimal a24_NO_OF_COURT_CASES) {
		A24_NO_OF_COURT_CASES = a24_NO_OF_COURT_CASES;
	}
	public BigDecimal getA24_AMT_OF_PENALTIES_IN_FAVOR() {
		return A24_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public void setA24_AMT_OF_PENALTIES_IN_FAVOR(BigDecimal a24_AMT_OF_PENALTIES_IN_FAVOR) {
		A24_AMT_OF_PENALTIES_IN_FAVOR = a24_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public BigDecimal getA24_NO_OF_PENDING_COURT_CASES() {
		return A24_NO_OF_PENDING_COURT_CASES;
	}
	public void setA24_NO_OF_PENDING_COURT_CASES(BigDecimal a24_NO_OF_PENDING_COURT_CASES) {
		A24_NO_OF_PENDING_COURT_CASES = a24_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA24_AMT_OF_PENALTIES_AGAINST_BANK() {
		return A24_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public void setA24_AMT_OF_PENALTIES_AGAINST_BANK(BigDecimal a24_AMT_OF_PENALTIES_AGAINST_BANK) {
		A24_AMT_OF_PENALTIES_AGAINST_BANK = a24_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA24_AMT_OF_PREV_PENALTIES_AGAINST_BANK() {
		return A24_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public void setA24_AMT_OF_PREV_PENALTIES_AGAINST_BANK(BigDecimal a24_AMT_OF_PREV_PENALTIES_AGAINST_BANK) {
		A24_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a24_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA24_NO_OF_COURT_POLICIES() {
		return A24_NO_OF_COURT_POLICIES;
	}
	public void setA24_NO_OF_COURT_POLICIES(BigDecimal a24_NO_OF_COURT_POLICIES) {
		A24_NO_OF_COURT_POLICIES = a24_NO_OF_COURT_POLICIES;
	}
	public String getA25_PRODUCT() {
		return A25_PRODUCT;
	}
	public void setA25_PRODUCT(String a25_PRODUCT) {
		A25_PRODUCT = a25_PRODUCT;
	}
	public String getA26_PRODUCT() {
		return A26_PRODUCT;
	}
	public void setA26_PRODUCT(String a26_PRODUCT) {
		A26_PRODUCT = a26_PRODUCT;
	}
	public BigDecimal getA26_NO_OF_COURT_CASES() {
		return A26_NO_OF_COURT_CASES;
	}
	public void setA26_NO_OF_COURT_CASES(BigDecimal a26_NO_OF_COURT_CASES) {
		A26_NO_OF_COURT_CASES = a26_NO_OF_COURT_CASES;
	}
	public BigDecimal getA26_AMT_OF_PENALTIES_IN_FAVOR() {
		return A26_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public void setA26_AMT_OF_PENALTIES_IN_FAVOR(BigDecimal a26_AMT_OF_PENALTIES_IN_FAVOR) {
		A26_AMT_OF_PENALTIES_IN_FAVOR = a26_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public BigDecimal getA26_NO_OF_PENDING_COURT_CASES() {
		return A26_NO_OF_PENDING_COURT_CASES;
	}
	public void setA26_NO_OF_PENDING_COURT_CASES(BigDecimal a26_NO_OF_PENDING_COURT_CASES) {
		A26_NO_OF_PENDING_COURT_CASES = a26_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA26_AMT_OF_PENALTIES_AGAINST_BANK() {
		return A26_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public void setA26_AMT_OF_PENALTIES_AGAINST_BANK(BigDecimal a26_AMT_OF_PENALTIES_AGAINST_BANK) {
		A26_AMT_OF_PENALTIES_AGAINST_BANK = a26_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA26_AMT_OF_PREV_PENALTIES_AGAINST_BANK() {
		return A26_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public void setA26_AMT_OF_PREV_PENALTIES_AGAINST_BANK(BigDecimal a26_AMT_OF_PREV_PENALTIES_AGAINST_BANK) {
		A26_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a26_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA26_NO_OF_COURT_POLICIES() {
		return A26_NO_OF_COURT_POLICIES;
	}
	public void setA26_NO_OF_COURT_POLICIES(BigDecimal a26_NO_OF_COURT_POLICIES) {
		A26_NO_OF_COURT_POLICIES = a26_NO_OF_COURT_POLICIES;
	}
	public String getA27_PRODUCT() {
		return A27_PRODUCT;
	}
	public void setA27_PRODUCT(String a27_PRODUCT) {
		A27_PRODUCT = a27_PRODUCT;
	}
	public BigDecimal getA27_NO_OF_COURT_CASES() {
		return A27_NO_OF_COURT_CASES;
	}
	public void setA27_NO_OF_COURT_CASES(BigDecimal a27_NO_OF_COURT_CASES) {
		A27_NO_OF_COURT_CASES = a27_NO_OF_COURT_CASES;
	}
	public BigDecimal getA27_AMT_OF_PENALTIES_IN_FAVOR() {
		return A27_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public void setA27_AMT_OF_PENALTIES_IN_FAVOR(BigDecimal a27_AMT_OF_PENALTIES_IN_FAVOR) {
		A27_AMT_OF_PENALTIES_IN_FAVOR = a27_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public BigDecimal getA27_NO_OF_PENDING_COURT_CASES() {
		return A27_NO_OF_PENDING_COURT_CASES;
	}
	public void setA27_NO_OF_PENDING_COURT_CASES(BigDecimal a27_NO_OF_PENDING_COURT_CASES) {
		A27_NO_OF_PENDING_COURT_CASES = a27_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA27_AMT_OF_PENALTIES_AGAINST_BANK() {
		return A27_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public void setA27_AMT_OF_PENALTIES_AGAINST_BANK(BigDecimal a27_AMT_OF_PENALTIES_AGAINST_BANK) {
		A27_AMT_OF_PENALTIES_AGAINST_BANK = a27_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA27_AMT_OF_PREV_PENALTIES_AGAINST_BANK() {
		return A27_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public void setA27_AMT_OF_PREV_PENALTIES_AGAINST_BANK(BigDecimal a27_AMT_OF_PREV_PENALTIES_AGAINST_BANK) {
		A27_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a27_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA27_NO_OF_COURT_POLICIES() {
		return A27_NO_OF_COURT_POLICIES;
	}
	public void setA27_NO_OF_COURT_POLICIES(BigDecimal a27_NO_OF_COURT_POLICIES) {
		A27_NO_OF_COURT_POLICIES = a27_NO_OF_COURT_POLICIES;
	}
	public String getA28_PRODUCT() {
		return A28_PRODUCT;
	}
	public void setA28_PRODUCT(String a28_PRODUCT) {
		A28_PRODUCT = a28_PRODUCT;
	}
	public BigDecimal getA28_NO_OF_COURT_CASES() {
		return A28_NO_OF_COURT_CASES;
	}
	public void setA28_NO_OF_COURT_CASES(BigDecimal a28_NO_OF_COURT_CASES) {
		A28_NO_OF_COURT_CASES = a28_NO_OF_COURT_CASES;
	}
	public BigDecimal getA28_AMT_OF_PENALTIES_IN_FAVOR() {
		return A28_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public void setA28_AMT_OF_PENALTIES_IN_FAVOR(BigDecimal a28_AMT_OF_PENALTIES_IN_FAVOR) {
		A28_AMT_OF_PENALTIES_IN_FAVOR = a28_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public BigDecimal getA28_NO_OF_PENDING_COURT_CASES() {
		return A28_NO_OF_PENDING_COURT_CASES;
	}
	public void setA28_NO_OF_PENDING_COURT_CASES(BigDecimal a28_NO_OF_PENDING_COURT_CASES) {
		A28_NO_OF_PENDING_COURT_CASES = a28_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA28_AMT_OF_PENALTIES_AGAINST_BANK() {
		return A28_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public void setA28_AMT_OF_PENALTIES_AGAINST_BANK(BigDecimal a28_AMT_OF_PENALTIES_AGAINST_BANK) {
		A28_AMT_OF_PENALTIES_AGAINST_BANK = a28_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA28_AMT_OF_PREV_PENALTIES_AGAINST_BANK() {
		return A28_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public void setA28_AMT_OF_PREV_PENALTIES_AGAINST_BANK(BigDecimal a28_AMT_OF_PREV_PENALTIES_AGAINST_BANK) {
		A28_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a28_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA28_NO_OF_COURT_POLICIES() {
		return A28_NO_OF_COURT_POLICIES;
	}
	public void setA28_NO_OF_COURT_POLICIES(BigDecimal a28_NO_OF_COURT_POLICIES) {
		A28_NO_OF_COURT_POLICIES = a28_NO_OF_COURT_POLICIES;
	}
	public String getA29_PRODUCT() {
		return A29_PRODUCT;
	}
	public void setA29_PRODUCT(String a29_PRODUCT) {
		A29_PRODUCT = a29_PRODUCT;
	}
	public BigDecimal getA29_NO_OF_COURT_CASES() {
		return A29_NO_OF_COURT_CASES;
	}
	public void setA29_NO_OF_COURT_CASES(BigDecimal a29_NO_OF_COURT_CASES) {
		A29_NO_OF_COURT_CASES = a29_NO_OF_COURT_CASES;
	}
	public BigDecimal getA29_AMT_OF_PENALTIES_IN_FAVOR() {
		return A29_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public void setA29_AMT_OF_PENALTIES_IN_FAVOR(BigDecimal a29_AMT_OF_PENALTIES_IN_FAVOR) {
		A29_AMT_OF_PENALTIES_IN_FAVOR = a29_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public BigDecimal getA29_NO_OF_PENDING_COURT_CASES() {
		return A29_NO_OF_PENDING_COURT_CASES;
	}
	public void setA29_NO_OF_PENDING_COURT_CASES(BigDecimal a29_NO_OF_PENDING_COURT_CASES) {
		A29_NO_OF_PENDING_COURT_CASES = a29_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA29_AMT_OF_PENALTIES_AGAINST_BANK() {
		return A29_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public void setA29_AMT_OF_PENALTIES_AGAINST_BANK(BigDecimal a29_AMT_OF_PENALTIES_AGAINST_BANK) {
		A29_AMT_OF_PENALTIES_AGAINST_BANK = a29_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA29_AMT_OF_PREV_PENALTIES_AGAINST_BANK() {
		return A29_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public void setA29_AMT_OF_PREV_PENALTIES_AGAINST_BANK(BigDecimal a29_AMT_OF_PREV_PENALTIES_AGAINST_BANK) {
		A29_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a29_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA29_NO_OF_COURT_POLICIES() {
		return A29_NO_OF_COURT_POLICIES;
	}
	public void setA29_NO_OF_COURT_POLICIES(BigDecimal a29_NO_OF_COURT_POLICIES) {
		A29_NO_OF_COURT_POLICIES = a29_NO_OF_COURT_POLICIES;
	}
	public String getA30_PRODUCT() {
		return A30_PRODUCT;
	}
	public void setA30_PRODUCT(String a30_PRODUCT) {
		A30_PRODUCT = a30_PRODUCT;
	}
	public BigDecimal getA30_NO_OF_COURT_CASES() {
		return A30_NO_OF_COURT_CASES;
	}
	public void setA30_NO_OF_COURT_CASES(BigDecimal a30_NO_OF_COURT_CASES) {
		A30_NO_OF_COURT_CASES = a30_NO_OF_COURT_CASES;
	}
	public BigDecimal getA30_AMT_OF_PENALTIES_IN_FAVOR() {
		return A30_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public void setA30_AMT_OF_PENALTIES_IN_FAVOR(BigDecimal a30_AMT_OF_PENALTIES_IN_FAVOR) {
		A30_AMT_OF_PENALTIES_IN_FAVOR = a30_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public BigDecimal getA30_NO_OF_PENDING_COURT_CASES() {
		return A30_NO_OF_PENDING_COURT_CASES;
	}
	public void setA30_NO_OF_PENDING_COURT_CASES(BigDecimal a30_NO_OF_PENDING_COURT_CASES) {
		A30_NO_OF_PENDING_COURT_CASES = a30_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA30_AMT_OF_PENALTIES_AGAINST_BANK() {
		return A30_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public void setA30_AMT_OF_PENALTIES_AGAINST_BANK(BigDecimal a30_AMT_OF_PENALTIES_AGAINST_BANK) {
		A30_AMT_OF_PENALTIES_AGAINST_BANK = a30_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA30_AMT_OF_PREV_PENALTIES_AGAINST_BANK() {
		return A30_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public void setA30_AMT_OF_PREV_PENALTIES_AGAINST_BANK(BigDecimal a30_AMT_OF_PREV_PENALTIES_AGAINST_BANK) {
		A30_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a30_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA30_NO_OF_COURT_POLICIES() {
		return A30_NO_OF_COURT_POLICIES;
	}
	public void setA30_NO_OF_COURT_POLICIES(BigDecimal a30_NO_OF_COURT_POLICIES) {
		A30_NO_OF_COURT_POLICIES = a30_NO_OF_COURT_POLICIES;
	}
	public String getA31_PRODUCT() {
		return A31_PRODUCT;
	}
	public void setA31_PRODUCT(String a31_PRODUCT) {
		A31_PRODUCT = a31_PRODUCT;
	}
	public String getA32_PRODUCT() {
		return A32_PRODUCT;
	}
	public void setA32_PRODUCT(String a32_PRODUCT) {
		A32_PRODUCT = a32_PRODUCT;
	}
	public BigDecimal getA32_NO_OF_COURT_CASES() {
		return A32_NO_OF_COURT_CASES;
	}
	public void setA32_NO_OF_COURT_CASES(BigDecimal a32_NO_OF_COURT_CASES) {
		A32_NO_OF_COURT_CASES = a32_NO_OF_COURT_CASES;
	}
	public BigDecimal getA32_AMT_OF_PENALTIES_IN_FAVOR() {
		return A32_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public void setA32_AMT_OF_PENALTIES_IN_FAVOR(BigDecimal a32_AMT_OF_PENALTIES_IN_FAVOR) {
		A32_AMT_OF_PENALTIES_IN_FAVOR = a32_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public BigDecimal getA32_NO_OF_PENDING_COURT_CASES() {
		return A32_NO_OF_PENDING_COURT_CASES;
	}
	public void setA32_NO_OF_PENDING_COURT_CASES(BigDecimal a32_NO_OF_PENDING_COURT_CASES) {
		A32_NO_OF_PENDING_COURT_CASES = a32_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA32_AMT_OF_PENALTIES_AGAINST_BANK() {
		return A32_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public void setA32_AMT_OF_PENALTIES_AGAINST_BANK(BigDecimal a32_AMT_OF_PENALTIES_AGAINST_BANK) {
		A32_AMT_OF_PENALTIES_AGAINST_BANK = a32_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA32_AMT_OF_PREV_PENALTIES_AGAINST_BANK() {
		return A32_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public void setA32_AMT_OF_PREV_PENALTIES_AGAINST_BANK(BigDecimal a32_AMT_OF_PREV_PENALTIES_AGAINST_BANK) {
		A32_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a32_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA32_NO_OF_COURT_POLICIES() {
		return A32_NO_OF_COURT_POLICIES;
	}
	public void setA32_NO_OF_COURT_POLICIES(BigDecimal a32_NO_OF_COURT_POLICIES) {
		A32_NO_OF_COURT_POLICIES = a32_NO_OF_COURT_POLICIES;
	}
	public String getA33_PRODUCT() {
		return A33_PRODUCT;
	}
	public void setA33_PRODUCT(String a33_PRODUCT) {
		A33_PRODUCT = a33_PRODUCT;
	}
	public BigDecimal getA33_NO_OF_COURT_CASES() {
		return A33_NO_OF_COURT_CASES;
	}
	public void setA33_NO_OF_COURT_CASES(BigDecimal a33_NO_OF_COURT_CASES) {
		A33_NO_OF_COURT_CASES = a33_NO_OF_COURT_CASES;
	}
	public BigDecimal getA33_AMT_OF_PENALTIES_IN_FAVOR() {
		return A33_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public void setA33_AMT_OF_PENALTIES_IN_FAVOR(BigDecimal a33_AMT_OF_PENALTIES_IN_FAVOR) {
		A33_AMT_OF_PENALTIES_IN_FAVOR = a33_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public BigDecimal getA33_NO_OF_PENDING_COURT_CASES() {
		return A33_NO_OF_PENDING_COURT_CASES;
	}
	public void setA33_NO_OF_PENDING_COURT_CASES(BigDecimal a33_NO_OF_PENDING_COURT_CASES) {
		A33_NO_OF_PENDING_COURT_CASES = a33_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA33_AMT_OF_PENALTIES_AGAINST_BANK() {
		return A33_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public void setA33_AMT_OF_PENALTIES_AGAINST_BANK(BigDecimal a33_AMT_OF_PENALTIES_AGAINST_BANK) {
		A33_AMT_OF_PENALTIES_AGAINST_BANK = a33_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA33_AMT_OF_PREV_PENALTIES_AGAINST_BANK() {
		return A33_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public void setA33_AMT_OF_PREV_PENALTIES_AGAINST_BANK(BigDecimal a33_AMT_OF_PREV_PENALTIES_AGAINST_BANK) {
		A33_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a33_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA33_NO_OF_COURT_POLICIES() {
		return A33_NO_OF_COURT_POLICIES;
	}
	public void setA33_NO_OF_COURT_POLICIES(BigDecimal a33_NO_OF_COURT_POLICIES) {
		A33_NO_OF_COURT_POLICIES = a33_NO_OF_COURT_POLICIES;
	}
	public String getA34_PRODUCT() {
		return A34_PRODUCT;
	}
	public void setA34_PRODUCT(String a34_PRODUCT) {
		A34_PRODUCT = a34_PRODUCT;
	}
	public BigDecimal getA34_NO_OF_COURT_CASES() {
		return A34_NO_OF_COURT_CASES;
	}
	public void setA34_NO_OF_COURT_CASES(BigDecimal a34_NO_OF_COURT_CASES) {
		A34_NO_OF_COURT_CASES = a34_NO_OF_COURT_CASES;
	}
	public BigDecimal getA34_AMT_OF_PENALTIES_IN_FAVOR() {
		return A34_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public void setA34_AMT_OF_PENALTIES_IN_FAVOR(BigDecimal a34_AMT_OF_PENALTIES_IN_FAVOR) {
		A34_AMT_OF_PENALTIES_IN_FAVOR = a34_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public BigDecimal getA34_NO_OF_PENDING_COURT_CASES() {
		return A34_NO_OF_PENDING_COURT_CASES;
	}
	public void setA34_NO_OF_PENDING_COURT_CASES(BigDecimal a34_NO_OF_PENDING_COURT_CASES) {
		A34_NO_OF_PENDING_COURT_CASES = a34_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA34_AMT_OF_PENALTIES_AGAINST_BANK() {
		return A34_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public void setA34_AMT_OF_PENALTIES_AGAINST_BANK(BigDecimal a34_AMT_OF_PENALTIES_AGAINST_BANK) {
		A34_AMT_OF_PENALTIES_AGAINST_BANK = a34_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA34_AMT_OF_PREV_PENALTIES_AGAINST_BANK() {
		return A34_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public void setA34_AMT_OF_PREV_PENALTIES_AGAINST_BANK(BigDecimal a34_AMT_OF_PREV_PENALTIES_AGAINST_BANK) {
		A34_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a34_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA34_NO_OF_COURT_POLICIES() {
		return A34_NO_OF_COURT_POLICIES;
	}
	public void setA34_NO_OF_COURT_POLICIES(BigDecimal a34_NO_OF_COURT_POLICIES) {
		A34_NO_OF_COURT_POLICIES = a34_NO_OF_COURT_POLICIES;
	}
	public String getA35_PRODUCT() {
		return A35_PRODUCT;
	}
	public void setA35_PRODUCT(String a35_PRODUCT) {
		A35_PRODUCT = a35_PRODUCT;
	}
	public BigDecimal getA35_NO_OF_COURT_CASES() {
		return A35_NO_OF_COURT_CASES;
	}
	public void setA35_NO_OF_COURT_CASES(BigDecimal a35_NO_OF_COURT_CASES) {
		A35_NO_OF_COURT_CASES = a35_NO_OF_COURT_CASES;
	}
	public BigDecimal getA35_AMT_OF_PENALTIES_IN_FAVOR() {
		return A35_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public void setA35_AMT_OF_PENALTIES_IN_FAVOR(BigDecimal a35_AMT_OF_PENALTIES_IN_FAVOR) {
		A35_AMT_OF_PENALTIES_IN_FAVOR = a35_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public BigDecimal getA35_NO_OF_PENDING_COURT_CASES() {
		return A35_NO_OF_PENDING_COURT_CASES;
	}
	public void setA35_NO_OF_PENDING_COURT_CASES(BigDecimal a35_NO_OF_PENDING_COURT_CASES) {
		A35_NO_OF_PENDING_COURT_CASES = a35_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA35_AMT_OF_PENALTIES_AGAINST_BANK() {
		return A35_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public void setA35_AMT_OF_PENALTIES_AGAINST_BANK(BigDecimal a35_AMT_OF_PENALTIES_AGAINST_BANK) {
		A35_AMT_OF_PENALTIES_AGAINST_BANK = a35_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA35_AMT_OF_PREV_PENALTIES_AGAINST_BANK() {
		return A35_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public void setA35_AMT_OF_PREV_PENALTIES_AGAINST_BANK(BigDecimal a35_AMT_OF_PREV_PENALTIES_AGAINST_BANK) {
		A35_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a35_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA35_NO_OF_COURT_POLICIES() {
		return A35_NO_OF_COURT_POLICIES;
	}
	public void setA35_NO_OF_COURT_POLICIES(BigDecimal a35_NO_OF_COURT_POLICIES) {
		A35_NO_OF_COURT_POLICIES = a35_NO_OF_COURT_POLICIES;
	}
	public String getA36_PRODUCT() {
		return A36_PRODUCT;
	}
	public void setA36_PRODUCT(String a36_PRODUCT) {
		A36_PRODUCT = a36_PRODUCT;
	}
	public BigDecimal getA36_NO_OF_COURT_CASES() {
		return A36_NO_OF_COURT_CASES;
	}
	public void setA36_NO_OF_COURT_CASES(BigDecimal a36_NO_OF_COURT_CASES) {
		A36_NO_OF_COURT_CASES = a36_NO_OF_COURT_CASES;
	}
	public BigDecimal getA36_AMT_OF_PENALTIES_IN_FAVOR() {
		return A36_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public void setA36_AMT_OF_PENALTIES_IN_FAVOR(BigDecimal a36_AMT_OF_PENALTIES_IN_FAVOR) {
		A36_AMT_OF_PENALTIES_IN_FAVOR = a36_AMT_OF_PENALTIES_IN_FAVOR;
	}
	public BigDecimal getA36_NO_OF_PENDING_COURT_CASES() {
		return A36_NO_OF_PENDING_COURT_CASES;
	}
	public void setA36_NO_OF_PENDING_COURT_CASES(BigDecimal a36_NO_OF_PENDING_COURT_CASES) {
		A36_NO_OF_PENDING_COURT_CASES = a36_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA36_AMT_OF_PENALTIES_AGAINST_BANK() {
		return A36_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public void setA36_AMT_OF_PENALTIES_AGAINST_BANK(BigDecimal a36_AMT_OF_PENALTIES_AGAINST_BANK) {
		A36_AMT_OF_PENALTIES_AGAINST_BANK = a36_AMT_OF_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA36_AMT_OF_PREV_PENALTIES_AGAINST_BANK() {
		return A36_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public void setA36_AMT_OF_PREV_PENALTIES_AGAINST_BANK(BigDecimal a36_AMT_OF_PREV_PENALTIES_AGAINST_BANK) {
		A36_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a36_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
	}
	public BigDecimal getA36_NO_OF_COURT_POLICIES() {
		return A36_NO_OF_COURT_POLICIES;
	}
	public void setA36_NO_OF_COURT_POLICIES(BigDecimal a36_NO_OF_COURT_POLICIES) {
		A36_NO_OF_COURT_POLICIES = a36_NO_OF_COURT_POLICIES;
	}
	public String getREPORT_CODE() {
		return REPORT_CODE;
	}
	public void setREPORT_CODE(String rEPORT_CODE) {
		REPORT_CODE = rEPORT_CODE;
	}
	public String getREPORT_NAME() {
		return REPORT_NAME;
	}
	public void setREPORT_NAME(String rEPORT_NAME) {
		REPORT_NAME = rEPORT_NAME;
	}
	public Date getREPORT_DATE() {
		return REPORT_DATE;
	}
	public void setREPORT_DATE(Date rEPORT_DATE) {
		REPORT_DATE = rEPORT_DATE;
	}
	public Date getREPORT_DUE_DATE() {
		return REPORT_DUE_DATE;
	}
	public void setREPORT_DUE_DATE(Date rEPORT_DUE_DATE) {
		REPORT_DUE_DATE = rEPORT_DUE_DATE;
	}
	public Date getREP_SUBMIT_DATE() {
		return REP_SUBMIT_DATE;
	}
	public void setREP_SUBMIT_DATE(Date rEP_SUBMIT_DATE) {
		REP_SUBMIT_DATE = rEP_SUBMIT_DATE;
	}
	public Date getREP_PERIOD_FROM() {
		return REP_PERIOD_FROM;
	}
	public void setREP_PERIOD_FROM(Date rEP_PERIOD_FROM) {
		REP_PERIOD_FROM = rEP_PERIOD_FROM;
	}
	public Date getREP_PERIOD_TO() {
		return REP_PERIOD_TO;
	}
	public void setREP_PERIOD_TO(Date rEP_PERIOD_TO) {
		REP_PERIOD_TO = rEP_PERIOD_TO;
	}
	public String getREP_FREQ() {
		return REP_FREQ;
	}
	public void setREP_FREQ(String rEP_FREQ) {
		REP_FREQ = rEP_FREQ;
	}
	public String getNIL_REPORT_FLG() {
		return NIL_REPORT_FLG;
	}
	public void setNIL_REPORT_FLG(String nIL_REPORT_FLG) {
		NIL_REPORT_FLG = nIL_REPORT_FLG;
	}
	public String getARCH_FLG() {
		return ARCH_FLG;
	}
	public void setARCH_FLG(String aRCH_FLG) {
		ARCH_FLG = aRCH_FLG;
	}
	public String getENTITY_FLG() {
		return ENTITY_FLG;
	}
	public void setENTITY_FLG(String eNTITY_FLG) {
		ENTITY_FLG = eNTITY_FLG;
	}
	public String getDEL_FLG() {
		return DEL_FLG;
	}
	public void setDEL_FLG(String dEL_FLG) {
		DEL_FLG = dEL_FLG;
	}
	public String getMODIFY_FLG() {
		return MODIFY_FLG;
	}
	public void setMODIFY_FLG(String mODIFY_FLG) {
		MODIFY_FLG = mODIFY_FLG;
	}
	public String getENTRY_USER() {
		return ENTRY_USER;
	}
	public void setENTRY_USER(String eNTRY_USER) {
		ENTRY_USER = eNTRY_USER;
	}
	public String getMODIFY_USER() {
		return MODIFY_USER;
	}
	public void setMODIFY_USER(String mODIFY_USER) {
		MODIFY_USER = mODIFY_USER;
	}
	public String getVERIFY_USER() {
		return VERIFY_USER;
	}
	public void setVERIFY_USER(String vERIFY_USER) {
		VERIFY_USER = vERIFY_USER;
	}
	public Date getENTRY_TIME() {
		return ENTRY_TIME;
	}
	public void setENTRY_TIME(Date eNTRY_TIME) {
		ENTRY_TIME = eNTRY_TIME;
	}
	public Date getMODIFY_TIME() {
		return MODIFY_TIME;
	}
	public void setMODIFY_TIME(Date mODIFY_TIME) {
		MODIFY_TIME = mODIFY_TIME;
	}
	public Date getVERIFY_TIME() {
		return VERIFY_TIME;
	}
	public void setVERIFY_TIME(Date vERIFY_TIME) {
		VERIFY_TIME = vERIFY_TIME;
	}
	public String getQTR_FLG() {
		return QTR_FLG;
	}
	public void setQTR_FLG(String qTR_FLG) {
		QTR_FLG = qTR_FLG;
	}
	public T19ORReport(String a1_PRODUCT, String a2_PRODUCT, BigDecimal a2_NO_OF_COURT_CASES,
			BigDecimal a2_AMT_OF_PENALTIES_IN_FAVOR, BigDecimal a2_NO_OF_PENDING_COURT_CASES,
			BigDecimal a2_AMT_OF_PENALTIES_AGAINST_BANK, BigDecimal a2_AMT_OF_PREV_PENALTIES_AGAINST_BANK,
			BigDecimal a2_NO_OF_COURT_POLICIES, String a3_PRODUCT, BigDecimal a3_NO_OF_COURT_CASES,
			BigDecimal a3_AMT_OF_PENALTIES_IN_FAVOR, BigDecimal a3_NO_OF_PENDING_COURT_CASES,
			BigDecimal a3_AMT_OF_PENALTIES_AGAINST_BANK, BigDecimal a3_AMT_OF_PREV_PENALTIES_AGAINST_BANK,
			BigDecimal a3_NO_OF_COURT_POLICIES, String a4_PRODUCT, BigDecimal a4_NO_OF_COURT_CASES,
			BigDecimal a4_AMT_OF_PENALTIES_IN_FAVOR, BigDecimal a4_NO_OF_PENDING_COURT_CASES,
			BigDecimal a4_AMT_OF_PENALTIES_AGAINST_BANK, BigDecimal a4_AMT_OF_PREV_PENALTIES_AGAINST_BANK,
			BigDecimal a4_NO_OF_COURT_POLICIES, String a5_PRODUCT, BigDecimal a5_NO_OF_COURT_CASES,
			BigDecimal a5_AMT_OF_PENALTIES_IN_FAVOR, BigDecimal a5_NO_OF_PENDING_COURT_CASES,
			BigDecimal a5_AMT_OF_PENALTIES_AGAINST_BANK, BigDecimal a5_AMT_OF_PREV_PENALTIES_AGAINST_BANK,
			BigDecimal a5_NO_OF_COURT_POLICIES, String a6_PRODUCT, BigDecimal a6_NO_OF_COURT_CASES,
			BigDecimal a6_AMT_OF_PENALTIES_IN_FAVOR, BigDecimal a6_NO_OF_PENDING_COURT_CASES,
			BigDecimal a6_AMT_OF_PENALTIES_AGAINST_BANK, BigDecimal a6_AMT_OF_PREV_PENALTIES_AGAINST_BANK,
			BigDecimal a6_NO_OF_COURT_POLICIES, String a7_PRODUCT, String a8_PRODUCT, BigDecimal a8_NO_OF_COURT_CASES,
			BigDecimal a8_AMT_OF_PENALTIES_IN_FAVOR, BigDecimal a8_NO_OF_PENDING_COURT_CASES,
			BigDecimal a8_AMT_OF_PENALTIES_AGAINST_BANK, BigDecimal a8_AMT_OF_PREV_PENALTIES_AGAINST_BANK,
			BigDecimal a8_NO_OF_COURT_POLICIES, String a9_PRODUCT, BigDecimal a9_NO_OF_COURT_CASES,
			BigDecimal a9_AMT_OF_PENALTIES_IN_FAVOR, BigDecimal a9_NO_OF_PENDING_COURT_CASES,
			BigDecimal a9_AMT_OF_PENALTIES_AGAINST_BANK, BigDecimal a9_AMT_OF_PREV_PENALTIES_AGAINST_BANK,
			BigDecimal a9_NO_OF_COURT_POLICIES, String a10_PRODUCT, BigDecimal a10_NO_OF_COURT_CASES,
			BigDecimal a10_AMT_OF_PENALTIES_IN_FAVOR, BigDecimal a10_NO_OF_PENDING_COURT_CASES,
			BigDecimal a10_AMT_OF_PENALTIES_AGAINST_BANK, BigDecimal a10_AMT_OF_PREV_PENALTIES_AGAINST_BANK,
			BigDecimal a10_NO_OF_COURT_POLICIES, String a11_PRODUCT, BigDecimal a11_NO_OF_COURT_CASES,
			BigDecimal a11_AMT_OF_PENALTIES_IN_FAVOR, BigDecimal a11_NO_OF_PENDING_COURT_CASES,
			BigDecimal a11_AMT_OF_PENALTIES_AGAINST_BANK, BigDecimal a11_AMT_OF_PREV_PENALTIES_AGAINST_BANK,
			BigDecimal a11_NO_OF_COURT_POLICIES, String a12_PRODUCT, BigDecimal a12_NO_OF_COURT_CASES,
			BigDecimal a12_AMT_OF_PENALTIES_IN_FAVOR, BigDecimal a12_NO_OF_PENDING_COURT_CASES,
			BigDecimal a12_AMT_OF_PENALTIES_AGAINST_BANK, BigDecimal a12_AMT_OF_PREV_PENALTIES_AGAINST_BANK,
			BigDecimal a12_NO_OF_COURT_POLICIES, String a13_PRODUCT, String a14_PRODUCT,
			BigDecimal a14_NO_OF_COURT_CASES, BigDecimal a14_AMT_OF_PENALTIES_IN_FAVOR,
			BigDecimal a14_NO_OF_PENDING_COURT_CASES, BigDecimal a14_AMT_OF_PENALTIES_AGAINST_BANK,
			BigDecimal a14_AMT_OF_PREV_PENALTIES_AGAINST_BANK, BigDecimal a14_NO_OF_COURT_POLICIES, String a15_PRODUCT,
			BigDecimal a15_NO_OF_COURT_CASES, BigDecimal a15_AMT_OF_PENALTIES_IN_FAVOR,
			BigDecimal a15_NO_OF_PENDING_COURT_CASES, BigDecimal a15_AMT_OF_PENALTIES_AGAINST_BANK,
			BigDecimal a15_AMT_OF_PREV_PENALTIES_AGAINST_BANK, BigDecimal a15_NO_OF_COURT_POLICIES, String a16_PRODUCT,
			BigDecimal a16_NO_OF_COURT_CASES, BigDecimal a16_AMT_OF_PENALTIES_IN_FAVOR,
			BigDecimal a16_NO_OF_PENDING_COURT_CASES, BigDecimal a16_AMT_OF_PENALTIES_AGAINST_BANK,
			BigDecimal a16_AMT_OF_PREV_PENALTIES_AGAINST_BANK, BigDecimal a16_NO_OF_COURT_POLICIES, String a17_PRODUCT,
			BigDecimal a17_NO_OF_COURT_CASES, BigDecimal a17_AMT_OF_PENALTIES_IN_FAVOR,
			BigDecimal a17_NO_OF_PENDING_COURT_CASES, BigDecimal a17_AMT_OF_PENALTIES_AGAINST_BANK,
			BigDecimal a17_AMT_OF_PREV_PENALTIES_AGAINST_BANK, BigDecimal a17_NO_OF_COURT_POLICIES, String a18_PRODUCT,
			BigDecimal a18_NO_OF_COURT_CASES, BigDecimal a18_AMT_OF_PENALTIES_IN_FAVOR,
			BigDecimal a18_NO_OF_PENDING_COURT_CASES, BigDecimal a18_AMT_OF_PENALTIES_AGAINST_BANK,
			BigDecimal a18_AMT_OF_PREV_PENALTIES_AGAINST_BANK, BigDecimal a18_NO_OF_COURT_POLICIES, String a19_PRODUCT,
			String a20_PRODUCT, BigDecimal a20_NO_OF_COURT_CASES, BigDecimal a20_AMT_OF_PENALTIES_IN_FAVOR,
			BigDecimal a20_NO_OF_PENDING_COURT_CASES, BigDecimal a20_AMT_OF_PENALTIES_AGAINST_BANK,
			BigDecimal a20_AMT_OF_PREV_PENALTIES_AGAINST_BANK, BigDecimal a20_NO_OF_COURT_POLICIES, String a21_PRODUCT,
			BigDecimal a21_NO_OF_COURT_CASES, BigDecimal a21_AMT_OF_PENALTIES_IN_FAVOR,
			BigDecimal a21_NO_OF_PENDING_COURT_CASES, BigDecimal a21_AMT_OF_PENALTIES_AGAINST_BANK,
			BigDecimal a21_AMT_OF_PREV_PENALTIES_AGAINST_BANK, BigDecimal a21_NO_OF_COURT_POLICIES, String a22_PRODUCT,
			BigDecimal a22_NO_OF_COURT_CASES, BigDecimal a22_AMT_OF_PENALTIES_IN_FAVOR,
			BigDecimal a22_NO_OF_PENDING_COURT_CASES, BigDecimal a22_AMT_OF_PENALTIES_AGAINST_BANK,
			BigDecimal a22_AMT_OF_PREV_PENALTIES_AGAINST_BANK, BigDecimal a22_NO_OF_COURT_POLICIES, String a23_PRODUCT,
			BigDecimal a23_NO_OF_COURT_CASES, BigDecimal a23_AMT_OF_PENALTIES_IN_FAVOR,
			BigDecimal a23_NO_OF_PENDING_COURT_CASES, BigDecimal a23_AMT_OF_PENALTIES_AGAINST_BANK,
			BigDecimal a23_AMT_OF_PREV_PENALTIES_AGAINST_BANK, BigDecimal a23_NO_OF_COURT_POLICIES, String a24_PRODUCT,
			BigDecimal a24_NO_OF_COURT_CASES, BigDecimal a24_AMT_OF_PENALTIES_IN_FAVOR,
			BigDecimal a24_NO_OF_PENDING_COURT_CASES, BigDecimal a24_AMT_OF_PENALTIES_AGAINST_BANK,
			BigDecimal a24_AMT_OF_PREV_PENALTIES_AGAINST_BANK, BigDecimal a24_NO_OF_COURT_POLICIES, String a25_PRODUCT,
			String a26_PRODUCT, BigDecimal a26_NO_OF_COURT_CASES, BigDecimal a26_AMT_OF_PENALTIES_IN_FAVOR,
			BigDecimal a26_NO_OF_PENDING_COURT_CASES, BigDecimal a26_AMT_OF_PENALTIES_AGAINST_BANK,
			BigDecimal a26_AMT_OF_PREV_PENALTIES_AGAINST_BANK, BigDecimal a26_NO_OF_COURT_POLICIES, String a27_PRODUCT,
			BigDecimal a27_NO_OF_COURT_CASES, BigDecimal a27_AMT_OF_PENALTIES_IN_FAVOR,
			BigDecimal a27_NO_OF_PENDING_COURT_CASES, BigDecimal a27_AMT_OF_PENALTIES_AGAINST_BANK,
			BigDecimal a27_AMT_OF_PREV_PENALTIES_AGAINST_BANK, BigDecimal a27_NO_OF_COURT_POLICIES, String a28_PRODUCT,
			BigDecimal a28_NO_OF_COURT_CASES, BigDecimal a28_AMT_OF_PENALTIES_IN_FAVOR,
			BigDecimal a28_NO_OF_PENDING_COURT_CASES, BigDecimal a28_AMT_OF_PENALTIES_AGAINST_BANK,
			BigDecimal a28_AMT_OF_PREV_PENALTIES_AGAINST_BANK, BigDecimal a28_NO_OF_COURT_POLICIES, String a29_PRODUCT,
			BigDecimal a29_NO_OF_COURT_CASES, BigDecimal a29_AMT_OF_PENALTIES_IN_FAVOR,
			BigDecimal a29_NO_OF_PENDING_COURT_CASES, BigDecimal a29_AMT_OF_PENALTIES_AGAINST_BANK,
			BigDecimal a29_AMT_OF_PREV_PENALTIES_AGAINST_BANK, BigDecimal a29_NO_OF_COURT_POLICIES, String a30_PRODUCT,
			BigDecimal a30_NO_OF_COURT_CASES, BigDecimal a30_AMT_OF_PENALTIES_IN_FAVOR,
			BigDecimal a30_NO_OF_PENDING_COURT_CASES, BigDecimal a30_AMT_OF_PENALTIES_AGAINST_BANK,
			BigDecimal a30_AMT_OF_PREV_PENALTIES_AGAINST_BANK, BigDecimal a30_NO_OF_COURT_POLICIES, String a31_PRODUCT,
			String a32_PRODUCT, BigDecimal a32_NO_OF_COURT_CASES, BigDecimal a32_AMT_OF_PENALTIES_IN_FAVOR,
			BigDecimal a32_NO_OF_PENDING_COURT_CASES, BigDecimal a32_AMT_OF_PENALTIES_AGAINST_BANK,
			BigDecimal a32_AMT_OF_PREV_PENALTIES_AGAINST_BANK, BigDecimal a32_NO_OF_COURT_POLICIES, String a33_PRODUCT,
			BigDecimal a33_NO_OF_COURT_CASES, BigDecimal a33_AMT_OF_PENALTIES_IN_FAVOR,
			BigDecimal a33_NO_OF_PENDING_COURT_CASES, BigDecimal a33_AMT_OF_PENALTIES_AGAINST_BANK,
			BigDecimal a33_AMT_OF_PREV_PENALTIES_AGAINST_BANK, BigDecimal a33_NO_OF_COURT_POLICIES, String a34_PRODUCT,
			BigDecimal a34_NO_OF_COURT_CASES, BigDecimal a34_AMT_OF_PENALTIES_IN_FAVOR,
			BigDecimal a34_NO_OF_PENDING_COURT_CASES, BigDecimal a34_AMT_OF_PENALTIES_AGAINST_BANK,
			BigDecimal a34_AMT_OF_PREV_PENALTIES_AGAINST_BANK, BigDecimal a34_NO_OF_COURT_POLICIES, String a35_PRODUCT,
			BigDecimal a35_NO_OF_COURT_CASES, BigDecimal a35_AMT_OF_PENALTIES_IN_FAVOR,
			BigDecimal a35_NO_OF_PENDING_COURT_CASES, BigDecimal a35_AMT_OF_PENALTIES_AGAINST_BANK,
			BigDecimal a35_AMT_OF_PREV_PENALTIES_AGAINST_BANK, BigDecimal a35_NO_OF_COURT_POLICIES, String a36_PRODUCT,
			BigDecimal a36_NO_OF_COURT_CASES, BigDecimal a36_AMT_OF_PENALTIES_IN_FAVOR,
			BigDecimal a36_NO_OF_PENDING_COURT_CASES, BigDecimal a36_AMT_OF_PENALTIES_AGAINST_BANK,
			BigDecimal a36_AMT_OF_PREV_PENALTIES_AGAINST_BANK, BigDecimal a36_NO_OF_COURT_POLICIES, String rEPORT_CODE,
			String rEPORT_NAME, Date rEPORT_DATE, Date rEPORT_DUE_DATE, Date rEP_SUBMIT_DATE, Date rEP_PERIOD_FROM,
			Date rEP_PERIOD_TO, String rEP_FREQ, String nIL_REPORT_FLG, String aRCH_FLG, String eNTITY_FLG,
			String dEL_FLG, String mODIFY_FLG, String eNTRY_USER, String mODIFY_USER, String vERIFY_USER,
			Date eNTRY_TIME, Date mODIFY_TIME, Date vERIFY_TIME, String qTR_FLG) {
		super();
		A1_PRODUCT = a1_PRODUCT;
		A2_PRODUCT = a2_PRODUCT;
		A2_NO_OF_COURT_CASES = a2_NO_OF_COURT_CASES;
		A2_AMT_OF_PENALTIES_IN_FAVOR = a2_AMT_OF_PENALTIES_IN_FAVOR;
		A2_NO_OF_PENDING_COURT_CASES = a2_NO_OF_PENDING_COURT_CASES;
		A2_AMT_OF_PENALTIES_AGAINST_BANK = a2_AMT_OF_PENALTIES_AGAINST_BANK;
		A2_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a2_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
		A2_NO_OF_COURT_POLICIES = a2_NO_OF_COURT_POLICIES;
		A3_PRODUCT = a3_PRODUCT;
		A3_NO_OF_COURT_CASES = a3_NO_OF_COURT_CASES;
		A3_AMT_OF_PENALTIES_IN_FAVOR = a3_AMT_OF_PENALTIES_IN_FAVOR;
		A3_NO_OF_PENDING_COURT_CASES = a3_NO_OF_PENDING_COURT_CASES;
		A3_AMT_OF_PENALTIES_AGAINST_BANK = a3_AMT_OF_PENALTIES_AGAINST_BANK;
		A3_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a3_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
		A3_NO_OF_COURT_POLICIES = a3_NO_OF_COURT_POLICIES;
		A4_PRODUCT = a4_PRODUCT;
		A4_NO_OF_COURT_CASES = a4_NO_OF_COURT_CASES;
		A4_AMT_OF_PENALTIES_IN_FAVOR = a4_AMT_OF_PENALTIES_IN_FAVOR;
		A4_NO_OF_PENDING_COURT_CASES = a4_NO_OF_PENDING_COURT_CASES;
		A4_AMT_OF_PENALTIES_AGAINST_BANK = a4_AMT_OF_PENALTIES_AGAINST_BANK;
		A4_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a4_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
		A4_NO_OF_COURT_POLICIES = a4_NO_OF_COURT_POLICIES;
		A5_PRODUCT = a5_PRODUCT;
		A5_NO_OF_COURT_CASES = a5_NO_OF_COURT_CASES;
		A5_AMT_OF_PENALTIES_IN_FAVOR = a5_AMT_OF_PENALTIES_IN_FAVOR;
		A5_NO_OF_PENDING_COURT_CASES = a5_NO_OF_PENDING_COURT_CASES;
		A5_AMT_OF_PENALTIES_AGAINST_BANK = a5_AMT_OF_PENALTIES_AGAINST_BANK;
		A5_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a5_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
		A5_NO_OF_COURT_POLICIES = a5_NO_OF_COURT_POLICIES;
		A6_PRODUCT = a6_PRODUCT;
		A6_NO_OF_COURT_CASES = a6_NO_OF_COURT_CASES;
		A6_AMT_OF_PENALTIES_IN_FAVOR = a6_AMT_OF_PENALTIES_IN_FAVOR;
		A6_NO_OF_PENDING_COURT_CASES = a6_NO_OF_PENDING_COURT_CASES;
		A6_AMT_OF_PENALTIES_AGAINST_BANK = a6_AMT_OF_PENALTIES_AGAINST_BANK;
		A6_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a6_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
		A6_NO_OF_COURT_POLICIES = a6_NO_OF_COURT_POLICIES;
		A7_PRODUCT = a7_PRODUCT;
		A8_PRODUCT = a8_PRODUCT;
		A8_NO_OF_COURT_CASES = a8_NO_OF_COURT_CASES;
		A8_AMT_OF_PENALTIES_IN_FAVOR = a8_AMT_OF_PENALTIES_IN_FAVOR;
		A8_NO_OF_PENDING_COURT_CASES = a8_NO_OF_PENDING_COURT_CASES;
		A8_AMT_OF_PENALTIES_AGAINST_BANK = a8_AMT_OF_PENALTIES_AGAINST_BANK;
		A8_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a8_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
		A8_NO_OF_COURT_POLICIES = a8_NO_OF_COURT_POLICIES;
		A9_PRODUCT = a9_PRODUCT;
		A9_NO_OF_COURT_CASES = a9_NO_OF_COURT_CASES;
		A9_AMT_OF_PENALTIES_IN_FAVOR = a9_AMT_OF_PENALTIES_IN_FAVOR;
		A9_NO_OF_PENDING_COURT_CASES = a9_NO_OF_PENDING_COURT_CASES;
		A9_AMT_OF_PENALTIES_AGAINST_BANK = a9_AMT_OF_PENALTIES_AGAINST_BANK;
		A9_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a9_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
		A9_NO_OF_COURT_POLICIES = a9_NO_OF_COURT_POLICIES;
		A10_PRODUCT = a10_PRODUCT;
		A10_NO_OF_COURT_CASES = a10_NO_OF_COURT_CASES;
		A10_AMT_OF_PENALTIES_IN_FAVOR = a10_AMT_OF_PENALTIES_IN_FAVOR;
		A10_NO_OF_PENDING_COURT_CASES = a10_NO_OF_PENDING_COURT_CASES;
		A10_AMT_OF_PENALTIES_AGAINST_BANK = a10_AMT_OF_PENALTIES_AGAINST_BANK;
		A10_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a10_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
		A10_NO_OF_COURT_POLICIES = a10_NO_OF_COURT_POLICIES;
		A11_PRODUCT = a11_PRODUCT;
		A11_NO_OF_COURT_CASES = a11_NO_OF_COURT_CASES;
		A11_AMT_OF_PENALTIES_IN_FAVOR = a11_AMT_OF_PENALTIES_IN_FAVOR;
		A11_NO_OF_PENDING_COURT_CASES = a11_NO_OF_PENDING_COURT_CASES;
		A11_AMT_OF_PENALTIES_AGAINST_BANK = a11_AMT_OF_PENALTIES_AGAINST_BANK;
		A11_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a11_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
		A11_NO_OF_COURT_POLICIES = a11_NO_OF_COURT_POLICIES;
		A12_PRODUCT = a12_PRODUCT;
		A12_NO_OF_COURT_CASES = a12_NO_OF_COURT_CASES;
		A12_AMT_OF_PENALTIES_IN_FAVOR = a12_AMT_OF_PENALTIES_IN_FAVOR;
		A12_NO_OF_PENDING_COURT_CASES = a12_NO_OF_PENDING_COURT_CASES;
		A12_AMT_OF_PENALTIES_AGAINST_BANK = a12_AMT_OF_PENALTIES_AGAINST_BANK;
		A12_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a12_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
		A12_NO_OF_COURT_POLICIES = a12_NO_OF_COURT_POLICIES;
		A13_PRODUCT = a13_PRODUCT;
		A14_PRODUCT = a14_PRODUCT;
		A14_NO_OF_COURT_CASES = a14_NO_OF_COURT_CASES;
		A14_AMT_OF_PENALTIES_IN_FAVOR = a14_AMT_OF_PENALTIES_IN_FAVOR;
		A14_NO_OF_PENDING_COURT_CASES = a14_NO_OF_PENDING_COURT_CASES;
		A14_AMT_OF_PENALTIES_AGAINST_BANK = a14_AMT_OF_PENALTIES_AGAINST_BANK;
		A14_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a14_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
		A14_NO_OF_COURT_POLICIES = a14_NO_OF_COURT_POLICIES;
		A15_PRODUCT = a15_PRODUCT;
		A15_NO_OF_COURT_CASES = a15_NO_OF_COURT_CASES;
		A15_AMT_OF_PENALTIES_IN_FAVOR = a15_AMT_OF_PENALTIES_IN_FAVOR;
		A15_NO_OF_PENDING_COURT_CASES = a15_NO_OF_PENDING_COURT_CASES;
		A15_AMT_OF_PENALTIES_AGAINST_BANK = a15_AMT_OF_PENALTIES_AGAINST_BANK;
		A15_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a15_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
		A15_NO_OF_COURT_POLICIES = a15_NO_OF_COURT_POLICIES;
		A16_PRODUCT = a16_PRODUCT;
		A16_NO_OF_COURT_CASES = a16_NO_OF_COURT_CASES;
		A16_AMT_OF_PENALTIES_IN_FAVOR = a16_AMT_OF_PENALTIES_IN_FAVOR;
		A16_NO_OF_PENDING_COURT_CASES = a16_NO_OF_PENDING_COURT_CASES;
		A16_AMT_OF_PENALTIES_AGAINST_BANK = a16_AMT_OF_PENALTIES_AGAINST_BANK;
		A16_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a16_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
		A16_NO_OF_COURT_POLICIES = a16_NO_OF_COURT_POLICIES;
		A17_PRODUCT = a17_PRODUCT;
		A17_NO_OF_COURT_CASES = a17_NO_OF_COURT_CASES;
		A17_AMT_OF_PENALTIES_IN_FAVOR = a17_AMT_OF_PENALTIES_IN_FAVOR;
		A17_NO_OF_PENDING_COURT_CASES = a17_NO_OF_PENDING_COURT_CASES;
		A17_AMT_OF_PENALTIES_AGAINST_BANK = a17_AMT_OF_PENALTIES_AGAINST_BANK;
		A17_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a17_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
		A17_NO_OF_COURT_POLICIES = a17_NO_OF_COURT_POLICIES;
		A18_PRODUCT = a18_PRODUCT;
		A18_NO_OF_COURT_CASES = a18_NO_OF_COURT_CASES;
		A18_AMT_OF_PENALTIES_IN_FAVOR = a18_AMT_OF_PENALTIES_IN_FAVOR;
		A18_NO_OF_PENDING_COURT_CASES = a18_NO_OF_PENDING_COURT_CASES;
		A18_AMT_OF_PENALTIES_AGAINST_BANK = a18_AMT_OF_PENALTIES_AGAINST_BANK;
		A18_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a18_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
		A18_NO_OF_COURT_POLICIES = a18_NO_OF_COURT_POLICIES;
		A19_PRODUCT = a19_PRODUCT;
		A20_PRODUCT = a20_PRODUCT;
		A20_NO_OF_COURT_CASES = a20_NO_OF_COURT_CASES;
		A20_AMT_OF_PENALTIES_IN_FAVOR = a20_AMT_OF_PENALTIES_IN_FAVOR;
		A20_NO_OF_PENDING_COURT_CASES = a20_NO_OF_PENDING_COURT_CASES;
		A20_AMT_OF_PENALTIES_AGAINST_BANK = a20_AMT_OF_PENALTIES_AGAINST_BANK;
		A20_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a20_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
		A20_NO_OF_COURT_POLICIES = a20_NO_OF_COURT_POLICIES;
		A21_PRODUCT = a21_PRODUCT;
		A21_NO_OF_COURT_CASES = a21_NO_OF_COURT_CASES;
		A21_AMT_OF_PENALTIES_IN_FAVOR = a21_AMT_OF_PENALTIES_IN_FAVOR;
		A21_NO_OF_PENDING_COURT_CASES = a21_NO_OF_PENDING_COURT_CASES;
		A21_AMT_OF_PENALTIES_AGAINST_BANK = a21_AMT_OF_PENALTIES_AGAINST_BANK;
		A21_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a21_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
		A21_NO_OF_COURT_POLICIES = a21_NO_OF_COURT_POLICIES;
		A22_PRODUCT = a22_PRODUCT;
		A22_NO_OF_COURT_CASES = a22_NO_OF_COURT_CASES;
		A22_AMT_OF_PENALTIES_IN_FAVOR = a22_AMT_OF_PENALTIES_IN_FAVOR;
		A22_NO_OF_PENDING_COURT_CASES = a22_NO_OF_PENDING_COURT_CASES;
		A22_AMT_OF_PENALTIES_AGAINST_BANK = a22_AMT_OF_PENALTIES_AGAINST_BANK;
		A22_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a22_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
		A22_NO_OF_COURT_POLICIES = a22_NO_OF_COURT_POLICIES;
		A23_PRODUCT = a23_PRODUCT;
		A23_NO_OF_COURT_CASES = a23_NO_OF_COURT_CASES;
		A23_AMT_OF_PENALTIES_IN_FAVOR = a23_AMT_OF_PENALTIES_IN_FAVOR;
		A23_NO_OF_PENDING_COURT_CASES = a23_NO_OF_PENDING_COURT_CASES;
		A23_AMT_OF_PENALTIES_AGAINST_BANK = a23_AMT_OF_PENALTIES_AGAINST_BANK;
		A23_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a23_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
		A23_NO_OF_COURT_POLICIES = a23_NO_OF_COURT_POLICIES;
		A24_PRODUCT = a24_PRODUCT;
		A24_NO_OF_COURT_CASES = a24_NO_OF_COURT_CASES;
		A24_AMT_OF_PENALTIES_IN_FAVOR = a24_AMT_OF_PENALTIES_IN_FAVOR;
		A24_NO_OF_PENDING_COURT_CASES = a24_NO_OF_PENDING_COURT_CASES;
		A24_AMT_OF_PENALTIES_AGAINST_BANK = a24_AMT_OF_PENALTIES_AGAINST_BANK;
		A24_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a24_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
		A24_NO_OF_COURT_POLICIES = a24_NO_OF_COURT_POLICIES;
		A25_PRODUCT = a25_PRODUCT;
		A26_PRODUCT = a26_PRODUCT;
		A26_NO_OF_COURT_CASES = a26_NO_OF_COURT_CASES;
		A26_AMT_OF_PENALTIES_IN_FAVOR = a26_AMT_OF_PENALTIES_IN_FAVOR;
		A26_NO_OF_PENDING_COURT_CASES = a26_NO_OF_PENDING_COURT_CASES;
		A26_AMT_OF_PENALTIES_AGAINST_BANK = a26_AMT_OF_PENALTIES_AGAINST_BANK;
		A26_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a26_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
		A26_NO_OF_COURT_POLICIES = a26_NO_OF_COURT_POLICIES;
		A27_PRODUCT = a27_PRODUCT;
		A27_NO_OF_COURT_CASES = a27_NO_OF_COURT_CASES;
		A27_AMT_OF_PENALTIES_IN_FAVOR = a27_AMT_OF_PENALTIES_IN_FAVOR;
		A27_NO_OF_PENDING_COURT_CASES = a27_NO_OF_PENDING_COURT_CASES;
		A27_AMT_OF_PENALTIES_AGAINST_BANK = a27_AMT_OF_PENALTIES_AGAINST_BANK;
		A27_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a27_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
		A27_NO_OF_COURT_POLICIES = a27_NO_OF_COURT_POLICIES;
		A28_PRODUCT = a28_PRODUCT;
		A28_NO_OF_COURT_CASES = a28_NO_OF_COURT_CASES;
		A28_AMT_OF_PENALTIES_IN_FAVOR = a28_AMT_OF_PENALTIES_IN_FAVOR;
		A28_NO_OF_PENDING_COURT_CASES = a28_NO_OF_PENDING_COURT_CASES;
		A28_AMT_OF_PENALTIES_AGAINST_BANK = a28_AMT_OF_PENALTIES_AGAINST_BANK;
		A28_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a28_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
		A28_NO_OF_COURT_POLICIES = a28_NO_OF_COURT_POLICIES;
		A29_PRODUCT = a29_PRODUCT;
		A29_NO_OF_COURT_CASES = a29_NO_OF_COURT_CASES;
		A29_AMT_OF_PENALTIES_IN_FAVOR = a29_AMT_OF_PENALTIES_IN_FAVOR;
		A29_NO_OF_PENDING_COURT_CASES = a29_NO_OF_PENDING_COURT_CASES;
		A29_AMT_OF_PENALTIES_AGAINST_BANK = a29_AMT_OF_PENALTIES_AGAINST_BANK;
		A29_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a29_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
		A29_NO_OF_COURT_POLICIES = a29_NO_OF_COURT_POLICIES;
		A30_PRODUCT = a30_PRODUCT;
		A30_NO_OF_COURT_CASES = a30_NO_OF_COURT_CASES;
		A30_AMT_OF_PENALTIES_IN_FAVOR = a30_AMT_OF_PENALTIES_IN_FAVOR;
		A30_NO_OF_PENDING_COURT_CASES = a30_NO_OF_PENDING_COURT_CASES;
		A30_AMT_OF_PENALTIES_AGAINST_BANK = a30_AMT_OF_PENALTIES_AGAINST_BANK;
		A30_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a30_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
		A30_NO_OF_COURT_POLICIES = a30_NO_OF_COURT_POLICIES;
		A31_PRODUCT = a31_PRODUCT;
		A32_PRODUCT = a32_PRODUCT;
		A32_NO_OF_COURT_CASES = a32_NO_OF_COURT_CASES;
		A32_AMT_OF_PENALTIES_IN_FAVOR = a32_AMT_OF_PENALTIES_IN_FAVOR;
		A32_NO_OF_PENDING_COURT_CASES = a32_NO_OF_PENDING_COURT_CASES;
		A32_AMT_OF_PENALTIES_AGAINST_BANK = a32_AMT_OF_PENALTIES_AGAINST_BANK;
		A32_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a32_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
		A32_NO_OF_COURT_POLICIES = a32_NO_OF_COURT_POLICIES;
		A33_PRODUCT = a33_PRODUCT;
		A33_NO_OF_COURT_CASES = a33_NO_OF_COURT_CASES;
		A33_AMT_OF_PENALTIES_IN_FAVOR = a33_AMT_OF_PENALTIES_IN_FAVOR;
		A33_NO_OF_PENDING_COURT_CASES = a33_NO_OF_PENDING_COURT_CASES;
		A33_AMT_OF_PENALTIES_AGAINST_BANK = a33_AMT_OF_PENALTIES_AGAINST_BANK;
		A33_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a33_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
		A33_NO_OF_COURT_POLICIES = a33_NO_OF_COURT_POLICIES;
		A34_PRODUCT = a34_PRODUCT;
		A34_NO_OF_COURT_CASES = a34_NO_OF_COURT_CASES;
		A34_AMT_OF_PENALTIES_IN_FAVOR = a34_AMT_OF_PENALTIES_IN_FAVOR;
		A34_NO_OF_PENDING_COURT_CASES = a34_NO_OF_PENDING_COURT_CASES;
		A34_AMT_OF_PENALTIES_AGAINST_BANK = a34_AMT_OF_PENALTIES_AGAINST_BANK;
		A34_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a34_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
		A34_NO_OF_COURT_POLICIES = a34_NO_OF_COURT_POLICIES;
		A35_PRODUCT = a35_PRODUCT;
		A35_NO_OF_COURT_CASES = a35_NO_OF_COURT_CASES;
		A35_AMT_OF_PENALTIES_IN_FAVOR = a35_AMT_OF_PENALTIES_IN_FAVOR;
		A35_NO_OF_PENDING_COURT_CASES = a35_NO_OF_PENDING_COURT_CASES;
		A35_AMT_OF_PENALTIES_AGAINST_BANK = a35_AMT_OF_PENALTIES_AGAINST_BANK;
		A35_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a35_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
		A35_NO_OF_COURT_POLICIES = a35_NO_OF_COURT_POLICIES;
		A36_PRODUCT = a36_PRODUCT;
		A36_NO_OF_COURT_CASES = a36_NO_OF_COURT_CASES;
		A36_AMT_OF_PENALTIES_IN_FAVOR = a36_AMT_OF_PENALTIES_IN_FAVOR;
		A36_NO_OF_PENDING_COURT_CASES = a36_NO_OF_PENDING_COURT_CASES;
		A36_AMT_OF_PENALTIES_AGAINST_BANK = a36_AMT_OF_PENALTIES_AGAINST_BANK;
		A36_AMT_OF_PREV_PENALTIES_AGAINST_BANK = a36_AMT_OF_PREV_PENALTIES_AGAINST_BANK;
		A36_NO_OF_COURT_POLICIES = a36_NO_OF_COURT_POLICIES;
		REPORT_CODE = rEPORT_CODE;
		REPORT_NAME = rEPORT_NAME;
		REPORT_DATE = rEPORT_DATE;
		REPORT_DUE_DATE = rEPORT_DUE_DATE;
		REP_SUBMIT_DATE = rEP_SUBMIT_DATE;
		REP_PERIOD_FROM = rEP_PERIOD_FROM;
		REP_PERIOD_TO = rEP_PERIOD_TO;
		REP_FREQ = rEP_FREQ;
		NIL_REPORT_FLG = nIL_REPORT_FLG;
		ARCH_FLG = aRCH_FLG;
		ENTITY_FLG = eNTITY_FLG;
		DEL_FLG = dEL_FLG;
		MODIFY_FLG = mODIFY_FLG;
		ENTRY_USER = eNTRY_USER;
		MODIFY_USER = mODIFY_USER;
		VERIFY_USER = vERIFY_USER;
		ENTRY_TIME = eNTRY_TIME;
		MODIFY_TIME = mODIFY_TIME;
		VERIFY_TIME = vERIFY_TIME;
		QTR_FLG = qTR_FLG;
	}
	public T19ORReport() {
		super();
		// TODO Auto-generated constructor stub
	}
    

}
