package com.bornfire.xbrl.entities.BRSS;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

@Entity
@Table(name="T32_OR_IT_HARDWARE_BANK_TABLE")
public class T32ORReport {
	private String	A1_PRODUCT;
	private BigDecimal	A1_ACTIVE_DEVICE_WITH_INTERNET;
	private BigDecimal	A1_ACTIVE_DEVICE_WITHOUT_INTERNET;
	private BigDecimal	A1_NOT_ACTIVE_DEVICES;
	private String	A2_PRODUCT;
	private String	A3_PRODUCT;
	private BigDecimal	A3_ACTIVE_DEVICE_WITH_INTERNET;
	private BigDecimal	A3_ACTIVE_DEVICE_WITHOUT_INTERNET;
	private BigDecimal	A3_NOT_ACTIVE_DEVICES;
	private String	A4_PRODUCT;
	private BigDecimal	A4_ACTIVE_DEVICE_WITH_INTERNET;
	private BigDecimal	A4_ACTIVE_DEVICE_WITHOUT_INTERNET;
	private BigDecimal	A4_NOT_ACTIVE_DEVICES;
	private String	A5_PRODUCT;
	private BigDecimal	A5_ACTIVE_DEVICE_WITH_INTERNET;
	private BigDecimal	A5_ACTIVE_DEVICE_WITHOUT_INTERNET;
	private BigDecimal	A5_NOT_ACTIVE_DEVICES;
	private String	A6_PRODUCT;
	private BigDecimal	A6_ACTIVE_DEVICE_WITH_INTERNET;
	private BigDecimal	A6_ACTIVE_DEVICE_WITHOUT_INTERNET;
	private BigDecimal	A6_NOT_ACTIVE_DEVICES;
	private String	A7_PRODUCT;
	private BigDecimal	A7_ACTIVE_DEVICE_WITH_INTERNET;
	private BigDecimal	A7_ACTIVE_DEVICE_WITHOUT_INTERNET;
	private BigDecimal	A7_NOT_ACTIVE_DEVICES;
	private String	A8_PRODUCT;
	private BigDecimal	A8_ACTIVE_DEVICE_WITH_INTERNET;
	private BigDecimal	A8_ACTIVE_DEVICE_WITHOUT_INTERNET;
	private BigDecimal	A8_NOT_ACTIVE_DEVICES;
	private String	A9_PRODUCT;
	private BigDecimal	A9_ACTIVE_DEVICE_WITH_INTERNET;
	private BigDecimal	A9_ACTIVE_DEVICE_WITHOUT_INTERNET;
	private BigDecimal	A9_NOT_ACTIVE_DEVICES;
	private String	A10_PRODUCT;
	private BigDecimal	A10_ACTIVE_DEVICE_WITH_INTERNET;
	private BigDecimal	A10_ACTIVE_DEVICE_WITHOUT_INTERNET;
	private BigDecimal	A10_NOT_ACTIVE_DEVICES;
	private String	A11_PRODUCT;
	private BigDecimal	A11_ACTIVE_DEVICE_WITH_INTERNET;
	private BigDecimal	A11_ACTIVE_DEVICE_WITHOUT_INTERNET;
	private BigDecimal	A11_NOT_ACTIVE_DEVICES;
	private String	A12_PRODUCT;
	private BigDecimal	A12_ACTIVE_DEVICE_WITH_INTERNET;
	private BigDecimal	A12_ACTIVE_DEVICE_WITHOUT_INTERNET;
	private BigDecimal	A12_NOT_ACTIVE_DEVICES;
	private String	A13_PRODUCT;
	private BigDecimal	A13_ACTIVE_DEVICE_WITH_INTERNET;
	private BigDecimal	A13_ACTIVE_DEVICE_WITHOUT_INTERNET;
	private BigDecimal	A13_NOT_ACTIVE_DEVICES;
	private String	A14_PRODUCT;
	private BigDecimal	A14_ACTIVE_DEVICE_WITH_INTERNET;
	private BigDecimal	A14_ACTIVE_DEVICE_WITHOUT_INTERNET;
	private BigDecimal	A14_NOT_ACTIVE_DEVICES;
	private String	A15_PRODUCT;
	private BigDecimal	A15_ACTIVE_DEVICE_WITH_INTERNET;
	private BigDecimal	A15_ACTIVE_DEVICE_WITHOUT_INTERNET;
	private BigDecimal	A15_NOT_ACTIVE_DEVICES;
	private String	A16_PRODUCT;
	private String	A17_PRODUCT;
	private BigDecimal	A17_ACTIVE_DEVICE_WITH_INTERNET;
	private BigDecimal	A17_ACTIVE_DEVICE_WITHOUT_INTERNET;
	private BigDecimal	A17_NOT_ACTIVE_DEVICES;
	private String	A18_PRODUCT;
	private BigDecimal	A18_ACTIVE_DEVICE_WITH_INTERNET;
	private BigDecimal	A18_ACTIVE_DEVICE_WITHOUT_INTERNET;
	private BigDecimal	A18_NOT_ACTIVE_DEVICES;
	private String	A19_PRODUCT;
	private BigDecimal	A19_ACTIVE_DEVICE_WITH_INTERNET;
	private BigDecimal	A19_ACTIVE_DEVICE_WITHOUT_INTERNET;
	private BigDecimal	A19_NOT_ACTIVE_DEVICES;
	private String	A20_PRODUCT;
	private BigDecimal	A20_ACTIVE_DEVICE_WITH_INTERNET;
	private BigDecimal	A20_ACTIVE_DEVICE_WITHOUT_INTERNET;
	private BigDecimal	A20_NOT_ACTIVE_DEVICES;
	private String	A21_PRODUCT;
	private BigDecimal	A21_ACTIVE_DEVICE_WITH_INTERNET;
	private BigDecimal	A21_ACTIVE_DEVICE_WITHOUT_INTERNET;
	private BigDecimal	A21_NOT_ACTIVE_DEVICES;
	private String	A22_PRODUCT;
	private BigDecimal	A22_ACTIVE_DEVICE_WITH_INTERNET;
	private BigDecimal	A22_ACTIVE_DEVICE_WITHOUT_INTERNET;
	private BigDecimal	A22_NOT_ACTIVE_DEVICES;
	private String	A23_PRODUCT;
	private BigDecimal	A23_ACTIVE_DEVICE_WITH_INTERNET;
	private BigDecimal	A23_ACTIVE_DEVICE_WITHOUT_INTERNET;
	private BigDecimal	A23_NOT_ACTIVE_DEVICES;
	private String	REPORT_CODE;
	private String	REPORT_NAME;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	@Id
	private Date	REPORT_DATE;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	REPORT_DUE_DATE;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	REP_SUBMIT_DATE;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	REP_PERIOD_FROM;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	REP_PERIOD_TO;
	private String	REP_FREQ;
	private String	NIL_REPORT_FLG;
	private String	ARCH_FLG;
	private String	ENTITY_FLG;
	private String	DEL_FLG;
	private String	MODIFY_FLG;
	private String	ENTRY_USER;
	private String	MODIFY_USER;
	private String	VERIFY_USER;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	ENTRY_TIME;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	MODIFY_TIME;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	VERIFY_TIME;
	private String	QTR_FLG;
	public String getA1_PRODUCT() {
		return A1_PRODUCT;
	}
	public void setA1_PRODUCT(String a1_PRODUCT) {
		A1_PRODUCT = a1_PRODUCT;
	}
	public BigDecimal getA1_ACTIVE_DEVICE_WITH_INTERNET() {
		return A1_ACTIVE_DEVICE_WITH_INTERNET;
	}
	public void setA1_ACTIVE_DEVICE_WITH_INTERNET(BigDecimal a1_ACTIVE_DEVICE_WITH_INTERNET) {
		A1_ACTIVE_DEVICE_WITH_INTERNET = a1_ACTIVE_DEVICE_WITH_INTERNET;
	}
	public BigDecimal getA1_ACTIVE_DEVICE_WITHOUT_INTERNET() {
		return A1_ACTIVE_DEVICE_WITHOUT_INTERNET;
	}
	public void setA1_ACTIVE_DEVICE_WITHOUT_INTERNET(BigDecimal a1_ACTIVE_DEVICE_WITHOUT_INTERNET) {
		A1_ACTIVE_DEVICE_WITHOUT_INTERNET = a1_ACTIVE_DEVICE_WITHOUT_INTERNET;
	}
	public BigDecimal getA1_NOT_ACTIVE_DEVICES() {
		return A1_NOT_ACTIVE_DEVICES;
	}
	public void setA1_NOT_ACTIVE_DEVICES(BigDecimal a1_NOT_ACTIVE_DEVICES) {
		A1_NOT_ACTIVE_DEVICES = a1_NOT_ACTIVE_DEVICES;
	}
	public String getA2_PRODUCT() {
		return A2_PRODUCT;
	}
	public void setA2_PRODUCT(String a2_PRODUCT) {
		A2_PRODUCT = a2_PRODUCT;
	}
	public String getA3_PRODUCT() {
		return A3_PRODUCT;
	}
	public void setA3_PRODUCT(String a3_PRODUCT) {
		A3_PRODUCT = a3_PRODUCT;
	}
	public BigDecimal getA3_ACTIVE_DEVICE_WITH_INTERNET() {
		return A3_ACTIVE_DEVICE_WITH_INTERNET;
	}
	public void setA3_ACTIVE_DEVICE_WITH_INTERNET(BigDecimal a3_ACTIVE_DEVICE_WITH_INTERNET) {
		A3_ACTIVE_DEVICE_WITH_INTERNET = a3_ACTIVE_DEVICE_WITH_INTERNET;
	}
	public BigDecimal getA3_ACTIVE_DEVICE_WITHOUT_INTERNET() {
		return A3_ACTIVE_DEVICE_WITHOUT_INTERNET;
	}
	public void setA3_ACTIVE_DEVICE_WITHOUT_INTERNET(BigDecimal a3_ACTIVE_DEVICE_WITHOUT_INTERNET) {
		A3_ACTIVE_DEVICE_WITHOUT_INTERNET = a3_ACTIVE_DEVICE_WITHOUT_INTERNET;
	}
	public BigDecimal getA3_NOT_ACTIVE_DEVICES() {
		return A3_NOT_ACTIVE_DEVICES;
	}
	public void setA3_NOT_ACTIVE_DEVICES(BigDecimal a3_NOT_ACTIVE_DEVICES) {
		A3_NOT_ACTIVE_DEVICES = a3_NOT_ACTIVE_DEVICES;
	}
	public String getA4_PRODUCT() {
		return A4_PRODUCT;
	}
	public void setA4_PRODUCT(String a4_PRODUCT) {
		A4_PRODUCT = a4_PRODUCT;
	}
	public BigDecimal getA4_ACTIVE_DEVICE_WITH_INTERNET() {
		return A4_ACTIVE_DEVICE_WITH_INTERNET;
	}
	public void setA4_ACTIVE_DEVICE_WITH_INTERNET(BigDecimal a4_ACTIVE_DEVICE_WITH_INTERNET) {
		A4_ACTIVE_DEVICE_WITH_INTERNET = a4_ACTIVE_DEVICE_WITH_INTERNET;
	}
	public BigDecimal getA4_ACTIVE_DEVICE_WITHOUT_INTERNET() {
		return A4_ACTIVE_DEVICE_WITHOUT_INTERNET;
	}
	public void setA4_ACTIVE_DEVICE_WITHOUT_INTERNET(BigDecimal a4_ACTIVE_DEVICE_WITHOUT_INTERNET) {
		A4_ACTIVE_DEVICE_WITHOUT_INTERNET = a4_ACTIVE_DEVICE_WITHOUT_INTERNET;
	}
	public BigDecimal getA4_NOT_ACTIVE_DEVICES() {
		return A4_NOT_ACTIVE_DEVICES;
	}
	public void setA4_NOT_ACTIVE_DEVICES(BigDecimal a4_NOT_ACTIVE_DEVICES) {
		A4_NOT_ACTIVE_DEVICES = a4_NOT_ACTIVE_DEVICES;
	}
	public String getA5_PRODUCT() {
		return A5_PRODUCT;
	}
	public void setA5_PRODUCT(String a5_PRODUCT) {
		A5_PRODUCT = a5_PRODUCT;
	}
	public BigDecimal getA5_ACTIVE_DEVICE_WITH_INTERNET() {
		return A5_ACTIVE_DEVICE_WITH_INTERNET;
	}
	public void setA5_ACTIVE_DEVICE_WITH_INTERNET(BigDecimal a5_ACTIVE_DEVICE_WITH_INTERNET) {
		A5_ACTIVE_DEVICE_WITH_INTERNET = a5_ACTIVE_DEVICE_WITH_INTERNET;
	}
	public BigDecimal getA5_ACTIVE_DEVICE_WITHOUT_INTERNET() {
		return A5_ACTIVE_DEVICE_WITHOUT_INTERNET;
	}
	public void setA5_ACTIVE_DEVICE_WITHOUT_INTERNET(BigDecimal a5_ACTIVE_DEVICE_WITHOUT_INTERNET) {
		A5_ACTIVE_DEVICE_WITHOUT_INTERNET = a5_ACTIVE_DEVICE_WITHOUT_INTERNET;
	}
	public BigDecimal getA5_NOT_ACTIVE_DEVICES() {
		return A5_NOT_ACTIVE_DEVICES;
	}
	public void setA5_NOT_ACTIVE_DEVICES(BigDecimal a5_NOT_ACTIVE_DEVICES) {
		A5_NOT_ACTIVE_DEVICES = a5_NOT_ACTIVE_DEVICES;
	}
	public String getA6_PRODUCT() {
		return A6_PRODUCT;
	}
	public void setA6_PRODUCT(String a6_PRODUCT) {
		A6_PRODUCT = a6_PRODUCT;
	}
	public BigDecimal getA6_ACTIVE_DEVICE_WITH_INTERNET() {
		return A6_ACTIVE_DEVICE_WITH_INTERNET;
	}
	public void setA6_ACTIVE_DEVICE_WITH_INTERNET(BigDecimal a6_ACTIVE_DEVICE_WITH_INTERNET) {
		A6_ACTIVE_DEVICE_WITH_INTERNET = a6_ACTIVE_DEVICE_WITH_INTERNET;
	}
	public BigDecimal getA6_ACTIVE_DEVICE_WITHOUT_INTERNET() {
		return A6_ACTIVE_DEVICE_WITHOUT_INTERNET;
	}
	public void setA6_ACTIVE_DEVICE_WITHOUT_INTERNET(BigDecimal a6_ACTIVE_DEVICE_WITHOUT_INTERNET) {
		A6_ACTIVE_DEVICE_WITHOUT_INTERNET = a6_ACTIVE_DEVICE_WITHOUT_INTERNET;
	}
	public BigDecimal getA6_NOT_ACTIVE_DEVICES() {
		return A6_NOT_ACTIVE_DEVICES;
	}
	public void setA6_NOT_ACTIVE_DEVICES(BigDecimal a6_NOT_ACTIVE_DEVICES) {
		A6_NOT_ACTIVE_DEVICES = a6_NOT_ACTIVE_DEVICES;
	}
	public String getA7_PRODUCT() {
		return A7_PRODUCT;
	}
	public void setA7_PRODUCT(String a7_PRODUCT) {
		A7_PRODUCT = a7_PRODUCT;
	}
	public BigDecimal getA7_ACTIVE_DEVICE_WITH_INTERNET() {
		return A7_ACTIVE_DEVICE_WITH_INTERNET;
	}
	public void setA7_ACTIVE_DEVICE_WITH_INTERNET(BigDecimal a7_ACTIVE_DEVICE_WITH_INTERNET) {
		A7_ACTIVE_DEVICE_WITH_INTERNET = a7_ACTIVE_DEVICE_WITH_INTERNET;
	}
	public BigDecimal getA7_ACTIVE_DEVICE_WITHOUT_INTERNET() {
		return A7_ACTIVE_DEVICE_WITHOUT_INTERNET;
	}
	public void setA7_ACTIVE_DEVICE_WITHOUT_INTERNET(BigDecimal a7_ACTIVE_DEVICE_WITHOUT_INTERNET) {
		A7_ACTIVE_DEVICE_WITHOUT_INTERNET = a7_ACTIVE_DEVICE_WITHOUT_INTERNET;
	}
	public BigDecimal getA7_NOT_ACTIVE_DEVICES() {
		return A7_NOT_ACTIVE_DEVICES;
	}
	public void setA7_NOT_ACTIVE_DEVICES(BigDecimal a7_NOT_ACTIVE_DEVICES) {
		A7_NOT_ACTIVE_DEVICES = a7_NOT_ACTIVE_DEVICES;
	}
	public String getA8_PRODUCT() {
		return A8_PRODUCT;
	}
	public void setA8_PRODUCT(String a8_PRODUCT) {
		A8_PRODUCT = a8_PRODUCT;
	}
	public BigDecimal getA8_ACTIVE_DEVICE_WITH_INTERNET() {
		return A8_ACTIVE_DEVICE_WITH_INTERNET;
	}
	public void setA8_ACTIVE_DEVICE_WITH_INTERNET(BigDecimal a8_ACTIVE_DEVICE_WITH_INTERNET) {
		A8_ACTIVE_DEVICE_WITH_INTERNET = a8_ACTIVE_DEVICE_WITH_INTERNET;
	}
	public BigDecimal getA8_ACTIVE_DEVICE_WITHOUT_INTERNET() {
		return A8_ACTIVE_DEVICE_WITHOUT_INTERNET;
	}
	public void setA8_ACTIVE_DEVICE_WITHOUT_INTERNET(BigDecimal a8_ACTIVE_DEVICE_WITHOUT_INTERNET) {
		A8_ACTIVE_DEVICE_WITHOUT_INTERNET = a8_ACTIVE_DEVICE_WITHOUT_INTERNET;
	}
	public BigDecimal getA8_NOT_ACTIVE_DEVICES() {
		return A8_NOT_ACTIVE_DEVICES;
	}
	public void setA8_NOT_ACTIVE_DEVICES(BigDecimal a8_NOT_ACTIVE_DEVICES) {
		A8_NOT_ACTIVE_DEVICES = a8_NOT_ACTIVE_DEVICES;
	}
	public String getA9_PRODUCT() {
		return A9_PRODUCT;
	}
	public void setA9_PRODUCT(String a9_PRODUCT) {
		A9_PRODUCT = a9_PRODUCT;
	}
	public BigDecimal getA9_ACTIVE_DEVICE_WITH_INTERNET() {
		return A9_ACTIVE_DEVICE_WITH_INTERNET;
	}
	public void setA9_ACTIVE_DEVICE_WITH_INTERNET(BigDecimal a9_ACTIVE_DEVICE_WITH_INTERNET) {
		A9_ACTIVE_DEVICE_WITH_INTERNET = a9_ACTIVE_DEVICE_WITH_INTERNET;
	}
	public BigDecimal getA9_ACTIVE_DEVICE_WITHOUT_INTERNET() {
		return A9_ACTIVE_DEVICE_WITHOUT_INTERNET;
	}
	public void setA9_ACTIVE_DEVICE_WITHOUT_INTERNET(BigDecimal a9_ACTIVE_DEVICE_WITHOUT_INTERNET) {
		A9_ACTIVE_DEVICE_WITHOUT_INTERNET = a9_ACTIVE_DEVICE_WITHOUT_INTERNET;
	}
	public BigDecimal getA9_NOT_ACTIVE_DEVICES() {
		return A9_NOT_ACTIVE_DEVICES;
	}
	public void setA9_NOT_ACTIVE_DEVICES(BigDecimal a9_NOT_ACTIVE_DEVICES) {
		A9_NOT_ACTIVE_DEVICES = a9_NOT_ACTIVE_DEVICES;
	}
	public String getA10_PRODUCT() {
		return A10_PRODUCT;
	}
	public void setA10_PRODUCT(String a10_PRODUCT) {
		A10_PRODUCT = a10_PRODUCT;
	}
	public BigDecimal getA10_ACTIVE_DEVICE_WITH_INTERNET() {
		return A10_ACTIVE_DEVICE_WITH_INTERNET;
	}
	public void setA10_ACTIVE_DEVICE_WITH_INTERNET(BigDecimal a10_ACTIVE_DEVICE_WITH_INTERNET) {
		A10_ACTIVE_DEVICE_WITH_INTERNET = a10_ACTIVE_DEVICE_WITH_INTERNET;
	}
	public BigDecimal getA10_ACTIVE_DEVICE_WITHOUT_INTERNET() {
		return A10_ACTIVE_DEVICE_WITHOUT_INTERNET;
	}
	public void setA10_ACTIVE_DEVICE_WITHOUT_INTERNET(BigDecimal a10_ACTIVE_DEVICE_WITHOUT_INTERNET) {
		A10_ACTIVE_DEVICE_WITHOUT_INTERNET = a10_ACTIVE_DEVICE_WITHOUT_INTERNET;
	}
	public BigDecimal getA10_NOT_ACTIVE_DEVICES() {
		return A10_NOT_ACTIVE_DEVICES;
	}
	public void setA10_NOT_ACTIVE_DEVICES(BigDecimal a10_NOT_ACTIVE_DEVICES) {
		A10_NOT_ACTIVE_DEVICES = a10_NOT_ACTIVE_DEVICES;
	}
	public String getA11_PRODUCT() {
		return A11_PRODUCT;
	}
	public void setA11_PRODUCT(String a11_PRODUCT) {
		A11_PRODUCT = a11_PRODUCT;
	}
	public BigDecimal getA11_ACTIVE_DEVICE_WITH_INTERNET() {
		return A11_ACTIVE_DEVICE_WITH_INTERNET;
	}
	public void setA11_ACTIVE_DEVICE_WITH_INTERNET(BigDecimal a11_ACTIVE_DEVICE_WITH_INTERNET) {
		A11_ACTIVE_DEVICE_WITH_INTERNET = a11_ACTIVE_DEVICE_WITH_INTERNET;
	}
	public BigDecimal getA11_ACTIVE_DEVICE_WITHOUT_INTERNET() {
		return A11_ACTIVE_DEVICE_WITHOUT_INTERNET;
	}
	public void setA11_ACTIVE_DEVICE_WITHOUT_INTERNET(BigDecimal a11_ACTIVE_DEVICE_WITHOUT_INTERNET) {
		A11_ACTIVE_DEVICE_WITHOUT_INTERNET = a11_ACTIVE_DEVICE_WITHOUT_INTERNET;
	}
	public BigDecimal getA11_NOT_ACTIVE_DEVICES() {
		return A11_NOT_ACTIVE_DEVICES;
	}
	public void setA11_NOT_ACTIVE_DEVICES(BigDecimal a11_NOT_ACTIVE_DEVICES) {
		A11_NOT_ACTIVE_DEVICES = a11_NOT_ACTIVE_DEVICES;
	}
	public String getA12_PRODUCT() {
		return A12_PRODUCT;
	}
	public void setA12_PRODUCT(String a12_PRODUCT) {
		A12_PRODUCT = a12_PRODUCT;
	}
	public BigDecimal getA12_ACTIVE_DEVICE_WITH_INTERNET() {
		return A12_ACTIVE_DEVICE_WITH_INTERNET;
	}
	public void setA12_ACTIVE_DEVICE_WITH_INTERNET(BigDecimal a12_ACTIVE_DEVICE_WITH_INTERNET) {
		A12_ACTIVE_DEVICE_WITH_INTERNET = a12_ACTIVE_DEVICE_WITH_INTERNET;
	}
	public BigDecimal getA12_ACTIVE_DEVICE_WITHOUT_INTERNET() {
		return A12_ACTIVE_DEVICE_WITHOUT_INTERNET;
	}
	public void setA12_ACTIVE_DEVICE_WITHOUT_INTERNET(BigDecimal a12_ACTIVE_DEVICE_WITHOUT_INTERNET) {
		A12_ACTIVE_DEVICE_WITHOUT_INTERNET = a12_ACTIVE_DEVICE_WITHOUT_INTERNET;
	}
	public BigDecimal getA12_NOT_ACTIVE_DEVICES() {
		return A12_NOT_ACTIVE_DEVICES;
	}
	public void setA12_NOT_ACTIVE_DEVICES(BigDecimal a12_NOT_ACTIVE_DEVICES) {
		A12_NOT_ACTIVE_DEVICES = a12_NOT_ACTIVE_DEVICES;
	}
	public String getA13_PRODUCT() {
		return A13_PRODUCT;
	}
	public void setA13_PRODUCT(String a13_PRODUCT) {
		A13_PRODUCT = a13_PRODUCT;
	}
	public BigDecimal getA13_ACTIVE_DEVICE_WITH_INTERNET() {
		return A13_ACTIVE_DEVICE_WITH_INTERNET;
	}
	public void setA13_ACTIVE_DEVICE_WITH_INTERNET(BigDecimal a13_ACTIVE_DEVICE_WITH_INTERNET) {
		A13_ACTIVE_DEVICE_WITH_INTERNET = a13_ACTIVE_DEVICE_WITH_INTERNET;
	}
	public BigDecimal getA13_ACTIVE_DEVICE_WITHOUT_INTERNET() {
		return A13_ACTIVE_DEVICE_WITHOUT_INTERNET;
	}
	public void setA13_ACTIVE_DEVICE_WITHOUT_INTERNET(BigDecimal a13_ACTIVE_DEVICE_WITHOUT_INTERNET) {
		A13_ACTIVE_DEVICE_WITHOUT_INTERNET = a13_ACTIVE_DEVICE_WITHOUT_INTERNET;
	}
	public BigDecimal getA13_NOT_ACTIVE_DEVICES() {
		return A13_NOT_ACTIVE_DEVICES;
	}
	public void setA13_NOT_ACTIVE_DEVICES(BigDecimal a13_NOT_ACTIVE_DEVICES) {
		A13_NOT_ACTIVE_DEVICES = a13_NOT_ACTIVE_DEVICES;
	}
	public String getA14_PRODUCT() {
		return A14_PRODUCT;
	}
	public void setA14_PRODUCT(String a14_PRODUCT) {
		A14_PRODUCT = a14_PRODUCT;
	}
	public BigDecimal getA14_ACTIVE_DEVICE_WITH_INTERNET() {
		return A14_ACTIVE_DEVICE_WITH_INTERNET;
	}
	public void setA14_ACTIVE_DEVICE_WITH_INTERNET(BigDecimal a14_ACTIVE_DEVICE_WITH_INTERNET) {
		A14_ACTIVE_DEVICE_WITH_INTERNET = a14_ACTIVE_DEVICE_WITH_INTERNET;
	}
	public BigDecimal getA14_ACTIVE_DEVICE_WITHOUT_INTERNET() {
		return A14_ACTIVE_DEVICE_WITHOUT_INTERNET;
	}
	public void setA14_ACTIVE_DEVICE_WITHOUT_INTERNET(BigDecimal a14_ACTIVE_DEVICE_WITHOUT_INTERNET) {
		A14_ACTIVE_DEVICE_WITHOUT_INTERNET = a14_ACTIVE_DEVICE_WITHOUT_INTERNET;
	}
	public BigDecimal getA14_NOT_ACTIVE_DEVICES() {
		return A14_NOT_ACTIVE_DEVICES;
	}
	public void setA14_NOT_ACTIVE_DEVICES(BigDecimal a14_NOT_ACTIVE_DEVICES) {
		A14_NOT_ACTIVE_DEVICES = a14_NOT_ACTIVE_DEVICES;
	}
	public String getA15_PRODUCT() {
		return A15_PRODUCT;
	}
	public void setA15_PRODUCT(String a15_PRODUCT) {
		A15_PRODUCT = a15_PRODUCT;
	}
	public BigDecimal getA15_ACTIVE_DEVICE_WITH_INTERNET() {
		return A15_ACTIVE_DEVICE_WITH_INTERNET;
	}
	public void setA15_ACTIVE_DEVICE_WITH_INTERNET(BigDecimal a15_ACTIVE_DEVICE_WITH_INTERNET) {
		A15_ACTIVE_DEVICE_WITH_INTERNET = a15_ACTIVE_DEVICE_WITH_INTERNET;
	}
	public BigDecimal getA15_ACTIVE_DEVICE_WITHOUT_INTERNET() {
		return A15_ACTIVE_DEVICE_WITHOUT_INTERNET;
	}
	public void setA15_ACTIVE_DEVICE_WITHOUT_INTERNET(BigDecimal a15_ACTIVE_DEVICE_WITHOUT_INTERNET) {
		A15_ACTIVE_DEVICE_WITHOUT_INTERNET = a15_ACTIVE_DEVICE_WITHOUT_INTERNET;
	}
	public BigDecimal getA15_NOT_ACTIVE_DEVICES() {
		return A15_NOT_ACTIVE_DEVICES;
	}
	public void setA15_NOT_ACTIVE_DEVICES(BigDecimal a15_NOT_ACTIVE_DEVICES) {
		A15_NOT_ACTIVE_DEVICES = a15_NOT_ACTIVE_DEVICES;
	}
	public String getA16_PRODUCT() {
		return A16_PRODUCT;
	}
	public void setA16_PRODUCT(String a16_PRODUCT) {
		A16_PRODUCT = a16_PRODUCT;
	}
	public String getA17_PRODUCT() {
		return A17_PRODUCT;
	}
	public void setA17_PRODUCT(String a17_PRODUCT) {
		A17_PRODUCT = a17_PRODUCT;
	}
	public BigDecimal getA17_ACTIVE_DEVICE_WITH_INTERNET() {
		return A17_ACTIVE_DEVICE_WITH_INTERNET;
	}
	public void setA17_ACTIVE_DEVICE_WITH_INTERNET(BigDecimal a17_ACTIVE_DEVICE_WITH_INTERNET) {
		A17_ACTIVE_DEVICE_WITH_INTERNET = a17_ACTIVE_DEVICE_WITH_INTERNET;
	}
	public BigDecimal getA17_ACTIVE_DEVICE_WITHOUT_INTERNET() {
		return A17_ACTIVE_DEVICE_WITHOUT_INTERNET;
	}
	public void setA17_ACTIVE_DEVICE_WITHOUT_INTERNET(BigDecimal a17_ACTIVE_DEVICE_WITHOUT_INTERNET) {
		A17_ACTIVE_DEVICE_WITHOUT_INTERNET = a17_ACTIVE_DEVICE_WITHOUT_INTERNET;
	}
	public BigDecimal getA17_NOT_ACTIVE_DEVICES() {
		return A17_NOT_ACTIVE_DEVICES;
	}
	public void setA17_NOT_ACTIVE_DEVICES(BigDecimal a17_NOT_ACTIVE_DEVICES) {
		A17_NOT_ACTIVE_DEVICES = a17_NOT_ACTIVE_DEVICES;
	}
	public String getA18_PRODUCT() {
		return A18_PRODUCT;
	}
	public void setA18_PRODUCT(String a18_PRODUCT) {
		A18_PRODUCT = a18_PRODUCT;
	}
	public BigDecimal getA18_ACTIVE_DEVICE_WITH_INTERNET() {
		return A18_ACTIVE_DEVICE_WITH_INTERNET;
	}
	public void setA18_ACTIVE_DEVICE_WITH_INTERNET(BigDecimal a18_ACTIVE_DEVICE_WITH_INTERNET) {
		A18_ACTIVE_DEVICE_WITH_INTERNET = a18_ACTIVE_DEVICE_WITH_INTERNET;
	}
	public BigDecimal getA18_ACTIVE_DEVICE_WITHOUT_INTERNET() {
		return A18_ACTIVE_DEVICE_WITHOUT_INTERNET;
	}
	public void setA18_ACTIVE_DEVICE_WITHOUT_INTERNET(BigDecimal a18_ACTIVE_DEVICE_WITHOUT_INTERNET) {
		A18_ACTIVE_DEVICE_WITHOUT_INTERNET = a18_ACTIVE_DEVICE_WITHOUT_INTERNET;
	}
	public BigDecimal getA18_NOT_ACTIVE_DEVICES() {
		return A18_NOT_ACTIVE_DEVICES;
	}
	public void setA18_NOT_ACTIVE_DEVICES(BigDecimal a18_NOT_ACTIVE_DEVICES) {
		A18_NOT_ACTIVE_DEVICES = a18_NOT_ACTIVE_DEVICES;
	}
	public String getA19_PRODUCT() {
		return A19_PRODUCT;
	}
	public void setA19_PRODUCT(String a19_PRODUCT) {
		A19_PRODUCT = a19_PRODUCT;
	}
	public BigDecimal getA19_ACTIVE_DEVICE_WITH_INTERNET() {
		return A19_ACTIVE_DEVICE_WITH_INTERNET;
	}
	public void setA19_ACTIVE_DEVICE_WITH_INTERNET(BigDecimal a19_ACTIVE_DEVICE_WITH_INTERNET) {
		A19_ACTIVE_DEVICE_WITH_INTERNET = a19_ACTIVE_DEVICE_WITH_INTERNET;
	}
	public BigDecimal getA19_ACTIVE_DEVICE_WITHOUT_INTERNET() {
		return A19_ACTIVE_DEVICE_WITHOUT_INTERNET;
	}
	public void setA19_ACTIVE_DEVICE_WITHOUT_INTERNET(BigDecimal a19_ACTIVE_DEVICE_WITHOUT_INTERNET) {
		A19_ACTIVE_DEVICE_WITHOUT_INTERNET = a19_ACTIVE_DEVICE_WITHOUT_INTERNET;
	}
	public BigDecimal getA19_NOT_ACTIVE_DEVICES() {
		return A19_NOT_ACTIVE_DEVICES;
	}
	public void setA19_NOT_ACTIVE_DEVICES(BigDecimal a19_NOT_ACTIVE_DEVICES) {
		A19_NOT_ACTIVE_DEVICES = a19_NOT_ACTIVE_DEVICES;
	}
	public String getA20_PRODUCT() {
		return A20_PRODUCT;
	}
	public void setA20_PRODUCT(String a20_PRODUCT) {
		A20_PRODUCT = a20_PRODUCT;
	}
	public BigDecimal getA20_ACTIVE_DEVICE_WITH_INTERNET() {
		return A20_ACTIVE_DEVICE_WITH_INTERNET;
	}
	public void setA20_ACTIVE_DEVICE_WITH_INTERNET(BigDecimal a20_ACTIVE_DEVICE_WITH_INTERNET) {
		A20_ACTIVE_DEVICE_WITH_INTERNET = a20_ACTIVE_DEVICE_WITH_INTERNET;
	}
	public BigDecimal getA20_ACTIVE_DEVICE_WITHOUT_INTERNET() {
		return A20_ACTIVE_DEVICE_WITHOUT_INTERNET;
	}
	public void setA20_ACTIVE_DEVICE_WITHOUT_INTERNET(BigDecimal a20_ACTIVE_DEVICE_WITHOUT_INTERNET) {
		A20_ACTIVE_DEVICE_WITHOUT_INTERNET = a20_ACTIVE_DEVICE_WITHOUT_INTERNET;
	}
	public BigDecimal getA20_NOT_ACTIVE_DEVICES() {
		return A20_NOT_ACTIVE_DEVICES;
	}
	public void setA20_NOT_ACTIVE_DEVICES(BigDecimal a20_NOT_ACTIVE_DEVICES) {
		A20_NOT_ACTIVE_DEVICES = a20_NOT_ACTIVE_DEVICES;
	}
	public String getA21_PRODUCT() {
		return A21_PRODUCT;
	}
	public void setA21_PRODUCT(String a21_PRODUCT) {
		A21_PRODUCT = a21_PRODUCT;
	}
	public BigDecimal getA21_ACTIVE_DEVICE_WITH_INTERNET() {
		return A21_ACTIVE_DEVICE_WITH_INTERNET;
	}
	public void setA21_ACTIVE_DEVICE_WITH_INTERNET(BigDecimal a21_ACTIVE_DEVICE_WITH_INTERNET) {
		A21_ACTIVE_DEVICE_WITH_INTERNET = a21_ACTIVE_DEVICE_WITH_INTERNET;
	}
	public BigDecimal getA21_ACTIVE_DEVICE_WITHOUT_INTERNET() {
		return A21_ACTIVE_DEVICE_WITHOUT_INTERNET;
	}
	public void setA21_ACTIVE_DEVICE_WITHOUT_INTERNET(BigDecimal a21_ACTIVE_DEVICE_WITHOUT_INTERNET) {
		A21_ACTIVE_DEVICE_WITHOUT_INTERNET = a21_ACTIVE_DEVICE_WITHOUT_INTERNET;
	}
	public BigDecimal getA21_NOT_ACTIVE_DEVICES() {
		return A21_NOT_ACTIVE_DEVICES;
	}
	public void setA21_NOT_ACTIVE_DEVICES(BigDecimal a21_NOT_ACTIVE_DEVICES) {
		A21_NOT_ACTIVE_DEVICES = a21_NOT_ACTIVE_DEVICES;
	}
	public String getA22_PRODUCT() {
		return A22_PRODUCT;
	}
	public void setA22_PRODUCT(String a22_PRODUCT) {
		A22_PRODUCT = a22_PRODUCT;
	}
	public BigDecimal getA22_ACTIVE_DEVICE_WITH_INTERNET() {
		return A22_ACTIVE_DEVICE_WITH_INTERNET;
	}
	public void setA22_ACTIVE_DEVICE_WITH_INTERNET(BigDecimal a22_ACTIVE_DEVICE_WITH_INTERNET) {
		A22_ACTIVE_DEVICE_WITH_INTERNET = a22_ACTIVE_DEVICE_WITH_INTERNET;
	}
	public BigDecimal getA22_ACTIVE_DEVICE_WITHOUT_INTERNET() {
		return A22_ACTIVE_DEVICE_WITHOUT_INTERNET;
	}
	public void setA22_ACTIVE_DEVICE_WITHOUT_INTERNET(BigDecimal a22_ACTIVE_DEVICE_WITHOUT_INTERNET) {
		A22_ACTIVE_DEVICE_WITHOUT_INTERNET = a22_ACTIVE_DEVICE_WITHOUT_INTERNET;
	}
	public BigDecimal getA22_NOT_ACTIVE_DEVICES() {
		return A22_NOT_ACTIVE_DEVICES;
	}
	public void setA22_NOT_ACTIVE_DEVICES(BigDecimal a22_NOT_ACTIVE_DEVICES) {
		A22_NOT_ACTIVE_DEVICES = a22_NOT_ACTIVE_DEVICES;
	}
	public String getA23_PRODUCT() {
		return A23_PRODUCT;
	}
	public void setA23_PRODUCT(String a23_PRODUCT) {
		A23_PRODUCT = a23_PRODUCT;
	}
	public BigDecimal getA23_ACTIVE_DEVICE_WITH_INTERNET() {
		return A23_ACTIVE_DEVICE_WITH_INTERNET;
	}
	public void setA23_ACTIVE_DEVICE_WITH_INTERNET(BigDecimal a23_ACTIVE_DEVICE_WITH_INTERNET) {
		A23_ACTIVE_DEVICE_WITH_INTERNET = a23_ACTIVE_DEVICE_WITH_INTERNET;
	}
	public BigDecimal getA23_ACTIVE_DEVICE_WITHOUT_INTERNET() {
		return A23_ACTIVE_DEVICE_WITHOUT_INTERNET;
	}
	public void setA23_ACTIVE_DEVICE_WITHOUT_INTERNET(BigDecimal a23_ACTIVE_DEVICE_WITHOUT_INTERNET) {
		A23_ACTIVE_DEVICE_WITHOUT_INTERNET = a23_ACTIVE_DEVICE_WITHOUT_INTERNET;
	}
	public BigDecimal getA23_NOT_ACTIVE_DEVICES() {
		return A23_NOT_ACTIVE_DEVICES;
	}
	public void setA23_NOT_ACTIVE_DEVICES(BigDecimal a23_NOT_ACTIVE_DEVICES) {
		A23_NOT_ACTIVE_DEVICES = a23_NOT_ACTIVE_DEVICES;
	}
	public String getREPORT_CODE() {
		return REPORT_CODE;
	}
	public void setREPORT_CODE(String rEPORT_CODE) {
		REPORT_CODE = rEPORT_CODE;
	}
	public String getREPORT_NAME() {
		return REPORT_NAME;
	}
	public void setREPORT_NAME(String rEPORT_NAME) {
		REPORT_NAME = rEPORT_NAME;
	}
	public Date getREPORT_DATE() {
		return REPORT_DATE;
	}
	public void setREPORT_DATE(Date rEPORT_DATE) {
		REPORT_DATE = rEPORT_DATE;
	}
	public Date getREPORT_DUE_DATE() {
		return REPORT_DUE_DATE;
	}
	public void setREPORT_DUE_DATE(Date rEPORT_DUE_DATE) {
		REPORT_DUE_DATE = rEPORT_DUE_DATE;
	}
	public Date getREP_SUBMIT_DATE() {
		return REP_SUBMIT_DATE;
	}
	public void setREP_SUBMIT_DATE(Date rEP_SUBMIT_DATE) {
		REP_SUBMIT_DATE = rEP_SUBMIT_DATE;
	}
	public Date getREP_PERIOD_FROM() {
		return REP_PERIOD_FROM;
	}
	public void setREP_PERIOD_FROM(Date rEP_PERIOD_FROM) {
		REP_PERIOD_FROM = rEP_PERIOD_FROM;
	}
	public Date getREP_PERIOD_TO() {
		return REP_PERIOD_TO;
	}
	public void setREP_PERIOD_TO(Date rEP_PERIOD_TO) {
		REP_PERIOD_TO = rEP_PERIOD_TO;
	}
	public String getREP_FREQ() {
		return REP_FREQ;
	}
	public void setREP_FREQ(String rEP_FREQ) {
		REP_FREQ = rEP_FREQ;
	}
	public String getNIL_REPORT_FLG() {
		return NIL_REPORT_FLG;
	}
	public void setNIL_REPORT_FLG(String nIL_REPORT_FLG) {
		NIL_REPORT_FLG = nIL_REPORT_FLG;
	}
	public String getARCH_FLG() {
		return ARCH_FLG;
	}
	public void setARCH_FLG(String aRCH_FLG) {
		ARCH_FLG = aRCH_FLG;
	}
	public String getENTITY_FLG() {
		return ENTITY_FLG;
	}
	public void setENTITY_FLG(String eNTITY_FLG) {
		ENTITY_FLG = eNTITY_FLG;
	}
	public String getDEL_FLG() {
		return DEL_FLG;
	}
	public void setDEL_FLG(String dEL_FLG) {
		DEL_FLG = dEL_FLG;
	}
	public String getMODIFY_FLG() {
		return MODIFY_FLG;
	}
	public void setMODIFY_FLG(String mODIFY_FLG) {
		MODIFY_FLG = mODIFY_FLG;
	}
	public String getENTRY_USER() {
		return ENTRY_USER;
	}
	public void setENTRY_USER(String eNTRY_USER) {
		ENTRY_USER = eNTRY_USER;
	}
	public String getMODIFY_USER() {
		return MODIFY_USER;
	}
	public void setMODIFY_USER(String mODIFY_USER) {
		MODIFY_USER = mODIFY_USER;
	}
	public String getVERIFY_USER() {
		return VERIFY_USER;
	}
	public void setVERIFY_USER(String vERIFY_USER) {
		VERIFY_USER = vERIFY_USER;
	}
	public Date getENTRY_TIME() {
		return ENTRY_TIME;
	}
	public void setENTRY_TIME(Date eNTRY_TIME) {
		ENTRY_TIME = eNTRY_TIME;
	}
	public Date getMODIFY_TIME() {
		return MODIFY_TIME;
	}
	public void setMODIFY_TIME(Date mODIFY_TIME) {
		MODIFY_TIME = mODIFY_TIME;
	}
	public Date getVERIFY_TIME() {
		return VERIFY_TIME;
	}
	public void setVERIFY_TIME(Date vERIFY_TIME) {
		VERIFY_TIME = vERIFY_TIME;
	}
	public String getQTR_FLG() {
		return QTR_FLG;
	}
	public void setQTR_FLG(String qTR_FLG) {
		QTR_FLG = qTR_FLG;
	}
	public T32ORReport(String a1_PRODUCT, BigDecimal a1_ACTIVE_DEVICE_WITH_INTERNET,
			BigDecimal a1_ACTIVE_DEVICE_WITHOUT_INTERNET, BigDecimal a1_NOT_ACTIVE_DEVICES, String a2_PRODUCT,
			String a3_PRODUCT, BigDecimal a3_ACTIVE_DEVICE_WITH_INTERNET, BigDecimal a3_ACTIVE_DEVICE_WITHOUT_INTERNET,
			BigDecimal a3_NOT_ACTIVE_DEVICES, String a4_PRODUCT, BigDecimal a4_ACTIVE_DEVICE_WITH_INTERNET,
			BigDecimal a4_ACTIVE_DEVICE_WITHOUT_INTERNET, BigDecimal a4_NOT_ACTIVE_DEVICES, String a5_PRODUCT,
			BigDecimal a5_ACTIVE_DEVICE_WITH_INTERNET, BigDecimal a5_ACTIVE_DEVICE_WITHOUT_INTERNET,
			BigDecimal a5_NOT_ACTIVE_DEVICES, String a6_PRODUCT, BigDecimal a6_ACTIVE_DEVICE_WITH_INTERNET,
			BigDecimal a6_ACTIVE_DEVICE_WITHOUT_INTERNET, BigDecimal a6_NOT_ACTIVE_DEVICES, String a7_PRODUCT,
			BigDecimal a7_ACTIVE_DEVICE_WITH_INTERNET, BigDecimal a7_ACTIVE_DEVICE_WITHOUT_INTERNET,
			BigDecimal a7_NOT_ACTIVE_DEVICES, String a8_PRODUCT, BigDecimal a8_ACTIVE_DEVICE_WITH_INTERNET,
			BigDecimal a8_ACTIVE_DEVICE_WITHOUT_INTERNET, BigDecimal a8_NOT_ACTIVE_DEVICES, String a9_PRODUCT,
			BigDecimal a9_ACTIVE_DEVICE_WITH_INTERNET, BigDecimal a9_ACTIVE_DEVICE_WITHOUT_INTERNET,
			BigDecimal a9_NOT_ACTIVE_DEVICES, String a10_PRODUCT, BigDecimal a10_ACTIVE_DEVICE_WITH_INTERNET,
			BigDecimal a10_ACTIVE_DEVICE_WITHOUT_INTERNET, BigDecimal a10_NOT_ACTIVE_DEVICES, String a11_PRODUCT,
			BigDecimal a11_ACTIVE_DEVICE_WITH_INTERNET, BigDecimal a11_ACTIVE_DEVICE_WITHOUT_INTERNET,
			BigDecimal a11_NOT_ACTIVE_DEVICES, String a12_PRODUCT, BigDecimal a12_ACTIVE_DEVICE_WITH_INTERNET,
			BigDecimal a12_ACTIVE_DEVICE_WITHOUT_INTERNET, BigDecimal a12_NOT_ACTIVE_DEVICES, String a13_PRODUCT,
			BigDecimal a13_ACTIVE_DEVICE_WITH_INTERNET, BigDecimal a13_ACTIVE_DEVICE_WITHOUT_INTERNET,
			BigDecimal a13_NOT_ACTIVE_DEVICES, String a14_PRODUCT, BigDecimal a14_ACTIVE_DEVICE_WITH_INTERNET,
			BigDecimal a14_ACTIVE_DEVICE_WITHOUT_INTERNET, BigDecimal a14_NOT_ACTIVE_DEVICES, String a15_PRODUCT,
			BigDecimal a15_ACTIVE_DEVICE_WITH_INTERNET, BigDecimal a15_ACTIVE_DEVICE_WITHOUT_INTERNET,
			BigDecimal a15_NOT_ACTIVE_DEVICES, String a16_PRODUCT, String a17_PRODUCT,
			BigDecimal a17_ACTIVE_DEVICE_WITH_INTERNET, BigDecimal a17_ACTIVE_DEVICE_WITHOUT_INTERNET,
			BigDecimal a17_NOT_ACTIVE_DEVICES, String a18_PRODUCT, BigDecimal a18_ACTIVE_DEVICE_WITH_INTERNET,
			BigDecimal a18_ACTIVE_DEVICE_WITHOUT_INTERNET, BigDecimal a18_NOT_ACTIVE_DEVICES, String a19_PRODUCT,
			BigDecimal a19_ACTIVE_DEVICE_WITH_INTERNET, BigDecimal a19_ACTIVE_DEVICE_WITHOUT_INTERNET,
			BigDecimal a19_NOT_ACTIVE_DEVICES, String a20_PRODUCT, BigDecimal a20_ACTIVE_DEVICE_WITH_INTERNET,
			BigDecimal a20_ACTIVE_DEVICE_WITHOUT_INTERNET, BigDecimal a20_NOT_ACTIVE_DEVICES, String a21_PRODUCT,
			BigDecimal a21_ACTIVE_DEVICE_WITH_INTERNET, BigDecimal a21_ACTIVE_DEVICE_WITHOUT_INTERNET,
			BigDecimal a21_NOT_ACTIVE_DEVICES, String a22_PRODUCT, BigDecimal a22_ACTIVE_DEVICE_WITH_INTERNET,
			BigDecimal a22_ACTIVE_DEVICE_WITHOUT_INTERNET, BigDecimal a22_NOT_ACTIVE_DEVICES, String a23_PRODUCT,
			BigDecimal a23_ACTIVE_DEVICE_WITH_INTERNET, BigDecimal a23_ACTIVE_DEVICE_WITHOUT_INTERNET,
			BigDecimal a23_NOT_ACTIVE_DEVICES, String rEPORT_CODE, String rEPORT_NAME, Date rEPORT_DATE,
			Date rEPORT_DUE_DATE, Date rEP_SUBMIT_DATE, Date rEP_PERIOD_FROM, Date rEP_PERIOD_TO, String rEP_FREQ,
			String nIL_REPORT_FLG, String aRCH_FLG, String eNTITY_FLG, String dEL_FLG, String mODIFY_FLG,
			String eNTRY_USER, String mODIFY_USER, String vERIFY_USER, Date eNTRY_TIME, Date mODIFY_TIME,
			Date vERIFY_TIME, String qTR_FLG) {
		super();
		A1_PRODUCT = a1_PRODUCT;
		A1_ACTIVE_DEVICE_WITH_INTERNET = a1_ACTIVE_DEVICE_WITH_INTERNET;
		A1_ACTIVE_DEVICE_WITHOUT_INTERNET = a1_ACTIVE_DEVICE_WITHOUT_INTERNET;
		A1_NOT_ACTIVE_DEVICES = a1_NOT_ACTIVE_DEVICES;
		A2_PRODUCT = a2_PRODUCT;
		A3_PRODUCT = a3_PRODUCT;
		A3_ACTIVE_DEVICE_WITH_INTERNET = a3_ACTIVE_DEVICE_WITH_INTERNET;
		A3_ACTIVE_DEVICE_WITHOUT_INTERNET = a3_ACTIVE_DEVICE_WITHOUT_INTERNET;
		A3_NOT_ACTIVE_DEVICES = a3_NOT_ACTIVE_DEVICES;
		A4_PRODUCT = a4_PRODUCT;
		A4_ACTIVE_DEVICE_WITH_INTERNET = a4_ACTIVE_DEVICE_WITH_INTERNET;
		A4_ACTIVE_DEVICE_WITHOUT_INTERNET = a4_ACTIVE_DEVICE_WITHOUT_INTERNET;
		A4_NOT_ACTIVE_DEVICES = a4_NOT_ACTIVE_DEVICES;
		A5_PRODUCT = a5_PRODUCT;
		A5_ACTIVE_DEVICE_WITH_INTERNET = a5_ACTIVE_DEVICE_WITH_INTERNET;
		A5_ACTIVE_DEVICE_WITHOUT_INTERNET = a5_ACTIVE_DEVICE_WITHOUT_INTERNET;
		A5_NOT_ACTIVE_DEVICES = a5_NOT_ACTIVE_DEVICES;
		A6_PRODUCT = a6_PRODUCT;
		A6_ACTIVE_DEVICE_WITH_INTERNET = a6_ACTIVE_DEVICE_WITH_INTERNET;
		A6_ACTIVE_DEVICE_WITHOUT_INTERNET = a6_ACTIVE_DEVICE_WITHOUT_INTERNET;
		A6_NOT_ACTIVE_DEVICES = a6_NOT_ACTIVE_DEVICES;
		A7_PRODUCT = a7_PRODUCT;
		A7_ACTIVE_DEVICE_WITH_INTERNET = a7_ACTIVE_DEVICE_WITH_INTERNET;
		A7_ACTIVE_DEVICE_WITHOUT_INTERNET = a7_ACTIVE_DEVICE_WITHOUT_INTERNET;
		A7_NOT_ACTIVE_DEVICES = a7_NOT_ACTIVE_DEVICES;
		A8_PRODUCT = a8_PRODUCT;
		A8_ACTIVE_DEVICE_WITH_INTERNET = a8_ACTIVE_DEVICE_WITH_INTERNET;
		A8_ACTIVE_DEVICE_WITHOUT_INTERNET = a8_ACTIVE_DEVICE_WITHOUT_INTERNET;
		A8_NOT_ACTIVE_DEVICES = a8_NOT_ACTIVE_DEVICES;
		A9_PRODUCT = a9_PRODUCT;
		A9_ACTIVE_DEVICE_WITH_INTERNET = a9_ACTIVE_DEVICE_WITH_INTERNET;
		A9_ACTIVE_DEVICE_WITHOUT_INTERNET = a9_ACTIVE_DEVICE_WITHOUT_INTERNET;
		A9_NOT_ACTIVE_DEVICES = a9_NOT_ACTIVE_DEVICES;
		A10_PRODUCT = a10_PRODUCT;
		A10_ACTIVE_DEVICE_WITH_INTERNET = a10_ACTIVE_DEVICE_WITH_INTERNET;
		A10_ACTIVE_DEVICE_WITHOUT_INTERNET = a10_ACTIVE_DEVICE_WITHOUT_INTERNET;
		A10_NOT_ACTIVE_DEVICES = a10_NOT_ACTIVE_DEVICES;
		A11_PRODUCT = a11_PRODUCT;
		A11_ACTIVE_DEVICE_WITH_INTERNET = a11_ACTIVE_DEVICE_WITH_INTERNET;
		A11_ACTIVE_DEVICE_WITHOUT_INTERNET = a11_ACTIVE_DEVICE_WITHOUT_INTERNET;
		A11_NOT_ACTIVE_DEVICES = a11_NOT_ACTIVE_DEVICES;
		A12_PRODUCT = a12_PRODUCT;
		A12_ACTIVE_DEVICE_WITH_INTERNET = a12_ACTIVE_DEVICE_WITH_INTERNET;
		A12_ACTIVE_DEVICE_WITHOUT_INTERNET = a12_ACTIVE_DEVICE_WITHOUT_INTERNET;
		A12_NOT_ACTIVE_DEVICES = a12_NOT_ACTIVE_DEVICES;
		A13_PRODUCT = a13_PRODUCT;
		A13_ACTIVE_DEVICE_WITH_INTERNET = a13_ACTIVE_DEVICE_WITH_INTERNET;
		A13_ACTIVE_DEVICE_WITHOUT_INTERNET = a13_ACTIVE_DEVICE_WITHOUT_INTERNET;
		A13_NOT_ACTIVE_DEVICES = a13_NOT_ACTIVE_DEVICES;
		A14_PRODUCT = a14_PRODUCT;
		A14_ACTIVE_DEVICE_WITH_INTERNET = a14_ACTIVE_DEVICE_WITH_INTERNET;
		A14_ACTIVE_DEVICE_WITHOUT_INTERNET = a14_ACTIVE_DEVICE_WITHOUT_INTERNET;
		A14_NOT_ACTIVE_DEVICES = a14_NOT_ACTIVE_DEVICES;
		A15_PRODUCT = a15_PRODUCT;
		A15_ACTIVE_DEVICE_WITH_INTERNET = a15_ACTIVE_DEVICE_WITH_INTERNET;
		A15_ACTIVE_DEVICE_WITHOUT_INTERNET = a15_ACTIVE_DEVICE_WITHOUT_INTERNET;
		A15_NOT_ACTIVE_DEVICES = a15_NOT_ACTIVE_DEVICES;
		A16_PRODUCT = a16_PRODUCT;
		A17_PRODUCT = a17_PRODUCT;
		A17_ACTIVE_DEVICE_WITH_INTERNET = a17_ACTIVE_DEVICE_WITH_INTERNET;
		A17_ACTIVE_DEVICE_WITHOUT_INTERNET = a17_ACTIVE_DEVICE_WITHOUT_INTERNET;
		A17_NOT_ACTIVE_DEVICES = a17_NOT_ACTIVE_DEVICES;
		A18_PRODUCT = a18_PRODUCT;
		A18_ACTIVE_DEVICE_WITH_INTERNET = a18_ACTIVE_DEVICE_WITH_INTERNET;
		A18_ACTIVE_DEVICE_WITHOUT_INTERNET = a18_ACTIVE_DEVICE_WITHOUT_INTERNET;
		A18_NOT_ACTIVE_DEVICES = a18_NOT_ACTIVE_DEVICES;
		A19_PRODUCT = a19_PRODUCT;
		A19_ACTIVE_DEVICE_WITH_INTERNET = a19_ACTIVE_DEVICE_WITH_INTERNET;
		A19_ACTIVE_DEVICE_WITHOUT_INTERNET = a19_ACTIVE_DEVICE_WITHOUT_INTERNET;
		A19_NOT_ACTIVE_DEVICES = a19_NOT_ACTIVE_DEVICES;
		A20_PRODUCT = a20_PRODUCT;
		A20_ACTIVE_DEVICE_WITH_INTERNET = a20_ACTIVE_DEVICE_WITH_INTERNET;
		A20_ACTIVE_DEVICE_WITHOUT_INTERNET = a20_ACTIVE_DEVICE_WITHOUT_INTERNET;
		A20_NOT_ACTIVE_DEVICES = a20_NOT_ACTIVE_DEVICES;
		A21_PRODUCT = a21_PRODUCT;
		A21_ACTIVE_DEVICE_WITH_INTERNET = a21_ACTIVE_DEVICE_WITH_INTERNET;
		A21_ACTIVE_DEVICE_WITHOUT_INTERNET = a21_ACTIVE_DEVICE_WITHOUT_INTERNET;
		A21_NOT_ACTIVE_DEVICES = a21_NOT_ACTIVE_DEVICES;
		A22_PRODUCT = a22_PRODUCT;
		A22_ACTIVE_DEVICE_WITH_INTERNET = a22_ACTIVE_DEVICE_WITH_INTERNET;
		A22_ACTIVE_DEVICE_WITHOUT_INTERNET = a22_ACTIVE_DEVICE_WITHOUT_INTERNET;
		A22_NOT_ACTIVE_DEVICES = a22_NOT_ACTIVE_DEVICES;
		A23_PRODUCT = a23_PRODUCT;
		A23_ACTIVE_DEVICE_WITH_INTERNET = a23_ACTIVE_DEVICE_WITH_INTERNET;
		A23_ACTIVE_DEVICE_WITHOUT_INTERNET = a23_ACTIVE_DEVICE_WITHOUT_INTERNET;
		A23_NOT_ACTIVE_DEVICES = a23_NOT_ACTIVE_DEVICES;
		REPORT_CODE = rEPORT_CODE;
		REPORT_NAME = rEPORT_NAME;
		REPORT_DATE = rEPORT_DATE;
		REPORT_DUE_DATE = rEPORT_DUE_DATE;
		REP_SUBMIT_DATE = rEP_SUBMIT_DATE;
		REP_PERIOD_FROM = rEP_PERIOD_FROM;
		REP_PERIOD_TO = rEP_PERIOD_TO;
		REP_FREQ = rEP_FREQ;
		NIL_REPORT_FLG = nIL_REPORT_FLG;
		ARCH_FLG = aRCH_FLG;
		ENTITY_FLG = eNTITY_FLG;
		DEL_FLG = dEL_FLG;
		MODIFY_FLG = mODIFY_FLG;
		ENTRY_USER = eNTRY_USER;
		MODIFY_USER = mODIFY_USER;
		VERIFY_USER = vERIFY_USER;
		ENTRY_TIME = eNTRY_TIME;
		MODIFY_TIME = mODIFY_TIME;
		VERIFY_TIME = vERIFY_TIME;
		QTR_FLG = qTR_FLG;
	}
	public T32ORReport() {
		super();
		// TODO Auto-generated constructor stub
	}
   
}
