package com.bornfire.xbrl.entities.BRSS;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

@Entity
@Table(name="T42_OR_IT_SUPPORT_OTHERBANK_TABLE")
public class T42ORReport {
	private String	A1_PRODUCT;
	private BigDecimal	A1_MUR_BANK_NO;
	private BigDecimal	A1_MUR_BANK_TOTAL_ASSETS;
	private BigDecimal	A1_MUR_OUTSIDE_BANK_NO;
	private BigDecimal	A1_MUR_OUTSIDE_BANK_ASSETS;
	private String	A2_PRODUCT;
	private BigDecimal	A2_MUR_BANK_NO;
	private BigDecimal	A2_MUR_BANK_TOTAL_ASSETS;
	private BigDecimal	A2_MUR_OUTSIDE_BANK_NO;
	private BigDecimal	A2_MUR_OUTSIDE_BANK_ASSETS;
	private String	A3_PRODUCT;
	private BigDecimal	A3_MUR_BANK_NO;
	private BigDecimal	A3_MUR_BANK_TOTAL_ASSETS;
	private BigDecimal	A3_MUR_OUTSIDE_BANK_NO;
	private BigDecimal	A3_MUR_OUTSIDE_BANK_ASSETS;
	private String	A4_PRODUCT;
	private BigDecimal	A4_MUR_BANK_NO;
	private BigDecimal	A4_MUR_BANK_TOTAL_ASSETS;
	private BigDecimal	A4_MUR_OUTSIDE_BANK_NO;
	private BigDecimal	A4_MUR_OUTSIDE_BANK_ASSETS;
	private String	A5_PRODUCT;
	private BigDecimal	A5_FIN_INST_MUR_NO;
	private BigDecimal	A5_FIN_INST_MUR_ASSETS;
	private BigDecimal	A5_FIN_INST_OUTSIDE_MUR_NO;
	private BigDecimal	A5_FIN_INST_OUTSIDE_MUR_ASSETS;
	private String	A6_PRODUCT;
	private BigDecimal	A6_FIN_INST_MUR_NO;
	private BigDecimal	A6_FIN_INST_MUR_ASSETS;
	private BigDecimal	A6_FIN_INST_OUTSIDE_MUR_NO;
	private BigDecimal	A6_FIN_INST_OUTSIDE_MUR_ASSETS;
	private String	A7_PRODUCT;
	private BigDecimal	A7_FIN_INST_MUR_NO;
	private BigDecimal	A7_FIN_INST_MUR_ASSETS;
	private BigDecimal	A7_FIN_INST_OUTSIDE_MUR_NO;
	private BigDecimal	A7_FIN_INST_OUTSIDE_MUR_ASSETS;
	private String	A8_PRODUCT;
	private BigDecimal	A8_FIN_INST_MUR_NO;
	private BigDecimal	A8_FIN_INST_MUR_ASSETS;
	private BigDecimal	A8_FIN_INST_OUTSIDE_MUR_NO;
	private BigDecimal	A8_FIN_INST_OUTSIDE_MUR_ASSETS;
	private String	A9_PRODUCT;
	private BigDecimal	A9_BANK_GRP_ENTITY_MUR_NO;
	private BigDecimal	A9_BANK_GRP_ENTITY_MUR_ASSETS;
	private BigDecimal	A9_BANK_GRP_ENTITY_OUTSIDE_MUR_NO;
	private BigDecimal	A9_BANK_GRP_ENTITY_OUTSIDE_MUR_ASSETS;
	private String	A10_PRODUCT;
	private BigDecimal	A10_BANK_GRP_ENTITY_MUR_NO;
	private BigDecimal	A10_BANK_GRP_ENTITY_MUR_ASSETS;
	private BigDecimal	A10_BANK_GRP_ENTITY_OUTSIDE_MUR_NO;
	private BigDecimal	A10_BANK_GRP_ENTITY_OUTSIDE_MUR_ASSETS;
	private String	A11_PRODUCT;
	private BigDecimal	A11_BANK_GRP_ENTITY_MUR_NO;
	private BigDecimal	A11_BANK_GRP_ENTITY_MUR_ASSETS;
	private BigDecimal	A11_BANK_GRP_ENTITY_OUTSIDE_MUR_NO;
	private BigDecimal	A11_BANK_GRP_ENTITY_OUTSIDE_MUR_ASSETS;
	private String	A12_PRODUCT;
	private BigDecimal	A12_BANK_GRP_ENTITY_MUR_NO;
	private BigDecimal	A12_BANK_GRP_ENTITY_MUR_ASSETS;
	private BigDecimal	A12_BANK_GRP_ENTITY_OUTSIDE_MUR_NO;
	private BigDecimal	A12_BANK_GRP_ENTITY_OUTSIDE_MUR_ASSETS;
	private String	A13_PRODUCT;
	private BigDecimal	A13_OTHER_ENTITY_MUR_NO;
	private BigDecimal	A13_OTHER_ENTITY_MUR_ASSETS;
	private BigDecimal	A13_OTHER_ENTITY_OTHER_MUR_NO;
	private BigDecimal	A13_OTHER_ENTITY_OUTISIDE_MUR_ASSETS;
	private String	A14_PRODUCT;
	private BigDecimal	A14_OTHER_ENTITY_MUR_NO;
	private BigDecimal	A14_OTHER_ENTITY_MUR_ASSETS;
	private BigDecimal	A14_OTHER_ENTITY_OTHER_MUR_NO;
	private BigDecimal	A14_OTHER_ENTITY_OUTISIDE_MUR_ASSETS;
	private String	A15_PRODUCT;
	private BigDecimal	A15_OTHER_ENTITY_MUR_NO;
	private BigDecimal	A15_OTHER_ENTITY_MUR_ASSETS;
	private BigDecimal	A15_OTHER_ENTITY_OTHER_MUR_NO;
	private BigDecimal	A15_OTHER_ENTITY_OUTISIDE_MUR_ASSETS;
	private String	A16_PRODUCT;
	private BigDecimal	A16_OTHER_ENTITY_MUR_NO;
	private BigDecimal	A16_OTHER_ENTITY_MUR_ASSETS;
	private BigDecimal	A16_OTHER_ENTITY_OTHER_MUR_NO;
	private BigDecimal	A16_OTHER_ENTITY_OUTISIDE_MUR_ASSETS;
	private String	REPORT_CODE;
	private String	REPORT_NAME;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	@Id
	private Date	REPORT_DATE;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	REPORT_DUE_DATE;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	REP_SUBMIT_DATE;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	REP_PERIOD_FROM;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	REP_PERIOD_TO;
	private String	REP_FREQ;
	private String	NIL_REPORT_FLG;
	private String	ARCH_FLG;
	private String	ENTITY_FLG;
	private String	DEL_FLG;
	private String	MODIFY_FLG;
	private String	ENTRY_USER;
	private String	MODIFY_USER;
	private String	VERIFY_USER;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	ENTRY_TIME;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	MODIFY_TIME;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	VERIFY_TIME;
	private String	QTR_FLG;
	public String getA1_PRODUCT() {
		return A1_PRODUCT;
	}
	public void setA1_PRODUCT(String a1_PRODUCT) {
		A1_PRODUCT = a1_PRODUCT;
	}
	public BigDecimal getA1_MUR_BANK_NO() {
		return A1_MUR_BANK_NO;
	}
	public void setA1_MUR_BANK_NO(BigDecimal a1_MUR_BANK_NO) {
		A1_MUR_BANK_NO = a1_MUR_BANK_NO;
	}
	public BigDecimal getA1_MUR_BANK_TOTAL_ASSETS() {
		return A1_MUR_BANK_TOTAL_ASSETS;
	}
	public void setA1_MUR_BANK_TOTAL_ASSETS(BigDecimal a1_MUR_BANK_TOTAL_ASSETS) {
		A1_MUR_BANK_TOTAL_ASSETS = a1_MUR_BANK_TOTAL_ASSETS;
	}
	public BigDecimal getA1_MUR_OUTSIDE_BANK_NO() {
		return A1_MUR_OUTSIDE_BANK_NO;
	}
	public void setA1_MUR_OUTSIDE_BANK_NO(BigDecimal a1_MUR_OUTSIDE_BANK_NO) {
		A1_MUR_OUTSIDE_BANK_NO = a1_MUR_OUTSIDE_BANK_NO;
	}
	public BigDecimal getA1_MUR_OUTSIDE_BANK_ASSETS() {
		return A1_MUR_OUTSIDE_BANK_ASSETS;
	}
	public void setA1_MUR_OUTSIDE_BANK_ASSETS(BigDecimal a1_MUR_OUTSIDE_BANK_ASSETS) {
		A1_MUR_OUTSIDE_BANK_ASSETS = a1_MUR_OUTSIDE_BANK_ASSETS;
	}
	public String getA2_PRODUCT() {
		return A2_PRODUCT;
	}
	public void setA2_PRODUCT(String a2_PRODUCT) {
		A2_PRODUCT = a2_PRODUCT;
	}
	public BigDecimal getA2_MUR_BANK_NO() {
		return A2_MUR_BANK_NO;
	}
	public void setA2_MUR_BANK_NO(BigDecimal a2_MUR_BANK_NO) {
		A2_MUR_BANK_NO = a2_MUR_BANK_NO;
	}
	public BigDecimal getA2_MUR_BANK_TOTAL_ASSETS() {
		return A2_MUR_BANK_TOTAL_ASSETS;
	}
	public void setA2_MUR_BANK_TOTAL_ASSETS(BigDecimal a2_MUR_BANK_TOTAL_ASSETS) {
		A2_MUR_BANK_TOTAL_ASSETS = a2_MUR_BANK_TOTAL_ASSETS;
	}
	public BigDecimal getA2_MUR_OUTSIDE_BANK_NO() {
		return A2_MUR_OUTSIDE_BANK_NO;
	}
	public void setA2_MUR_OUTSIDE_BANK_NO(BigDecimal a2_MUR_OUTSIDE_BANK_NO) {
		A2_MUR_OUTSIDE_BANK_NO = a2_MUR_OUTSIDE_BANK_NO;
	}
	public BigDecimal getA2_MUR_OUTSIDE_BANK_ASSETS() {
		return A2_MUR_OUTSIDE_BANK_ASSETS;
	}
	public void setA2_MUR_OUTSIDE_BANK_ASSETS(BigDecimal a2_MUR_OUTSIDE_BANK_ASSETS) {
		A2_MUR_OUTSIDE_BANK_ASSETS = a2_MUR_OUTSIDE_BANK_ASSETS;
	}
	public String getA3_PRODUCT() {
		return A3_PRODUCT;
	}
	public void setA3_PRODUCT(String a3_PRODUCT) {
		A3_PRODUCT = a3_PRODUCT;
	}
	public BigDecimal getA3_MUR_BANK_NO() {
		return A3_MUR_BANK_NO;
	}
	public void setA3_MUR_BANK_NO(BigDecimal a3_MUR_BANK_NO) {
		A3_MUR_BANK_NO = a3_MUR_BANK_NO;
	}
	public BigDecimal getA3_MUR_BANK_TOTAL_ASSETS() {
		return A3_MUR_BANK_TOTAL_ASSETS;
	}
	public void setA3_MUR_BANK_TOTAL_ASSETS(BigDecimal a3_MUR_BANK_TOTAL_ASSETS) {
		A3_MUR_BANK_TOTAL_ASSETS = a3_MUR_BANK_TOTAL_ASSETS;
	}
	public BigDecimal getA3_MUR_OUTSIDE_BANK_NO() {
		return A3_MUR_OUTSIDE_BANK_NO;
	}
	public void setA3_MUR_OUTSIDE_BANK_NO(BigDecimal a3_MUR_OUTSIDE_BANK_NO) {
		A3_MUR_OUTSIDE_BANK_NO = a3_MUR_OUTSIDE_BANK_NO;
	}
	public BigDecimal getA3_MUR_OUTSIDE_BANK_ASSETS() {
		return A3_MUR_OUTSIDE_BANK_ASSETS;
	}
	public void setA3_MUR_OUTSIDE_BANK_ASSETS(BigDecimal a3_MUR_OUTSIDE_BANK_ASSETS) {
		A3_MUR_OUTSIDE_BANK_ASSETS = a3_MUR_OUTSIDE_BANK_ASSETS;
	}
	public String getA4_PRODUCT() {
		return A4_PRODUCT;
	}
	public void setA4_PRODUCT(String a4_PRODUCT) {
		A4_PRODUCT = a4_PRODUCT;
	}
	public BigDecimal getA4_MUR_BANK_NO() {
		return A4_MUR_BANK_NO;
	}
	public void setA4_MUR_BANK_NO(BigDecimal a4_MUR_BANK_NO) {
		A4_MUR_BANK_NO = a4_MUR_BANK_NO;
	}
	public BigDecimal getA4_MUR_BANK_TOTAL_ASSETS() {
		return A4_MUR_BANK_TOTAL_ASSETS;
	}
	public void setA4_MUR_BANK_TOTAL_ASSETS(BigDecimal a4_MUR_BANK_TOTAL_ASSETS) {
		A4_MUR_BANK_TOTAL_ASSETS = a4_MUR_BANK_TOTAL_ASSETS;
	}
	public BigDecimal getA4_MUR_OUTSIDE_BANK_NO() {
		return A4_MUR_OUTSIDE_BANK_NO;
	}
	public void setA4_MUR_OUTSIDE_BANK_NO(BigDecimal a4_MUR_OUTSIDE_BANK_NO) {
		A4_MUR_OUTSIDE_BANK_NO = a4_MUR_OUTSIDE_BANK_NO;
	}
	public BigDecimal getA4_MUR_OUTSIDE_BANK_ASSETS() {
		return A4_MUR_OUTSIDE_BANK_ASSETS;
	}
	public void setA4_MUR_OUTSIDE_BANK_ASSETS(BigDecimal a4_MUR_OUTSIDE_BANK_ASSETS) {
		A4_MUR_OUTSIDE_BANK_ASSETS = a4_MUR_OUTSIDE_BANK_ASSETS;
	}
	public String getA5_PRODUCT() {
		return A5_PRODUCT;
	}
	public void setA5_PRODUCT(String a5_PRODUCT) {
		A5_PRODUCT = a5_PRODUCT;
	}
	public BigDecimal getA5_FIN_INST_MUR_NO() {
		return A5_FIN_INST_MUR_NO;
	}
	public void setA5_FIN_INST_MUR_NO(BigDecimal a5_FIN_INST_MUR_NO) {
		A5_FIN_INST_MUR_NO = a5_FIN_INST_MUR_NO;
	}
	public BigDecimal getA5_FIN_INST_MUR_ASSETS() {
		return A5_FIN_INST_MUR_ASSETS;
	}
	public void setA5_FIN_INST_MUR_ASSETS(BigDecimal a5_FIN_INST_MUR_ASSETS) {
		A5_FIN_INST_MUR_ASSETS = a5_FIN_INST_MUR_ASSETS;
	}
	public BigDecimal getA5_FIN_INST_OUTSIDE_MUR_NO() {
		return A5_FIN_INST_OUTSIDE_MUR_NO;
	}
	public void setA5_FIN_INST_OUTSIDE_MUR_NO(BigDecimal a5_FIN_INST_OUTSIDE_MUR_NO) {
		A5_FIN_INST_OUTSIDE_MUR_NO = a5_FIN_INST_OUTSIDE_MUR_NO;
	}
	public BigDecimal getA5_FIN_INST_OUTSIDE_MUR_ASSETS() {
		return A5_FIN_INST_OUTSIDE_MUR_ASSETS;
	}
	public void setA5_FIN_INST_OUTSIDE_MUR_ASSETS(BigDecimal a5_FIN_INST_OUTSIDE_MUR_ASSETS) {
		A5_FIN_INST_OUTSIDE_MUR_ASSETS = a5_FIN_INST_OUTSIDE_MUR_ASSETS;
	}
	public String getA6_PRODUCT() {
		return A6_PRODUCT;
	}
	public void setA6_PRODUCT(String a6_PRODUCT) {
		A6_PRODUCT = a6_PRODUCT;
	}
	public BigDecimal getA6_FIN_INST_MUR_NO() {
		return A6_FIN_INST_MUR_NO;
	}
	public void setA6_FIN_INST_MUR_NO(BigDecimal a6_FIN_INST_MUR_NO) {
		A6_FIN_INST_MUR_NO = a6_FIN_INST_MUR_NO;
	}
	public BigDecimal getA6_FIN_INST_MUR_ASSETS() {
		return A6_FIN_INST_MUR_ASSETS;
	}
	public void setA6_FIN_INST_MUR_ASSETS(BigDecimal a6_FIN_INST_MUR_ASSETS) {
		A6_FIN_INST_MUR_ASSETS = a6_FIN_INST_MUR_ASSETS;
	}
	public BigDecimal getA6_FIN_INST_OUTSIDE_MUR_NO() {
		return A6_FIN_INST_OUTSIDE_MUR_NO;
	}
	public void setA6_FIN_INST_OUTSIDE_MUR_NO(BigDecimal a6_FIN_INST_OUTSIDE_MUR_NO) {
		A6_FIN_INST_OUTSIDE_MUR_NO = a6_FIN_INST_OUTSIDE_MUR_NO;
	}
	public BigDecimal getA6_FIN_INST_OUTSIDE_MUR_ASSETS() {
		return A6_FIN_INST_OUTSIDE_MUR_ASSETS;
	}
	public void setA6_FIN_INST_OUTSIDE_MUR_ASSETS(BigDecimal a6_FIN_INST_OUTSIDE_MUR_ASSETS) {
		A6_FIN_INST_OUTSIDE_MUR_ASSETS = a6_FIN_INST_OUTSIDE_MUR_ASSETS;
	}
	public String getA7_PRODUCT() {
		return A7_PRODUCT;
	}
	public void setA7_PRODUCT(String a7_PRODUCT) {
		A7_PRODUCT = a7_PRODUCT;
	}
	public BigDecimal getA7_FIN_INST_MUR_NO() {
		return A7_FIN_INST_MUR_NO;
	}
	public void setA7_FIN_INST_MUR_NO(BigDecimal a7_FIN_INST_MUR_NO) {
		A7_FIN_INST_MUR_NO = a7_FIN_INST_MUR_NO;
	}
	public BigDecimal getA7_FIN_INST_MUR_ASSETS() {
		return A7_FIN_INST_MUR_ASSETS;
	}
	public void setA7_FIN_INST_MUR_ASSETS(BigDecimal a7_FIN_INST_MUR_ASSETS) {
		A7_FIN_INST_MUR_ASSETS = a7_FIN_INST_MUR_ASSETS;
	}
	public BigDecimal getA7_FIN_INST_OUTSIDE_MUR_NO() {
		return A7_FIN_INST_OUTSIDE_MUR_NO;
	}
	public void setA7_FIN_INST_OUTSIDE_MUR_NO(BigDecimal a7_FIN_INST_OUTSIDE_MUR_NO) {
		A7_FIN_INST_OUTSIDE_MUR_NO = a7_FIN_INST_OUTSIDE_MUR_NO;
	}
	public BigDecimal getA7_FIN_INST_OUTSIDE_MUR_ASSETS() {
		return A7_FIN_INST_OUTSIDE_MUR_ASSETS;
	}
	public void setA7_FIN_INST_OUTSIDE_MUR_ASSETS(BigDecimal a7_FIN_INST_OUTSIDE_MUR_ASSETS) {
		A7_FIN_INST_OUTSIDE_MUR_ASSETS = a7_FIN_INST_OUTSIDE_MUR_ASSETS;
	}
	public String getA8_PRODUCT() {
		return A8_PRODUCT;
	}
	public void setA8_PRODUCT(String a8_PRODUCT) {
		A8_PRODUCT = a8_PRODUCT;
	}
	public BigDecimal getA8_FIN_INST_MUR_NO() {
		return A8_FIN_INST_MUR_NO;
	}
	public void setA8_FIN_INST_MUR_NO(BigDecimal a8_FIN_INST_MUR_NO) {
		A8_FIN_INST_MUR_NO = a8_FIN_INST_MUR_NO;
	}
	public BigDecimal getA8_FIN_INST_MUR_ASSETS() {
		return A8_FIN_INST_MUR_ASSETS;
	}
	public void setA8_FIN_INST_MUR_ASSETS(BigDecimal a8_FIN_INST_MUR_ASSETS) {
		A8_FIN_INST_MUR_ASSETS = a8_FIN_INST_MUR_ASSETS;
	}
	public BigDecimal getA8_FIN_INST_OUTSIDE_MUR_NO() {
		return A8_FIN_INST_OUTSIDE_MUR_NO;
	}
	public void setA8_FIN_INST_OUTSIDE_MUR_NO(BigDecimal a8_FIN_INST_OUTSIDE_MUR_NO) {
		A8_FIN_INST_OUTSIDE_MUR_NO = a8_FIN_INST_OUTSIDE_MUR_NO;
	}
	public BigDecimal getA8_FIN_INST_OUTSIDE_MUR_ASSETS() {
		return A8_FIN_INST_OUTSIDE_MUR_ASSETS;
	}
	public void setA8_FIN_INST_OUTSIDE_MUR_ASSETS(BigDecimal a8_FIN_INST_OUTSIDE_MUR_ASSETS) {
		A8_FIN_INST_OUTSIDE_MUR_ASSETS = a8_FIN_INST_OUTSIDE_MUR_ASSETS;
	}
	public String getA9_PRODUCT() {
		return A9_PRODUCT;
	}
	public void setA9_PRODUCT(String a9_PRODUCT) {
		A9_PRODUCT = a9_PRODUCT;
	}
	public BigDecimal getA9_BANK_GRP_ENTITY_MUR_NO() {
		return A9_BANK_GRP_ENTITY_MUR_NO;
	}
	public void setA9_BANK_GRP_ENTITY_MUR_NO(BigDecimal a9_BANK_GRP_ENTITY_MUR_NO) {
		A9_BANK_GRP_ENTITY_MUR_NO = a9_BANK_GRP_ENTITY_MUR_NO;
	}
	public BigDecimal getA9_BANK_GRP_ENTITY_MUR_ASSETS() {
		return A9_BANK_GRP_ENTITY_MUR_ASSETS;
	}
	public void setA9_BANK_GRP_ENTITY_MUR_ASSETS(BigDecimal a9_BANK_GRP_ENTITY_MUR_ASSETS) {
		A9_BANK_GRP_ENTITY_MUR_ASSETS = a9_BANK_GRP_ENTITY_MUR_ASSETS;
	}
	public BigDecimal getA9_BANK_GRP_ENTITY_OUTSIDE_MUR_NO() {
		return A9_BANK_GRP_ENTITY_OUTSIDE_MUR_NO;
	}
	public void setA9_BANK_GRP_ENTITY_OUTSIDE_MUR_NO(BigDecimal a9_BANK_GRP_ENTITY_OUTSIDE_MUR_NO) {
		A9_BANK_GRP_ENTITY_OUTSIDE_MUR_NO = a9_BANK_GRP_ENTITY_OUTSIDE_MUR_NO;
	}
	public BigDecimal getA9_BANK_GRP_ENTITY_OUTSIDE_MUR_ASSETS() {
		return A9_BANK_GRP_ENTITY_OUTSIDE_MUR_ASSETS;
	}
	public void setA9_BANK_GRP_ENTITY_OUTSIDE_MUR_ASSETS(BigDecimal a9_BANK_GRP_ENTITY_OUTSIDE_MUR_ASSETS) {
		A9_BANK_GRP_ENTITY_OUTSIDE_MUR_ASSETS = a9_BANK_GRP_ENTITY_OUTSIDE_MUR_ASSETS;
	}
	public String getA10_PRODUCT() {
		return A10_PRODUCT;
	}
	public void setA10_PRODUCT(String a10_PRODUCT) {
		A10_PRODUCT = a10_PRODUCT;
	}
	public BigDecimal getA10_BANK_GRP_ENTITY_MUR_NO() {
		return A10_BANK_GRP_ENTITY_MUR_NO;
	}
	public void setA10_BANK_GRP_ENTITY_MUR_NO(BigDecimal a10_BANK_GRP_ENTITY_MUR_NO) {
		A10_BANK_GRP_ENTITY_MUR_NO = a10_BANK_GRP_ENTITY_MUR_NO;
	}
	public BigDecimal getA10_BANK_GRP_ENTITY_MUR_ASSETS() {
		return A10_BANK_GRP_ENTITY_MUR_ASSETS;
	}
	public void setA10_BANK_GRP_ENTITY_MUR_ASSETS(BigDecimal a10_BANK_GRP_ENTITY_MUR_ASSETS) {
		A10_BANK_GRP_ENTITY_MUR_ASSETS = a10_BANK_GRP_ENTITY_MUR_ASSETS;
	}
	public BigDecimal getA10_BANK_GRP_ENTITY_OUTSIDE_MUR_NO() {
		return A10_BANK_GRP_ENTITY_OUTSIDE_MUR_NO;
	}
	public void setA10_BANK_GRP_ENTITY_OUTSIDE_MUR_NO(BigDecimal a10_BANK_GRP_ENTITY_OUTSIDE_MUR_NO) {
		A10_BANK_GRP_ENTITY_OUTSIDE_MUR_NO = a10_BANK_GRP_ENTITY_OUTSIDE_MUR_NO;
	}
	public BigDecimal getA10_BANK_GRP_ENTITY_OUTSIDE_MUR_ASSETS() {
		return A10_BANK_GRP_ENTITY_OUTSIDE_MUR_ASSETS;
	}
	public void setA10_BANK_GRP_ENTITY_OUTSIDE_MUR_ASSETS(BigDecimal a10_BANK_GRP_ENTITY_OUTSIDE_MUR_ASSETS) {
		A10_BANK_GRP_ENTITY_OUTSIDE_MUR_ASSETS = a10_BANK_GRP_ENTITY_OUTSIDE_MUR_ASSETS;
	}
	public String getA11_PRODUCT() {
		return A11_PRODUCT;
	}
	public void setA11_PRODUCT(String a11_PRODUCT) {
		A11_PRODUCT = a11_PRODUCT;
	}
	public BigDecimal getA11_BANK_GRP_ENTITY_MUR_NO() {
		return A11_BANK_GRP_ENTITY_MUR_NO;
	}
	public void setA11_BANK_GRP_ENTITY_MUR_NO(BigDecimal a11_BANK_GRP_ENTITY_MUR_NO) {
		A11_BANK_GRP_ENTITY_MUR_NO = a11_BANK_GRP_ENTITY_MUR_NO;
	}
	public BigDecimal getA11_BANK_GRP_ENTITY_MUR_ASSETS() {
		return A11_BANK_GRP_ENTITY_MUR_ASSETS;
	}
	public void setA11_BANK_GRP_ENTITY_MUR_ASSETS(BigDecimal a11_BANK_GRP_ENTITY_MUR_ASSETS) {
		A11_BANK_GRP_ENTITY_MUR_ASSETS = a11_BANK_GRP_ENTITY_MUR_ASSETS;
	}
	public BigDecimal getA11_BANK_GRP_ENTITY_OUTSIDE_MUR_NO() {
		return A11_BANK_GRP_ENTITY_OUTSIDE_MUR_NO;
	}
	public void setA11_BANK_GRP_ENTITY_OUTSIDE_MUR_NO(BigDecimal a11_BANK_GRP_ENTITY_OUTSIDE_MUR_NO) {
		A11_BANK_GRP_ENTITY_OUTSIDE_MUR_NO = a11_BANK_GRP_ENTITY_OUTSIDE_MUR_NO;
	}
	public BigDecimal getA11_BANK_GRP_ENTITY_OUTSIDE_MUR_ASSETS() {
		return A11_BANK_GRP_ENTITY_OUTSIDE_MUR_ASSETS;
	}
	public void setA11_BANK_GRP_ENTITY_OUTSIDE_MUR_ASSETS(BigDecimal a11_BANK_GRP_ENTITY_OUTSIDE_MUR_ASSETS) {
		A11_BANK_GRP_ENTITY_OUTSIDE_MUR_ASSETS = a11_BANK_GRP_ENTITY_OUTSIDE_MUR_ASSETS;
	}
	public String getA12_PRODUCT() {
		return A12_PRODUCT;
	}
	public void setA12_PRODUCT(String a12_PRODUCT) {
		A12_PRODUCT = a12_PRODUCT;
	}
	public BigDecimal getA12_BANK_GRP_ENTITY_MUR_NO() {
		return A12_BANK_GRP_ENTITY_MUR_NO;
	}
	public void setA12_BANK_GRP_ENTITY_MUR_NO(BigDecimal a12_BANK_GRP_ENTITY_MUR_NO) {
		A12_BANK_GRP_ENTITY_MUR_NO = a12_BANK_GRP_ENTITY_MUR_NO;
	}
	public BigDecimal getA12_BANK_GRP_ENTITY_MUR_ASSETS() {
		return A12_BANK_GRP_ENTITY_MUR_ASSETS;
	}
	public void setA12_BANK_GRP_ENTITY_MUR_ASSETS(BigDecimal a12_BANK_GRP_ENTITY_MUR_ASSETS) {
		A12_BANK_GRP_ENTITY_MUR_ASSETS = a12_BANK_GRP_ENTITY_MUR_ASSETS;
	}
	public BigDecimal getA12_BANK_GRP_ENTITY_OUTSIDE_MUR_NO() {
		return A12_BANK_GRP_ENTITY_OUTSIDE_MUR_NO;
	}
	public void setA12_BANK_GRP_ENTITY_OUTSIDE_MUR_NO(BigDecimal a12_BANK_GRP_ENTITY_OUTSIDE_MUR_NO) {
		A12_BANK_GRP_ENTITY_OUTSIDE_MUR_NO = a12_BANK_GRP_ENTITY_OUTSIDE_MUR_NO;
	}
	public BigDecimal getA12_BANK_GRP_ENTITY_OUTSIDE_MUR_ASSETS() {
		return A12_BANK_GRP_ENTITY_OUTSIDE_MUR_ASSETS;
	}
	public void setA12_BANK_GRP_ENTITY_OUTSIDE_MUR_ASSETS(BigDecimal a12_BANK_GRP_ENTITY_OUTSIDE_MUR_ASSETS) {
		A12_BANK_GRP_ENTITY_OUTSIDE_MUR_ASSETS = a12_BANK_GRP_ENTITY_OUTSIDE_MUR_ASSETS;
	}
	public String getA13_PRODUCT() {
		return A13_PRODUCT;
	}
	public void setA13_PRODUCT(String a13_PRODUCT) {
		A13_PRODUCT = a13_PRODUCT;
	}
	public BigDecimal getA13_OTHER_ENTITY_MUR_NO() {
		return A13_OTHER_ENTITY_MUR_NO;
	}
	public void setA13_OTHER_ENTITY_MUR_NO(BigDecimal a13_OTHER_ENTITY_MUR_NO) {
		A13_OTHER_ENTITY_MUR_NO = a13_OTHER_ENTITY_MUR_NO;
	}
	public BigDecimal getA13_OTHER_ENTITY_MUR_ASSETS() {
		return A13_OTHER_ENTITY_MUR_ASSETS;
	}
	public void setA13_OTHER_ENTITY_MUR_ASSETS(BigDecimal a13_OTHER_ENTITY_MUR_ASSETS) {
		A13_OTHER_ENTITY_MUR_ASSETS = a13_OTHER_ENTITY_MUR_ASSETS;
	}
	public BigDecimal getA13_OTHER_ENTITY_OTHER_MUR_NO() {
		return A13_OTHER_ENTITY_OTHER_MUR_NO;
	}
	public void setA13_OTHER_ENTITY_OTHER_MUR_NO(BigDecimal a13_OTHER_ENTITY_OTHER_MUR_NO) {
		A13_OTHER_ENTITY_OTHER_MUR_NO = a13_OTHER_ENTITY_OTHER_MUR_NO;
	}
	public BigDecimal getA13_OTHER_ENTITY_OUTISIDE_MUR_ASSETS() {
		return A13_OTHER_ENTITY_OUTISIDE_MUR_ASSETS;
	}
	public void setA13_OTHER_ENTITY_OUTISIDE_MUR_ASSETS(BigDecimal a13_OTHER_ENTITY_OUTISIDE_MUR_ASSETS) {
		A13_OTHER_ENTITY_OUTISIDE_MUR_ASSETS = a13_OTHER_ENTITY_OUTISIDE_MUR_ASSETS;
	}
	public String getA14_PRODUCT() {
		return A14_PRODUCT;
	}
	public void setA14_PRODUCT(String a14_PRODUCT) {
		A14_PRODUCT = a14_PRODUCT;
	}
	public BigDecimal getA14_OTHER_ENTITY_MUR_NO() {
		return A14_OTHER_ENTITY_MUR_NO;
	}
	public void setA14_OTHER_ENTITY_MUR_NO(BigDecimal a14_OTHER_ENTITY_MUR_NO) {
		A14_OTHER_ENTITY_MUR_NO = a14_OTHER_ENTITY_MUR_NO;
	}
	public BigDecimal getA14_OTHER_ENTITY_MUR_ASSETS() {
		return A14_OTHER_ENTITY_MUR_ASSETS;
	}
	public void setA14_OTHER_ENTITY_MUR_ASSETS(BigDecimal a14_OTHER_ENTITY_MUR_ASSETS) {
		A14_OTHER_ENTITY_MUR_ASSETS = a14_OTHER_ENTITY_MUR_ASSETS;
	}
	public BigDecimal getA14_OTHER_ENTITY_OTHER_MUR_NO() {
		return A14_OTHER_ENTITY_OTHER_MUR_NO;
	}
	public void setA14_OTHER_ENTITY_OTHER_MUR_NO(BigDecimal a14_OTHER_ENTITY_OTHER_MUR_NO) {
		A14_OTHER_ENTITY_OTHER_MUR_NO = a14_OTHER_ENTITY_OTHER_MUR_NO;
	}
	public BigDecimal getA14_OTHER_ENTITY_OUTISIDE_MUR_ASSETS() {
		return A14_OTHER_ENTITY_OUTISIDE_MUR_ASSETS;
	}
	public void setA14_OTHER_ENTITY_OUTISIDE_MUR_ASSETS(BigDecimal a14_OTHER_ENTITY_OUTISIDE_MUR_ASSETS) {
		A14_OTHER_ENTITY_OUTISIDE_MUR_ASSETS = a14_OTHER_ENTITY_OUTISIDE_MUR_ASSETS;
	}
	public String getA15_PRODUCT() {
		return A15_PRODUCT;
	}
	public void setA15_PRODUCT(String a15_PRODUCT) {
		A15_PRODUCT = a15_PRODUCT;
	}
	public BigDecimal getA15_OTHER_ENTITY_MUR_NO() {
		return A15_OTHER_ENTITY_MUR_NO;
	}
	public void setA15_OTHER_ENTITY_MUR_NO(BigDecimal a15_OTHER_ENTITY_MUR_NO) {
		A15_OTHER_ENTITY_MUR_NO = a15_OTHER_ENTITY_MUR_NO;
	}
	public BigDecimal getA15_OTHER_ENTITY_MUR_ASSETS() {
		return A15_OTHER_ENTITY_MUR_ASSETS;
	}
	public void setA15_OTHER_ENTITY_MUR_ASSETS(BigDecimal a15_OTHER_ENTITY_MUR_ASSETS) {
		A15_OTHER_ENTITY_MUR_ASSETS = a15_OTHER_ENTITY_MUR_ASSETS;
	}
	public BigDecimal getA15_OTHER_ENTITY_OTHER_MUR_NO() {
		return A15_OTHER_ENTITY_OTHER_MUR_NO;
	}
	public void setA15_OTHER_ENTITY_OTHER_MUR_NO(BigDecimal a15_OTHER_ENTITY_OTHER_MUR_NO) {
		A15_OTHER_ENTITY_OTHER_MUR_NO = a15_OTHER_ENTITY_OTHER_MUR_NO;
	}
	public BigDecimal getA15_OTHER_ENTITY_OUTISIDE_MUR_ASSETS() {
		return A15_OTHER_ENTITY_OUTISIDE_MUR_ASSETS;
	}
	public void setA15_OTHER_ENTITY_OUTISIDE_MUR_ASSETS(BigDecimal a15_OTHER_ENTITY_OUTISIDE_MUR_ASSETS) {
		A15_OTHER_ENTITY_OUTISIDE_MUR_ASSETS = a15_OTHER_ENTITY_OUTISIDE_MUR_ASSETS;
	}
	public String getA16_PRODUCT() {
		return A16_PRODUCT;
	}
	public void setA16_PRODUCT(String a16_PRODUCT) {
		A16_PRODUCT = a16_PRODUCT;
	}
	public BigDecimal getA16_OTHER_ENTITY_MUR_NO() {
		return A16_OTHER_ENTITY_MUR_NO;
	}
	public void setA16_OTHER_ENTITY_MUR_NO(BigDecimal a16_OTHER_ENTITY_MUR_NO) {
		A16_OTHER_ENTITY_MUR_NO = a16_OTHER_ENTITY_MUR_NO;
	}
	public BigDecimal getA16_OTHER_ENTITY_MUR_ASSETS() {
		return A16_OTHER_ENTITY_MUR_ASSETS;
	}
	public void setA16_OTHER_ENTITY_MUR_ASSETS(BigDecimal a16_OTHER_ENTITY_MUR_ASSETS) {
		A16_OTHER_ENTITY_MUR_ASSETS = a16_OTHER_ENTITY_MUR_ASSETS;
	}
	public BigDecimal getA16_OTHER_ENTITY_OTHER_MUR_NO() {
		return A16_OTHER_ENTITY_OTHER_MUR_NO;
	}
	public void setA16_OTHER_ENTITY_OTHER_MUR_NO(BigDecimal a16_OTHER_ENTITY_OTHER_MUR_NO) {
		A16_OTHER_ENTITY_OTHER_MUR_NO = a16_OTHER_ENTITY_OTHER_MUR_NO;
	}
	public BigDecimal getA16_OTHER_ENTITY_OUTISIDE_MUR_ASSETS() {
		return A16_OTHER_ENTITY_OUTISIDE_MUR_ASSETS;
	}
	public void setA16_OTHER_ENTITY_OUTISIDE_MUR_ASSETS(BigDecimal a16_OTHER_ENTITY_OUTISIDE_MUR_ASSETS) {
		A16_OTHER_ENTITY_OUTISIDE_MUR_ASSETS = a16_OTHER_ENTITY_OUTISIDE_MUR_ASSETS;
	}
	public String getREPORT_CODE() {
		return REPORT_CODE;
	}
	public void setREPORT_CODE(String rEPORT_CODE) {
		REPORT_CODE = rEPORT_CODE;
	}
	public String getREPORT_NAME() {
		return REPORT_NAME;
	}
	public void setREPORT_NAME(String rEPORT_NAME) {
		REPORT_NAME = rEPORT_NAME;
	}
	public Date getREPORT_DATE() {
		return REPORT_DATE;
	}
	public void setREPORT_DATE(Date rEPORT_DATE) {
		REPORT_DATE = rEPORT_DATE;
	}
	public Date getREPORT_DUE_DATE() {
		return REPORT_DUE_DATE;
	}
	public void setREPORT_DUE_DATE(Date rEPORT_DUE_DATE) {
		REPORT_DUE_DATE = rEPORT_DUE_DATE;
	}
	public Date getREP_SUBMIT_DATE() {
		return REP_SUBMIT_DATE;
	}
	public void setREP_SUBMIT_DATE(Date rEP_SUBMIT_DATE) {
		REP_SUBMIT_DATE = rEP_SUBMIT_DATE;
	}
	public Date getREP_PERIOD_FROM() {
		return REP_PERIOD_FROM;
	}
	public void setREP_PERIOD_FROM(Date rEP_PERIOD_FROM) {
		REP_PERIOD_FROM = rEP_PERIOD_FROM;
	}
	public Date getREP_PERIOD_TO() {
		return REP_PERIOD_TO;
	}
	public void setREP_PERIOD_TO(Date rEP_PERIOD_TO) {
		REP_PERIOD_TO = rEP_PERIOD_TO;
	}
	public String getREP_FREQ() {
		return REP_FREQ;
	}
	public void setREP_FREQ(String rEP_FREQ) {
		REP_FREQ = rEP_FREQ;
	}
	public String getNIL_REPORT_FLG() {
		return NIL_REPORT_FLG;
	}
	public void setNIL_REPORT_FLG(String nIL_REPORT_FLG) {
		NIL_REPORT_FLG = nIL_REPORT_FLG;
	}
	public String getARCH_FLG() {
		return ARCH_FLG;
	}
	public void setARCH_FLG(String aRCH_FLG) {
		ARCH_FLG = aRCH_FLG;
	}
	public String getENTITY_FLG() {
		return ENTITY_FLG;
	}
	public void setENTITY_FLG(String eNTITY_FLG) {
		ENTITY_FLG = eNTITY_FLG;
	}
	public String getDEL_FLG() {
		return DEL_FLG;
	}
	public void setDEL_FLG(String dEL_FLG) {
		DEL_FLG = dEL_FLG;
	}
	public String getMODIFY_FLG() {
		return MODIFY_FLG;
	}
	public void setMODIFY_FLG(String mODIFY_FLG) {
		MODIFY_FLG = mODIFY_FLG;
	}
	public String getENTRY_USER() {
		return ENTRY_USER;
	}
	public void setENTRY_USER(String eNTRY_USER) {
		ENTRY_USER = eNTRY_USER;
	}
	public String getMODIFY_USER() {
		return MODIFY_USER;
	}
	public void setMODIFY_USER(String mODIFY_USER) {
		MODIFY_USER = mODIFY_USER;
	}
	public String getVERIFY_USER() {
		return VERIFY_USER;
	}
	public void setVERIFY_USER(String vERIFY_USER) {
		VERIFY_USER = vERIFY_USER;
	}
	public Date getENTRY_TIME() {
		return ENTRY_TIME;
	}
	public void setENTRY_TIME(Date eNTRY_TIME) {
		ENTRY_TIME = eNTRY_TIME;
	}
	public Date getMODIFY_TIME() {
		return MODIFY_TIME;
	}
	public void setMODIFY_TIME(Date mODIFY_TIME) {
		MODIFY_TIME = mODIFY_TIME;
	}
	public Date getVERIFY_TIME() {
		return VERIFY_TIME;
	}
	public void setVERIFY_TIME(Date vERIFY_TIME) {
		VERIFY_TIME = vERIFY_TIME;
	}
	public String getQTR_FLG() {
		return QTR_FLG;
	}
	public void setQTR_FLG(String qTR_FLG) {
		QTR_FLG = qTR_FLG;
	}
	public T42ORReport(String a1_PRODUCT, BigDecimal a1_MUR_BANK_NO, BigDecimal a1_MUR_BANK_TOTAL_ASSETS,
			BigDecimal a1_MUR_OUTSIDE_BANK_NO, BigDecimal a1_MUR_OUTSIDE_BANK_ASSETS, String a2_PRODUCT,
			BigDecimal a2_MUR_BANK_NO, BigDecimal a2_MUR_BANK_TOTAL_ASSETS, BigDecimal a2_MUR_OUTSIDE_BANK_NO,
			BigDecimal a2_MUR_OUTSIDE_BANK_ASSETS, String a3_PRODUCT, BigDecimal a3_MUR_BANK_NO,
			BigDecimal a3_MUR_BANK_TOTAL_ASSETS, BigDecimal a3_MUR_OUTSIDE_BANK_NO,
			BigDecimal a3_MUR_OUTSIDE_BANK_ASSETS, String a4_PRODUCT, BigDecimal a4_MUR_BANK_NO,
			BigDecimal a4_MUR_BANK_TOTAL_ASSETS, BigDecimal a4_MUR_OUTSIDE_BANK_NO,
			BigDecimal a4_MUR_OUTSIDE_BANK_ASSETS, String a5_PRODUCT, BigDecimal a5_FIN_INST_MUR_NO,
			BigDecimal a5_FIN_INST_MUR_ASSETS, BigDecimal a5_FIN_INST_OUTSIDE_MUR_NO,
			BigDecimal a5_FIN_INST_OUTSIDE_MUR_ASSETS, String a6_PRODUCT, BigDecimal a6_FIN_INST_MUR_NO,
			BigDecimal a6_FIN_INST_MUR_ASSETS, BigDecimal a6_FIN_INST_OUTSIDE_MUR_NO,
			BigDecimal a6_FIN_INST_OUTSIDE_MUR_ASSETS, String a7_PRODUCT, BigDecimal a7_FIN_INST_MUR_NO,
			BigDecimal a7_FIN_INST_MUR_ASSETS, BigDecimal a7_FIN_INST_OUTSIDE_MUR_NO,
			BigDecimal a7_FIN_INST_OUTSIDE_MUR_ASSETS, String a8_PRODUCT, BigDecimal a8_FIN_INST_MUR_NO,
			BigDecimal a8_FIN_INST_MUR_ASSETS, BigDecimal a8_FIN_INST_OUTSIDE_MUR_NO,
			BigDecimal a8_FIN_INST_OUTSIDE_MUR_ASSETS, String a9_PRODUCT, BigDecimal a9_BANK_GRP_ENTITY_MUR_NO,
			BigDecimal a9_BANK_GRP_ENTITY_MUR_ASSETS, BigDecimal a9_BANK_GRP_ENTITY_OUTSIDE_MUR_NO,
			BigDecimal a9_BANK_GRP_ENTITY_OUTSIDE_MUR_ASSETS, String a10_PRODUCT, BigDecimal a10_BANK_GRP_ENTITY_MUR_NO,
			BigDecimal a10_BANK_GRP_ENTITY_MUR_ASSETS, BigDecimal a10_BANK_GRP_ENTITY_OUTSIDE_MUR_NO,
			BigDecimal a10_BANK_GRP_ENTITY_OUTSIDE_MUR_ASSETS, String a11_PRODUCT,
			BigDecimal a11_BANK_GRP_ENTITY_MUR_NO, BigDecimal a11_BANK_GRP_ENTITY_MUR_ASSETS,
			BigDecimal a11_BANK_GRP_ENTITY_OUTSIDE_MUR_NO, BigDecimal a11_BANK_GRP_ENTITY_OUTSIDE_MUR_ASSETS,
			String a12_PRODUCT, BigDecimal a12_BANK_GRP_ENTITY_MUR_NO, BigDecimal a12_BANK_GRP_ENTITY_MUR_ASSETS,
			BigDecimal a12_BANK_GRP_ENTITY_OUTSIDE_MUR_NO, BigDecimal a12_BANK_GRP_ENTITY_OUTSIDE_MUR_ASSETS,
			String a13_PRODUCT, BigDecimal a13_OTHER_ENTITY_MUR_NO, BigDecimal a13_OTHER_ENTITY_MUR_ASSETS,
			BigDecimal a13_OTHER_ENTITY_OTHER_MUR_NO, BigDecimal a13_OTHER_ENTITY_OUTISIDE_MUR_ASSETS,
			String a14_PRODUCT, BigDecimal a14_OTHER_ENTITY_MUR_NO, BigDecimal a14_OTHER_ENTITY_MUR_ASSETS,
			BigDecimal a14_OTHER_ENTITY_OTHER_MUR_NO, BigDecimal a14_OTHER_ENTITY_OUTISIDE_MUR_ASSETS,
			String a15_PRODUCT, BigDecimal a15_OTHER_ENTITY_MUR_NO, BigDecimal a15_OTHER_ENTITY_MUR_ASSETS,
			BigDecimal a15_OTHER_ENTITY_OTHER_MUR_NO, BigDecimal a15_OTHER_ENTITY_OUTISIDE_MUR_ASSETS,
			String a16_PRODUCT, BigDecimal a16_OTHER_ENTITY_MUR_NO, BigDecimal a16_OTHER_ENTITY_MUR_ASSETS,
			BigDecimal a16_OTHER_ENTITY_OTHER_MUR_NO, BigDecimal a16_OTHER_ENTITY_OUTISIDE_MUR_ASSETS,
			String rEPORT_CODE, String rEPORT_NAME, Date rEPORT_DATE, Date rEPORT_DUE_DATE, Date rEP_SUBMIT_DATE,
			Date rEP_PERIOD_FROM, Date rEP_PERIOD_TO, String rEP_FREQ, String nIL_REPORT_FLG, String aRCH_FLG,
			String eNTITY_FLG, String dEL_FLG, String mODIFY_FLG, String eNTRY_USER, String mODIFY_USER,
			String vERIFY_USER, Date eNTRY_TIME, Date mODIFY_TIME, Date vERIFY_TIME, String qTR_FLG) {
		super();
		A1_PRODUCT = a1_PRODUCT;
		A1_MUR_BANK_NO = a1_MUR_BANK_NO;
		A1_MUR_BANK_TOTAL_ASSETS = a1_MUR_BANK_TOTAL_ASSETS;
		A1_MUR_OUTSIDE_BANK_NO = a1_MUR_OUTSIDE_BANK_NO;
		A1_MUR_OUTSIDE_BANK_ASSETS = a1_MUR_OUTSIDE_BANK_ASSETS;
		A2_PRODUCT = a2_PRODUCT;
		A2_MUR_BANK_NO = a2_MUR_BANK_NO;
		A2_MUR_BANK_TOTAL_ASSETS = a2_MUR_BANK_TOTAL_ASSETS;
		A2_MUR_OUTSIDE_BANK_NO = a2_MUR_OUTSIDE_BANK_NO;
		A2_MUR_OUTSIDE_BANK_ASSETS = a2_MUR_OUTSIDE_BANK_ASSETS;
		A3_PRODUCT = a3_PRODUCT;
		A3_MUR_BANK_NO = a3_MUR_BANK_NO;
		A3_MUR_BANK_TOTAL_ASSETS = a3_MUR_BANK_TOTAL_ASSETS;
		A3_MUR_OUTSIDE_BANK_NO = a3_MUR_OUTSIDE_BANK_NO;
		A3_MUR_OUTSIDE_BANK_ASSETS = a3_MUR_OUTSIDE_BANK_ASSETS;
		A4_PRODUCT = a4_PRODUCT;
		A4_MUR_BANK_NO = a4_MUR_BANK_NO;
		A4_MUR_BANK_TOTAL_ASSETS = a4_MUR_BANK_TOTAL_ASSETS;
		A4_MUR_OUTSIDE_BANK_NO = a4_MUR_OUTSIDE_BANK_NO;
		A4_MUR_OUTSIDE_BANK_ASSETS = a4_MUR_OUTSIDE_BANK_ASSETS;
		A5_PRODUCT = a5_PRODUCT;
		A5_FIN_INST_MUR_NO = a5_FIN_INST_MUR_NO;
		A5_FIN_INST_MUR_ASSETS = a5_FIN_INST_MUR_ASSETS;
		A5_FIN_INST_OUTSIDE_MUR_NO = a5_FIN_INST_OUTSIDE_MUR_NO;
		A5_FIN_INST_OUTSIDE_MUR_ASSETS = a5_FIN_INST_OUTSIDE_MUR_ASSETS;
		A6_PRODUCT = a6_PRODUCT;
		A6_FIN_INST_MUR_NO = a6_FIN_INST_MUR_NO;
		A6_FIN_INST_MUR_ASSETS = a6_FIN_INST_MUR_ASSETS;
		A6_FIN_INST_OUTSIDE_MUR_NO = a6_FIN_INST_OUTSIDE_MUR_NO;
		A6_FIN_INST_OUTSIDE_MUR_ASSETS = a6_FIN_INST_OUTSIDE_MUR_ASSETS;
		A7_PRODUCT = a7_PRODUCT;
		A7_FIN_INST_MUR_NO = a7_FIN_INST_MUR_NO;
		A7_FIN_INST_MUR_ASSETS = a7_FIN_INST_MUR_ASSETS;
		A7_FIN_INST_OUTSIDE_MUR_NO = a7_FIN_INST_OUTSIDE_MUR_NO;
		A7_FIN_INST_OUTSIDE_MUR_ASSETS = a7_FIN_INST_OUTSIDE_MUR_ASSETS;
		A8_PRODUCT = a8_PRODUCT;
		A8_FIN_INST_MUR_NO = a8_FIN_INST_MUR_NO;
		A8_FIN_INST_MUR_ASSETS = a8_FIN_INST_MUR_ASSETS;
		A8_FIN_INST_OUTSIDE_MUR_NO = a8_FIN_INST_OUTSIDE_MUR_NO;
		A8_FIN_INST_OUTSIDE_MUR_ASSETS = a8_FIN_INST_OUTSIDE_MUR_ASSETS;
		A9_PRODUCT = a9_PRODUCT;
		A9_BANK_GRP_ENTITY_MUR_NO = a9_BANK_GRP_ENTITY_MUR_NO;
		A9_BANK_GRP_ENTITY_MUR_ASSETS = a9_BANK_GRP_ENTITY_MUR_ASSETS;
		A9_BANK_GRP_ENTITY_OUTSIDE_MUR_NO = a9_BANK_GRP_ENTITY_OUTSIDE_MUR_NO;
		A9_BANK_GRP_ENTITY_OUTSIDE_MUR_ASSETS = a9_BANK_GRP_ENTITY_OUTSIDE_MUR_ASSETS;
		A10_PRODUCT = a10_PRODUCT;
		A10_BANK_GRP_ENTITY_MUR_NO = a10_BANK_GRP_ENTITY_MUR_NO;
		A10_BANK_GRP_ENTITY_MUR_ASSETS = a10_BANK_GRP_ENTITY_MUR_ASSETS;
		A10_BANK_GRP_ENTITY_OUTSIDE_MUR_NO = a10_BANK_GRP_ENTITY_OUTSIDE_MUR_NO;
		A10_BANK_GRP_ENTITY_OUTSIDE_MUR_ASSETS = a10_BANK_GRP_ENTITY_OUTSIDE_MUR_ASSETS;
		A11_PRODUCT = a11_PRODUCT;
		A11_BANK_GRP_ENTITY_MUR_NO = a11_BANK_GRP_ENTITY_MUR_NO;
		A11_BANK_GRP_ENTITY_MUR_ASSETS = a11_BANK_GRP_ENTITY_MUR_ASSETS;
		A11_BANK_GRP_ENTITY_OUTSIDE_MUR_NO = a11_BANK_GRP_ENTITY_OUTSIDE_MUR_NO;
		A11_BANK_GRP_ENTITY_OUTSIDE_MUR_ASSETS = a11_BANK_GRP_ENTITY_OUTSIDE_MUR_ASSETS;
		A12_PRODUCT = a12_PRODUCT;
		A12_BANK_GRP_ENTITY_MUR_NO = a12_BANK_GRP_ENTITY_MUR_NO;
		A12_BANK_GRP_ENTITY_MUR_ASSETS = a12_BANK_GRP_ENTITY_MUR_ASSETS;
		A12_BANK_GRP_ENTITY_OUTSIDE_MUR_NO = a12_BANK_GRP_ENTITY_OUTSIDE_MUR_NO;
		A12_BANK_GRP_ENTITY_OUTSIDE_MUR_ASSETS = a12_BANK_GRP_ENTITY_OUTSIDE_MUR_ASSETS;
		A13_PRODUCT = a13_PRODUCT;
		A13_OTHER_ENTITY_MUR_NO = a13_OTHER_ENTITY_MUR_NO;
		A13_OTHER_ENTITY_MUR_ASSETS = a13_OTHER_ENTITY_MUR_ASSETS;
		A13_OTHER_ENTITY_OTHER_MUR_NO = a13_OTHER_ENTITY_OTHER_MUR_NO;
		A13_OTHER_ENTITY_OUTISIDE_MUR_ASSETS = a13_OTHER_ENTITY_OUTISIDE_MUR_ASSETS;
		A14_PRODUCT = a14_PRODUCT;
		A14_OTHER_ENTITY_MUR_NO = a14_OTHER_ENTITY_MUR_NO;
		A14_OTHER_ENTITY_MUR_ASSETS = a14_OTHER_ENTITY_MUR_ASSETS;
		A14_OTHER_ENTITY_OTHER_MUR_NO = a14_OTHER_ENTITY_OTHER_MUR_NO;
		A14_OTHER_ENTITY_OUTISIDE_MUR_ASSETS = a14_OTHER_ENTITY_OUTISIDE_MUR_ASSETS;
		A15_PRODUCT = a15_PRODUCT;
		A15_OTHER_ENTITY_MUR_NO = a15_OTHER_ENTITY_MUR_NO;
		A15_OTHER_ENTITY_MUR_ASSETS = a15_OTHER_ENTITY_MUR_ASSETS;
		A15_OTHER_ENTITY_OTHER_MUR_NO = a15_OTHER_ENTITY_OTHER_MUR_NO;
		A15_OTHER_ENTITY_OUTISIDE_MUR_ASSETS = a15_OTHER_ENTITY_OUTISIDE_MUR_ASSETS;
		A16_PRODUCT = a16_PRODUCT;
		A16_OTHER_ENTITY_MUR_NO = a16_OTHER_ENTITY_MUR_NO;
		A16_OTHER_ENTITY_MUR_ASSETS = a16_OTHER_ENTITY_MUR_ASSETS;
		A16_OTHER_ENTITY_OTHER_MUR_NO = a16_OTHER_ENTITY_OTHER_MUR_NO;
		A16_OTHER_ENTITY_OUTISIDE_MUR_ASSETS = a16_OTHER_ENTITY_OUTISIDE_MUR_ASSETS;
		REPORT_CODE = rEPORT_CODE;
		REPORT_NAME = rEPORT_NAME;
		REPORT_DATE = rEPORT_DATE;
		REPORT_DUE_DATE = rEPORT_DUE_DATE;
		REP_SUBMIT_DATE = rEP_SUBMIT_DATE;
		REP_PERIOD_FROM = rEP_PERIOD_FROM;
		REP_PERIOD_TO = rEP_PERIOD_TO;
		REP_FREQ = rEP_FREQ;
		NIL_REPORT_FLG = nIL_REPORT_FLG;
		ARCH_FLG = aRCH_FLG;
		ENTITY_FLG = eNTITY_FLG;
		DEL_FLG = dEL_FLG;
		MODIFY_FLG = mODIFY_FLG;
		ENTRY_USER = eNTRY_USER;
		MODIFY_USER = mODIFY_USER;
		VERIFY_USER = vERIFY_USER;
		ENTRY_TIME = eNTRY_TIME;
		MODIFY_TIME = mODIFY_TIME;
		VERIFY_TIME = vERIFY_TIME;
		QTR_FLG = qTR_FLG;
	}
	public T42ORReport() {
		super();
		// TODO Auto-generated constructor stub
	}
    
}
