package com.bornfire.xbrl.entities.BRSS;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;
@Entity
@Table(name="T9_OR_COURT_CASE_AGAINST_BANK_EMP_TABLE")
public class T9ORReport {
	private String	A1_PRODUCT;
	private BigDecimal	A1_NO_OF_COURT_CASES;
	private BigDecimal	A1_AMOUNT_OF_PENALTIES;
	private BigDecimal	A1_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A1_AMOUNT_OF_PENALTIES_PENDING;
	private String	A2_PRODUCT;
	private BigDecimal	A2_NO_OF_COURT_CASES;
	private BigDecimal	A2_AMOUNT_OF_PENALTIES;
	private BigDecimal	A2_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A2_AMOUNT_OF_PENALTIES_PENDING;
	private String	A3_PRODUCT;
	private BigDecimal	A3_NO_OF_COURT_CASES;
	private BigDecimal	A3_AMOUNT_OF_PENALTIES;
	private BigDecimal	A3_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A3_AMOUNT_OF_PENALTIES_PENDING;
	private String	A4_PRODUCT;
	private BigDecimal	A4_NO_OF_COURT_CASES;
	private BigDecimal	A4_AMOUNT_OF_PENALTIES;
	private BigDecimal	A4_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A4_AMOUNT_OF_PENALTIES_PENDING;
	private String	A5_PRODUCT;
	private BigDecimal	A5_NO_OF_COURT_CASES;
	private BigDecimal	A5_AMOUNT_OF_PENALTIES;
	private BigDecimal	A5_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A5_AMOUNT_OF_PENALTIES_PENDING;
	private String	A6_PRODUCT;
	private BigDecimal	A6_NO_OF_COURT_CASES;
	private BigDecimal	A6_AMOUNT_OF_PENALTIES;
	private BigDecimal	A6_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A6_AMOUNT_OF_PENALTIES_PENDING;
	private String	A7_PRODUCT;
	private BigDecimal	A7_NO_OF_COURT_CASES;
	private BigDecimal	A7_AMOUNT_OF_PENALTIES;
	private BigDecimal	A7_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A7_AMOUNT_OF_PENALTIES_PENDING;
	private String	A8_PRODUCT;
	private BigDecimal	A8_NO_OF_COURT_CASES;
	private BigDecimal	A8_AMOUNT_OF_PENALTIES;
	private BigDecimal	A8_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A8_AMOUNT_OF_PENALTIES_PENDING;
	private String	A9_PRODUCT;
	private BigDecimal	A9_NO_OF_COURT_CASES;
	private BigDecimal	A9_AMOUNT_OF_PENALTIES;
	private BigDecimal	A9_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A9_AMOUNT_OF_PENALTIES_PENDING;
	private String	A10_PRODUCT;
	private BigDecimal	A10_NO_OF_COURT_CASES;
	private BigDecimal	A10_AMOUNT_OF_PENALTIES;
	private BigDecimal	A10_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A10_AMOUNT_OF_PENALTIES_PENDING;
	private String	A11_PRODUCT;
	private BigDecimal	A11_NO_OF_COURT_CASES;
	private BigDecimal	A11_AMOUNT_OF_PENALTIES;
	private BigDecimal	A11_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A11_AMOUNT_OF_PENALTIES_PENDING;
	private String	A12_PRODUCT;
	private BigDecimal	A12_NO_OF_COURT_CASES;
	private BigDecimal	A12_AMOUNT_OF_PENALTIES;
	private BigDecimal	A12_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A12_AMOUNT_OF_PENALTIES_PENDING;
	private String	A13_PRODUCT;
	private BigDecimal	A13_NO_OF_COURT_CASES;
	private BigDecimal	A13_AMOUNT_OF_PENALTIES;
	private BigDecimal	A13_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A13_AMOUNT_OF_PENALTIES_PENDING;
	private String	A14_PRODUCT;
	private BigDecimal	A14_NO_OF_COURT_CASES;
	private BigDecimal	A14_AMOUNT_OF_PENALTIES;
	private BigDecimal	A14_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A14_AMOUNT_OF_PENALTIES_PENDING;
	private String	A15_PRODUCT;
	private BigDecimal	A15_NO_OF_COURT_CASES;
	private BigDecimal	A15_AMOUNT_OF_PENALTIES;
	private BigDecimal	A15_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A15_AMOUNT_OF_PENALTIES_PENDING;
	private String	A16_PRODUCT;
	private BigDecimal	A16_NO_OF_COURT_CASES;
	private BigDecimal	A16_AMOUNT_OF_PENALTIES;
	private BigDecimal	A16_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A16_AMOUNT_OF_PENALTIES_PENDING;
	private String	A17_PRODUCT;
	private BigDecimal	A17_NO_OF_COURT_CASES;
	private BigDecimal	A17_AMOUNT_OF_PENALTIES;
	private BigDecimal	A17_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A17_AMOUNT_OF_PENALTIES_PENDING;
	private String	A18_PRODUCT;
	private BigDecimal	A18_NO_OF_COURT_CASES;
	private BigDecimal	A18_AMOUNT_OF_PENALTIES;
	private BigDecimal	A18_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A18_AMOUNT_OF_PENALTIES_PENDING;
	private String	A19_PRODUCT;
	private BigDecimal	A19_NO_OF_COURT_CASES;
	private BigDecimal	A19_AMOUNT_OF_PENALTIES;
	private BigDecimal	A19_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A19_AMOUNT_OF_PENALTIES_PENDING;
	private String	A20_PRODUCT;
	private BigDecimal	A20_NO_OF_COURT_CASES;
	private BigDecimal	A20_AMOUNT_OF_PENALTIES;
	private BigDecimal	A20_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A20_AMOUNT_OF_PENALTIES_PENDING;
	private String	A21_PRODUCT;
	private BigDecimal	A21_NO_OF_COURT_CASES;
	private BigDecimal	A21_AMOUNT_OF_PENALTIES;
	private BigDecimal	A21_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A21_AMOUNT_OF_PENALTIES_PENDING;
	private String	A22_PRODUCT;
	private BigDecimal	A22_NO_OF_COURT_CASES;
	private BigDecimal	A22_AMOUNT_OF_PENALTIES;
	private BigDecimal	A22_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A22_AMOUNT_OF_PENALTIES_PENDING;
	private String	A23_PRODUCT;
	private BigDecimal	A23_NO_OF_COURT_CASES;
	private BigDecimal	A23_AMOUNT_OF_PENALTIES;
	private BigDecimal	A23_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A23_AMOUNT_OF_PENALTIES_PENDING;
	private String	A24_PRODUCT;
	private BigDecimal	A24_NO_OF_COURT_CASES;
	private BigDecimal	A24_AMOUNT_OF_PENALTIES;
	private BigDecimal	A24_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A24_AMOUNT_OF_PENALTIES_PENDING;
	private String	A25_PRODUCT;
	private BigDecimal	A25_NO_OF_COURT_CASES;
	private BigDecimal	A25_AMOUNT_OF_PENALTIES;
	private BigDecimal	A25_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A25_AMOUNT_OF_PENALTIES_PENDING;
	private String	A26_PRODUCT;
	private BigDecimal	A26_NO_OF_COURT_CASES;
	private BigDecimal	A26_AMOUNT_OF_PENALTIES;
	private BigDecimal	A26_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A26_AMOUNT_OF_PENALTIES_PENDING;
	private String	A27_PRODUCT;
	private BigDecimal	A27_NO_OF_COURT_CASES;
	private BigDecimal	A27_AMOUNT_OF_PENALTIES;
	private BigDecimal	A27_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A27_AMOUNT_OF_PENALTIES_PENDING;
	private String	A28_PRODUCT;
	private BigDecimal	A28_NO_OF_COURT_CASES;
	private BigDecimal	A28_AMOUNT_OF_PENALTIES;
	private BigDecimal	A28_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A28_AMOUNT_OF_PENALTIES_PENDING;
	private String	A29_PRODUCT;
	private BigDecimal	A29_NO_OF_COURT_CASES;
	private BigDecimal	A29_AMOUNT_OF_PENALTIES;
	private BigDecimal	A29_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A29_AMOUNT_OF_PENALTIES_PENDING;
	private String	A30_PRODUCT;
	private BigDecimal	A30_NO_OF_COURT_CASES;
	private BigDecimal	A30_AMOUNT_OF_PENALTIES;
	private BigDecimal	A30_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A30_AMOUNT_OF_PENALTIES_PENDING;
	private String	A31_PRODUCT;
	private BigDecimal	A31_NO_OF_COURT_CASES;
	private BigDecimal	A31_AMOUNT_OF_PENALTIES;
	private BigDecimal	A31_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A31_AMOUNT_OF_PENALTIES_PENDING;
	private String	A32_PRODUCT;
	private BigDecimal	A32_NO_OF_COURT_CASES;
	private BigDecimal	A32_AMOUNT_OF_PENALTIES;
	private BigDecimal	A32_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A32_AMOUNT_OF_PENALTIES_PENDING;
	private String	A33_PRODUCT;
	private BigDecimal	A33_NO_OF_COURT_CASES;
	private BigDecimal	A33_AMOUNT_OF_PENALTIES;
	private BigDecimal	A33_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A33_AMOUNT_OF_PENALTIES_PENDING;
	private String	A34_PRODUCT;
	private BigDecimal	A34_NO_OF_COURT_CASES;
	private BigDecimal	A34_AMOUNT_OF_PENALTIES;
	private BigDecimal	A34_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A34_AMOUNT_OF_PENALTIES_PENDING;
	private String	A35_PRODUCT;
	private BigDecimal	A35_NO_OF_COURT_CASES;
	private BigDecimal	A35_AMOUNT_OF_PENALTIES;
	private BigDecimal	A35_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A35_AMOUNT_OF_PENALTIES_PENDING;
	private String	A36_PRODUCT;
	private BigDecimal	A36_NO_OF_COURT_CASES;
	private BigDecimal	A36_AMOUNT_OF_PENALTIES;
	private BigDecimal	A36_NO_OF_PENDING_COURT_CASES;
	private BigDecimal	A36_AMOUNT_OF_PENALTIES_PENDING;
	private String	REPORT_CODE;
	private String	REPORT_NAME;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	@Id
	private Date	REPORT_DATE;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	REPORT_DUE_DATE;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	REP_SUBMIT_DATE;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	REP_PERIOD_FROM;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	REP_PERIOD_TO;
	private String	REP_FREQ;
	private String	NIL_REPORT_FLG;
	private String	ARCH_FLG;
	private String	ENTITY_FLG;
	private String	DEL_FLG;
	private String	MODIFY_FLG;
	private String	ENTRY_USER;
	private String	MODIFY_USER;
	private String	VERIFY_USER;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	ENTRY_TIME;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	MODIFY_TIME;
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	VERIFY_TIME;
	private String	QTR_FLG;
	public String getA1_PRODUCT() {
		return A1_PRODUCT;
	}
	public void setA1_PRODUCT(String a1_PRODUCT) {
		A1_PRODUCT = a1_PRODUCT;
	}
	public BigDecimal getA1_NO_OF_COURT_CASES() {
		return A1_NO_OF_COURT_CASES;
	}
	public void setA1_NO_OF_COURT_CASES(BigDecimal a1_NO_OF_COURT_CASES) {
		A1_NO_OF_COURT_CASES = a1_NO_OF_COURT_CASES;
	}
	public BigDecimal getA1_AMOUNT_OF_PENALTIES() {
		return A1_AMOUNT_OF_PENALTIES;
	}
	public void setA1_AMOUNT_OF_PENALTIES(BigDecimal a1_AMOUNT_OF_PENALTIES) {
		A1_AMOUNT_OF_PENALTIES = a1_AMOUNT_OF_PENALTIES;
	}
	public BigDecimal getA1_NO_OF_PENDING_COURT_CASES() {
		return A1_NO_OF_PENDING_COURT_CASES;
	}
	public void setA1_NO_OF_PENDING_COURT_CASES(BigDecimal a1_NO_OF_PENDING_COURT_CASES) {
		A1_NO_OF_PENDING_COURT_CASES = a1_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA1_AMOUNT_OF_PENALTIES_PENDING() {
		return A1_AMOUNT_OF_PENALTIES_PENDING;
	}
	public void setA1_AMOUNT_OF_PENALTIES_PENDING(BigDecimal a1_AMOUNT_OF_PENALTIES_PENDING) {
		A1_AMOUNT_OF_PENALTIES_PENDING = a1_AMOUNT_OF_PENALTIES_PENDING;
	}
	public String getA2_PRODUCT() {
		return A2_PRODUCT;
	}
	public void setA2_PRODUCT(String a2_PRODUCT) {
		A2_PRODUCT = a2_PRODUCT;
	}
	public BigDecimal getA2_NO_OF_COURT_CASES() {
		return A2_NO_OF_COURT_CASES;
	}
	public void setA2_NO_OF_COURT_CASES(BigDecimal a2_NO_OF_COURT_CASES) {
		A2_NO_OF_COURT_CASES = a2_NO_OF_COURT_CASES;
	}
	public BigDecimal getA2_AMOUNT_OF_PENALTIES() {
		return A2_AMOUNT_OF_PENALTIES;
	}
	public void setA2_AMOUNT_OF_PENALTIES(BigDecimal a2_AMOUNT_OF_PENALTIES) {
		A2_AMOUNT_OF_PENALTIES = a2_AMOUNT_OF_PENALTIES;
	}
	public BigDecimal getA2_NO_OF_PENDING_COURT_CASES() {
		return A2_NO_OF_PENDING_COURT_CASES;
	}
	public void setA2_NO_OF_PENDING_COURT_CASES(BigDecimal a2_NO_OF_PENDING_COURT_CASES) {
		A2_NO_OF_PENDING_COURT_CASES = a2_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA2_AMOUNT_OF_PENALTIES_PENDING() {
		return A2_AMOUNT_OF_PENALTIES_PENDING;
	}
	public void setA2_AMOUNT_OF_PENALTIES_PENDING(BigDecimal a2_AMOUNT_OF_PENALTIES_PENDING) {
		A2_AMOUNT_OF_PENALTIES_PENDING = a2_AMOUNT_OF_PENALTIES_PENDING;
	}
	public String getA3_PRODUCT() {
		return A3_PRODUCT;
	}
	public void setA3_PRODUCT(String a3_PRODUCT) {
		A3_PRODUCT = a3_PRODUCT;
	}
	public BigDecimal getA3_NO_OF_COURT_CASES() {
		return A3_NO_OF_COURT_CASES;
	}
	public void setA3_NO_OF_COURT_CASES(BigDecimal a3_NO_OF_COURT_CASES) {
		A3_NO_OF_COURT_CASES = a3_NO_OF_COURT_CASES;
	}
	public BigDecimal getA3_AMOUNT_OF_PENALTIES() {
		return A3_AMOUNT_OF_PENALTIES;
	}
	public void setA3_AMOUNT_OF_PENALTIES(BigDecimal a3_AMOUNT_OF_PENALTIES) {
		A3_AMOUNT_OF_PENALTIES = a3_AMOUNT_OF_PENALTIES;
	}
	public BigDecimal getA3_NO_OF_PENDING_COURT_CASES() {
		return A3_NO_OF_PENDING_COURT_CASES;
	}
	public void setA3_NO_OF_PENDING_COURT_CASES(BigDecimal a3_NO_OF_PENDING_COURT_CASES) {
		A3_NO_OF_PENDING_COURT_CASES = a3_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA3_AMOUNT_OF_PENALTIES_PENDING() {
		return A3_AMOUNT_OF_PENALTIES_PENDING;
	}
	public void setA3_AMOUNT_OF_PENALTIES_PENDING(BigDecimal a3_AMOUNT_OF_PENALTIES_PENDING) {
		A3_AMOUNT_OF_PENALTIES_PENDING = a3_AMOUNT_OF_PENALTIES_PENDING;
	}
	public String getA4_PRODUCT() {
		return A4_PRODUCT;
	}
	public void setA4_PRODUCT(String a4_PRODUCT) {
		A4_PRODUCT = a4_PRODUCT;
	}
	public BigDecimal getA4_NO_OF_COURT_CASES() {
		return A4_NO_OF_COURT_CASES;
	}
	public void setA4_NO_OF_COURT_CASES(BigDecimal a4_NO_OF_COURT_CASES) {
		A4_NO_OF_COURT_CASES = a4_NO_OF_COURT_CASES;
	}
	public BigDecimal getA4_AMOUNT_OF_PENALTIES() {
		return A4_AMOUNT_OF_PENALTIES;
	}
	public void setA4_AMOUNT_OF_PENALTIES(BigDecimal a4_AMOUNT_OF_PENALTIES) {
		A4_AMOUNT_OF_PENALTIES = a4_AMOUNT_OF_PENALTIES;
	}
	public BigDecimal getA4_NO_OF_PENDING_COURT_CASES() {
		return A4_NO_OF_PENDING_COURT_CASES;
	}
	public void setA4_NO_OF_PENDING_COURT_CASES(BigDecimal a4_NO_OF_PENDING_COURT_CASES) {
		A4_NO_OF_PENDING_COURT_CASES = a4_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA4_AMOUNT_OF_PENALTIES_PENDING() {
		return A4_AMOUNT_OF_PENALTIES_PENDING;
	}
	public void setA4_AMOUNT_OF_PENALTIES_PENDING(BigDecimal a4_AMOUNT_OF_PENALTIES_PENDING) {
		A4_AMOUNT_OF_PENALTIES_PENDING = a4_AMOUNT_OF_PENALTIES_PENDING;
	}
	public String getA5_PRODUCT() {
		return A5_PRODUCT;
	}
	public void setA5_PRODUCT(String a5_PRODUCT) {
		A5_PRODUCT = a5_PRODUCT;
	}
	public BigDecimal getA5_NO_OF_COURT_CASES() {
		return A5_NO_OF_COURT_CASES;
	}
	public void setA5_NO_OF_COURT_CASES(BigDecimal a5_NO_OF_COURT_CASES) {
		A5_NO_OF_COURT_CASES = a5_NO_OF_COURT_CASES;
	}
	public BigDecimal getA5_AMOUNT_OF_PENALTIES() {
		return A5_AMOUNT_OF_PENALTIES;
	}
	public void setA5_AMOUNT_OF_PENALTIES(BigDecimal a5_AMOUNT_OF_PENALTIES) {
		A5_AMOUNT_OF_PENALTIES = a5_AMOUNT_OF_PENALTIES;
	}
	public BigDecimal getA5_NO_OF_PENDING_COURT_CASES() {
		return A5_NO_OF_PENDING_COURT_CASES;
	}
	public void setA5_NO_OF_PENDING_COURT_CASES(BigDecimal a5_NO_OF_PENDING_COURT_CASES) {
		A5_NO_OF_PENDING_COURT_CASES = a5_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA5_AMOUNT_OF_PENALTIES_PENDING() {
		return A5_AMOUNT_OF_PENALTIES_PENDING;
	}
	public void setA5_AMOUNT_OF_PENALTIES_PENDING(BigDecimal a5_AMOUNT_OF_PENALTIES_PENDING) {
		A5_AMOUNT_OF_PENALTIES_PENDING = a5_AMOUNT_OF_PENALTIES_PENDING;
	}
	public String getA6_PRODUCT() {
		return A6_PRODUCT;
	}
	public void setA6_PRODUCT(String a6_PRODUCT) {
		A6_PRODUCT = a6_PRODUCT;
	}
	public BigDecimal getA6_NO_OF_COURT_CASES() {
		return A6_NO_OF_COURT_CASES;
	}
	public void setA6_NO_OF_COURT_CASES(BigDecimal a6_NO_OF_COURT_CASES) {
		A6_NO_OF_COURT_CASES = a6_NO_OF_COURT_CASES;
	}
	public BigDecimal getA6_AMOUNT_OF_PENALTIES() {
		return A6_AMOUNT_OF_PENALTIES;
	}
	public void setA6_AMOUNT_OF_PENALTIES(BigDecimal a6_AMOUNT_OF_PENALTIES) {
		A6_AMOUNT_OF_PENALTIES = a6_AMOUNT_OF_PENALTIES;
	}
	public BigDecimal getA6_NO_OF_PENDING_COURT_CASES() {
		return A6_NO_OF_PENDING_COURT_CASES;
	}
	public void setA6_NO_OF_PENDING_COURT_CASES(BigDecimal a6_NO_OF_PENDING_COURT_CASES) {
		A6_NO_OF_PENDING_COURT_CASES = a6_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA6_AMOUNT_OF_PENALTIES_PENDING() {
		return A6_AMOUNT_OF_PENALTIES_PENDING;
	}
	public void setA6_AMOUNT_OF_PENALTIES_PENDING(BigDecimal a6_AMOUNT_OF_PENALTIES_PENDING) {
		A6_AMOUNT_OF_PENALTIES_PENDING = a6_AMOUNT_OF_PENALTIES_PENDING;
	}
	public String getA7_PRODUCT() {
		return A7_PRODUCT;
	}
	public void setA7_PRODUCT(String a7_PRODUCT) {
		A7_PRODUCT = a7_PRODUCT;
	}
	public BigDecimal getA7_NO_OF_COURT_CASES() {
		return A7_NO_OF_COURT_CASES;
	}
	public void setA7_NO_OF_COURT_CASES(BigDecimal a7_NO_OF_COURT_CASES) {
		A7_NO_OF_COURT_CASES = a7_NO_OF_COURT_CASES;
	}
	public BigDecimal getA7_AMOUNT_OF_PENALTIES() {
		return A7_AMOUNT_OF_PENALTIES;
	}
	public void setA7_AMOUNT_OF_PENALTIES(BigDecimal a7_AMOUNT_OF_PENALTIES) {
		A7_AMOUNT_OF_PENALTIES = a7_AMOUNT_OF_PENALTIES;
	}
	public BigDecimal getA7_NO_OF_PENDING_COURT_CASES() {
		return A7_NO_OF_PENDING_COURT_CASES;
	}
	public void setA7_NO_OF_PENDING_COURT_CASES(BigDecimal a7_NO_OF_PENDING_COURT_CASES) {
		A7_NO_OF_PENDING_COURT_CASES = a7_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA7_AMOUNT_OF_PENALTIES_PENDING() {
		return A7_AMOUNT_OF_PENALTIES_PENDING;
	}
	public void setA7_AMOUNT_OF_PENALTIES_PENDING(BigDecimal a7_AMOUNT_OF_PENALTIES_PENDING) {
		A7_AMOUNT_OF_PENALTIES_PENDING = a7_AMOUNT_OF_PENALTIES_PENDING;
	}
	public String getA8_PRODUCT() {
		return A8_PRODUCT;
	}
	public void setA8_PRODUCT(String a8_PRODUCT) {
		A8_PRODUCT = a8_PRODUCT;
	}
	public BigDecimal getA8_NO_OF_COURT_CASES() {
		return A8_NO_OF_COURT_CASES;
	}
	public void setA8_NO_OF_COURT_CASES(BigDecimal a8_NO_OF_COURT_CASES) {
		A8_NO_OF_COURT_CASES = a8_NO_OF_COURT_CASES;
	}
	public BigDecimal getA8_AMOUNT_OF_PENALTIES() {
		return A8_AMOUNT_OF_PENALTIES;
	}
	public void setA8_AMOUNT_OF_PENALTIES(BigDecimal a8_AMOUNT_OF_PENALTIES) {
		A8_AMOUNT_OF_PENALTIES = a8_AMOUNT_OF_PENALTIES;
	}
	public BigDecimal getA8_NO_OF_PENDING_COURT_CASES() {
		return A8_NO_OF_PENDING_COURT_CASES;
	}
	public void setA8_NO_OF_PENDING_COURT_CASES(BigDecimal a8_NO_OF_PENDING_COURT_CASES) {
		A8_NO_OF_PENDING_COURT_CASES = a8_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA8_AMOUNT_OF_PENALTIES_PENDING() {
		return A8_AMOUNT_OF_PENALTIES_PENDING;
	}
	public void setA8_AMOUNT_OF_PENALTIES_PENDING(BigDecimal a8_AMOUNT_OF_PENALTIES_PENDING) {
		A8_AMOUNT_OF_PENALTIES_PENDING = a8_AMOUNT_OF_PENALTIES_PENDING;
	}
	public String getA9_PRODUCT() {
		return A9_PRODUCT;
	}
	public void setA9_PRODUCT(String a9_PRODUCT) {
		A9_PRODUCT = a9_PRODUCT;
	}
	public BigDecimal getA9_NO_OF_COURT_CASES() {
		return A9_NO_OF_COURT_CASES;
	}
	public void setA9_NO_OF_COURT_CASES(BigDecimal a9_NO_OF_COURT_CASES) {
		A9_NO_OF_COURT_CASES = a9_NO_OF_COURT_CASES;
	}
	public BigDecimal getA9_AMOUNT_OF_PENALTIES() {
		return A9_AMOUNT_OF_PENALTIES;
	}
	public void setA9_AMOUNT_OF_PENALTIES(BigDecimal a9_AMOUNT_OF_PENALTIES) {
		A9_AMOUNT_OF_PENALTIES = a9_AMOUNT_OF_PENALTIES;
	}
	public BigDecimal getA9_NO_OF_PENDING_COURT_CASES() {
		return A9_NO_OF_PENDING_COURT_CASES;
	}
	public void setA9_NO_OF_PENDING_COURT_CASES(BigDecimal a9_NO_OF_PENDING_COURT_CASES) {
		A9_NO_OF_PENDING_COURT_CASES = a9_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA9_AMOUNT_OF_PENALTIES_PENDING() {
		return A9_AMOUNT_OF_PENALTIES_PENDING;
	}
	public void setA9_AMOUNT_OF_PENALTIES_PENDING(BigDecimal a9_AMOUNT_OF_PENALTIES_PENDING) {
		A9_AMOUNT_OF_PENALTIES_PENDING = a9_AMOUNT_OF_PENALTIES_PENDING;
	}
	public String getA10_PRODUCT() {
		return A10_PRODUCT;
	}
	public void setA10_PRODUCT(String a10_PRODUCT) {
		A10_PRODUCT = a10_PRODUCT;
	}
	public BigDecimal getA10_NO_OF_COURT_CASES() {
		return A10_NO_OF_COURT_CASES;
	}
	public void setA10_NO_OF_COURT_CASES(BigDecimal a10_NO_OF_COURT_CASES) {
		A10_NO_OF_COURT_CASES = a10_NO_OF_COURT_CASES;
	}
	public BigDecimal getA10_AMOUNT_OF_PENALTIES() {
		return A10_AMOUNT_OF_PENALTIES;
	}
	public void setA10_AMOUNT_OF_PENALTIES(BigDecimal a10_AMOUNT_OF_PENALTIES) {
		A10_AMOUNT_OF_PENALTIES = a10_AMOUNT_OF_PENALTIES;
	}
	public BigDecimal getA10_NO_OF_PENDING_COURT_CASES() {
		return A10_NO_OF_PENDING_COURT_CASES;
	}
	public void setA10_NO_OF_PENDING_COURT_CASES(BigDecimal a10_NO_OF_PENDING_COURT_CASES) {
		A10_NO_OF_PENDING_COURT_CASES = a10_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA10_AMOUNT_OF_PENALTIES_PENDING() {
		return A10_AMOUNT_OF_PENALTIES_PENDING;
	}
	public void setA10_AMOUNT_OF_PENALTIES_PENDING(BigDecimal a10_AMOUNT_OF_PENALTIES_PENDING) {
		A10_AMOUNT_OF_PENALTIES_PENDING = a10_AMOUNT_OF_PENALTIES_PENDING;
	}
	public String getA11_PRODUCT() {
		return A11_PRODUCT;
	}
	public void setA11_PRODUCT(String a11_PRODUCT) {
		A11_PRODUCT = a11_PRODUCT;
	}
	public BigDecimal getA11_NO_OF_COURT_CASES() {
		return A11_NO_OF_COURT_CASES;
	}
	public void setA11_NO_OF_COURT_CASES(BigDecimal a11_NO_OF_COURT_CASES) {
		A11_NO_OF_COURT_CASES = a11_NO_OF_COURT_CASES;
	}
	public BigDecimal getA11_AMOUNT_OF_PENALTIES() {
		return A11_AMOUNT_OF_PENALTIES;
	}
	public void setA11_AMOUNT_OF_PENALTIES(BigDecimal a11_AMOUNT_OF_PENALTIES) {
		A11_AMOUNT_OF_PENALTIES = a11_AMOUNT_OF_PENALTIES;
	}
	public BigDecimal getA11_NO_OF_PENDING_COURT_CASES() {
		return A11_NO_OF_PENDING_COURT_CASES;
	}
	public void setA11_NO_OF_PENDING_COURT_CASES(BigDecimal a11_NO_OF_PENDING_COURT_CASES) {
		A11_NO_OF_PENDING_COURT_CASES = a11_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA11_AMOUNT_OF_PENALTIES_PENDING() {
		return A11_AMOUNT_OF_PENALTIES_PENDING;
	}
	public void setA11_AMOUNT_OF_PENALTIES_PENDING(BigDecimal a11_AMOUNT_OF_PENALTIES_PENDING) {
		A11_AMOUNT_OF_PENALTIES_PENDING = a11_AMOUNT_OF_PENALTIES_PENDING;
	}
	public String getA12_PRODUCT() {
		return A12_PRODUCT;
	}
	public void setA12_PRODUCT(String a12_PRODUCT) {
		A12_PRODUCT = a12_PRODUCT;
	}
	public BigDecimal getA12_NO_OF_COURT_CASES() {
		return A12_NO_OF_COURT_CASES;
	}
	public void setA12_NO_OF_COURT_CASES(BigDecimal a12_NO_OF_COURT_CASES) {
		A12_NO_OF_COURT_CASES = a12_NO_OF_COURT_CASES;
	}
	public BigDecimal getA12_AMOUNT_OF_PENALTIES() {
		return A12_AMOUNT_OF_PENALTIES;
	}
	public void setA12_AMOUNT_OF_PENALTIES(BigDecimal a12_AMOUNT_OF_PENALTIES) {
		A12_AMOUNT_OF_PENALTIES = a12_AMOUNT_OF_PENALTIES;
	}
	public BigDecimal getA12_NO_OF_PENDING_COURT_CASES() {
		return A12_NO_OF_PENDING_COURT_CASES;
	}
	public void setA12_NO_OF_PENDING_COURT_CASES(BigDecimal a12_NO_OF_PENDING_COURT_CASES) {
		A12_NO_OF_PENDING_COURT_CASES = a12_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA12_AMOUNT_OF_PENALTIES_PENDING() {
		return A12_AMOUNT_OF_PENALTIES_PENDING;
	}
	public void setA12_AMOUNT_OF_PENALTIES_PENDING(BigDecimal a12_AMOUNT_OF_PENALTIES_PENDING) {
		A12_AMOUNT_OF_PENALTIES_PENDING = a12_AMOUNT_OF_PENALTIES_PENDING;
	}
	public String getA13_PRODUCT() {
		return A13_PRODUCT;
	}
	public void setA13_PRODUCT(String a13_PRODUCT) {
		A13_PRODUCT = a13_PRODUCT;
	}
	public BigDecimal getA13_NO_OF_COURT_CASES() {
		return A13_NO_OF_COURT_CASES;
	}
	public void setA13_NO_OF_COURT_CASES(BigDecimal a13_NO_OF_COURT_CASES) {
		A13_NO_OF_COURT_CASES = a13_NO_OF_COURT_CASES;
	}
	public BigDecimal getA13_AMOUNT_OF_PENALTIES() {
		return A13_AMOUNT_OF_PENALTIES;
	}
	public void setA13_AMOUNT_OF_PENALTIES(BigDecimal a13_AMOUNT_OF_PENALTIES) {
		A13_AMOUNT_OF_PENALTIES = a13_AMOUNT_OF_PENALTIES;
	}
	public BigDecimal getA13_NO_OF_PENDING_COURT_CASES() {
		return A13_NO_OF_PENDING_COURT_CASES;
	}
	public void setA13_NO_OF_PENDING_COURT_CASES(BigDecimal a13_NO_OF_PENDING_COURT_CASES) {
		A13_NO_OF_PENDING_COURT_CASES = a13_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA13_AMOUNT_OF_PENALTIES_PENDING() {
		return A13_AMOUNT_OF_PENALTIES_PENDING;
	}
	public void setA13_AMOUNT_OF_PENALTIES_PENDING(BigDecimal a13_AMOUNT_OF_PENALTIES_PENDING) {
		A13_AMOUNT_OF_PENALTIES_PENDING = a13_AMOUNT_OF_PENALTIES_PENDING;
	}
	public String getA14_PRODUCT() {
		return A14_PRODUCT;
	}
	public void setA14_PRODUCT(String a14_PRODUCT) {
		A14_PRODUCT = a14_PRODUCT;
	}
	public BigDecimal getA14_NO_OF_COURT_CASES() {
		return A14_NO_OF_COURT_CASES;
	}
	public void setA14_NO_OF_COURT_CASES(BigDecimal a14_NO_OF_COURT_CASES) {
		A14_NO_OF_COURT_CASES = a14_NO_OF_COURT_CASES;
	}
	public BigDecimal getA14_AMOUNT_OF_PENALTIES() {
		return A14_AMOUNT_OF_PENALTIES;
	}
	public void setA14_AMOUNT_OF_PENALTIES(BigDecimal a14_AMOUNT_OF_PENALTIES) {
		A14_AMOUNT_OF_PENALTIES = a14_AMOUNT_OF_PENALTIES;
	}
	public BigDecimal getA14_NO_OF_PENDING_COURT_CASES() {
		return A14_NO_OF_PENDING_COURT_CASES;
	}
	public void setA14_NO_OF_PENDING_COURT_CASES(BigDecimal a14_NO_OF_PENDING_COURT_CASES) {
		A14_NO_OF_PENDING_COURT_CASES = a14_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA14_AMOUNT_OF_PENALTIES_PENDING() {
		return A14_AMOUNT_OF_PENALTIES_PENDING;
	}
	public void setA14_AMOUNT_OF_PENALTIES_PENDING(BigDecimal a14_AMOUNT_OF_PENALTIES_PENDING) {
		A14_AMOUNT_OF_PENALTIES_PENDING = a14_AMOUNT_OF_PENALTIES_PENDING;
	}
	public String getA15_PRODUCT() {
		return A15_PRODUCT;
	}
	public void setA15_PRODUCT(String a15_PRODUCT) {
		A15_PRODUCT = a15_PRODUCT;
	}
	public BigDecimal getA15_NO_OF_COURT_CASES() {
		return A15_NO_OF_COURT_CASES;
	}
	public void setA15_NO_OF_COURT_CASES(BigDecimal a15_NO_OF_COURT_CASES) {
		A15_NO_OF_COURT_CASES = a15_NO_OF_COURT_CASES;
	}
	public BigDecimal getA15_AMOUNT_OF_PENALTIES() {
		return A15_AMOUNT_OF_PENALTIES;
	}
	public void setA15_AMOUNT_OF_PENALTIES(BigDecimal a15_AMOUNT_OF_PENALTIES) {
		A15_AMOUNT_OF_PENALTIES = a15_AMOUNT_OF_PENALTIES;
	}
	public BigDecimal getA15_NO_OF_PENDING_COURT_CASES() {
		return A15_NO_OF_PENDING_COURT_CASES;
	}
	public void setA15_NO_OF_PENDING_COURT_CASES(BigDecimal a15_NO_OF_PENDING_COURT_CASES) {
		A15_NO_OF_PENDING_COURT_CASES = a15_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA15_AMOUNT_OF_PENALTIES_PENDING() {
		return A15_AMOUNT_OF_PENALTIES_PENDING;
	}
	public void setA15_AMOUNT_OF_PENALTIES_PENDING(BigDecimal a15_AMOUNT_OF_PENALTIES_PENDING) {
		A15_AMOUNT_OF_PENALTIES_PENDING = a15_AMOUNT_OF_PENALTIES_PENDING;
	}
	public String getA16_PRODUCT() {
		return A16_PRODUCT;
	}
	public void setA16_PRODUCT(String a16_PRODUCT) {
		A16_PRODUCT = a16_PRODUCT;
	}
	public BigDecimal getA16_NO_OF_COURT_CASES() {
		return A16_NO_OF_COURT_CASES;
	}
	public void setA16_NO_OF_COURT_CASES(BigDecimal a16_NO_OF_COURT_CASES) {
		A16_NO_OF_COURT_CASES = a16_NO_OF_COURT_CASES;
	}
	public BigDecimal getA16_AMOUNT_OF_PENALTIES() {
		return A16_AMOUNT_OF_PENALTIES;
	}
	public void setA16_AMOUNT_OF_PENALTIES(BigDecimal a16_AMOUNT_OF_PENALTIES) {
		A16_AMOUNT_OF_PENALTIES = a16_AMOUNT_OF_PENALTIES;
	}
	public BigDecimal getA16_NO_OF_PENDING_COURT_CASES() {
		return A16_NO_OF_PENDING_COURT_CASES;
	}
	public void setA16_NO_OF_PENDING_COURT_CASES(BigDecimal a16_NO_OF_PENDING_COURT_CASES) {
		A16_NO_OF_PENDING_COURT_CASES = a16_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA16_AMOUNT_OF_PENALTIES_PENDING() {
		return A16_AMOUNT_OF_PENALTIES_PENDING;
	}
	public void setA16_AMOUNT_OF_PENALTIES_PENDING(BigDecimal a16_AMOUNT_OF_PENALTIES_PENDING) {
		A16_AMOUNT_OF_PENALTIES_PENDING = a16_AMOUNT_OF_PENALTIES_PENDING;
	}
	public String getA17_PRODUCT() {
		return A17_PRODUCT;
	}
	public void setA17_PRODUCT(String a17_PRODUCT) {
		A17_PRODUCT = a17_PRODUCT;
	}
	public BigDecimal getA17_NO_OF_COURT_CASES() {
		return A17_NO_OF_COURT_CASES;
	}
	public void setA17_NO_OF_COURT_CASES(BigDecimal a17_NO_OF_COURT_CASES) {
		A17_NO_OF_COURT_CASES = a17_NO_OF_COURT_CASES;
	}
	public BigDecimal getA17_AMOUNT_OF_PENALTIES() {
		return A17_AMOUNT_OF_PENALTIES;
	}
	public void setA17_AMOUNT_OF_PENALTIES(BigDecimal a17_AMOUNT_OF_PENALTIES) {
		A17_AMOUNT_OF_PENALTIES = a17_AMOUNT_OF_PENALTIES;
	}
	public BigDecimal getA17_NO_OF_PENDING_COURT_CASES() {
		return A17_NO_OF_PENDING_COURT_CASES;
	}
	public void setA17_NO_OF_PENDING_COURT_CASES(BigDecimal a17_NO_OF_PENDING_COURT_CASES) {
		A17_NO_OF_PENDING_COURT_CASES = a17_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA17_AMOUNT_OF_PENALTIES_PENDING() {
		return A17_AMOUNT_OF_PENALTIES_PENDING;
	}
	public void setA17_AMOUNT_OF_PENALTIES_PENDING(BigDecimal a17_AMOUNT_OF_PENALTIES_PENDING) {
		A17_AMOUNT_OF_PENALTIES_PENDING = a17_AMOUNT_OF_PENALTIES_PENDING;
	}
	public String getA18_PRODUCT() {
		return A18_PRODUCT;
	}
	public void setA18_PRODUCT(String a18_PRODUCT) {
		A18_PRODUCT = a18_PRODUCT;
	}
	public BigDecimal getA18_NO_OF_COURT_CASES() {
		return A18_NO_OF_COURT_CASES;
	}
	public void setA18_NO_OF_COURT_CASES(BigDecimal a18_NO_OF_COURT_CASES) {
		A18_NO_OF_COURT_CASES = a18_NO_OF_COURT_CASES;
	}
	public BigDecimal getA18_AMOUNT_OF_PENALTIES() {
		return A18_AMOUNT_OF_PENALTIES;
	}
	public void setA18_AMOUNT_OF_PENALTIES(BigDecimal a18_AMOUNT_OF_PENALTIES) {
		A18_AMOUNT_OF_PENALTIES = a18_AMOUNT_OF_PENALTIES;
	}
	public BigDecimal getA18_NO_OF_PENDING_COURT_CASES() {
		return A18_NO_OF_PENDING_COURT_CASES;
	}
	public void setA18_NO_OF_PENDING_COURT_CASES(BigDecimal a18_NO_OF_PENDING_COURT_CASES) {
		A18_NO_OF_PENDING_COURT_CASES = a18_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA18_AMOUNT_OF_PENALTIES_PENDING() {
		return A18_AMOUNT_OF_PENALTIES_PENDING;
	}
	public void setA18_AMOUNT_OF_PENALTIES_PENDING(BigDecimal a18_AMOUNT_OF_PENALTIES_PENDING) {
		A18_AMOUNT_OF_PENALTIES_PENDING = a18_AMOUNT_OF_PENALTIES_PENDING;
	}
	public String getA19_PRODUCT() {
		return A19_PRODUCT;
	}
	public void setA19_PRODUCT(String a19_PRODUCT) {
		A19_PRODUCT = a19_PRODUCT;
	}
	public BigDecimal getA19_NO_OF_COURT_CASES() {
		return A19_NO_OF_COURT_CASES;
	}
	public void setA19_NO_OF_COURT_CASES(BigDecimal a19_NO_OF_COURT_CASES) {
		A19_NO_OF_COURT_CASES = a19_NO_OF_COURT_CASES;
	}
	public BigDecimal getA19_AMOUNT_OF_PENALTIES() {
		return A19_AMOUNT_OF_PENALTIES;
	}
	public void setA19_AMOUNT_OF_PENALTIES(BigDecimal a19_AMOUNT_OF_PENALTIES) {
		A19_AMOUNT_OF_PENALTIES = a19_AMOUNT_OF_PENALTIES;
	}
	public BigDecimal getA19_NO_OF_PENDING_COURT_CASES() {
		return A19_NO_OF_PENDING_COURT_CASES;
	}
	public void setA19_NO_OF_PENDING_COURT_CASES(BigDecimal a19_NO_OF_PENDING_COURT_CASES) {
		A19_NO_OF_PENDING_COURT_CASES = a19_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA19_AMOUNT_OF_PENALTIES_PENDING() {
		return A19_AMOUNT_OF_PENALTIES_PENDING;
	}
	public void setA19_AMOUNT_OF_PENALTIES_PENDING(BigDecimal a19_AMOUNT_OF_PENALTIES_PENDING) {
		A19_AMOUNT_OF_PENALTIES_PENDING = a19_AMOUNT_OF_PENALTIES_PENDING;
	}
	public String getA20_PRODUCT() {
		return A20_PRODUCT;
	}
	public void setA20_PRODUCT(String a20_PRODUCT) {
		A20_PRODUCT = a20_PRODUCT;
	}
	public BigDecimal getA20_NO_OF_COURT_CASES() {
		return A20_NO_OF_COURT_CASES;
	}
	public void setA20_NO_OF_COURT_CASES(BigDecimal a20_NO_OF_COURT_CASES) {
		A20_NO_OF_COURT_CASES = a20_NO_OF_COURT_CASES;
	}
	public BigDecimal getA20_AMOUNT_OF_PENALTIES() {
		return A20_AMOUNT_OF_PENALTIES;
	}
	public void setA20_AMOUNT_OF_PENALTIES(BigDecimal a20_AMOUNT_OF_PENALTIES) {
		A20_AMOUNT_OF_PENALTIES = a20_AMOUNT_OF_PENALTIES;
	}
	public BigDecimal getA20_NO_OF_PENDING_COURT_CASES() {
		return A20_NO_OF_PENDING_COURT_CASES;
	}
	public void setA20_NO_OF_PENDING_COURT_CASES(BigDecimal a20_NO_OF_PENDING_COURT_CASES) {
		A20_NO_OF_PENDING_COURT_CASES = a20_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA20_AMOUNT_OF_PENALTIES_PENDING() {
		return A20_AMOUNT_OF_PENALTIES_PENDING;
	}
	public void setA20_AMOUNT_OF_PENALTIES_PENDING(BigDecimal a20_AMOUNT_OF_PENALTIES_PENDING) {
		A20_AMOUNT_OF_PENALTIES_PENDING = a20_AMOUNT_OF_PENALTIES_PENDING;
	}
	public String getA21_PRODUCT() {
		return A21_PRODUCT;
	}
	public void setA21_PRODUCT(String a21_PRODUCT) {
		A21_PRODUCT = a21_PRODUCT;
	}
	public BigDecimal getA21_NO_OF_COURT_CASES() {
		return A21_NO_OF_COURT_CASES;
	}
	public void setA21_NO_OF_COURT_CASES(BigDecimal a21_NO_OF_COURT_CASES) {
		A21_NO_OF_COURT_CASES = a21_NO_OF_COURT_CASES;
	}
	public BigDecimal getA21_AMOUNT_OF_PENALTIES() {
		return A21_AMOUNT_OF_PENALTIES;
	}
	public void setA21_AMOUNT_OF_PENALTIES(BigDecimal a21_AMOUNT_OF_PENALTIES) {
		A21_AMOUNT_OF_PENALTIES = a21_AMOUNT_OF_PENALTIES;
	}
	public BigDecimal getA21_NO_OF_PENDING_COURT_CASES() {
		return A21_NO_OF_PENDING_COURT_CASES;
	}
	public void setA21_NO_OF_PENDING_COURT_CASES(BigDecimal a21_NO_OF_PENDING_COURT_CASES) {
		A21_NO_OF_PENDING_COURT_CASES = a21_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA21_AMOUNT_OF_PENALTIES_PENDING() {
		return A21_AMOUNT_OF_PENALTIES_PENDING;
	}
	public void setA21_AMOUNT_OF_PENALTIES_PENDING(BigDecimal a21_AMOUNT_OF_PENALTIES_PENDING) {
		A21_AMOUNT_OF_PENALTIES_PENDING = a21_AMOUNT_OF_PENALTIES_PENDING;
	}
	public String getA22_PRODUCT() {
		return A22_PRODUCT;
	}
	public void setA22_PRODUCT(String a22_PRODUCT) {
		A22_PRODUCT = a22_PRODUCT;
	}
	public BigDecimal getA22_NO_OF_COURT_CASES() {
		return A22_NO_OF_COURT_CASES;
	}
	public void setA22_NO_OF_COURT_CASES(BigDecimal a22_NO_OF_COURT_CASES) {
		A22_NO_OF_COURT_CASES = a22_NO_OF_COURT_CASES;
	}
	public BigDecimal getA22_AMOUNT_OF_PENALTIES() {
		return A22_AMOUNT_OF_PENALTIES;
	}
	public void setA22_AMOUNT_OF_PENALTIES(BigDecimal a22_AMOUNT_OF_PENALTIES) {
		A22_AMOUNT_OF_PENALTIES = a22_AMOUNT_OF_PENALTIES;
	}
	public BigDecimal getA22_NO_OF_PENDING_COURT_CASES() {
		return A22_NO_OF_PENDING_COURT_CASES;
	}
	public void setA22_NO_OF_PENDING_COURT_CASES(BigDecimal a22_NO_OF_PENDING_COURT_CASES) {
		A22_NO_OF_PENDING_COURT_CASES = a22_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA22_AMOUNT_OF_PENALTIES_PENDING() {
		return A22_AMOUNT_OF_PENALTIES_PENDING;
	}
	public void setA22_AMOUNT_OF_PENALTIES_PENDING(BigDecimal a22_AMOUNT_OF_PENALTIES_PENDING) {
		A22_AMOUNT_OF_PENALTIES_PENDING = a22_AMOUNT_OF_PENALTIES_PENDING;
	}
	public String getA23_PRODUCT() {
		return A23_PRODUCT;
	}
	public void setA23_PRODUCT(String a23_PRODUCT) {
		A23_PRODUCT = a23_PRODUCT;
	}
	public BigDecimal getA23_NO_OF_COURT_CASES() {
		return A23_NO_OF_COURT_CASES;
	}
	public void setA23_NO_OF_COURT_CASES(BigDecimal a23_NO_OF_COURT_CASES) {
		A23_NO_OF_COURT_CASES = a23_NO_OF_COURT_CASES;
	}
	public BigDecimal getA23_AMOUNT_OF_PENALTIES() {
		return A23_AMOUNT_OF_PENALTIES;
	}
	public void setA23_AMOUNT_OF_PENALTIES(BigDecimal a23_AMOUNT_OF_PENALTIES) {
		A23_AMOUNT_OF_PENALTIES = a23_AMOUNT_OF_PENALTIES;
	}
	public BigDecimal getA23_NO_OF_PENDING_COURT_CASES() {
		return A23_NO_OF_PENDING_COURT_CASES;
	}
	public void setA23_NO_OF_PENDING_COURT_CASES(BigDecimal a23_NO_OF_PENDING_COURT_CASES) {
		A23_NO_OF_PENDING_COURT_CASES = a23_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA23_AMOUNT_OF_PENALTIES_PENDING() {
		return A23_AMOUNT_OF_PENALTIES_PENDING;
	}
	public void setA23_AMOUNT_OF_PENALTIES_PENDING(BigDecimal a23_AMOUNT_OF_PENALTIES_PENDING) {
		A23_AMOUNT_OF_PENALTIES_PENDING = a23_AMOUNT_OF_PENALTIES_PENDING;
	}
	public String getA24_PRODUCT() {
		return A24_PRODUCT;
	}
	public void setA24_PRODUCT(String a24_PRODUCT) {
		A24_PRODUCT = a24_PRODUCT;
	}
	public BigDecimal getA24_NO_OF_COURT_CASES() {
		return A24_NO_OF_COURT_CASES;
	}
	public void setA24_NO_OF_COURT_CASES(BigDecimal a24_NO_OF_COURT_CASES) {
		A24_NO_OF_COURT_CASES = a24_NO_OF_COURT_CASES;
	}
	public BigDecimal getA24_AMOUNT_OF_PENALTIES() {
		return A24_AMOUNT_OF_PENALTIES;
	}
	public void setA24_AMOUNT_OF_PENALTIES(BigDecimal a24_AMOUNT_OF_PENALTIES) {
		A24_AMOUNT_OF_PENALTIES = a24_AMOUNT_OF_PENALTIES;
	}
	public BigDecimal getA24_NO_OF_PENDING_COURT_CASES() {
		return A24_NO_OF_PENDING_COURT_CASES;
	}
	public void setA24_NO_OF_PENDING_COURT_CASES(BigDecimal a24_NO_OF_PENDING_COURT_CASES) {
		A24_NO_OF_PENDING_COURT_CASES = a24_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA24_AMOUNT_OF_PENALTIES_PENDING() {
		return A24_AMOUNT_OF_PENALTIES_PENDING;
	}
	public void setA24_AMOUNT_OF_PENALTIES_PENDING(BigDecimal a24_AMOUNT_OF_PENALTIES_PENDING) {
		A24_AMOUNT_OF_PENALTIES_PENDING = a24_AMOUNT_OF_PENALTIES_PENDING;
	}
	public String getA25_PRODUCT() {
		return A25_PRODUCT;
	}
	public void setA25_PRODUCT(String a25_PRODUCT) {
		A25_PRODUCT = a25_PRODUCT;
	}
	public BigDecimal getA25_NO_OF_COURT_CASES() {
		return A25_NO_OF_COURT_CASES;
	}
	public void setA25_NO_OF_COURT_CASES(BigDecimal a25_NO_OF_COURT_CASES) {
		A25_NO_OF_COURT_CASES = a25_NO_OF_COURT_CASES;
	}
	public BigDecimal getA25_AMOUNT_OF_PENALTIES() {
		return A25_AMOUNT_OF_PENALTIES;
	}
	public void setA25_AMOUNT_OF_PENALTIES(BigDecimal a25_AMOUNT_OF_PENALTIES) {
		A25_AMOUNT_OF_PENALTIES = a25_AMOUNT_OF_PENALTIES;
	}
	public BigDecimal getA25_NO_OF_PENDING_COURT_CASES() {
		return A25_NO_OF_PENDING_COURT_CASES;
	}
	public void setA25_NO_OF_PENDING_COURT_CASES(BigDecimal a25_NO_OF_PENDING_COURT_CASES) {
		A25_NO_OF_PENDING_COURT_CASES = a25_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA25_AMOUNT_OF_PENALTIES_PENDING() {
		return A25_AMOUNT_OF_PENALTIES_PENDING;
	}
	public void setA25_AMOUNT_OF_PENALTIES_PENDING(BigDecimal a25_AMOUNT_OF_PENALTIES_PENDING) {
		A25_AMOUNT_OF_PENALTIES_PENDING = a25_AMOUNT_OF_PENALTIES_PENDING;
	}
	public String getA26_PRODUCT() {
		return A26_PRODUCT;
	}
	public void setA26_PRODUCT(String a26_PRODUCT) {
		A26_PRODUCT = a26_PRODUCT;
	}
	public BigDecimal getA26_NO_OF_COURT_CASES() {
		return A26_NO_OF_COURT_CASES;
	}
	public void setA26_NO_OF_COURT_CASES(BigDecimal a26_NO_OF_COURT_CASES) {
		A26_NO_OF_COURT_CASES = a26_NO_OF_COURT_CASES;
	}
	public BigDecimal getA26_AMOUNT_OF_PENALTIES() {
		return A26_AMOUNT_OF_PENALTIES;
	}
	public void setA26_AMOUNT_OF_PENALTIES(BigDecimal a26_AMOUNT_OF_PENALTIES) {
		A26_AMOUNT_OF_PENALTIES = a26_AMOUNT_OF_PENALTIES;
	}
	public BigDecimal getA26_NO_OF_PENDING_COURT_CASES() {
		return A26_NO_OF_PENDING_COURT_CASES;
	}
	public void setA26_NO_OF_PENDING_COURT_CASES(BigDecimal a26_NO_OF_PENDING_COURT_CASES) {
		A26_NO_OF_PENDING_COURT_CASES = a26_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA26_AMOUNT_OF_PENALTIES_PENDING() {
		return A26_AMOUNT_OF_PENALTIES_PENDING;
	}
	public void setA26_AMOUNT_OF_PENALTIES_PENDING(BigDecimal a26_AMOUNT_OF_PENALTIES_PENDING) {
		A26_AMOUNT_OF_PENALTIES_PENDING = a26_AMOUNT_OF_PENALTIES_PENDING;
	}
	public String getA27_PRODUCT() {
		return A27_PRODUCT;
	}
	public void setA27_PRODUCT(String a27_PRODUCT) {
		A27_PRODUCT = a27_PRODUCT;
	}
	public BigDecimal getA27_NO_OF_COURT_CASES() {
		return A27_NO_OF_COURT_CASES;
	}
	public void setA27_NO_OF_COURT_CASES(BigDecimal a27_NO_OF_COURT_CASES) {
		A27_NO_OF_COURT_CASES = a27_NO_OF_COURT_CASES;
	}
	public BigDecimal getA27_AMOUNT_OF_PENALTIES() {
		return A27_AMOUNT_OF_PENALTIES;
	}
	public void setA27_AMOUNT_OF_PENALTIES(BigDecimal a27_AMOUNT_OF_PENALTIES) {
		A27_AMOUNT_OF_PENALTIES = a27_AMOUNT_OF_PENALTIES;
	}
	public BigDecimal getA27_NO_OF_PENDING_COURT_CASES() {
		return A27_NO_OF_PENDING_COURT_CASES;
	}
	public void setA27_NO_OF_PENDING_COURT_CASES(BigDecimal a27_NO_OF_PENDING_COURT_CASES) {
		A27_NO_OF_PENDING_COURT_CASES = a27_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA27_AMOUNT_OF_PENALTIES_PENDING() {
		return A27_AMOUNT_OF_PENALTIES_PENDING;
	}
	public void setA27_AMOUNT_OF_PENALTIES_PENDING(BigDecimal a27_AMOUNT_OF_PENALTIES_PENDING) {
		A27_AMOUNT_OF_PENALTIES_PENDING = a27_AMOUNT_OF_PENALTIES_PENDING;
	}
	public String getA28_PRODUCT() {
		return A28_PRODUCT;
	}
	public void setA28_PRODUCT(String a28_PRODUCT) {
		A28_PRODUCT = a28_PRODUCT;
	}
	public BigDecimal getA28_NO_OF_COURT_CASES() {
		return A28_NO_OF_COURT_CASES;
	}
	public void setA28_NO_OF_COURT_CASES(BigDecimal a28_NO_OF_COURT_CASES) {
		A28_NO_OF_COURT_CASES = a28_NO_OF_COURT_CASES;
	}
	public BigDecimal getA28_AMOUNT_OF_PENALTIES() {
		return A28_AMOUNT_OF_PENALTIES;
	}
	public void setA28_AMOUNT_OF_PENALTIES(BigDecimal a28_AMOUNT_OF_PENALTIES) {
		A28_AMOUNT_OF_PENALTIES = a28_AMOUNT_OF_PENALTIES;
	}
	public BigDecimal getA28_NO_OF_PENDING_COURT_CASES() {
		return A28_NO_OF_PENDING_COURT_CASES;
	}
	public void setA28_NO_OF_PENDING_COURT_CASES(BigDecimal a28_NO_OF_PENDING_COURT_CASES) {
		A28_NO_OF_PENDING_COURT_CASES = a28_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA28_AMOUNT_OF_PENALTIES_PENDING() {
		return A28_AMOUNT_OF_PENALTIES_PENDING;
	}
	public void setA28_AMOUNT_OF_PENALTIES_PENDING(BigDecimal a28_AMOUNT_OF_PENALTIES_PENDING) {
		A28_AMOUNT_OF_PENALTIES_PENDING = a28_AMOUNT_OF_PENALTIES_PENDING;
	}
	public String getA29_PRODUCT() {
		return A29_PRODUCT;
	}
	public void setA29_PRODUCT(String a29_PRODUCT) {
		A29_PRODUCT = a29_PRODUCT;
	}
	public BigDecimal getA29_NO_OF_COURT_CASES() {
		return A29_NO_OF_COURT_CASES;
	}
	public void setA29_NO_OF_COURT_CASES(BigDecimal a29_NO_OF_COURT_CASES) {
		A29_NO_OF_COURT_CASES = a29_NO_OF_COURT_CASES;
	}
	public BigDecimal getA29_AMOUNT_OF_PENALTIES() {
		return A29_AMOUNT_OF_PENALTIES;
	}
	public void setA29_AMOUNT_OF_PENALTIES(BigDecimal a29_AMOUNT_OF_PENALTIES) {
		A29_AMOUNT_OF_PENALTIES = a29_AMOUNT_OF_PENALTIES;
	}
	public BigDecimal getA29_NO_OF_PENDING_COURT_CASES() {
		return A29_NO_OF_PENDING_COURT_CASES;
	}
	public void setA29_NO_OF_PENDING_COURT_CASES(BigDecimal a29_NO_OF_PENDING_COURT_CASES) {
		A29_NO_OF_PENDING_COURT_CASES = a29_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA29_AMOUNT_OF_PENALTIES_PENDING() {
		return A29_AMOUNT_OF_PENALTIES_PENDING;
	}
	public void setA29_AMOUNT_OF_PENALTIES_PENDING(BigDecimal a29_AMOUNT_OF_PENALTIES_PENDING) {
		A29_AMOUNT_OF_PENALTIES_PENDING = a29_AMOUNT_OF_PENALTIES_PENDING;
	}
	public String getA30_PRODUCT() {
		return A30_PRODUCT;
	}
	public void setA30_PRODUCT(String a30_PRODUCT) {
		A30_PRODUCT = a30_PRODUCT;
	}
	public BigDecimal getA30_NO_OF_COURT_CASES() {
		return A30_NO_OF_COURT_CASES;
	}
	public void setA30_NO_OF_COURT_CASES(BigDecimal a30_NO_OF_COURT_CASES) {
		A30_NO_OF_COURT_CASES = a30_NO_OF_COURT_CASES;
	}
	public BigDecimal getA30_AMOUNT_OF_PENALTIES() {
		return A30_AMOUNT_OF_PENALTIES;
	}
	public void setA30_AMOUNT_OF_PENALTIES(BigDecimal a30_AMOUNT_OF_PENALTIES) {
		A30_AMOUNT_OF_PENALTIES = a30_AMOUNT_OF_PENALTIES;
	}
	public BigDecimal getA30_NO_OF_PENDING_COURT_CASES() {
		return A30_NO_OF_PENDING_COURT_CASES;
	}
	public void setA30_NO_OF_PENDING_COURT_CASES(BigDecimal a30_NO_OF_PENDING_COURT_CASES) {
		A30_NO_OF_PENDING_COURT_CASES = a30_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA30_AMOUNT_OF_PENALTIES_PENDING() {
		return A30_AMOUNT_OF_PENALTIES_PENDING;
	}
	public void setA30_AMOUNT_OF_PENALTIES_PENDING(BigDecimal a30_AMOUNT_OF_PENALTIES_PENDING) {
		A30_AMOUNT_OF_PENALTIES_PENDING = a30_AMOUNT_OF_PENALTIES_PENDING;
	}
	public String getA31_PRODUCT() {
		return A31_PRODUCT;
	}
	public void setA31_PRODUCT(String a31_PRODUCT) {
		A31_PRODUCT = a31_PRODUCT;
	}
	public BigDecimal getA31_NO_OF_COURT_CASES() {
		return A31_NO_OF_COURT_CASES;
	}
	public void setA31_NO_OF_COURT_CASES(BigDecimal a31_NO_OF_COURT_CASES) {
		A31_NO_OF_COURT_CASES = a31_NO_OF_COURT_CASES;
	}
	public BigDecimal getA31_AMOUNT_OF_PENALTIES() {
		return A31_AMOUNT_OF_PENALTIES;
	}
	public void setA31_AMOUNT_OF_PENALTIES(BigDecimal a31_AMOUNT_OF_PENALTIES) {
		A31_AMOUNT_OF_PENALTIES = a31_AMOUNT_OF_PENALTIES;
	}
	public BigDecimal getA31_NO_OF_PENDING_COURT_CASES() {
		return A31_NO_OF_PENDING_COURT_CASES;
	}
	public void setA31_NO_OF_PENDING_COURT_CASES(BigDecimal a31_NO_OF_PENDING_COURT_CASES) {
		A31_NO_OF_PENDING_COURT_CASES = a31_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA31_AMOUNT_OF_PENALTIES_PENDING() {
		return A31_AMOUNT_OF_PENALTIES_PENDING;
	}
	public void setA31_AMOUNT_OF_PENALTIES_PENDING(BigDecimal a31_AMOUNT_OF_PENALTIES_PENDING) {
		A31_AMOUNT_OF_PENALTIES_PENDING = a31_AMOUNT_OF_PENALTIES_PENDING;
	}
	public String getA32_PRODUCT() {
		return A32_PRODUCT;
	}
	public void setA32_PRODUCT(String a32_PRODUCT) {
		A32_PRODUCT = a32_PRODUCT;
	}
	public BigDecimal getA32_NO_OF_COURT_CASES() {
		return A32_NO_OF_COURT_CASES;
	}
	public void setA32_NO_OF_COURT_CASES(BigDecimal a32_NO_OF_COURT_CASES) {
		A32_NO_OF_COURT_CASES = a32_NO_OF_COURT_CASES;
	}
	public BigDecimal getA32_AMOUNT_OF_PENALTIES() {
		return A32_AMOUNT_OF_PENALTIES;
	}
	public void setA32_AMOUNT_OF_PENALTIES(BigDecimal a32_AMOUNT_OF_PENALTIES) {
		A32_AMOUNT_OF_PENALTIES = a32_AMOUNT_OF_PENALTIES;
	}
	public BigDecimal getA32_NO_OF_PENDING_COURT_CASES() {
		return A32_NO_OF_PENDING_COURT_CASES;
	}
	public void setA32_NO_OF_PENDING_COURT_CASES(BigDecimal a32_NO_OF_PENDING_COURT_CASES) {
		A32_NO_OF_PENDING_COURT_CASES = a32_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA32_AMOUNT_OF_PENALTIES_PENDING() {
		return A32_AMOUNT_OF_PENALTIES_PENDING;
	}
	public void setA32_AMOUNT_OF_PENALTIES_PENDING(BigDecimal a32_AMOUNT_OF_PENALTIES_PENDING) {
		A32_AMOUNT_OF_PENALTIES_PENDING = a32_AMOUNT_OF_PENALTIES_PENDING;
	}
	public String getA33_PRODUCT() {
		return A33_PRODUCT;
	}
	public void setA33_PRODUCT(String a33_PRODUCT) {
		A33_PRODUCT = a33_PRODUCT;
	}
	public BigDecimal getA33_NO_OF_COURT_CASES() {
		return A33_NO_OF_COURT_CASES;
	}
	public void setA33_NO_OF_COURT_CASES(BigDecimal a33_NO_OF_COURT_CASES) {
		A33_NO_OF_COURT_CASES = a33_NO_OF_COURT_CASES;
	}
	public BigDecimal getA33_AMOUNT_OF_PENALTIES() {
		return A33_AMOUNT_OF_PENALTIES;
	}
	public void setA33_AMOUNT_OF_PENALTIES(BigDecimal a33_AMOUNT_OF_PENALTIES) {
		A33_AMOUNT_OF_PENALTIES = a33_AMOUNT_OF_PENALTIES;
	}
	public BigDecimal getA33_NO_OF_PENDING_COURT_CASES() {
		return A33_NO_OF_PENDING_COURT_CASES;
	}
	public void setA33_NO_OF_PENDING_COURT_CASES(BigDecimal a33_NO_OF_PENDING_COURT_CASES) {
		A33_NO_OF_PENDING_COURT_CASES = a33_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA33_AMOUNT_OF_PENALTIES_PENDING() {
		return A33_AMOUNT_OF_PENALTIES_PENDING;
	}
	public void setA33_AMOUNT_OF_PENALTIES_PENDING(BigDecimal a33_AMOUNT_OF_PENALTIES_PENDING) {
		A33_AMOUNT_OF_PENALTIES_PENDING = a33_AMOUNT_OF_PENALTIES_PENDING;
	}
	public String getA34_PRODUCT() {
		return A34_PRODUCT;
	}
	public void setA34_PRODUCT(String a34_PRODUCT) {
		A34_PRODUCT = a34_PRODUCT;
	}
	public BigDecimal getA34_NO_OF_COURT_CASES() {
		return A34_NO_OF_COURT_CASES;
	}
	public void setA34_NO_OF_COURT_CASES(BigDecimal a34_NO_OF_COURT_CASES) {
		A34_NO_OF_COURT_CASES = a34_NO_OF_COURT_CASES;
	}
	public BigDecimal getA34_AMOUNT_OF_PENALTIES() {
		return A34_AMOUNT_OF_PENALTIES;
	}
	public void setA34_AMOUNT_OF_PENALTIES(BigDecimal a34_AMOUNT_OF_PENALTIES) {
		A34_AMOUNT_OF_PENALTIES = a34_AMOUNT_OF_PENALTIES;
	}
	public BigDecimal getA34_NO_OF_PENDING_COURT_CASES() {
		return A34_NO_OF_PENDING_COURT_CASES;
	}
	public void setA34_NO_OF_PENDING_COURT_CASES(BigDecimal a34_NO_OF_PENDING_COURT_CASES) {
		A34_NO_OF_PENDING_COURT_CASES = a34_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA34_AMOUNT_OF_PENALTIES_PENDING() {
		return A34_AMOUNT_OF_PENALTIES_PENDING;
	}
	public void setA34_AMOUNT_OF_PENALTIES_PENDING(BigDecimal a34_AMOUNT_OF_PENALTIES_PENDING) {
		A34_AMOUNT_OF_PENALTIES_PENDING = a34_AMOUNT_OF_PENALTIES_PENDING;
	}
	public String getA35_PRODUCT() {
		return A35_PRODUCT;
	}
	public void setA35_PRODUCT(String a35_PRODUCT) {
		A35_PRODUCT = a35_PRODUCT;
	}
	public BigDecimal getA35_NO_OF_COURT_CASES() {
		return A35_NO_OF_COURT_CASES;
	}
	public void setA35_NO_OF_COURT_CASES(BigDecimal a35_NO_OF_COURT_CASES) {
		A35_NO_OF_COURT_CASES = a35_NO_OF_COURT_CASES;
	}
	public BigDecimal getA35_AMOUNT_OF_PENALTIES() {
		return A35_AMOUNT_OF_PENALTIES;
	}
	public void setA35_AMOUNT_OF_PENALTIES(BigDecimal a35_AMOUNT_OF_PENALTIES) {
		A35_AMOUNT_OF_PENALTIES = a35_AMOUNT_OF_PENALTIES;
	}
	public BigDecimal getA35_NO_OF_PENDING_COURT_CASES() {
		return A35_NO_OF_PENDING_COURT_CASES;
	}
	public void setA35_NO_OF_PENDING_COURT_CASES(BigDecimal a35_NO_OF_PENDING_COURT_CASES) {
		A35_NO_OF_PENDING_COURT_CASES = a35_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA35_AMOUNT_OF_PENALTIES_PENDING() {
		return A35_AMOUNT_OF_PENALTIES_PENDING;
	}
	public void setA35_AMOUNT_OF_PENALTIES_PENDING(BigDecimal a35_AMOUNT_OF_PENALTIES_PENDING) {
		A35_AMOUNT_OF_PENALTIES_PENDING = a35_AMOUNT_OF_PENALTIES_PENDING;
	}
	public String getA36_PRODUCT() {
		return A36_PRODUCT;
	}
	public void setA36_PRODUCT(String a36_PRODUCT) {
		A36_PRODUCT = a36_PRODUCT;
	}
	public BigDecimal getA36_NO_OF_COURT_CASES() {
		return A36_NO_OF_COURT_CASES;
	}
	public void setA36_NO_OF_COURT_CASES(BigDecimal a36_NO_OF_COURT_CASES) {
		A36_NO_OF_COURT_CASES = a36_NO_OF_COURT_CASES;
	}
	public BigDecimal getA36_AMOUNT_OF_PENALTIES() {
		return A36_AMOUNT_OF_PENALTIES;
	}
	public void setA36_AMOUNT_OF_PENALTIES(BigDecimal a36_AMOUNT_OF_PENALTIES) {
		A36_AMOUNT_OF_PENALTIES = a36_AMOUNT_OF_PENALTIES;
	}
	public BigDecimal getA36_NO_OF_PENDING_COURT_CASES() {
		return A36_NO_OF_PENDING_COURT_CASES;
	}
	public void setA36_NO_OF_PENDING_COURT_CASES(BigDecimal a36_NO_OF_PENDING_COURT_CASES) {
		A36_NO_OF_PENDING_COURT_CASES = a36_NO_OF_PENDING_COURT_CASES;
	}
	public BigDecimal getA36_AMOUNT_OF_PENALTIES_PENDING() {
		return A36_AMOUNT_OF_PENALTIES_PENDING;
	}
	public void setA36_AMOUNT_OF_PENALTIES_PENDING(BigDecimal a36_AMOUNT_OF_PENALTIES_PENDING) {
		A36_AMOUNT_OF_PENALTIES_PENDING = a36_AMOUNT_OF_PENALTIES_PENDING;
	}
	public String getREPORT_CODE() {
		return REPORT_CODE;
	}
	public void setREPORT_CODE(String rEPORT_CODE) {
		REPORT_CODE = rEPORT_CODE;
	}
	public String getREPORT_NAME() {
		return REPORT_NAME;
	}
	public void setREPORT_NAME(String rEPORT_NAME) {
		REPORT_NAME = rEPORT_NAME;
	}
	public Date getREPORT_DATE() {
		return REPORT_DATE;
	}
	public void setREPORT_DATE(Date rEPORT_DATE) {
		REPORT_DATE = rEPORT_DATE;
	}
	public Date getREPORT_DUE_DATE() {
		return REPORT_DUE_DATE;
	}
	public void setREPORT_DUE_DATE(Date rEPORT_DUE_DATE) {
		REPORT_DUE_DATE = rEPORT_DUE_DATE;
	}
	public Date getREP_SUBMIT_DATE() {
		return REP_SUBMIT_DATE;
	}
	public void setREP_SUBMIT_DATE(Date rEP_SUBMIT_DATE) {
		REP_SUBMIT_DATE = rEP_SUBMIT_DATE;
	}
	public Date getREP_PERIOD_FROM() {
		return REP_PERIOD_FROM;
	}
	public void setREP_PERIOD_FROM(Date rEP_PERIOD_FROM) {
		REP_PERIOD_FROM = rEP_PERIOD_FROM;
	}
	public Date getREP_PERIOD_TO() {
		return REP_PERIOD_TO;
	}
	public void setREP_PERIOD_TO(Date rEP_PERIOD_TO) {
		REP_PERIOD_TO = rEP_PERIOD_TO;
	}
	public String getREP_FREQ() {
		return REP_FREQ;
	}
	public void setREP_FREQ(String rEP_FREQ) {
		REP_FREQ = rEP_FREQ;
	}
	public String getNIL_REPORT_FLG() {
		return NIL_REPORT_FLG;
	}
	public void setNIL_REPORT_FLG(String nIL_REPORT_FLG) {
		NIL_REPORT_FLG = nIL_REPORT_FLG;
	}
	public String getARCH_FLG() {
		return ARCH_FLG;
	}
	public void setARCH_FLG(String aRCH_FLG) {
		ARCH_FLG = aRCH_FLG;
	}
	public String getENTITY_FLG() {
		return ENTITY_FLG;
	}
	public void setENTITY_FLG(String eNTITY_FLG) {
		ENTITY_FLG = eNTITY_FLG;
	}
	public String getDEL_FLG() {
		return DEL_FLG;
	}
	public void setDEL_FLG(String dEL_FLG) {
		DEL_FLG = dEL_FLG;
	}
	public String getMODIFY_FLG() {
		return MODIFY_FLG;
	}
	public void setMODIFY_FLG(String mODIFY_FLG) {
		MODIFY_FLG = mODIFY_FLG;
	}
	public String getENTRY_USER() {
		return ENTRY_USER;
	}
	public void setENTRY_USER(String eNTRY_USER) {
		ENTRY_USER = eNTRY_USER;
	}
	public String getMODIFY_USER() {
		return MODIFY_USER;
	}
	public void setMODIFY_USER(String mODIFY_USER) {
		MODIFY_USER = mODIFY_USER;
	}
	public String getVERIFY_USER() {
		return VERIFY_USER;
	}
	public void setVERIFY_USER(String vERIFY_USER) {
		VERIFY_USER = vERIFY_USER;
	}
	public Date getENTRY_TIME() {
		return ENTRY_TIME;
	}
	public void setENTRY_TIME(Date eNTRY_TIME) {
		ENTRY_TIME = eNTRY_TIME;
	}
	public Date getMODIFY_TIME() {
		return MODIFY_TIME;
	}
	public void setMODIFY_TIME(Date mODIFY_TIME) {
		MODIFY_TIME = mODIFY_TIME;
	}
	public Date getVERIFY_TIME() {
		return VERIFY_TIME;
	}
	public void setVERIFY_TIME(Date vERIFY_TIME) {
		VERIFY_TIME = vERIFY_TIME;
	}
	public String getQTR_FLG() {
		return QTR_FLG;
	}
	public void setQTR_FLG(String qTR_FLG) {
		QTR_FLG = qTR_FLG;
	}
	public T9ORReport(String a1_PRODUCT, BigDecimal a1_NO_OF_COURT_CASES, BigDecimal a1_AMOUNT_OF_PENALTIES,
			BigDecimal a1_NO_OF_PENDING_COURT_CASES, BigDecimal a1_AMOUNT_OF_PENALTIES_PENDING, String a2_PRODUCT,
			BigDecimal a2_NO_OF_COURT_CASES, BigDecimal a2_AMOUNT_OF_PENALTIES, BigDecimal a2_NO_OF_PENDING_COURT_CASES,
			BigDecimal a2_AMOUNT_OF_PENALTIES_PENDING, String a3_PRODUCT, BigDecimal a3_NO_OF_COURT_CASES,
			BigDecimal a3_AMOUNT_OF_PENALTIES, BigDecimal a3_NO_OF_PENDING_COURT_CASES,
			BigDecimal a3_AMOUNT_OF_PENALTIES_PENDING, String a4_PRODUCT, BigDecimal a4_NO_OF_COURT_CASES,
			BigDecimal a4_AMOUNT_OF_PENALTIES, BigDecimal a4_NO_OF_PENDING_COURT_CASES,
			BigDecimal a4_AMOUNT_OF_PENALTIES_PENDING, String a5_PRODUCT, BigDecimal a5_NO_OF_COURT_CASES,
			BigDecimal a5_AMOUNT_OF_PENALTIES, BigDecimal a5_NO_OF_PENDING_COURT_CASES,
			BigDecimal a5_AMOUNT_OF_PENALTIES_PENDING, String a6_PRODUCT, BigDecimal a6_NO_OF_COURT_CASES,
			BigDecimal a6_AMOUNT_OF_PENALTIES, BigDecimal a6_NO_OF_PENDING_COURT_CASES,
			BigDecimal a6_AMOUNT_OF_PENALTIES_PENDING, String a7_PRODUCT, BigDecimal a7_NO_OF_COURT_CASES,
			BigDecimal a7_AMOUNT_OF_PENALTIES, BigDecimal a7_NO_OF_PENDING_COURT_CASES,
			BigDecimal a7_AMOUNT_OF_PENALTIES_PENDING, String a8_PRODUCT, BigDecimal a8_NO_OF_COURT_CASES,
			BigDecimal a8_AMOUNT_OF_PENALTIES, BigDecimal a8_NO_OF_PENDING_COURT_CASES,
			BigDecimal a8_AMOUNT_OF_PENALTIES_PENDING, String a9_PRODUCT, BigDecimal a9_NO_OF_COURT_CASES,
			BigDecimal a9_AMOUNT_OF_PENALTIES, BigDecimal a9_NO_OF_PENDING_COURT_CASES,
			BigDecimal a9_AMOUNT_OF_PENALTIES_PENDING, String a10_PRODUCT, BigDecimal a10_NO_OF_COURT_CASES,
			BigDecimal a10_AMOUNT_OF_PENALTIES, BigDecimal a10_NO_OF_PENDING_COURT_CASES,
			BigDecimal a10_AMOUNT_OF_PENALTIES_PENDING, String a11_PRODUCT, BigDecimal a11_NO_OF_COURT_CASES,
			BigDecimal a11_AMOUNT_OF_PENALTIES, BigDecimal a11_NO_OF_PENDING_COURT_CASES,
			BigDecimal a11_AMOUNT_OF_PENALTIES_PENDING, String a12_PRODUCT, BigDecimal a12_NO_OF_COURT_CASES,
			BigDecimal a12_AMOUNT_OF_PENALTIES, BigDecimal a12_NO_OF_PENDING_COURT_CASES,
			BigDecimal a12_AMOUNT_OF_PENALTIES_PENDING, String a13_PRODUCT, BigDecimal a13_NO_OF_COURT_CASES,
			BigDecimal a13_AMOUNT_OF_PENALTIES, BigDecimal a13_NO_OF_PENDING_COURT_CASES,
			BigDecimal a13_AMOUNT_OF_PENALTIES_PENDING, String a14_PRODUCT, BigDecimal a14_NO_OF_COURT_CASES,
			BigDecimal a14_AMOUNT_OF_PENALTIES, BigDecimal a14_NO_OF_PENDING_COURT_CASES,
			BigDecimal a14_AMOUNT_OF_PENALTIES_PENDING, String a15_PRODUCT, BigDecimal a15_NO_OF_COURT_CASES,
			BigDecimal a15_AMOUNT_OF_PENALTIES, BigDecimal a15_NO_OF_PENDING_COURT_CASES,
			BigDecimal a15_AMOUNT_OF_PENALTIES_PENDING, String a16_PRODUCT, BigDecimal a16_NO_OF_COURT_CASES,
			BigDecimal a16_AMOUNT_OF_PENALTIES, BigDecimal a16_NO_OF_PENDING_COURT_CASES,
			BigDecimal a16_AMOUNT_OF_PENALTIES_PENDING, String a17_PRODUCT, BigDecimal a17_NO_OF_COURT_CASES,
			BigDecimal a17_AMOUNT_OF_PENALTIES, BigDecimal a17_NO_OF_PENDING_COURT_CASES,
			BigDecimal a17_AMOUNT_OF_PENALTIES_PENDING, String a18_PRODUCT, BigDecimal a18_NO_OF_COURT_CASES,
			BigDecimal a18_AMOUNT_OF_PENALTIES, BigDecimal a18_NO_OF_PENDING_COURT_CASES,
			BigDecimal a18_AMOUNT_OF_PENALTIES_PENDING, String a19_PRODUCT, BigDecimal a19_NO_OF_COURT_CASES,
			BigDecimal a19_AMOUNT_OF_PENALTIES, BigDecimal a19_NO_OF_PENDING_COURT_CASES,
			BigDecimal a19_AMOUNT_OF_PENALTIES_PENDING, String a20_PRODUCT, BigDecimal a20_NO_OF_COURT_CASES,
			BigDecimal a20_AMOUNT_OF_PENALTIES, BigDecimal a20_NO_OF_PENDING_COURT_CASES,
			BigDecimal a20_AMOUNT_OF_PENALTIES_PENDING, String a21_PRODUCT, BigDecimal a21_NO_OF_COURT_CASES,
			BigDecimal a21_AMOUNT_OF_PENALTIES, BigDecimal a21_NO_OF_PENDING_COURT_CASES,
			BigDecimal a21_AMOUNT_OF_PENALTIES_PENDING, String a22_PRODUCT, BigDecimal a22_NO_OF_COURT_CASES,
			BigDecimal a22_AMOUNT_OF_PENALTIES, BigDecimal a22_NO_OF_PENDING_COURT_CASES,
			BigDecimal a22_AMOUNT_OF_PENALTIES_PENDING, String a23_PRODUCT, BigDecimal a23_NO_OF_COURT_CASES,
			BigDecimal a23_AMOUNT_OF_PENALTIES, BigDecimal a23_NO_OF_PENDING_COURT_CASES,
			BigDecimal a23_AMOUNT_OF_PENALTIES_PENDING, String a24_PRODUCT, BigDecimal a24_NO_OF_COURT_CASES,
			BigDecimal a24_AMOUNT_OF_PENALTIES, BigDecimal a24_NO_OF_PENDING_COURT_CASES,
			BigDecimal a24_AMOUNT_OF_PENALTIES_PENDING, String a25_PRODUCT, BigDecimal a25_NO_OF_COURT_CASES,
			BigDecimal a25_AMOUNT_OF_PENALTIES, BigDecimal a25_NO_OF_PENDING_COURT_CASES,
			BigDecimal a25_AMOUNT_OF_PENALTIES_PENDING, String a26_PRODUCT, BigDecimal a26_NO_OF_COURT_CASES,
			BigDecimal a26_AMOUNT_OF_PENALTIES, BigDecimal a26_NO_OF_PENDING_COURT_CASES,
			BigDecimal a26_AMOUNT_OF_PENALTIES_PENDING, String a27_PRODUCT, BigDecimal a27_NO_OF_COURT_CASES,
			BigDecimal a27_AMOUNT_OF_PENALTIES, BigDecimal a27_NO_OF_PENDING_COURT_CASES,
			BigDecimal a27_AMOUNT_OF_PENALTIES_PENDING, String a28_PRODUCT, BigDecimal a28_NO_OF_COURT_CASES,
			BigDecimal a28_AMOUNT_OF_PENALTIES, BigDecimal a28_NO_OF_PENDING_COURT_CASES,
			BigDecimal a28_AMOUNT_OF_PENALTIES_PENDING, String a29_PRODUCT, BigDecimal a29_NO_OF_COURT_CASES,
			BigDecimal a29_AMOUNT_OF_PENALTIES, BigDecimal a29_NO_OF_PENDING_COURT_CASES,
			BigDecimal a29_AMOUNT_OF_PENALTIES_PENDING, String a30_PRODUCT, BigDecimal a30_NO_OF_COURT_CASES,
			BigDecimal a30_AMOUNT_OF_PENALTIES, BigDecimal a30_NO_OF_PENDING_COURT_CASES,
			BigDecimal a30_AMOUNT_OF_PENALTIES_PENDING, String a31_PRODUCT, BigDecimal a31_NO_OF_COURT_CASES,
			BigDecimal a31_AMOUNT_OF_PENALTIES, BigDecimal a31_NO_OF_PENDING_COURT_CASES,
			BigDecimal a31_AMOUNT_OF_PENALTIES_PENDING, String a32_PRODUCT, BigDecimal a32_NO_OF_COURT_CASES,
			BigDecimal a32_AMOUNT_OF_PENALTIES, BigDecimal a32_NO_OF_PENDING_COURT_CASES,
			BigDecimal a32_AMOUNT_OF_PENALTIES_PENDING, String a33_PRODUCT, BigDecimal a33_NO_OF_COURT_CASES,
			BigDecimal a33_AMOUNT_OF_PENALTIES, BigDecimal a33_NO_OF_PENDING_COURT_CASES,
			BigDecimal a33_AMOUNT_OF_PENALTIES_PENDING, String a34_PRODUCT, BigDecimal a34_NO_OF_COURT_CASES,
			BigDecimal a34_AMOUNT_OF_PENALTIES, BigDecimal a34_NO_OF_PENDING_COURT_CASES,
			BigDecimal a34_AMOUNT_OF_PENALTIES_PENDING, String a35_PRODUCT, BigDecimal a35_NO_OF_COURT_CASES,
			BigDecimal a35_AMOUNT_OF_PENALTIES, BigDecimal a35_NO_OF_PENDING_COURT_CASES,
			BigDecimal a35_AMOUNT_OF_PENALTIES_PENDING, String a36_PRODUCT, BigDecimal a36_NO_OF_COURT_CASES,
			BigDecimal a36_AMOUNT_OF_PENALTIES, BigDecimal a36_NO_OF_PENDING_COURT_CASES,
			BigDecimal a36_AMOUNT_OF_PENALTIES_PENDING, String rEPORT_CODE, String rEPORT_NAME, Date rEPORT_DATE,
			Date rEPORT_DUE_DATE, Date rEP_SUBMIT_DATE, Date rEP_PERIOD_FROM, Date rEP_PERIOD_TO, String rEP_FREQ,
			String nIL_REPORT_FLG, String aRCH_FLG, String eNTITY_FLG, String dEL_FLG, String mODIFY_FLG,
			String eNTRY_USER, String mODIFY_USER, String vERIFY_USER, Date eNTRY_TIME, Date mODIFY_TIME,
			Date vERIFY_TIME, String qTR_FLG) {
		super();
		A1_PRODUCT = a1_PRODUCT;
		A1_NO_OF_COURT_CASES = a1_NO_OF_COURT_CASES;
		A1_AMOUNT_OF_PENALTIES = a1_AMOUNT_OF_PENALTIES;
		A1_NO_OF_PENDING_COURT_CASES = a1_NO_OF_PENDING_COURT_CASES;
		A1_AMOUNT_OF_PENALTIES_PENDING = a1_AMOUNT_OF_PENALTIES_PENDING;
		A2_PRODUCT = a2_PRODUCT;
		A2_NO_OF_COURT_CASES = a2_NO_OF_COURT_CASES;
		A2_AMOUNT_OF_PENALTIES = a2_AMOUNT_OF_PENALTIES;
		A2_NO_OF_PENDING_COURT_CASES = a2_NO_OF_PENDING_COURT_CASES;
		A2_AMOUNT_OF_PENALTIES_PENDING = a2_AMOUNT_OF_PENALTIES_PENDING;
		A3_PRODUCT = a3_PRODUCT;
		A3_NO_OF_COURT_CASES = a3_NO_OF_COURT_CASES;
		A3_AMOUNT_OF_PENALTIES = a3_AMOUNT_OF_PENALTIES;
		A3_NO_OF_PENDING_COURT_CASES = a3_NO_OF_PENDING_COURT_CASES;
		A3_AMOUNT_OF_PENALTIES_PENDING = a3_AMOUNT_OF_PENALTIES_PENDING;
		A4_PRODUCT = a4_PRODUCT;
		A4_NO_OF_COURT_CASES = a4_NO_OF_COURT_CASES;
		A4_AMOUNT_OF_PENALTIES = a4_AMOUNT_OF_PENALTIES;
		A4_NO_OF_PENDING_COURT_CASES = a4_NO_OF_PENDING_COURT_CASES;
		A4_AMOUNT_OF_PENALTIES_PENDING = a4_AMOUNT_OF_PENALTIES_PENDING;
		A5_PRODUCT = a5_PRODUCT;
		A5_NO_OF_COURT_CASES = a5_NO_OF_COURT_CASES;
		A5_AMOUNT_OF_PENALTIES = a5_AMOUNT_OF_PENALTIES;
		A5_NO_OF_PENDING_COURT_CASES = a5_NO_OF_PENDING_COURT_CASES;
		A5_AMOUNT_OF_PENALTIES_PENDING = a5_AMOUNT_OF_PENALTIES_PENDING;
		A6_PRODUCT = a6_PRODUCT;
		A6_NO_OF_COURT_CASES = a6_NO_OF_COURT_CASES;
		A6_AMOUNT_OF_PENALTIES = a6_AMOUNT_OF_PENALTIES;
		A6_NO_OF_PENDING_COURT_CASES = a6_NO_OF_PENDING_COURT_CASES;
		A6_AMOUNT_OF_PENALTIES_PENDING = a6_AMOUNT_OF_PENALTIES_PENDING;
		A7_PRODUCT = a7_PRODUCT;
		A7_NO_OF_COURT_CASES = a7_NO_OF_COURT_CASES;
		A7_AMOUNT_OF_PENALTIES = a7_AMOUNT_OF_PENALTIES;
		A7_NO_OF_PENDING_COURT_CASES = a7_NO_OF_PENDING_COURT_CASES;
		A7_AMOUNT_OF_PENALTIES_PENDING = a7_AMOUNT_OF_PENALTIES_PENDING;
		A8_PRODUCT = a8_PRODUCT;
		A8_NO_OF_COURT_CASES = a8_NO_OF_COURT_CASES;
		A8_AMOUNT_OF_PENALTIES = a8_AMOUNT_OF_PENALTIES;
		A8_NO_OF_PENDING_COURT_CASES = a8_NO_OF_PENDING_COURT_CASES;
		A8_AMOUNT_OF_PENALTIES_PENDING = a8_AMOUNT_OF_PENALTIES_PENDING;
		A9_PRODUCT = a9_PRODUCT;
		A9_NO_OF_COURT_CASES = a9_NO_OF_COURT_CASES;
		A9_AMOUNT_OF_PENALTIES = a9_AMOUNT_OF_PENALTIES;
		A9_NO_OF_PENDING_COURT_CASES = a9_NO_OF_PENDING_COURT_CASES;
		A9_AMOUNT_OF_PENALTIES_PENDING = a9_AMOUNT_OF_PENALTIES_PENDING;
		A10_PRODUCT = a10_PRODUCT;
		A10_NO_OF_COURT_CASES = a10_NO_OF_COURT_CASES;
		A10_AMOUNT_OF_PENALTIES = a10_AMOUNT_OF_PENALTIES;
		A10_NO_OF_PENDING_COURT_CASES = a10_NO_OF_PENDING_COURT_CASES;
		A10_AMOUNT_OF_PENALTIES_PENDING = a10_AMOUNT_OF_PENALTIES_PENDING;
		A11_PRODUCT = a11_PRODUCT;
		A11_NO_OF_COURT_CASES = a11_NO_OF_COURT_CASES;
		A11_AMOUNT_OF_PENALTIES = a11_AMOUNT_OF_PENALTIES;
		A11_NO_OF_PENDING_COURT_CASES = a11_NO_OF_PENDING_COURT_CASES;
		A11_AMOUNT_OF_PENALTIES_PENDING = a11_AMOUNT_OF_PENALTIES_PENDING;
		A12_PRODUCT = a12_PRODUCT;
		A12_NO_OF_COURT_CASES = a12_NO_OF_COURT_CASES;
		A12_AMOUNT_OF_PENALTIES = a12_AMOUNT_OF_PENALTIES;
		A12_NO_OF_PENDING_COURT_CASES = a12_NO_OF_PENDING_COURT_CASES;
		A12_AMOUNT_OF_PENALTIES_PENDING = a12_AMOUNT_OF_PENALTIES_PENDING;
		A13_PRODUCT = a13_PRODUCT;
		A13_NO_OF_COURT_CASES = a13_NO_OF_COURT_CASES;
		A13_AMOUNT_OF_PENALTIES = a13_AMOUNT_OF_PENALTIES;
		A13_NO_OF_PENDING_COURT_CASES = a13_NO_OF_PENDING_COURT_CASES;
		A13_AMOUNT_OF_PENALTIES_PENDING = a13_AMOUNT_OF_PENALTIES_PENDING;
		A14_PRODUCT = a14_PRODUCT;
		A14_NO_OF_COURT_CASES = a14_NO_OF_COURT_CASES;
		A14_AMOUNT_OF_PENALTIES = a14_AMOUNT_OF_PENALTIES;
		A14_NO_OF_PENDING_COURT_CASES = a14_NO_OF_PENDING_COURT_CASES;
		A14_AMOUNT_OF_PENALTIES_PENDING = a14_AMOUNT_OF_PENALTIES_PENDING;
		A15_PRODUCT = a15_PRODUCT;
		A15_NO_OF_COURT_CASES = a15_NO_OF_COURT_CASES;
		A15_AMOUNT_OF_PENALTIES = a15_AMOUNT_OF_PENALTIES;
		A15_NO_OF_PENDING_COURT_CASES = a15_NO_OF_PENDING_COURT_CASES;
		A15_AMOUNT_OF_PENALTIES_PENDING = a15_AMOUNT_OF_PENALTIES_PENDING;
		A16_PRODUCT = a16_PRODUCT;
		A16_NO_OF_COURT_CASES = a16_NO_OF_COURT_CASES;
		A16_AMOUNT_OF_PENALTIES = a16_AMOUNT_OF_PENALTIES;
		A16_NO_OF_PENDING_COURT_CASES = a16_NO_OF_PENDING_COURT_CASES;
		A16_AMOUNT_OF_PENALTIES_PENDING = a16_AMOUNT_OF_PENALTIES_PENDING;
		A17_PRODUCT = a17_PRODUCT;
		A17_NO_OF_COURT_CASES = a17_NO_OF_COURT_CASES;
		A17_AMOUNT_OF_PENALTIES = a17_AMOUNT_OF_PENALTIES;
		A17_NO_OF_PENDING_COURT_CASES = a17_NO_OF_PENDING_COURT_CASES;
		A17_AMOUNT_OF_PENALTIES_PENDING = a17_AMOUNT_OF_PENALTIES_PENDING;
		A18_PRODUCT = a18_PRODUCT;
		A18_NO_OF_COURT_CASES = a18_NO_OF_COURT_CASES;
		A18_AMOUNT_OF_PENALTIES = a18_AMOUNT_OF_PENALTIES;
		A18_NO_OF_PENDING_COURT_CASES = a18_NO_OF_PENDING_COURT_CASES;
		A18_AMOUNT_OF_PENALTIES_PENDING = a18_AMOUNT_OF_PENALTIES_PENDING;
		A19_PRODUCT = a19_PRODUCT;
		A19_NO_OF_COURT_CASES = a19_NO_OF_COURT_CASES;
		A19_AMOUNT_OF_PENALTIES = a19_AMOUNT_OF_PENALTIES;
		A19_NO_OF_PENDING_COURT_CASES = a19_NO_OF_PENDING_COURT_CASES;
		A19_AMOUNT_OF_PENALTIES_PENDING = a19_AMOUNT_OF_PENALTIES_PENDING;
		A20_PRODUCT = a20_PRODUCT;
		A20_NO_OF_COURT_CASES = a20_NO_OF_COURT_CASES;
		A20_AMOUNT_OF_PENALTIES = a20_AMOUNT_OF_PENALTIES;
		A20_NO_OF_PENDING_COURT_CASES = a20_NO_OF_PENDING_COURT_CASES;
		A20_AMOUNT_OF_PENALTIES_PENDING = a20_AMOUNT_OF_PENALTIES_PENDING;
		A21_PRODUCT = a21_PRODUCT;
		A21_NO_OF_COURT_CASES = a21_NO_OF_COURT_CASES;
		A21_AMOUNT_OF_PENALTIES = a21_AMOUNT_OF_PENALTIES;
		A21_NO_OF_PENDING_COURT_CASES = a21_NO_OF_PENDING_COURT_CASES;
		A21_AMOUNT_OF_PENALTIES_PENDING = a21_AMOUNT_OF_PENALTIES_PENDING;
		A22_PRODUCT = a22_PRODUCT;
		A22_NO_OF_COURT_CASES = a22_NO_OF_COURT_CASES;
		A22_AMOUNT_OF_PENALTIES = a22_AMOUNT_OF_PENALTIES;
		A22_NO_OF_PENDING_COURT_CASES = a22_NO_OF_PENDING_COURT_CASES;
		A22_AMOUNT_OF_PENALTIES_PENDING = a22_AMOUNT_OF_PENALTIES_PENDING;
		A23_PRODUCT = a23_PRODUCT;
		A23_NO_OF_COURT_CASES = a23_NO_OF_COURT_CASES;
		A23_AMOUNT_OF_PENALTIES = a23_AMOUNT_OF_PENALTIES;
		A23_NO_OF_PENDING_COURT_CASES = a23_NO_OF_PENDING_COURT_CASES;
		A23_AMOUNT_OF_PENALTIES_PENDING = a23_AMOUNT_OF_PENALTIES_PENDING;
		A24_PRODUCT = a24_PRODUCT;
		A24_NO_OF_COURT_CASES = a24_NO_OF_COURT_CASES;
		A24_AMOUNT_OF_PENALTIES = a24_AMOUNT_OF_PENALTIES;
		A24_NO_OF_PENDING_COURT_CASES = a24_NO_OF_PENDING_COURT_CASES;
		A24_AMOUNT_OF_PENALTIES_PENDING = a24_AMOUNT_OF_PENALTIES_PENDING;
		A25_PRODUCT = a25_PRODUCT;
		A25_NO_OF_COURT_CASES = a25_NO_OF_COURT_CASES;
		A25_AMOUNT_OF_PENALTIES = a25_AMOUNT_OF_PENALTIES;
		A25_NO_OF_PENDING_COURT_CASES = a25_NO_OF_PENDING_COURT_CASES;
		A25_AMOUNT_OF_PENALTIES_PENDING = a25_AMOUNT_OF_PENALTIES_PENDING;
		A26_PRODUCT = a26_PRODUCT;
		A26_NO_OF_COURT_CASES = a26_NO_OF_COURT_CASES;
		A26_AMOUNT_OF_PENALTIES = a26_AMOUNT_OF_PENALTIES;
		A26_NO_OF_PENDING_COURT_CASES = a26_NO_OF_PENDING_COURT_CASES;
		A26_AMOUNT_OF_PENALTIES_PENDING = a26_AMOUNT_OF_PENALTIES_PENDING;
		A27_PRODUCT = a27_PRODUCT;
		A27_NO_OF_COURT_CASES = a27_NO_OF_COURT_CASES;
		A27_AMOUNT_OF_PENALTIES = a27_AMOUNT_OF_PENALTIES;
		A27_NO_OF_PENDING_COURT_CASES = a27_NO_OF_PENDING_COURT_CASES;
		A27_AMOUNT_OF_PENALTIES_PENDING = a27_AMOUNT_OF_PENALTIES_PENDING;
		A28_PRODUCT = a28_PRODUCT;
		A28_NO_OF_COURT_CASES = a28_NO_OF_COURT_CASES;
		A28_AMOUNT_OF_PENALTIES = a28_AMOUNT_OF_PENALTIES;
		A28_NO_OF_PENDING_COURT_CASES = a28_NO_OF_PENDING_COURT_CASES;
		A28_AMOUNT_OF_PENALTIES_PENDING = a28_AMOUNT_OF_PENALTIES_PENDING;
		A29_PRODUCT = a29_PRODUCT;
		A29_NO_OF_COURT_CASES = a29_NO_OF_COURT_CASES;
		A29_AMOUNT_OF_PENALTIES = a29_AMOUNT_OF_PENALTIES;
		A29_NO_OF_PENDING_COURT_CASES = a29_NO_OF_PENDING_COURT_CASES;
		A29_AMOUNT_OF_PENALTIES_PENDING = a29_AMOUNT_OF_PENALTIES_PENDING;
		A30_PRODUCT = a30_PRODUCT;
		A30_NO_OF_COURT_CASES = a30_NO_OF_COURT_CASES;
		A30_AMOUNT_OF_PENALTIES = a30_AMOUNT_OF_PENALTIES;
		A30_NO_OF_PENDING_COURT_CASES = a30_NO_OF_PENDING_COURT_CASES;
		A30_AMOUNT_OF_PENALTIES_PENDING = a30_AMOUNT_OF_PENALTIES_PENDING;
		A31_PRODUCT = a31_PRODUCT;
		A31_NO_OF_COURT_CASES = a31_NO_OF_COURT_CASES;
		A31_AMOUNT_OF_PENALTIES = a31_AMOUNT_OF_PENALTIES;
		A31_NO_OF_PENDING_COURT_CASES = a31_NO_OF_PENDING_COURT_CASES;
		A31_AMOUNT_OF_PENALTIES_PENDING = a31_AMOUNT_OF_PENALTIES_PENDING;
		A32_PRODUCT = a32_PRODUCT;
		A32_NO_OF_COURT_CASES = a32_NO_OF_COURT_CASES;
		A32_AMOUNT_OF_PENALTIES = a32_AMOUNT_OF_PENALTIES;
		A32_NO_OF_PENDING_COURT_CASES = a32_NO_OF_PENDING_COURT_CASES;
		A32_AMOUNT_OF_PENALTIES_PENDING = a32_AMOUNT_OF_PENALTIES_PENDING;
		A33_PRODUCT = a33_PRODUCT;
		A33_NO_OF_COURT_CASES = a33_NO_OF_COURT_CASES;
		A33_AMOUNT_OF_PENALTIES = a33_AMOUNT_OF_PENALTIES;
		A33_NO_OF_PENDING_COURT_CASES = a33_NO_OF_PENDING_COURT_CASES;
		A33_AMOUNT_OF_PENALTIES_PENDING = a33_AMOUNT_OF_PENALTIES_PENDING;
		A34_PRODUCT = a34_PRODUCT;
		A34_NO_OF_COURT_CASES = a34_NO_OF_COURT_CASES;
		A34_AMOUNT_OF_PENALTIES = a34_AMOUNT_OF_PENALTIES;
		A34_NO_OF_PENDING_COURT_CASES = a34_NO_OF_PENDING_COURT_CASES;
		A34_AMOUNT_OF_PENALTIES_PENDING = a34_AMOUNT_OF_PENALTIES_PENDING;
		A35_PRODUCT = a35_PRODUCT;
		A35_NO_OF_COURT_CASES = a35_NO_OF_COURT_CASES;
		A35_AMOUNT_OF_PENALTIES = a35_AMOUNT_OF_PENALTIES;
		A35_NO_OF_PENDING_COURT_CASES = a35_NO_OF_PENDING_COURT_CASES;
		A35_AMOUNT_OF_PENALTIES_PENDING = a35_AMOUNT_OF_PENALTIES_PENDING;
		A36_PRODUCT = a36_PRODUCT;
		A36_NO_OF_COURT_CASES = a36_NO_OF_COURT_CASES;
		A36_AMOUNT_OF_PENALTIES = a36_AMOUNT_OF_PENALTIES;
		A36_NO_OF_PENDING_COURT_CASES = a36_NO_OF_PENDING_COURT_CASES;
		A36_AMOUNT_OF_PENALTIES_PENDING = a36_AMOUNT_OF_PENALTIES_PENDING;
		REPORT_CODE = rEPORT_CODE;
		REPORT_NAME = rEPORT_NAME;
		REPORT_DATE = rEPORT_DATE;
		REPORT_DUE_DATE = rEPORT_DUE_DATE;
		REP_SUBMIT_DATE = rEP_SUBMIT_DATE;
		REP_PERIOD_FROM = rEP_PERIOD_FROM;
		REP_PERIOD_TO = rEP_PERIOD_TO;
		REP_FREQ = rEP_FREQ;
		NIL_REPORT_FLG = nIL_REPORT_FLG;
		ARCH_FLG = aRCH_FLG;
		ENTITY_FLG = eNTITY_FLG;
		DEL_FLG = dEL_FLG;
		MODIFY_FLG = mODIFY_FLG;
		ENTRY_USER = eNTRY_USER;
		MODIFY_USER = mODIFY_USER;
		VERIFY_USER = vERIFY_USER;
		ENTRY_TIME = eNTRY_TIME;
		MODIFY_TIME = mODIFY_TIME;
		VERIFY_TIME = vERIFY_TIME;
		QTR_FLG = qTR_FLG;
	}
	public T9ORReport() {
		super();
		// TODO Auto-generated constructor stub
	}
	

}
