package com.bornfire.xbrl.entities.BRSS;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.springframework.format.annotation.DateTimeFormat;
@Entity
@Table(name = "T9_RISK_RATING_MIG_SUMARY_TABLE")
public class T9ReportMaster {

	
	private String	T9_1_NAME;
	private BigDecimal	T9_1C_TOTAL_CUST_UPGRADE_CUR_FACETOFACE;
	private BigDecimal	T9_1D_TOTAL_CUST_UPGRADE_CUR_NON_FACETOFACE;
	private String	T9_2_NAME;
	private BigDecimal	T9_2C_HIGH_TO_MED_CUR_FACETOFACE;
	private BigDecimal	T9_2D_HIGH_TO_MED_CUR_NON_FACETOFACE;
	private String	T9_3_NAME;
	private BigDecimal	T9_3C_HIGH_TO_LOW_CUR_FACETOFACE;
	private BigDecimal	T9_3D_HIGH_TO_LOW_CUR_NON_FACETOFACE;
	private String	T9_4_NAME;
	private BigDecimal	T9_4C_MED_TO_LOW_CUR_FACETOFACE;
	private BigDecimal	T9_4D_MED_TO_LOW_CUR_NON_FACETOFACE;
	private String	T9_5_NAME;
	private BigDecimal	T9_5C_TOTAL_CUST_DOWNGRADE_CUR_FACETOFACE;
	private BigDecimal	T9_5D_TOTAL_CUST_DOWNGRADE_CUR_NON_FACETOFACE;
	private String	T9_6_NAME;
	private BigDecimal	T9_6C_LOW_TO_MED_CUR_FACETOFACE;
	private BigDecimal	T9_6D_LOW_TO_MED_CUR_NON_FACETOFACE;
	private String	T9_7_NAME;
	private BigDecimal	T9_7C_LOW_TO_HIGH_CUR_FACETOFACE;
	private BigDecimal	T9_7D_LOW_TO_HIGH_CUR_NON_FACETOFACE;
	private String	T9_8_NAME;
	private BigDecimal	T9_8C_MED_TO_HIGH_CUR_FACETOFACE;
	private BigDecimal	T9_8D_MED_TO_HIGH_CUR_NON_FACETOFACE;
	private String	T9_9_NAME;
	private BigDecimal	T9_9C_TOTAL_CUST_UNCHANGE_CUR_FACETOFACE;
	private BigDecimal	T9_9D_TOTAL_CUST_UNCHANGE_CUR_NON_FACETOFACE;
	private String	T9_10_NAME;
	private BigDecimal	T9_10C_TOTAL_CUR_FACETOFACE;
	private BigDecimal	T9_10D_TOTAL_CUR_NON_FACETOFACE;
	private String	T9_11_NAME;
	private String	T9_11C_VALIDATION;
	private String	T9_11D_VALIDATION;
	private String	T9_12_NAME;
	private BigDecimal	T9_12C_CUSTOMER_TERMINATED_CDD_CUR_FACETOFACE;
	private BigDecimal	T9_12D_CUSTOMER_TERMINATED_CDD_CUR_NON_FACETOFACE;
	private String	T9_13_NAME;
	private BigDecimal	T9_13C_CUSTOMER_CEASED_CUR_FACETOFACE;
	private BigDecimal	T9_13D_CUSTOMER_CEASED_CUR_NON_FACETOFACE;
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	T9_REPORT_SUBMIT_DATE;
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	T9_REPORT_GENERATE_DATE;
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	T9_REPORT_DUE_DATE;
	private String	T9_NIL_REPORT_FLG;
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	T9_REPORT_FROM_DATE;
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	T9_REPORT_TO_DATE;
	private String	T9_FREQUENCY;
	private String	REPORT_NAME;
	private String	REPORT_CODE;
	@Id
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date	REPORT_DATE;
	public String getT9_1_NAME() {
		return T9_1_NAME;
	}
	public void setT9_1_NAME(String t9_1_NAME) {
		T9_1_NAME = t9_1_NAME;
	}
	public BigDecimal getT9_1C_TOTAL_CUST_UPGRADE_CUR_FACETOFACE() {
		return T9_1C_TOTAL_CUST_UPGRADE_CUR_FACETOFACE;
	}
	public void setT9_1C_TOTAL_CUST_UPGRADE_CUR_FACETOFACE(BigDecimal t9_1c_TOTAL_CUST_UPGRADE_CUR_FACETOFACE) {
		T9_1C_TOTAL_CUST_UPGRADE_CUR_FACETOFACE = t9_1c_TOTAL_CUST_UPGRADE_CUR_FACETOFACE;
	}
	public BigDecimal getT9_1D_TOTAL_CUST_UPGRADE_CUR_NON_FACETOFACE() {
		return T9_1D_TOTAL_CUST_UPGRADE_CUR_NON_FACETOFACE;
	}
	public void setT9_1D_TOTAL_CUST_UPGRADE_CUR_NON_FACETOFACE(BigDecimal t9_1d_TOTAL_CUST_UPGRADE_CUR_NON_FACETOFACE) {
		T9_1D_TOTAL_CUST_UPGRADE_CUR_NON_FACETOFACE = t9_1d_TOTAL_CUST_UPGRADE_CUR_NON_FACETOFACE;
	}
	public String getT9_2_NAME() {
		return T9_2_NAME;
	}
	public void setT9_2_NAME(String t9_2_NAME) {
		T9_2_NAME = t9_2_NAME;
	}
	public BigDecimal getT9_2C_HIGH_TO_MED_CUR_FACETOFACE() {
		return T9_2C_HIGH_TO_MED_CUR_FACETOFACE;
	}
	public void setT9_2C_HIGH_TO_MED_CUR_FACETOFACE(BigDecimal t9_2c_HIGH_TO_MED_CUR_FACETOFACE) {
		T9_2C_HIGH_TO_MED_CUR_FACETOFACE = t9_2c_HIGH_TO_MED_CUR_FACETOFACE;
	}
	public BigDecimal getT9_2D_HIGH_TO_MED_CUR_NON_FACETOFACE() {
		return T9_2D_HIGH_TO_MED_CUR_NON_FACETOFACE;
	}
	public void setT9_2D_HIGH_TO_MED_CUR_NON_FACETOFACE(BigDecimal t9_2d_HIGH_TO_MED_CUR_NON_FACETOFACE) {
		T9_2D_HIGH_TO_MED_CUR_NON_FACETOFACE = t9_2d_HIGH_TO_MED_CUR_NON_FACETOFACE;
	}
	public String getT9_3_NAME() {
		return T9_3_NAME;
	}
	public void setT9_3_NAME(String t9_3_NAME) {
		T9_3_NAME = t9_3_NAME;
	}
	public BigDecimal getT9_3C_HIGH_TO_LOW_CUR_FACETOFACE() {
		return T9_3C_HIGH_TO_LOW_CUR_FACETOFACE;
	}
	public void setT9_3C_HIGH_TO_LOW_CUR_FACETOFACE(BigDecimal t9_3c_HIGH_TO_LOW_CUR_FACETOFACE) {
		T9_3C_HIGH_TO_LOW_CUR_FACETOFACE = t9_3c_HIGH_TO_LOW_CUR_FACETOFACE;
	}
	public BigDecimal getT9_3D_HIGH_TO_LOW_CUR_NON_FACETOFACE() {
		return T9_3D_HIGH_TO_LOW_CUR_NON_FACETOFACE;
	}
	public void setT9_3D_HIGH_TO_LOW_CUR_NON_FACETOFACE(BigDecimal t9_3d_HIGH_TO_LOW_CUR_NON_FACETOFACE) {
		T9_3D_HIGH_TO_LOW_CUR_NON_FACETOFACE = t9_3d_HIGH_TO_LOW_CUR_NON_FACETOFACE;
	}
	public String getT9_4_NAME() {
		return T9_4_NAME;
	}
	public void setT9_4_NAME(String t9_4_NAME) {
		T9_4_NAME = t9_4_NAME;
	}
	public BigDecimal getT9_4C_MED_TO_LOW_CUR_FACETOFACE() {
		return T9_4C_MED_TO_LOW_CUR_FACETOFACE;
	}
	public void setT9_4C_MED_TO_LOW_CUR_FACETOFACE(BigDecimal t9_4c_MED_TO_LOW_CUR_FACETOFACE) {
		T9_4C_MED_TO_LOW_CUR_FACETOFACE = t9_4c_MED_TO_LOW_CUR_FACETOFACE;
	}
	public BigDecimal getT9_4D_MED_TO_LOW_CUR_NON_FACETOFACE() {
		return T9_4D_MED_TO_LOW_CUR_NON_FACETOFACE;
	}
	public void setT9_4D_MED_TO_LOW_CUR_NON_FACETOFACE(BigDecimal t9_4d_MED_TO_LOW_CUR_NON_FACETOFACE) {
		T9_4D_MED_TO_LOW_CUR_NON_FACETOFACE = t9_4d_MED_TO_LOW_CUR_NON_FACETOFACE;
	}
	public String getT9_5_NAME() {
		return T9_5_NAME;
	}
	public void setT9_5_NAME(String t9_5_NAME) {
		T9_5_NAME = t9_5_NAME;
	}
	public BigDecimal getT9_5C_TOTAL_CUST_DOWNGRADE_CUR_FACETOFACE() {
		return T9_5C_TOTAL_CUST_DOWNGRADE_CUR_FACETOFACE;
	}
	public void setT9_5C_TOTAL_CUST_DOWNGRADE_CUR_FACETOFACE(BigDecimal t9_5c_TOTAL_CUST_DOWNGRADE_CUR_FACETOFACE) {
		T9_5C_TOTAL_CUST_DOWNGRADE_CUR_FACETOFACE = t9_5c_TOTAL_CUST_DOWNGRADE_CUR_FACETOFACE;
	}
	public BigDecimal getT9_5D_TOTAL_CUST_DOWNGRADE_CUR_NON_FACETOFACE() {
		return T9_5D_TOTAL_CUST_DOWNGRADE_CUR_NON_FACETOFACE;
	}
	public void setT9_5D_TOTAL_CUST_DOWNGRADE_CUR_NON_FACETOFACE(BigDecimal t9_5d_TOTAL_CUST_DOWNGRADE_CUR_NON_FACETOFACE) {
		T9_5D_TOTAL_CUST_DOWNGRADE_CUR_NON_FACETOFACE = t9_5d_TOTAL_CUST_DOWNGRADE_CUR_NON_FACETOFACE;
	}
	public String getT9_6_NAME() {
		return T9_6_NAME;
	}
	public void setT9_6_NAME(String t9_6_NAME) {
		T9_6_NAME = t9_6_NAME;
	}
	public BigDecimal getT9_6C_LOW_TO_MED_CUR_FACETOFACE() {
		return T9_6C_LOW_TO_MED_CUR_FACETOFACE;
	}
	public void setT9_6C_LOW_TO_MED_CUR_FACETOFACE(BigDecimal t9_6c_LOW_TO_MED_CUR_FACETOFACE) {
		T9_6C_LOW_TO_MED_CUR_FACETOFACE = t9_6c_LOW_TO_MED_CUR_FACETOFACE;
	}
	public BigDecimal getT9_6D_LOW_TO_MED_CUR_NON_FACETOFACE() {
		return T9_6D_LOW_TO_MED_CUR_NON_FACETOFACE;
	}
	public void setT9_6D_LOW_TO_MED_CUR_NON_FACETOFACE(BigDecimal t9_6d_LOW_TO_MED_CUR_NON_FACETOFACE) {
		T9_6D_LOW_TO_MED_CUR_NON_FACETOFACE = t9_6d_LOW_TO_MED_CUR_NON_FACETOFACE;
	}
	public String getT9_7_NAME() {
		return T9_7_NAME;
	}
	public void setT9_7_NAME(String t9_7_NAME) {
		T9_7_NAME = t9_7_NAME;
	}
	public BigDecimal getT9_7C_LOW_TO_HIGH_CUR_FACETOFACE() {
		return T9_7C_LOW_TO_HIGH_CUR_FACETOFACE;
	}
	public void setT9_7C_LOW_TO_HIGH_CUR_FACETOFACE(BigDecimal t9_7c_LOW_TO_HIGH_CUR_FACETOFACE) {
		T9_7C_LOW_TO_HIGH_CUR_FACETOFACE = t9_7c_LOW_TO_HIGH_CUR_FACETOFACE;
	}
	public BigDecimal getT9_7D_LOW_TO_HIGH_CUR_NON_FACETOFACE() {
		return T9_7D_LOW_TO_HIGH_CUR_NON_FACETOFACE;
	}
	public void setT9_7D_LOW_TO_HIGH_CUR_NON_FACETOFACE(BigDecimal t9_7d_LOW_TO_HIGH_CUR_NON_FACETOFACE) {
		T9_7D_LOW_TO_HIGH_CUR_NON_FACETOFACE = t9_7d_LOW_TO_HIGH_CUR_NON_FACETOFACE;
	}
	public String getT9_8_NAME() {
		return T9_8_NAME;
	}
	public void setT9_8_NAME(String t9_8_NAME) {
		T9_8_NAME = t9_8_NAME;
	}
	public BigDecimal getT9_8C_MED_TO_HIGH_CUR_FACETOFACE() {
		return T9_8C_MED_TO_HIGH_CUR_FACETOFACE;
	}
	public void setT9_8C_MED_TO_HIGH_CUR_FACETOFACE(BigDecimal t9_8c_MED_TO_HIGH_CUR_FACETOFACE) {
		T9_8C_MED_TO_HIGH_CUR_FACETOFACE = t9_8c_MED_TO_HIGH_CUR_FACETOFACE;
	}
	public BigDecimal getT9_8D_MED_TO_HIGH_CUR_NON_FACETOFACE() {
		return T9_8D_MED_TO_HIGH_CUR_NON_FACETOFACE;
	}
	public void setT9_8D_MED_TO_HIGH_CUR_NON_FACETOFACE(BigDecimal t9_8d_MED_TO_HIGH_CUR_NON_FACETOFACE) {
		T9_8D_MED_TO_HIGH_CUR_NON_FACETOFACE = t9_8d_MED_TO_HIGH_CUR_NON_FACETOFACE;
	}
	public String getT9_9_NAME() {
		return T9_9_NAME;
	}
	public void setT9_9_NAME(String t9_9_NAME) {
		T9_9_NAME = t9_9_NAME;
	}
	public BigDecimal getT9_9C_TOTAL_CUST_UNCHANGE_CUR_FACETOFACE() {
		return T9_9C_TOTAL_CUST_UNCHANGE_CUR_FACETOFACE;
	}
	public void setT9_9C_TOTAL_CUST_UNCHANGE_CUR_FACETOFACE(BigDecimal t9_9c_TOTAL_CUST_UNCHANGE_CUR_FACETOFACE) {
		T9_9C_TOTAL_CUST_UNCHANGE_CUR_FACETOFACE = t9_9c_TOTAL_CUST_UNCHANGE_CUR_FACETOFACE;
	}
	public BigDecimal getT9_9D_TOTAL_CUST_UNCHANGE_CUR_NON_FACETOFACE() {
		return T9_9D_TOTAL_CUST_UNCHANGE_CUR_NON_FACETOFACE;
	}
	public void setT9_9D_TOTAL_CUST_UNCHANGE_CUR_NON_FACETOFACE(BigDecimal t9_9d_TOTAL_CUST_UNCHANGE_CUR_NON_FACETOFACE) {
		T9_9D_TOTAL_CUST_UNCHANGE_CUR_NON_FACETOFACE = t9_9d_TOTAL_CUST_UNCHANGE_CUR_NON_FACETOFACE;
	}
	public String getT9_10_NAME() {
		return T9_10_NAME;
	}
	public void setT9_10_NAME(String t9_10_NAME) {
		T9_10_NAME = t9_10_NAME;
	}
	public BigDecimal getT9_10C_TOTAL_CUR_FACETOFACE() {
		return T9_10C_TOTAL_CUR_FACETOFACE;
	}
	public void setT9_10C_TOTAL_CUR_FACETOFACE(BigDecimal t9_10c_TOTAL_CUR_FACETOFACE) {
		T9_10C_TOTAL_CUR_FACETOFACE = t9_10c_TOTAL_CUR_FACETOFACE;
	}
	public BigDecimal getT9_10D_TOTAL_CUR_NON_FACETOFACE() {
		return T9_10D_TOTAL_CUR_NON_FACETOFACE;
	}
	public void setT9_10D_TOTAL_CUR_NON_FACETOFACE(BigDecimal t9_10d_TOTAL_CUR_NON_FACETOFACE) {
		T9_10D_TOTAL_CUR_NON_FACETOFACE = t9_10d_TOTAL_CUR_NON_FACETOFACE;
	}
	public String getT9_11_NAME() {
		return T9_11_NAME;
	}
	public void setT9_11_NAME(String t9_11_NAME) {
		T9_11_NAME = t9_11_NAME;
	}
	public String getT9_11C_VALIDATION() {
		return T9_11C_VALIDATION;
	}
	public void setT9_11C_VALIDATION(String t9_11c_VALIDATION) {
		T9_11C_VALIDATION = t9_11c_VALIDATION;
	}
	public String getT9_11D_VALIDATION() {
		return T9_11D_VALIDATION;
	}
	public void setT9_11D_VALIDATION(String t9_11d_VALIDATION) {
		T9_11D_VALIDATION = t9_11d_VALIDATION;
	}
	public String getT9_12_NAME() {
		return T9_12_NAME;
	}
	public void setT9_12_NAME(String t9_12_NAME) {
		T9_12_NAME = t9_12_NAME;
	}
	public BigDecimal getT9_12C_CUSTOMER_TERMINATED_CDD_CUR_FACETOFACE() {
		return T9_12C_CUSTOMER_TERMINATED_CDD_CUR_FACETOFACE;
	}
	public void setT9_12C_CUSTOMER_TERMINATED_CDD_CUR_FACETOFACE(BigDecimal t9_12c_CUSTOMER_TERMINATED_CDD_CUR_FACETOFACE) {
		T9_12C_CUSTOMER_TERMINATED_CDD_CUR_FACETOFACE = t9_12c_CUSTOMER_TERMINATED_CDD_CUR_FACETOFACE;
	}
	public BigDecimal getT9_12D_CUSTOMER_TERMINATED_CDD_CUR_NON_FACETOFACE() {
		return T9_12D_CUSTOMER_TERMINATED_CDD_CUR_NON_FACETOFACE;
	}
	public void setT9_12D_CUSTOMER_TERMINATED_CDD_CUR_NON_FACETOFACE(
			BigDecimal t9_12d_CUSTOMER_TERMINATED_CDD_CUR_NON_FACETOFACE) {
		T9_12D_CUSTOMER_TERMINATED_CDD_CUR_NON_FACETOFACE = t9_12d_CUSTOMER_TERMINATED_CDD_CUR_NON_FACETOFACE;
	}
	public String getT9_13_NAME() {
		return T9_13_NAME;
	}
	public void setT9_13_NAME(String t9_13_NAME) {
		T9_13_NAME = t9_13_NAME;
	}
	public BigDecimal getT9_13C_CUSTOMER_CEASED_CUR_FACETOFACE() {
		return T9_13C_CUSTOMER_CEASED_CUR_FACETOFACE;
	}
	public void setT9_13C_CUSTOMER_CEASED_CUR_FACETOFACE(BigDecimal t9_13c_CUSTOMER_CEASED_CUR_FACETOFACE) {
		T9_13C_CUSTOMER_CEASED_CUR_FACETOFACE = t9_13c_CUSTOMER_CEASED_CUR_FACETOFACE;
	}
	public BigDecimal getT9_13D_CUSTOMER_CEASED_CUR_NON_FACETOFACE() {
		return T9_13D_CUSTOMER_CEASED_CUR_NON_FACETOFACE;
	}
	public void setT9_13D_CUSTOMER_CEASED_CUR_NON_FACETOFACE(BigDecimal t9_13d_CUSTOMER_CEASED_CUR_NON_FACETOFACE) {
		T9_13D_CUSTOMER_CEASED_CUR_NON_FACETOFACE = t9_13d_CUSTOMER_CEASED_CUR_NON_FACETOFACE;
	}
	public Date getT9_REPORT_SUBMIT_DATE() {
		return T9_REPORT_SUBMIT_DATE;
	}
	public void setT9_REPORT_SUBMIT_DATE(Date t9_REPORT_SUBMIT_DATE) {
		T9_REPORT_SUBMIT_DATE = t9_REPORT_SUBMIT_DATE;
	}
	public Date getT9_REPORT_GENERATE_DATE() {
		return T9_REPORT_GENERATE_DATE;
	}
	public void setT9_REPORT_GENERATE_DATE(Date t9_REPORT_GENERATE_DATE) {
		T9_REPORT_GENERATE_DATE = t9_REPORT_GENERATE_DATE;
	}
	public Date getT9_REPORT_DUE_DATE() {
		return T9_REPORT_DUE_DATE;
	}
	public void setT9_REPORT_DUE_DATE(Date t9_REPORT_DUE_DATE) {
		T9_REPORT_DUE_DATE = t9_REPORT_DUE_DATE;
	}
	public String getT9_NIL_REPORT_FLG() {
		return T9_NIL_REPORT_FLG;
	}
	public void setT9_NIL_REPORT_FLG(String t9_NIL_REPORT_FLG) {
		T9_NIL_REPORT_FLG = t9_NIL_REPORT_FLG;
	}
	public Date getT9_REPORT_FROM_DATE() {
		return T9_REPORT_FROM_DATE;
	}
	public void setT9_REPORT_FROM_DATE(Date t9_REPORT_FROM_DATE) {
		T9_REPORT_FROM_DATE = t9_REPORT_FROM_DATE;
	}
	public Date getT9_REPORT_TO_DATE() {
		return T9_REPORT_TO_DATE;
	}
	public void setT9_REPORT_TO_DATE(Date t9_REPORT_TO_DATE) {
		T9_REPORT_TO_DATE = t9_REPORT_TO_DATE;
	}
	public String getT9_FREQUENCY() {
		return T9_FREQUENCY;
	}
	public void setT9_FREQUENCY(String t9_FREQUENCY) {
		T9_FREQUENCY = t9_FREQUENCY;
	}
	public String getREPORT_NAME() {
		return REPORT_NAME;
	}
	public void setREPORT_NAME(String rEPORT_NAME) {
		REPORT_NAME = rEPORT_NAME;
	}
	public String getREPORT_CODE() {
		return REPORT_CODE;
	}
	public void setREPORT_CODE(String rEPORT_CODE) {
		REPORT_CODE = rEPORT_CODE;
	}
	public Date getREPORT_DATE() {
		return REPORT_DATE;
	}
	public void setREPORT_DATE(Date rEPORT_DATE) {
		REPORT_DATE = rEPORT_DATE;
	}
	public T9ReportMaster(String t9_1_NAME, BigDecimal t9_1c_TOTAL_CUST_UPGRADE_CUR_FACETOFACE,
			BigDecimal t9_1d_TOTAL_CUST_UPGRADE_CUR_NON_FACETOFACE, String t9_2_NAME,
			BigDecimal t9_2c_HIGH_TO_MED_CUR_FACETOFACE, BigDecimal t9_2d_HIGH_TO_MED_CUR_NON_FACETOFACE,
			String t9_3_NAME, BigDecimal t9_3c_HIGH_TO_LOW_CUR_FACETOFACE,
			BigDecimal t9_3d_HIGH_TO_LOW_CUR_NON_FACETOFACE, String t9_4_NAME,
			BigDecimal t9_4c_MED_TO_LOW_CUR_FACETOFACE, BigDecimal t9_4d_MED_TO_LOW_CUR_NON_FACETOFACE,
			String t9_5_NAME, BigDecimal t9_5c_TOTAL_CUST_DOWNGRADE_CUR_FACETOFACE,
			BigDecimal t9_5d_TOTAL_CUST_DOWNGRADE_CUR_NON_FACETOFACE, String t9_6_NAME,
			BigDecimal t9_6c_LOW_TO_MED_CUR_FACETOFACE, BigDecimal t9_6d_LOW_TO_MED_CUR_NON_FACETOFACE,
			String t9_7_NAME, BigDecimal t9_7c_LOW_TO_HIGH_CUR_FACETOFACE,
			BigDecimal t9_7d_LOW_TO_HIGH_CUR_NON_FACETOFACE, String t9_8_NAME,
			BigDecimal t9_8c_MED_TO_HIGH_CUR_FACETOFACE, BigDecimal t9_8d_MED_TO_HIGH_CUR_NON_FACETOFACE,
			String t9_9_NAME, BigDecimal t9_9c_TOTAL_CUST_UNCHANGE_CUR_FACETOFACE,
			BigDecimal t9_9d_TOTAL_CUST_UNCHANGE_CUR_NON_FACETOFACE, String t9_10_NAME,
			BigDecimal t9_10c_TOTAL_CUR_FACETOFACE, BigDecimal t9_10d_TOTAL_CUR_NON_FACETOFACE, String t9_11_NAME,
			String t9_11c_VALIDATION, String t9_11d_VALIDATION, String t9_12_NAME,
			BigDecimal t9_12c_CUSTOMER_TERMINATED_CDD_CUR_FACETOFACE,
			BigDecimal t9_12d_CUSTOMER_TERMINATED_CDD_CUR_NON_FACETOFACE, String t9_13_NAME,
			BigDecimal t9_13c_CUSTOMER_CEASED_CUR_FACETOFACE, BigDecimal t9_13d_CUSTOMER_CEASED_CUR_NON_FACETOFACE,
			Date t9_REPORT_SUBMIT_DATE, Date t9_REPORT_GENERATE_DATE, Date t9_REPORT_DUE_DATE, String t9_NIL_REPORT_FLG,
			Date t9_REPORT_FROM_DATE, Date t9_REPORT_TO_DATE, String t9_FREQUENCY, String rEPORT_NAME,
			String rEPORT_CODE, Date rEPORT_DATE) {
		super();
		T9_1_NAME = t9_1_NAME;
		T9_1C_TOTAL_CUST_UPGRADE_CUR_FACETOFACE = t9_1c_TOTAL_CUST_UPGRADE_CUR_FACETOFACE;
		T9_1D_TOTAL_CUST_UPGRADE_CUR_NON_FACETOFACE = t9_1d_TOTAL_CUST_UPGRADE_CUR_NON_FACETOFACE;
		T9_2_NAME = t9_2_NAME;
		T9_2C_HIGH_TO_MED_CUR_FACETOFACE = t9_2c_HIGH_TO_MED_CUR_FACETOFACE;
		T9_2D_HIGH_TO_MED_CUR_NON_FACETOFACE = t9_2d_HIGH_TO_MED_CUR_NON_FACETOFACE;
		T9_3_NAME = t9_3_NAME;
		T9_3C_HIGH_TO_LOW_CUR_FACETOFACE = t9_3c_HIGH_TO_LOW_CUR_FACETOFACE;
		T9_3D_HIGH_TO_LOW_CUR_NON_FACETOFACE = t9_3d_HIGH_TO_LOW_CUR_NON_FACETOFACE;
		T9_4_NAME = t9_4_NAME;
		T9_4C_MED_TO_LOW_CUR_FACETOFACE = t9_4c_MED_TO_LOW_CUR_FACETOFACE;
		T9_4D_MED_TO_LOW_CUR_NON_FACETOFACE = t9_4d_MED_TO_LOW_CUR_NON_FACETOFACE;
		T9_5_NAME = t9_5_NAME;
		T9_5C_TOTAL_CUST_DOWNGRADE_CUR_FACETOFACE = t9_5c_TOTAL_CUST_DOWNGRADE_CUR_FACETOFACE;
		T9_5D_TOTAL_CUST_DOWNGRADE_CUR_NON_FACETOFACE = t9_5d_TOTAL_CUST_DOWNGRADE_CUR_NON_FACETOFACE;
		T9_6_NAME = t9_6_NAME;
		T9_6C_LOW_TO_MED_CUR_FACETOFACE = t9_6c_LOW_TO_MED_CUR_FACETOFACE;
		T9_6D_LOW_TO_MED_CUR_NON_FACETOFACE = t9_6d_LOW_TO_MED_CUR_NON_FACETOFACE;
		T9_7_NAME = t9_7_NAME;
		T9_7C_LOW_TO_HIGH_CUR_FACETOFACE = t9_7c_LOW_TO_HIGH_CUR_FACETOFACE;
		T9_7D_LOW_TO_HIGH_CUR_NON_FACETOFACE = t9_7d_LOW_TO_HIGH_CUR_NON_FACETOFACE;
		T9_8_NAME = t9_8_NAME;
		T9_8C_MED_TO_HIGH_CUR_FACETOFACE = t9_8c_MED_TO_HIGH_CUR_FACETOFACE;
		T9_8D_MED_TO_HIGH_CUR_NON_FACETOFACE = t9_8d_MED_TO_HIGH_CUR_NON_FACETOFACE;
		T9_9_NAME = t9_9_NAME;
		T9_9C_TOTAL_CUST_UNCHANGE_CUR_FACETOFACE = t9_9c_TOTAL_CUST_UNCHANGE_CUR_FACETOFACE;
		T9_9D_TOTAL_CUST_UNCHANGE_CUR_NON_FACETOFACE = t9_9d_TOTAL_CUST_UNCHANGE_CUR_NON_FACETOFACE;
		T9_10_NAME = t9_10_NAME;
		T9_10C_TOTAL_CUR_FACETOFACE = t9_10c_TOTAL_CUR_FACETOFACE;
		T9_10D_TOTAL_CUR_NON_FACETOFACE = t9_10d_TOTAL_CUR_NON_FACETOFACE;
		T9_11_NAME = t9_11_NAME;
		T9_11C_VALIDATION = t9_11c_VALIDATION;
		T9_11D_VALIDATION = t9_11d_VALIDATION;
		T9_12_NAME = t9_12_NAME;
		T9_12C_CUSTOMER_TERMINATED_CDD_CUR_FACETOFACE = t9_12c_CUSTOMER_TERMINATED_CDD_CUR_FACETOFACE;
		T9_12D_CUSTOMER_TERMINATED_CDD_CUR_NON_FACETOFACE = t9_12d_CUSTOMER_TERMINATED_CDD_CUR_NON_FACETOFACE;
		T9_13_NAME = t9_13_NAME;
		T9_13C_CUSTOMER_CEASED_CUR_FACETOFACE = t9_13c_CUSTOMER_CEASED_CUR_FACETOFACE;
		T9_13D_CUSTOMER_CEASED_CUR_NON_FACETOFACE = t9_13d_CUSTOMER_CEASED_CUR_NON_FACETOFACE;
		T9_REPORT_SUBMIT_DATE = t9_REPORT_SUBMIT_DATE;
		T9_REPORT_GENERATE_DATE = t9_REPORT_GENERATE_DATE;
		T9_REPORT_DUE_DATE = t9_REPORT_DUE_DATE;
		T9_NIL_REPORT_FLG = t9_NIL_REPORT_FLG;
		T9_REPORT_FROM_DATE = t9_REPORT_FROM_DATE;
		T9_REPORT_TO_DATE = t9_REPORT_TO_DATE;
		T9_FREQUENCY = t9_FREQUENCY;
		REPORT_NAME = rEPORT_NAME;
		REPORT_CODE = rEPORT_CODE;
		REPORT_DATE = rEPORT_DATE;
	}
	public T9ReportMaster() {
		super();
		// TODO Auto-generated constructor stub
	}

	
	
}
