CREATE TABLE Persons (
id INT,
FirstName VARCHAR(100),
LastName VARCHAR(100),
Address VARCHAR(100),
City VARCHAR(100)
);

CREATE SEQUENCE PERSONS_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

COMMIT;

INSERT INTO Persons (id,FIRSTNAME,LASTNAME,ADDRESS,CITY) VALUES(1,'MUKESH','PRADHAN','JUNNASANDRA','BANGALORE');
INSERT INTO Persons (id,FIRSTNAME,LASTNAME,ADDRESS,CITY) VALUES(2,'BIJAYANI','PRADHAN','JUNNASANDRA','BANGALORE');
INSERT INTO Persons (id,FIRSTNAME,LASTNAME,ADDRESS,CITY) VALUES(3,'KHITISH','PRADHAN','BHUBANESWAR','ODISHA');
INSERT INTO Persons (id,FIRSTNAME,LASTNAME,ADDRESS,CITY) VALUES(4,'DHRUBACHARAN','PRADHAN','TALCHER','ODISHA');
INSERT INTO Persons (id,FIRSTNAME,LASTNAME,ADDRESS,CITY) VALUES(5,'SOUBHAGYA','PRADHAN','ANGUL','ODISHA');

COMMIT;


select * from Persons;



