package com.bornfire.brf.entities;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.springframework.format.annotation.DateTimeFormat;

@Entity
@Table(name = "BRRS_M_IS_SUMMARYTABLE2")

public class M_IS_Summary_Entity2 {
	public String R21_PRODUCT;
   public BigDecimal R21_HELD_FOR_TRADING;
   public BigDecimal R21_AMORTISED_COST;
   public BigDecimal R21_AVAILABLE_FOR_SALE;
   public BigDecimal R21_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS;
   public BigDecimal R21_QUALIFYING_FOR_HEDGE_ACCOUNTING;
   public BigDecimal R21_TOTAL;
   public String R22_PRODUCT;
   public BigDecimal R22_HELD_FOR_TRADING;
   public BigDecimal R22_AMORTISED_COST;
   public BigDecimal R22_AVAILABLE_FOR_SALE;
   public BigDecimal R22_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS;
   public BigDecimal R22_QUALIFYING_FOR_HEDGE_ACCOUNTING;
   public BigDecimal R22_TOTAL;
   public String R23_PRODUCT;
   public BigDecimal R23_HELD_FOR_TRADING;
   public BigDecimal R23_AMORTISED_COST;
   public BigDecimal R23_AVAILABLE_FOR_SALE;
   public BigDecimal R23_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS;
   public BigDecimal R23_QUALIFYING_FOR_HEDGE_ACCOUNTING;
   public BigDecimal R23_TOTAL;
   public String R24_PRODUCT;
   public BigDecimal R24_HELD_FOR_TRADING;
   public BigDecimal R24_AMORTISED_COST;
   public BigDecimal R24_AVAILABLE_FOR_SALE;
   public BigDecimal R24_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS;
   public BigDecimal R24_QUALIFYING_FOR_HEDGE_ACCOUNTING;
   public BigDecimal R24_TOTAL;
   public String R25_PRODUCT;
   public BigDecimal R25_HELD_FOR_TRADING;
   public BigDecimal R25_AMORTISED_COST;
   public BigDecimal R25_AVAILABLE_FOR_SALE;
   public BigDecimal R25_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS;
   public BigDecimal R25_QUALIFYING_FOR_HEDGE_ACCOUNTING;
   public BigDecimal R25_TOTAL;
   public String R26_PRODUCT;
   public BigDecimal R26_HELD_FOR_TRADING;
   public BigDecimal R26_AMORTISED_COST;
   public BigDecimal R26_AVAILABLE_FOR_SALE;
   public BigDecimal R26_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS;
   public BigDecimal R26_QUALIFYING_FOR_HEDGE_ACCOUNTING;
   public BigDecimal R26_TOTAL;
   public String R27_PRODUCT;
   public BigDecimal R27_HELD_FOR_TRADING;
   public BigDecimal R27_AMORTISED_COST;
   public BigDecimal R27_AVAILABLE_FOR_SALE;
   public BigDecimal R27_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS;
   public BigDecimal R27_QUALIFYING_FOR_HEDGE_ACCOUNTING;
   public BigDecimal R27_TOTAL;
   public String R28_PRODUCT;
   public BigDecimal R28_HELD_FOR_TRADING;
   public BigDecimal R28_AMORTISED_COST;
   public BigDecimal R28_AVAILABLE_FOR_SALE;
   public BigDecimal R28_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS;
   public BigDecimal R28_QUALIFYING_FOR_HEDGE_ACCOUNTING;
   public BigDecimal R28_TOTAL;
   public String R29_PRODUCT;
   public BigDecimal R29_HELD_FOR_TRADING;
   public BigDecimal R29_AMORTISED_COST;
   public BigDecimal R29_AVAILABLE_FOR_SALE;
   public BigDecimal R29_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS;
   public BigDecimal R29_QUALIFYING_FOR_HEDGE_ACCOUNTING;
   public BigDecimal R29_TOTAL;
   public String R30_PRODUCT;
   public BigDecimal R30_HELD_FOR_TRADING;
   public BigDecimal R30_AMORTISED_COST;
   public BigDecimal R30_AVAILABLE_FOR_SALE;
   public BigDecimal R30_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS;
   public BigDecimal R30_QUALIFYING_FOR_HEDGE_ACCOUNTING;
   public BigDecimal R30_TOTAL;
   public String R31_PRODUCT;
   public BigDecimal R31_HELD_FOR_TRADING;
   public BigDecimal R31_AMORTISED_COST;
   public BigDecimal R31_AVAILABLE_FOR_SALE;
   public BigDecimal R31_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS;
   public BigDecimal R31_QUALIFYING_FOR_HEDGE_ACCOUNTING;
   public BigDecimal R31_TOTAL;
   public String R32_PRODUCT;
   public BigDecimal R32_HELD_FOR_TRADING;
   public BigDecimal R32_AMORTISED_COST;
   public BigDecimal R32_AVAILABLE_FOR_SALE;
   public BigDecimal R32_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS;
   public BigDecimal R32_QUALIFYING_FOR_HEDGE_ACCOUNTING;
   public BigDecimal R32_TOTAL;
   public String R33_PRODUCT;
   public BigDecimal R33_HELD_FOR_TRADING;
   public BigDecimal R33_AMORTISED_COST;
   public BigDecimal R33_AVAILABLE_FOR_SALE;
   public BigDecimal R33_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS;
   public BigDecimal R33_QUALIFYING_FOR_HEDGE_ACCOUNTING;
   public BigDecimal R33_TOTAL;
   public String R34_PRODUCT;
   public BigDecimal R34_HELD_FOR_TRADING;
   public BigDecimal R34_AMORTISED_COST;
   public BigDecimal R34_AVAILABLE_FOR_SALE;
   public BigDecimal R34_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS;
   public BigDecimal R34_QUALIFYING_FOR_HEDGE_ACCOUNTING;
   public BigDecimal R34_TOTAL;
   public String R35_PRODUCT;
   public BigDecimal R35_HELD_FOR_TRADING;
   public BigDecimal R35_AMORTISED_COST;
   public BigDecimal R35_AVAILABLE_FOR_SALE;
   public BigDecimal R35_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS;
   public BigDecimal R35_QUALIFYING_FOR_HEDGE_ACCOUNTING;
   public BigDecimal R35_TOTAL;
		

	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	@Id
	@Column(name = "REPORT_DATE")
	private Date reportDate;
	@Column(name = "REPORT_VERSION")
	private String reportVersion;
   public String REPORT_FREQUENCY;
   public String REPORT_CODE;
   public String REPORT_DESC;
   public String ENTITY_FLG;
   public String MODIFY_FLG;
   public String DEL_FLG;
	public String getR21_PRODUCT() {
		return R21_PRODUCT;
	}
	public void setR21_PRODUCT(String r21_PRODUCT) {
		R21_PRODUCT = r21_PRODUCT;
	}
	public BigDecimal getR21_HELD_FOR_TRADING() {
		return R21_HELD_FOR_TRADING;
	}
	public void setR21_HELD_FOR_TRADING(BigDecimal r21_HELD_FOR_TRADING) {
		R21_HELD_FOR_TRADING = r21_HELD_FOR_TRADING;
	}
	public BigDecimal getR21_AMORTISED_COST() {
		return R21_AMORTISED_COST;
	}
	public void setR21_AMORTISED_COST(BigDecimal r21_AMORTISED_COST) {
		R21_AMORTISED_COST = r21_AMORTISED_COST;
	}
	public BigDecimal getR21_AVAILABLE_FOR_SALE() {
		return R21_AVAILABLE_FOR_SALE;
	}
	public void setR21_AVAILABLE_FOR_SALE(BigDecimal r21_AVAILABLE_FOR_SALE) {
		R21_AVAILABLE_FOR_SALE = r21_AVAILABLE_FOR_SALE;
	}
	public BigDecimal getR21_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS() {
		return R21_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS;
	}
	public void setR21_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS(BigDecimal r21_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS) {
		R21_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS = r21_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS;
	}
	public BigDecimal getR21_QUALIFYING_FOR_HEDGE_ACCOUNTING() {
		return R21_QUALIFYING_FOR_HEDGE_ACCOUNTING;
	}
	public void setR21_QUALIFYING_FOR_HEDGE_ACCOUNTING(BigDecimal r21_QUALIFYING_FOR_HEDGE_ACCOUNTING) {
		R21_QUALIFYING_FOR_HEDGE_ACCOUNTING = r21_QUALIFYING_FOR_HEDGE_ACCOUNTING;
	}
	public BigDecimal getR21_TOTAL() {
		return R21_TOTAL;
	}
	public void setR21_TOTAL(BigDecimal r21_TOTAL) {
		R21_TOTAL = r21_TOTAL;
	}
	public String getR22_PRODUCT() {
		return R22_PRODUCT;
	}
	public void setR22_PRODUCT(String r22_PRODUCT) {
		R22_PRODUCT = r22_PRODUCT;
	}
	public BigDecimal getR22_HELD_FOR_TRADING() {
		return R22_HELD_FOR_TRADING;
	}
	public void setR22_HELD_FOR_TRADING(BigDecimal r22_HELD_FOR_TRADING) {
		R22_HELD_FOR_TRADING = r22_HELD_FOR_TRADING;
	}
	public BigDecimal getR22_AMORTISED_COST() {
		return R22_AMORTISED_COST;
	}
	public void setR22_AMORTISED_COST(BigDecimal r22_AMORTISED_COST) {
		R22_AMORTISED_COST = r22_AMORTISED_COST;
	}
	public BigDecimal getR22_AVAILABLE_FOR_SALE() {
		return R22_AVAILABLE_FOR_SALE;
	}
	public void setR22_AVAILABLE_FOR_SALE(BigDecimal r22_AVAILABLE_FOR_SALE) {
		R22_AVAILABLE_FOR_SALE = r22_AVAILABLE_FOR_SALE;
	}
	public BigDecimal getR22_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS() {
		return R22_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS;
	}
	public void setR22_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS(BigDecimal r22_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS) {
		R22_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS = r22_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS;
	}
	public BigDecimal getR22_QUALIFYING_FOR_HEDGE_ACCOUNTING() {
		return R22_QUALIFYING_FOR_HEDGE_ACCOUNTING;
	}
	public void setR22_QUALIFYING_FOR_HEDGE_ACCOUNTING(BigDecimal r22_QUALIFYING_FOR_HEDGE_ACCOUNTING) {
		R22_QUALIFYING_FOR_HEDGE_ACCOUNTING = r22_QUALIFYING_FOR_HEDGE_ACCOUNTING;
	}
	public BigDecimal getR22_TOTAL() {
		return R22_TOTAL;
	}
	public void setR22_TOTAL(BigDecimal r22_TOTAL) {
		R22_TOTAL = r22_TOTAL;
	}
	public String getR23_PRODUCT() {
		return R23_PRODUCT;
	}
	public void setR23_PRODUCT(String r23_PRODUCT) {
		R23_PRODUCT = r23_PRODUCT;
	}
	public BigDecimal getR23_HELD_FOR_TRADING() {
		return R23_HELD_FOR_TRADING;
	}
	public void setR23_HELD_FOR_TRADING(BigDecimal r23_HELD_FOR_TRADING) {
		R23_HELD_FOR_TRADING = r23_HELD_FOR_TRADING;
	}
	public BigDecimal getR23_AMORTISED_COST() {
		return R23_AMORTISED_COST;
	}
	public void setR23_AMORTISED_COST(BigDecimal r23_AMORTISED_COST) {
		R23_AMORTISED_COST = r23_AMORTISED_COST;
	}
	public BigDecimal getR23_AVAILABLE_FOR_SALE() {
		return R23_AVAILABLE_FOR_SALE;
	}
	public void setR23_AVAILABLE_FOR_SALE(BigDecimal r23_AVAILABLE_FOR_SALE) {
		R23_AVAILABLE_FOR_SALE = r23_AVAILABLE_FOR_SALE;
	}
	public BigDecimal getR23_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS() {
		return R23_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS;
	}
	public void setR23_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS(BigDecimal r23_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS) {
		R23_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS = r23_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS;
	}
	public BigDecimal getR23_QUALIFYING_FOR_HEDGE_ACCOUNTING() {
		return R23_QUALIFYING_FOR_HEDGE_ACCOUNTING;
	}
	public void setR23_QUALIFYING_FOR_HEDGE_ACCOUNTING(BigDecimal r23_QUALIFYING_FOR_HEDGE_ACCOUNTING) {
		R23_QUALIFYING_FOR_HEDGE_ACCOUNTING = r23_QUALIFYING_FOR_HEDGE_ACCOUNTING;
	}
	public BigDecimal getR23_TOTAL() {
		return R23_TOTAL;
	}
	public void setR23_TOTAL(BigDecimal r23_TOTAL) {
		R23_TOTAL = r23_TOTAL;
	}
	public String getR24_PRODUCT() {
		return R24_PRODUCT;
	}
	public void setR24_PRODUCT(String r24_PRODUCT) {
		R24_PRODUCT = r24_PRODUCT;
	}
	public BigDecimal getR24_HELD_FOR_TRADING() {
		return R24_HELD_FOR_TRADING;
	}
	public void setR24_HELD_FOR_TRADING(BigDecimal r24_HELD_FOR_TRADING) {
		R24_HELD_FOR_TRADING = r24_HELD_FOR_TRADING;
	}
	public BigDecimal getR24_AMORTISED_COST() {
		return R24_AMORTISED_COST;
	}
	public void setR24_AMORTISED_COST(BigDecimal r24_AMORTISED_COST) {
		R24_AMORTISED_COST = r24_AMORTISED_COST;
	}
	public BigDecimal getR24_AVAILABLE_FOR_SALE() {
		return R24_AVAILABLE_FOR_SALE;
	}
	public void setR24_AVAILABLE_FOR_SALE(BigDecimal r24_AVAILABLE_FOR_SALE) {
		R24_AVAILABLE_FOR_SALE = r24_AVAILABLE_FOR_SALE;
	}
	public BigDecimal getR24_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS() {
		return R24_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS;
	}
	public void setR24_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS(BigDecimal r24_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS) {
		R24_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS = r24_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS;
	}
	public BigDecimal getR24_QUALIFYING_FOR_HEDGE_ACCOUNTING() {
		return R24_QUALIFYING_FOR_HEDGE_ACCOUNTING;
	}
	public void setR24_QUALIFYING_FOR_HEDGE_ACCOUNTING(BigDecimal r24_QUALIFYING_FOR_HEDGE_ACCOUNTING) {
		R24_QUALIFYING_FOR_HEDGE_ACCOUNTING = r24_QUALIFYING_FOR_HEDGE_ACCOUNTING;
	}
	public BigDecimal getR24_TOTAL() {
		return R24_TOTAL;
	}
	public void setR24_TOTAL(BigDecimal r24_TOTAL) {
		R24_TOTAL = r24_TOTAL;
	}
	public String getR25_PRODUCT() {
		return R25_PRODUCT;
	}
	public void setR25_PRODUCT(String r25_PRODUCT) {
		R25_PRODUCT = r25_PRODUCT;
	}
	public BigDecimal getR25_HELD_FOR_TRADING() {
		return R25_HELD_FOR_TRADING;
	}
	public void setR25_HELD_FOR_TRADING(BigDecimal r25_HELD_FOR_TRADING) {
		R25_HELD_FOR_TRADING = r25_HELD_FOR_TRADING;
	}
	public BigDecimal getR25_AMORTISED_COST() {
		return R25_AMORTISED_COST;
	}
	public void setR25_AMORTISED_COST(BigDecimal r25_AMORTISED_COST) {
		R25_AMORTISED_COST = r25_AMORTISED_COST;
	}
	public BigDecimal getR25_AVAILABLE_FOR_SALE() {
		return R25_AVAILABLE_FOR_SALE;
	}
	public void setR25_AVAILABLE_FOR_SALE(BigDecimal r25_AVAILABLE_FOR_SALE) {
		R25_AVAILABLE_FOR_SALE = r25_AVAILABLE_FOR_SALE;
	}
	public BigDecimal getR25_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS() {
		return R25_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS;
	}
	public void setR25_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS(BigDecimal r25_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS) {
		R25_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS = r25_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS;
	}
	public BigDecimal getR25_QUALIFYING_FOR_HEDGE_ACCOUNTING() {
		return R25_QUALIFYING_FOR_HEDGE_ACCOUNTING;
	}
	public void setR25_QUALIFYING_FOR_HEDGE_ACCOUNTING(BigDecimal r25_QUALIFYING_FOR_HEDGE_ACCOUNTING) {
		R25_QUALIFYING_FOR_HEDGE_ACCOUNTING = r25_QUALIFYING_FOR_HEDGE_ACCOUNTING;
	}
	public BigDecimal getR25_TOTAL() {
		return R25_TOTAL;
	}
	public void setR25_TOTAL(BigDecimal r25_TOTAL) {
		R25_TOTAL = r25_TOTAL;
	}
	public String getR26_PRODUCT() {
		return R26_PRODUCT;
	}
	public void setR26_PRODUCT(String r26_PRODUCT) {
		R26_PRODUCT = r26_PRODUCT;
	}
	public BigDecimal getR26_HELD_FOR_TRADING() {
		return R26_HELD_FOR_TRADING;
	}
	public void setR26_HELD_FOR_TRADING(BigDecimal r26_HELD_FOR_TRADING) {
		R26_HELD_FOR_TRADING = r26_HELD_FOR_TRADING;
	}
	public BigDecimal getR26_AMORTISED_COST() {
		return R26_AMORTISED_COST;
	}
	public void setR26_AMORTISED_COST(BigDecimal r26_AMORTISED_COST) {
		R26_AMORTISED_COST = r26_AMORTISED_COST;
	}
	public BigDecimal getR26_AVAILABLE_FOR_SALE() {
		return R26_AVAILABLE_FOR_SALE;
	}
	public void setR26_AVAILABLE_FOR_SALE(BigDecimal r26_AVAILABLE_FOR_SALE) {
		R26_AVAILABLE_FOR_SALE = r26_AVAILABLE_FOR_SALE;
	}
	public BigDecimal getR26_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS() {
		return R26_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS;
	}
	public void setR26_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS(BigDecimal r26_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS) {
		R26_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS = r26_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS;
	}
	public BigDecimal getR26_QUALIFYING_FOR_HEDGE_ACCOUNTING() {
		return R26_QUALIFYING_FOR_HEDGE_ACCOUNTING;
	}
	public void setR26_QUALIFYING_FOR_HEDGE_ACCOUNTING(BigDecimal r26_QUALIFYING_FOR_HEDGE_ACCOUNTING) {
		R26_QUALIFYING_FOR_HEDGE_ACCOUNTING = r26_QUALIFYING_FOR_HEDGE_ACCOUNTING;
	}
	public BigDecimal getR26_TOTAL() {
		return R26_TOTAL;
	}
	public void setR26_TOTAL(BigDecimal r26_TOTAL) {
		R26_TOTAL = r26_TOTAL;
	}
	public String getR27_PRODUCT() {
		return R27_PRODUCT;
	}
	public void setR27_PRODUCT(String r27_PRODUCT) {
		R27_PRODUCT = r27_PRODUCT;
	}
	public BigDecimal getR27_HELD_FOR_TRADING() {
		return R27_HELD_FOR_TRADING;
	}
	public void setR27_HELD_FOR_TRADING(BigDecimal r27_HELD_FOR_TRADING) {
		R27_HELD_FOR_TRADING = r27_HELD_FOR_TRADING;
	}
	public BigDecimal getR27_AMORTISED_COST() {
		return R27_AMORTISED_COST;
	}
	public void setR27_AMORTISED_COST(BigDecimal r27_AMORTISED_COST) {
		R27_AMORTISED_COST = r27_AMORTISED_COST;
	}
	public BigDecimal getR27_AVAILABLE_FOR_SALE() {
		return R27_AVAILABLE_FOR_SALE;
	}
	public void setR27_AVAILABLE_FOR_SALE(BigDecimal r27_AVAILABLE_FOR_SALE) {
		R27_AVAILABLE_FOR_SALE = r27_AVAILABLE_FOR_SALE;
	}
	public BigDecimal getR27_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS() {
		return R27_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS;
	}
	public void setR27_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS(BigDecimal r27_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS) {
		R27_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS = r27_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS;
	}
	public BigDecimal getR27_QUALIFYING_FOR_HEDGE_ACCOUNTING() {
		return R27_QUALIFYING_FOR_HEDGE_ACCOUNTING;
	}
	public void setR27_QUALIFYING_FOR_HEDGE_ACCOUNTING(BigDecimal r27_QUALIFYING_FOR_HEDGE_ACCOUNTING) {
		R27_QUALIFYING_FOR_HEDGE_ACCOUNTING = r27_QUALIFYING_FOR_HEDGE_ACCOUNTING;
	}
	public BigDecimal getR27_TOTAL() {
		return R27_TOTAL;
	}
	public void setR27_TOTAL(BigDecimal r27_TOTAL) {
		R27_TOTAL = r27_TOTAL;
	}
	public String getR28_PRODUCT() {
		return R28_PRODUCT;
	}
	public void setR28_PRODUCT(String r28_PRODUCT) {
		R28_PRODUCT = r28_PRODUCT;
	}
	// public BigDecimal getR28_HELD_FOR_TRADING() {
	// 	return R28_HELD_FOR_TRADING;
	// }
	// public void setR28_HELD_FOR_TRADING(BigDecimal r28_HELD_FOR_TRADING) {
	// 	R28_HELD_FOR_TRADING = r28_HELD_FOR_TRADING;
	// }
	public BigDecimal getR28_AMORTISED_COST() {
		return R28_AMORTISED_COST;
	}
	public void setR28_AMORTISED_COST(BigDecimal r28_AMORTISED_COST) {
		R28_AMORTISED_COST = r28_AMORTISED_COST;
	}
	public BigDecimal getR28_AVAILABLE_FOR_SALE() {
		return R28_AVAILABLE_FOR_SALE;
	}
	public void setR28_AVAILABLE_FOR_SALE(BigDecimal r28_AVAILABLE_FOR_SALE) {
		R28_AVAILABLE_FOR_SALE = r28_AVAILABLE_FOR_SALE;
	}
	public BigDecimal getR28_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS() {
		return R28_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS;
	}
	public void setR28_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS(BigDecimal r28_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS) {
		R28_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS = r28_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS;
	}
	public BigDecimal getR28_QUALIFYING_FOR_HEDGE_ACCOUNTING() {
		return R28_QUALIFYING_FOR_HEDGE_ACCOUNTING;
	}
	public void setR28_QUALIFYING_FOR_HEDGE_ACCOUNTING(BigDecimal r28_QUALIFYING_FOR_HEDGE_ACCOUNTING) {
		R28_QUALIFYING_FOR_HEDGE_ACCOUNTING = r28_QUALIFYING_FOR_HEDGE_ACCOUNTING;
	}
	public BigDecimal getR28_TOTAL() {
		return R28_TOTAL;
	}
	public void setR28_TOTAL(BigDecimal r28_TOTAL) {
		R28_TOTAL = r28_TOTAL;
	}
	public String getR29_PRODUCT() {
		return R29_PRODUCT;
	}
	public void setR29_PRODUCT(String r29_PRODUCT) {
		R29_PRODUCT = r29_PRODUCT;
	}
	public BigDecimal getR29_HELD_FOR_TRADING() {
		return R29_HELD_FOR_TRADING;
	}
	public void setR29_HELD_FOR_TRADING(BigDecimal r29_HELD_FOR_TRADING) {
		R29_HELD_FOR_TRADING = r29_HELD_FOR_TRADING;
	}
	public BigDecimal getR29_AMORTISED_COST() {
		return R29_AMORTISED_COST;
	}
	public void setR29_AMORTISED_COST(BigDecimal r29_AMORTISED_COST) {
		R29_AMORTISED_COST = r29_AMORTISED_COST;
	}
	public BigDecimal getR29_AVAILABLE_FOR_SALE() {
		return R29_AVAILABLE_FOR_SALE;
	}
	public void setR29_AVAILABLE_FOR_SALE(BigDecimal r29_AVAILABLE_FOR_SALE) {
		R29_AVAILABLE_FOR_SALE = r29_AVAILABLE_FOR_SALE;
	}
	public BigDecimal getR29_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS() {
		return R29_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS;
	}
	public void setR29_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS(BigDecimal r29_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS) {
		R29_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS = r29_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS;
	}
	public BigDecimal getR29_QUALIFYING_FOR_HEDGE_ACCOUNTING() {
		return R29_QUALIFYING_FOR_HEDGE_ACCOUNTING;
	}
	public void setR29_QUALIFYING_FOR_HEDGE_ACCOUNTING(BigDecimal r29_QUALIFYING_FOR_HEDGE_ACCOUNTING) {
		R29_QUALIFYING_FOR_HEDGE_ACCOUNTING = r29_QUALIFYING_FOR_HEDGE_ACCOUNTING;
	}
	public BigDecimal getR29_TOTAL() {
		return R29_TOTAL;
	}
	public void setR29_TOTAL(BigDecimal r29_TOTAL) {
		R29_TOTAL = r29_TOTAL;
	}
	public String getR30_PRODUCT() {
		return R30_PRODUCT;
	}
	public void setR30_PRODUCT(String r30_PRODUCT) {
		R30_PRODUCT = r30_PRODUCT;
	}
	public BigDecimal getR30_HELD_FOR_TRADING() {
		return R30_HELD_FOR_TRADING;
	}
	public void setR30_HELD_FOR_TRADING(BigDecimal r30_HELD_FOR_TRADING) {
		R30_HELD_FOR_TRADING = r30_HELD_FOR_TRADING;
	}
	public BigDecimal getR30_AMORTISED_COST() {
		return R30_AMORTISED_COST;
	}
	public void setR30_AMORTISED_COST(BigDecimal r30_AMORTISED_COST) {
		R30_AMORTISED_COST = r30_AMORTISED_COST;
	}
	public BigDecimal getR30_AVAILABLE_FOR_SALE() {
		return R30_AVAILABLE_FOR_SALE;
	}
	public void setR30_AVAILABLE_FOR_SALE(BigDecimal r30_AVAILABLE_FOR_SALE) {
		R30_AVAILABLE_FOR_SALE = r30_AVAILABLE_FOR_SALE;
	}
	public BigDecimal getR30_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS() {
		return R30_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS;
	}
	public void setR30_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS(BigDecimal r30_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS) {
		R30_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS = r30_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS;
	}
	public BigDecimal getR30_QUALIFYING_FOR_HEDGE_ACCOUNTING() {
		return R30_QUALIFYING_FOR_HEDGE_ACCOUNTING;
	}
	public void setR30_QUALIFYING_FOR_HEDGE_ACCOUNTING(BigDecimal r30_QUALIFYING_FOR_HEDGE_ACCOUNTING) {
		R30_QUALIFYING_FOR_HEDGE_ACCOUNTING = r30_QUALIFYING_FOR_HEDGE_ACCOUNTING;
	}
	public BigDecimal getR30_TOTAL() {
		return R30_TOTAL;
	}
	public void setR30_TOTAL(BigDecimal r30_TOTAL) {
		R30_TOTAL = r30_TOTAL;
	}
	public String getR31_PRODUCT() {
		return R31_PRODUCT;
	}
	public void setR31_PRODUCT(String r31_PRODUCT) {
		R31_PRODUCT = r31_PRODUCT;
	}
	public BigDecimal getR31_HELD_FOR_TRADING() {
		return R31_HELD_FOR_TRADING;
	}
	public void setR31_HELD_FOR_TRADING(BigDecimal r31_HELD_FOR_TRADING) {
		R31_HELD_FOR_TRADING = r31_HELD_FOR_TRADING;
	}
	public BigDecimal getR31_AMORTISED_COST() {
		return R31_AMORTISED_COST;
	}
	public void setR31_AMORTISED_COST(BigDecimal r31_AMORTISED_COST) {
		R31_AMORTISED_COST = r31_AMORTISED_COST;
	}
	public BigDecimal getR31_AVAILABLE_FOR_SALE() {
		return R31_AVAILABLE_FOR_SALE;
	}
	public void setR31_AVAILABLE_FOR_SALE(BigDecimal r31_AVAILABLE_FOR_SALE) {
		R31_AVAILABLE_FOR_SALE = r31_AVAILABLE_FOR_SALE;
	}
	public BigDecimal getR31_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS() {
		return R31_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS;
	}
	public void setR31_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS(BigDecimal r31_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS) {
		R31_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS = r31_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS;
	}
	public BigDecimal getR31_QUALIFYING_FOR_HEDGE_ACCOUNTING() {
		return R31_QUALIFYING_FOR_HEDGE_ACCOUNTING;
	}
	public void setR31_QUALIFYING_FOR_HEDGE_ACCOUNTING(BigDecimal r31_QUALIFYING_FOR_HEDGE_ACCOUNTING) {
		R31_QUALIFYING_FOR_HEDGE_ACCOUNTING = r31_QUALIFYING_FOR_HEDGE_ACCOUNTING;
	}
	public BigDecimal getR31_TOTAL() {
		return R31_TOTAL;
	}
	public void setR31_TOTAL(BigDecimal r31_TOTAL) {
		R31_TOTAL = r31_TOTAL;
	}
	public String getR32_PRODUCT() {
		return R32_PRODUCT;
	}
	public void setR32_PRODUCT(String r32_PRODUCT) {
		R32_PRODUCT = r32_PRODUCT;
	}
	public BigDecimal getR32_HELD_FOR_TRADING() {
		return R32_HELD_FOR_TRADING;
	}
	public void setR32_HELD_FOR_TRADING(BigDecimal r32_HELD_FOR_TRADING) {
		R32_HELD_FOR_TRADING = r32_HELD_FOR_TRADING;
	}
	public BigDecimal getR32_AMORTISED_COST() {
		return R32_AMORTISED_COST;
	}
	public void setR32_AMORTISED_COST(BigDecimal r32_AMORTISED_COST) {
		R32_AMORTISED_COST = r32_AMORTISED_COST;
	}
	public BigDecimal getR32_AVAILABLE_FOR_SALE() {
		return R32_AVAILABLE_FOR_SALE;
	}
	public void setR32_AVAILABLE_FOR_SALE(BigDecimal r32_AVAILABLE_FOR_SALE) {
		R32_AVAILABLE_FOR_SALE = r32_AVAILABLE_FOR_SALE;
	}
	public BigDecimal getR32_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS() {
		return R32_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS;
	}
	public void setR32_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS(BigDecimal r32_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS) {
		R32_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS = r32_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS;
	}
	public BigDecimal getR32_QUALIFYING_FOR_HEDGE_ACCOUNTING() {
		return R32_QUALIFYING_FOR_HEDGE_ACCOUNTING;
	}
	public void setR32_QUALIFYING_FOR_HEDGE_ACCOUNTING(BigDecimal r32_QUALIFYING_FOR_HEDGE_ACCOUNTING) {
		R32_QUALIFYING_FOR_HEDGE_ACCOUNTING = r32_QUALIFYING_FOR_HEDGE_ACCOUNTING;
	}
	public BigDecimal getR32_TOTAL() {
		return R32_TOTAL;
	}
	public void setR32_TOTAL(BigDecimal r32_TOTAL) {
		R32_TOTAL = r32_TOTAL;
	}
	public String getR33_PRODUCT() {
		return R33_PRODUCT;
	}
	public void setR33_PRODUCT(String r33_PRODUCT) {
		R33_PRODUCT = r33_PRODUCT;
	}
	public BigDecimal getR33_HELD_FOR_TRADING() {
		return R33_HELD_FOR_TRADING;
	}
	public void setR33_HELD_FOR_TRADING(BigDecimal r33_HELD_FOR_TRADING) {
		R33_HELD_FOR_TRADING = r33_HELD_FOR_TRADING;
	}
	public BigDecimal getR33_AMORTISED_COST() {
		return R33_AMORTISED_COST;
	}
	public void setR33_AMORTISED_COST(BigDecimal r33_AMORTISED_COST) {
		R33_AMORTISED_COST = r33_AMORTISED_COST;
	}
	public BigDecimal getR33_AVAILABLE_FOR_SALE() {
		return R33_AVAILABLE_FOR_SALE;
	}
	public void setR33_AVAILABLE_FOR_SALE(BigDecimal r33_AVAILABLE_FOR_SALE) {
		R33_AVAILABLE_FOR_SALE = r33_AVAILABLE_FOR_SALE;
	}
	public BigDecimal getR33_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS() {
		return R33_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS;
	}
	public void setR33_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS(BigDecimal r33_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS) {
		R33_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS = r33_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS;
	}
	public BigDecimal getR33_QUALIFYING_FOR_HEDGE_ACCOUNTING() {
		return R33_QUALIFYING_FOR_HEDGE_ACCOUNTING;
	}
	public void setR33_QUALIFYING_FOR_HEDGE_ACCOUNTING(BigDecimal r33_QUALIFYING_FOR_HEDGE_ACCOUNTING) {
		R33_QUALIFYING_FOR_HEDGE_ACCOUNTING = r33_QUALIFYING_FOR_HEDGE_ACCOUNTING;
	}
	public BigDecimal getR33_TOTAL() {
		return R33_TOTAL;
	}
	public void setR33_TOTAL(BigDecimal r33_TOTAL) {
		R33_TOTAL = r33_TOTAL;
	}
	public String getR34_PRODUCT() {
		return R34_PRODUCT;
	}
	public void setR34_PRODUCT(String r34_PRODUCT) {
		R34_PRODUCT = r34_PRODUCT;
	}
	public BigDecimal getR34_HELD_FOR_TRADING() {
		return R34_HELD_FOR_TRADING;
	}
	public void setR34_HELD_FOR_TRADING(BigDecimal r34_HELD_FOR_TRADING) {
		R34_HELD_FOR_TRADING = r34_HELD_FOR_TRADING;
	}
	public BigDecimal getR34_AMORTISED_COST() {
		return R34_AMORTISED_COST;
	}
	public void setR34_AMORTISED_COST(BigDecimal r34_AMORTISED_COST) {
		R34_AMORTISED_COST = r34_AMORTISED_COST;
	}
	public BigDecimal getR34_AVAILABLE_FOR_SALE() {
		return R34_AVAILABLE_FOR_SALE;
	}
	public void setR34_AVAILABLE_FOR_SALE(BigDecimal r34_AVAILABLE_FOR_SALE) {
		R34_AVAILABLE_FOR_SALE = r34_AVAILABLE_FOR_SALE;
	}
	public BigDecimal getR34_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS() {
		return R34_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS;
	}
	public void setR34_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS(BigDecimal r34_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS) {
		R34_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS = r34_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS;
	}
	public BigDecimal getR34_QUALIFYING_FOR_HEDGE_ACCOUNTING() {
		return R34_QUALIFYING_FOR_HEDGE_ACCOUNTING;
	}
	public void setR34_QUALIFYING_FOR_HEDGE_ACCOUNTING(BigDecimal r34_QUALIFYING_FOR_HEDGE_ACCOUNTING) {
		R34_QUALIFYING_FOR_HEDGE_ACCOUNTING = r34_QUALIFYING_FOR_HEDGE_ACCOUNTING;
	}
	public BigDecimal getR34_TOTAL() {
		return R34_TOTAL;
	}
	public void setR34_TOTAL(BigDecimal r34_TOTAL) {
		R34_TOTAL = r34_TOTAL;
	}
	public String getR35_PRODUCT() {
		return R35_PRODUCT;
	}
	public void setR35_PRODUCT(String r35_PRODUCT) {
		R35_PRODUCT = r35_PRODUCT;
	}
	public BigDecimal getR35_HELD_FOR_TRADING() {
		return R35_HELD_FOR_TRADING;
	}
	public void setR35_HELD_FOR_TRADING(BigDecimal r35_HELD_FOR_TRADING) {
		R35_HELD_FOR_TRADING = r35_HELD_FOR_TRADING;
	}
	public BigDecimal getR35_AMORTISED_COST() {
		return R35_AMORTISED_COST;
	}
	public void setR35_AMORTISED_COST(BigDecimal r35_AMORTISED_COST) {
		R35_AMORTISED_COST = r35_AMORTISED_COST;
	}
	public BigDecimal getR35_AVAILABLE_FOR_SALE() {
		return R35_AVAILABLE_FOR_SALE;
	}
	public void setR35_AVAILABLE_FOR_SALE(BigDecimal r35_AVAILABLE_FOR_SALE) {
		R35_AVAILABLE_FOR_SALE = r35_AVAILABLE_FOR_SALE;
	}
	public BigDecimal getR35_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS() {
		return R35_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS;
	}
	public void setR35_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS(BigDecimal r35_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS) {
		R35_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS = r35_FAIR_VALUE_THROUGH_PROFIT_AND_LOSS;
	}
	public BigDecimal getR35_QUALIFYING_FOR_HEDGE_ACCOUNTING() {
		return R35_QUALIFYING_FOR_HEDGE_ACCOUNTING;
	}
	public void setR35_QUALIFYING_FOR_HEDGE_ACCOUNTING(BigDecimal r35_QUALIFYING_FOR_HEDGE_ACCOUNTING) {
		R35_QUALIFYING_FOR_HEDGE_ACCOUNTING = r35_QUALIFYING_FOR_HEDGE_ACCOUNTING;
	}
	public BigDecimal getR35_TOTAL() {
		return R35_TOTAL;
	}
	public void setR35_TOTAL(BigDecimal r35_TOTAL) {
		R35_TOTAL = r35_TOTAL;
	}

	public Date getReportDate() {
		return reportDate;
	}
	public void setReportDate(Date reportDate) {
		this.reportDate = reportDate;
	}
	public String getReportVersion() {
		return reportVersion;
	}
	public void setReportVersion(String reportVersion) {
		this.reportVersion = reportVersion;
	}
	public String getREPORT_FREQUENCY() {
		return REPORT_FREQUENCY;
	}
	public void setREPORT_FREQUENCY(String rEPORT_FREQUENCY) {
		REPORT_FREQUENCY = rEPORT_FREQUENCY;
	}
	public String getREPORT_CODE() {
		return REPORT_CODE;
	}
	public void setREPORT_CODE(String rEPORT_CODE) {
		REPORT_CODE = rEPORT_CODE;
	}
	public String getREPORT_DESC() {
		return REPORT_DESC;
	}
	public void setREPORT_DESC(String rEPORT_DESC) {
		REPORT_DESC = rEPORT_DESC;
	}
	public String getENTITY_FLG() {
		return ENTITY_FLG;
	}
	public void setENTITY_FLG(String eNTITY_FLG) {
		ENTITY_FLG = eNTITY_FLG;
	}
	public String getMODIFY_FLG() {
		return MODIFY_FLG;
	}
	public void setMODIFY_FLG(String mODIFY_FLG) {
		MODIFY_FLG = mODIFY_FLG;
	}
	public String getDEL_FLG() {
		return DEL_FLG;
	}
	public void setDEL_FLG(String dEL_FLG) {
		DEL_FLG = dEL_FLG;
	}
	
	public BigDecimal getR28_HELD_FOR_TRADING() {
		return R28_HELD_FOR_TRADING;
	}
	public void setR28_HELD_FOR_TRADING(BigDecimal r28_HELD_FOR_TRADING) {
		R28_HELD_FOR_TRADING = r28_HELD_FOR_TRADING;
	}
	public M_IS_Summary_Entity2() {
		super();
		// TODO Auto-generated constructor stub
	}
  
  
  
}	
	
	
	
	
	
	
	
	
	
	
	
