/*V_R2_AMOUNT_AED_DORMANT :=  V_R2_AMOUNT_AED_5YEAR ;
V_R3_AMOUNT_AED_DORMANT :=  V_R3_AMOUNT_AED_5YEAR ;
V_R4_AMOUNT_AED_DORMANT :=  V_R4_AMOUNT_AED_5YEAR ;
V_R5_AMOUNT_AED_DORMANT :=  V_R5_AMOUNT_AED_5YEAR ;
V_R7_AMOUNT_AED_DORMANT :=  V_R7_AMOUNT_AED_5YEAR ;
V_R8_AMOUNT_AED_DORMANT :=  V_R8_AMOUNT_AED_5YEAR ;
V_R9_AMOUNT_AED_DORMANT :=  V_R9_AMOUNT_AED_5YEAR ;
V_R10_AMOUNT_AED_DORMANT :=  V_R10_AMOUNT_AED_5YEAR ;
V_R12_AMOUNT_AED_DORMANT :=  V_R12_AMOUNT_AED_5YEAR ;
V_R14_AMOUNT_AED_DORMANT :=  V_R14_AMOUNT_AED_5YEAR ;
V_R15_AMOUNT_AED_DORMANT :=  V_R15_AMOUNT_AED_5YEAR ;
V_R17_AMOUNT_AED_DORMANT :=   V_R17_AMOUNT_AED_5YEAR  +
V_R17_AMOUNT_AED_2YEAR +
V_R17_AMOUNT_AED_3YEAR ;
V_R18_AMOUNT_AED_DORMANT :=   V_R18_AMOUNT_AED_5YEAR  +
V_R18_AMOUNT_AED_2YEAR +
V_R18_AMOUNT_AED_3YEAR ;
V_R19_AMOUNT_AED_DORMANT :=   V_R19_AMOUNT_AED_5YEAR  +
V_R19_AMOUNT_AED_2YEAR +
V_R19_AMOUNT_AED_3YEAR ;
V_R21_AMOUNT_AED_DORMANT :=  V_R21_AMOUNT_AED_ABOVE ;
V_R24_AMOUNT_AED_DORMANT :=  V_R24_AMOUNT_AED_5YEAR ;
V_R26_AMOUNT_AED_DORMANT :=  V_R26_AMOUNT_AED_5YEAR ;
V_R28_AMOUNT_AED_DORMANT := 
V_R1_AMOUNT_AED_DORMANT +
V_R6_AMOUNT_AED_DORMANT +
V_R11_AMOUNT_AED_DORMANT +
V_R16_AMOUNT_AED_DORMANT +
V_R22_AMOUNT_AED_DORMANT + 
V_R23_AMOUNT_AED_DORMANT ;
V_R29_AMOUNT_AED_DORMANT := 
V_R5_AMOUNT_AED_DORMANT +
V_R10_AMOUNT_AED_DORMANT +
V_R15_AMOUNT_AED_DORMANT +
V_R21_AMOUNT_AED_DORMANT +
V_R26_AMOUNT_AED_DORMANT + 
V_R27_AMOUNT_AED_DORMANT ;*/